# Musical Congruence Pipeline
**Sound and Sense: Multimodal Emotional Congruence in Music and Its Effect on Streaming Popularity**

This notebook runs the full pipeline end-to-end by sourcing each step script rather than duplicating their code.

| Step | Script | Description |
|------|--------|-------------|
| 1 | `01_scrape_lyrics.py` | Genius API → lyrics JSON |
| 2 | `02_scrape_audio.py` | yt-dlp → MP3s |
| 3 | `03_build_schema.py` | Auto-generate schema `.py` files |
| 4 | `04_embed_mulan.py` | MuQ-MuLan embeddings |
| 5 | `05_embed_clap.py` | LAION-CLAP-Music embeddings |
| 6 | `06_embed_mert_sbert.py` | MERT + Sentence-BERT (late-fusion baseline) |
| 7 | `07_segment_analysis.py` | Verse/chorus/bridge segment-level LMC |
| 8 | `08_get_popularity.py` | Spotify popularity + audio features |
| 9 | `09_combine_results.py` | Merge all outputs → `master_results.csv` |

---
## 0. Environment Setup
Sets the working directory, confirms API keys are present, and defines a helper that loads numbered scripts via `importlib`.

In [1]:
import os
import getpass

os.environ["GENIUS_API_TOKEN"]      = getpass.getpass("Genius API Token: ")
os.environ["SPOTIFY_CLIENT_ID"]     = getpass.getpass("Spotify Client ID: ")
os.environ["SPOTIFY_CLIENT_SECRET"] = getpass.getpass("Spotify Client Secret: ")

# Force config to pick up the new values
import config
config.GENIUS_API_TOKEN      = os.environ["GENIUS_API_TOKEN"]
config.SPOTIFY_CLIENT_ID     = os.environ["SPOTIFY_CLIENT_ID"]
config.SPOTIFY_CLIENT_SECRET = os.environ["SPOTIFY_CLIENT_SECRET"]

print("Keys set ✓")

Genius API Token:  ········
Spotify Client ID:  ········
Spotify Client Secret:  ········

Keys set ✓

In [2]:
import sys
import importlib.util

# ── Working directory ─────────────────────────────────────────────────────────
# Point this at the folder containing config.py and the 0N_*.py scripts.
PROJECT_DIR = os.path.dirname(os.path.abspath("__file__"))  # same dir as this notebook
os.chdir(PROJECT_DIR)
if PROJECT_DIR not in sys.path:
    sys.path.insert(0, PROJECT_DIR)

print(f"Working directory: {os.getcwd()}")

# ── API key check ─────────────────────────────────────────────────────────────
REQUIRED_KEYS = ["GENIUS_API_TOKEN", "SPOTIFY_CLIENT_ID", "SPOTIFY_CLIENT_SECRET"]
for key in REQUIRED_KEYS:
    val = os.environ.get(key, "")
    status = "✓ set" if val and "YOUR_" not in val else "✗ MISSING"
    print(f"  {key:35s} {status}")

# ── Script loader ─────────────────────────────────────────────────────────────
# Python cannot import files whose names start with a digit, so we use importlib.
def load_script(alias, filename):
    """Load a pipeline script by filename and register it under `alias`."""
    path = os.path.join(PROJECT_DIR, filename)
    if not os.path.exists(path):
        raise FileNotFoundError(f"Script not found: {path}")
    spec = importlib.util.spec_from_file_location(alias, path)
    mod  = importlib.util.module_from_spec(spec)
    sys.modules[alias] = mod
    spec.loader.exec_module(mod)
    return mod

# ── Device report ─────────────────────────────────────────────────────────────
import torch
if   torch.cuda.is_available():              device = "cuda"
elif torch.backends.mps.is_available():      device = "mps"
else:                                        device = "cpu"
os.environ.setdefault("PYTORCH_ENABLE_MPS_FALLBACK", "1")
print(f"\nDevice: {device}")

# ── Catalog summary ───────────────────────────────────────────────────────────
from config import CATALOG, total_songs
print(f"Catalog: {len(CATALOG)} artists, {total_songs()} songs")

Working directory: /Users/budge.13/Desktop/Music Analysis
  GENIUS_API_TOKEN                    ✓ set
  SPOTIFY_CLIENT_ID                   ✓ set
  SPOTIFY_CLIENT_SECRET               ✓ set

Device: mps
Catalog: 34 artists, 441 songs

---
## Step 1 — Scrape Lyrics
Pulls lyrics from the Genius API for every song in the catalog.  
**Outputs:** `lyrics/{SONG_ID}.json` for each song, `lyrics/_manifest.json`  
**Resume-safe:** songs already in `lyrics/` are skipped automatically.

> Set `artist_filter` to a list like `["KL", "GD"]` to restrict to specific artists.

In [3]:
scrape_lyrics = load_script("scrape_lyrics", "01_scrape_lyrics.py")

manifest_lyrics = scrape_lyrics.scrape_all(
    dry_run       = False,   # set True to preview without fetching
    artist_filter = None,    # e.g. ["KL", "GD", "TS"] — None = all artists
)

print(f"\nFetched : {manifest_lyrics['n_fetched']}")
print(f"Skipped : {manifest_lyrics['n_skipped']}")
print(f"Failed  : {manifest_lyrics['n_failed']}")
if manifest_lyrics['failed']:
    print(f"Failed IDs: {manifest_lyrics['failed']}")

23:02:55 | INFO | scrape_lyrics |
────────────────────────────────────────────────────────────
23:02:55 | INFO | scrape_lyrics | Artist: Run the Jewels  (RTJ)
23:02:55 | INFO | scrape_lyrics |   [RTJ_01] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [RTJ_02] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [RTJ_03] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [RTJ_04] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [RTJ_05] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [RTJ_06] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [RTJ_07] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [RTJ_08] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [RTJ_09] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [RTJ_10] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [RTJ_11] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [RTJ_12] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [RTJ_13] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [RTJ_14] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [RTJ_15] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |
────────────────────────────────────────────────────────────
23:02:55 | INFO | scrape_lyrics | Artist: Kendrick Lamar  (KL)
23:02:55 | INFO | scrape_lyrics |   [KL_01] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [KL_02] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [KL_03] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [KL_04] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [KL_05] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [KL_06] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [KL_07] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [KL_08] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [KL_09] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [KL_10] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [KL_11] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [KL_12] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [KL_13] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [KL_14] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [KL_15] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |
────────────────────────────────────────────────────────────
23:02:55 | INFO | scrape_lyrics | Artist: J. Cole  (JC)
23:02:55 | INFO | scrape_lyrics |   [JC_01] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [JC_02] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [JC_03] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [JC_04] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [JC_05] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [JC_06] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [JC_07] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [JC_08] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [JC_09] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [JC_10] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [JC_11] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [JC_12] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [JC_13] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [JC_14] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |   [JC_15] SKIP (already fetched)
23:02:55 | INFO | scrape_lyrics |
────────────────────────────────────────────────────────────
23:02:55 | INFO | scrape_lyrics | Artist: Drake  (DR)
23:02:55 | INFO | scrape_lyrics |   [DR_01] Fetching: God's Plan
23:02:55 | INFO | lyricsgenius.genius | Searching for "Gods Plan Drake"...
23:02:57 | INFO | lyricsgenius.genius | Done.
23:02:57 | INFO | scrape_lyrics |     ✓ Saved (349 words)
23:02:58 | INFO | scrape_lyrics |   [DR_02] Fetching: Hotline Bling
23:02:58 | INFO | lyricsgenius.genius | Searching for "Hotline Bling Drake"...
23:02:59 | INFO | lyricsgenius.genius | Done.
23:02:59 | INFO | scrape_lyrics |     ✓ Saved (431 words)
23:03:00 | INFO | scrape_lyrics |   [DR_03] Fetching: One Dance
23:03:00 | INFO | lyricsgenius.genius | Searching for "One Dance Drake"...
23:03:02 | INFO | lyricsgenius.genius | Done.
23:03:02 | INFO | scrape_lyrics |     ✓ Saved (469 words)
23:03:02 | INFO | scrape_lyrics |   [DR_04] Fetching: Passionfruit
23:03:02 | INFO | lyricsgenius.genius | Searching for "Passionfruit Drake"...
23:03:04 | INFO | lyricsgenius.genius | Done.
23:03:04 | INFO | scrape_lyrics |     ✓ Saved (228 words)
23:03:04 | INFO | scrape_lyrics |   [DR_05] Fetching: Started From the Bottom
23:03:04 | INFO | lyricsgenius.genius | Searching for "Started From the Bottom Drake"...
23:03:06 | INFO | lyricsgenius.genius | Done.
23:03:06 | INFO | scrape_lyrics |     ✓ Saved (463 words)
23:03:07 | INFO | scrape_lyrics |   [DR_06] Fetching: Take Care
23:03:07 | INFO | lyricsgenius.genius | Searching for "Take Care Drake"...
23:03:08 | INFO | lyricsgenius.genius | Done.
23:03:08 | INFO | scrape_lyrics |     ✓ Saved (481 words)
23:03:09 | INFO | scrape_lyrics |   [DR_07] Fetching: Marvins Room
23:03:09 | INFO | lyricsgenius.genius | Searching for "Marvins Room Drake"...
23:03:10 | INFO | lyricsgenius.genius | Done.
23:03:10 | INFO | scrape_lyrics |     ✓ Saved (578 words)
23:03:11 | INFO | scrape_lyrics |   [DR_08] Fetching: Hold On We're Going Home
23:03:11 | INFO | lyricsgenius.genius | Searching for "Hold On Were Going Home Drake"...
23:03:13 | INFO | lyricsgenius.genius | Done.
23:03:13 | INFO | scrape_lyrics |     ✓ Saved (339 words)
23:03:13 | INFO | scrape_lyrics |   [DR_09] Fetching: Forever
23:03:13 | INFO | lyricsgenius.genius | Searching for "Forever Drake"...
23:03:15 | INFO | lyricsgenius.genius | Done.
23:03:15 | INFO | scrape_lyrics |     ✓ Saved (1081 words)
23:03:16 | INFO | scrape_lyrics |   [DR_10] Fetching: Best I Ever Had
23:03:16 | INFO | lyricsgenius.genius | Searching for "Best I Ever Had Drake"...
23:03:17 | INFO | lyricsgenius.genius | Done.
23:03:17 | INFO | scrape_lyrics |     ✓ Saved (837 words)
23:03:18 | INFO | scrape_lyrics |   [DR_11] Fetching: Fancy
23:03:18 | INFO | lyricsgenius.genius | Searching for "Fancy Drake"...
23:03:19 | INFO | lyricsgenius.genius | Done.
23:03:19 | INFO | scrape_lyrics |     ✓ Saved (949 words)
23:03:20 | INFO | scrape_lyrics |   [DR_12] Fetching: From Time
23:03:20 | INFO | lyricsgenius.genius | Searching for "From Time Drake"...
23:03:21 | INFO | lyricsgenius.genius | Done.
23:03:21 | INFO | scrape_lyrics |     ✓ Saved (743 words)
23:03:22 | INFO | scrape_lyrics |
────────────────────────────────────────────────────────────
23:03:22 | INFO | scrape_lyrics | Artist: Eminem  (EM)
23:03:22 | INFO | scrape_lyrics |   [EM_01] Fetching: Lose Yourself
23:03:22 | INFO | lyricsgenius.genius | Searching for "Lose Yourself Eminem"...
23:03:23 | INFO | lyricsgenius.genius | Done.
23:03:23 | INFO | scrape_lyrics |     ✓ Saved (794 words)
23:03:24 | INFO | scrape_lyrics |   [EM_02] Fetching: Stan
23:03:24 | INFO | lyricsgenius.genius | Searching for "Stan Eminem"...
23:03:26 | INFO | lyricsgenius.genius | Done.
23:03:26 | INFO | scrape_lyrics |     ✓ Saved (1341 words)
23:03:26 | INFO | scrape_lyrics |   [EM_03] Fetching: The Real Slim Shady
23:03:26 | INFO | lyricsgenius.genius | Searching for "The Real Slim Shady Eminem"...
23:03:28 | INFO | lyricsgenius.genius | Done.
23:03:28 | INFO | scrape_lyrics |     ✓ Saved (1015 words)
23:03:28 | INFO | scrape_lyrics |   [EM_04] Fetching: Without Me
23:03:28 | INFO | lyricsgenius.genius | Searching for "Without Me Eminem"...
23:03:30 | INFO | lyricsgenius.genius | Done.
23:03:30 | INFO | scrape_lyrics |     ✓ Saved (762 words)
23:03:30 | INFO | scrape_lyrics |   [EM_05] Fetching: Not Afraid
23:03:30 | INFO | lyricsgenius.genius | Searching for "Not Afraid Eminem"...
23:03:32 | INFO | lyricsgenius.genius | Done.
23:03:32 | INFO | scrape_lyrics |     ✓ Saved (857 words)
23:03:33 | INFO | scrape_lyrics |   [EM_06] Fetching: Love The Way You Lie
23:03:33 | INFO | lyricsgenius.genius | Searching for "Love The Way You Lie Eminem"...
23:03:34 | INFO | lyricsgenius.genius | Done.
23:03:34 | INFO | scrape_lyrics |     ✓ Saved (736 words)
23:03:35 | INFO | scrape_lyrics |   [EM_07] Fetching: Rap God
23:03:35 | INFO | lyricsgenius.genius | Searching for "Rap God Eminem"...
23:03:37 | INFO | lyricsgenius.genius | Done.
23:03:37 | INFO | scrape_lyrics |     ✓ Saved (1544 words)
23:03:37 | INFO | scrape_lyrics |   [EM_08] Fetching: River
23:03:37 | INFO | lyricsgenius.genius | Searching for "River Eminem"...
23:03:42 | INFO | lyricsgenius.genius | Done.
23:03:42 | INFO | scrape_lyrics |     ✓ Saved (723 words)
23:03:42 | INFO | scrape_lyrics |   [EM_09] Fetching: Cleanin Out My Closet
23:03:42 | INFO | lyricsgenius.genius | Searching for "Cleanin Out My Closet Eminem"...
23:03:44 | INFO | lyricsgenius.genius | Done.
23:03:44 | INFO | scrape_lyrics |     ✓ Saved (729 words)
23:03:45 | INFO | scrape_lyrics |   [EM_10] Fetching: When I'm Gone
23:03:45 | INFO | lyricsgenius.genius | Searching for "When Im Gone Eminem"...
23:03:47 | INFO | lyricsgenius.genius | Done.
23:03:47 | INFO | scrape_lyrics |     ✓ Saved (919 words)
23:03:47 | INFO | scrape_lyrics |   [EM_11] Fetching: Mockingbird
23:03:47 | INFO | lyricsgenius.genius | Searching for "Mockingbird Eminem"...
23:03:49 | INFO | lyricsgenius.genius | Done.
23:03:49 | INFO | scrape_lyrics |     ✓ Saved (898 words)
23:03:50 | INFO | scrape_lyrics |   [EM_12] Fetching: Beautiful
23:03:50 | INFO | lyricsgenius.genius | Searching for "Beautiful Eminem"...
23:03:51 | INFO | lyricsgenius.genius | Done.
23:03:51 | INFO | scrape_lyrics |     ✓ Saved (1019 words)
23:03:52 | INFO | scrape_lyrics |
────────────────────────────────────────────────────────────
23:03:52 | INFO | scrape_lyrics | Artist: Tyler, the Creator  (TC2)
23:03:52 | INFO | scrape_lyrics |   [TC2_01] Fetching: See You Again
23:03:52 | INFO | lyricsgenius.genius | Searching for "See You Again Tyler the Creator"...
23:03:54 | INFO | lyricsgenius.genius | Done.
23:03:54 | INFO | scrape_lyrics |     ✓ Saved (471 words)
23:03:55 | INFO | scrape_lyrics |   [TC2_02] Fetching: EARFQUAKE
23:03:55 | INFO | lyricsgenius.genius | Searching for "EARFQUAKE Tyler the Creator"...
23:03:57 | INFO | lyricsgenius.genius | Done.
23:03:57 | INFO | scrape_lyrics |     ✓ Saved (403 words)
23:03:57 | INFO | scrape_lyrics |   [TC2_03] Fetching: Enjoy Right Now Today
23:03:57 | INFO | lyricsgenius.genius | Searching for "Enjoy Right Now Today Tyler the Creator"...
23:03:59 | INFO | lyricsgenius.genius | Done.
23:03:59 | INFO | scrape_lyrics |     ✓ Saved (4 words)
23:03:59 | INFO | scrape_lyrics |   [TC2_04] Fetching: I THINK
23:03:59 | INFO | lyricsgenius.genius | Searching for "I THINK Tyler the Creator"...
23:04:01 | INFO | lyricsgenius.genius | Done.
23:04:01 | INFO | scrape_lyrics |     ✓ Saved (408 words)
23:04:02 | INFO | scrape_lyrics |   [TC2_05] Fetching: NEW MAGIC WAND
23:04:02 | INFO | lyricsgenius.genius | Searching for "NEW MAGIC WAND Tyler the Creator"...
23:04:03 | INFO | lyricsgenius.genius | Done.
23:04:03 | INFO | scrape_lyrics |     ✓ Saved (494 words)
23:04:04 | INFO | scrape_lyrics |   [TC2_06] Fetching: WUSYANAME
23:04:04 | INFO | lyricsgenius.genius | Searching for "WUSYANAME Tyler the Creator"...
23:04:06 | INFO | lyricsgenius.genius | Done.
23:04:06 | INFO | scrape_lyrics |     ✓ Saved (453 words)
23:04:06 | INFO | scrape_lyrics |   [TC2_07] Fetching: Lumberjack
23:04:06 | INFO | lyricsgenius.genius | Searching for "Lumberjack Tyler the Creator"...
23:04:08 | INFO | lyricsgenius.genius | Done.
23:04:08 | INFO | scrape_lyrics |     ✓ Saved (534 words)
23:04:08 | INFO | scrape_lyrics |   [TC2_08] Fetching: 911 / Mr. Lonely
23:04:08 | INFO | lyricsgenius.genius | Searching for "911 Mr Lonely Tyler the Creator"...
23:04:10 | INFO | lyricsgenius.genius | Done.
23:04:10 | INFO | scrape_lyrics |     ✓ Saved (743 words)
23:04:11 | INFO | scrape_lyrics |   [TC2_09] Fetching: Who Dat Boy
23:04:11 | INFO | lyricsgenius.genius | Searching for "Who Dat Boy Tyler the Creator"...
23:04:12 | INFO | lyricsgenius.genius | Done.
23:04:12 | INFO | scrape_lyrics |     ✓ Saved (517 words)
23:04:13 | INFO | scrape_lyrics |   [TC2_10] Fetching: Gone Gone / Thank You
23:04:13 | INFO | lyricsgenius.genius | Searching for "Gone Gone Tyler the Creator"...
23:04:15 | INFO | lyricsgenius.genius | Done.
23:04:15 | INFO | scrape_lyrics |     ✓ Saved (593 words)
23:04:15 | INFO | scrape_lyrics |   [TC2_11] Fetching: Foreword
23:04:15 | INFO | lyricsgenius.genius | Searching for "Foreword Tyler the Creator"...
23:04:17 | INFO | lyricsgenius.genius | Done.
23:04:17 | INFO | scrape_lyrics |     ✓ Saved (460 words)
23:04:17 | INFO | scrape_lyrics |   [TC2_12] Fetching: MASSA
23:04:17 | INFO | lyricsgenius.genius | Searching for "MASSA Tyler the Creator"...
23:04:20 | INFO | lyricsgenius.genius | Done.
23:04:20 | INFO | scrape_lyrics |     ✓ Saved (709 words)
23:04:20 | INFO | scrape_lyrics |
────────────────────────────────────────────────────────────
23:04:20 | INFO | scrape_lyrics | Artist: Mac Miller  (MM)
23:04:20 | INFO | scrape_lyrics |   [MM_01] Fetching: Self Care
23:04:20 | INFO | lyricsgenius.genius | Searching for "Self Care Mac Miller"...
23:04:22 | INFO | lyricsgenius.genius | Done.
23:04:22 | INFO | scrape_lyrics |     ✓ Saved (721 words)
23:04:23 | INFO | scrape_lyrics |   [MM_02] Fetching: Small Worlds
23:04:23 | INFO | lyricsgenius.genius | Searching for "Small Worlds Mac Miller"...
23:04:24 | INFO | lyricsgenius.genius | Done.
23:04:24 | INFO | scrape_lyrics |     ✓ Saved (653 words)
23:04:25 | INFO | scrape_lyrics |   [MM_03] Fetching: Circles
23:04:25 | INFO | lyricsgenius.genius | Searching for "Circles Mac Miller"...
23:04:27 | INFO | lyricsgenius.genius | Done.
23:04:27 | INFO | scrape_lyrics |     ✓ Saved (161 words)
23:04:27 | INFO | scrape_lyrics |   [MM_04] Fetching: 2009
23:04:27 | INFO | lyricsgenius.genius | Searching for "2009 Mac Miller"...
23:04:29 | INFO | lyricsgenius.genius | Done.
23:04:29 | INFO | scrape_lyrics |     ✓ Saved (618 words)
23:04:29 | INFO | scrape_lyrics |   [MM_05] Fetching: Objects in the Mirror
23:04:29 | INFO | lyricsgenius.genius | Searching for "Objects in the Mirror Mac Miller"...
23:04:32 | INFO | lyricsgenius.genius | Done.
23:04:32 | INFO | scrape_lyrics |     ✓ Saved (457 words)
23:04:32 | INFO | scrape_lyrics |   [MM_06] Fetching: Diablo
23:04:32 | INFO | lyricsgenius.genius | Searching for "Diablo Mac Miller"...
23:04:33 | INFO | lyricsgenius.genius | Done.
23:04:33 | INFO | scrape_lyrics |     ✓ Saved (496 words)
23:04:34 | INFO | scrape_lyrics |   [MM_07] Fetching: Programs
23:04:34 | INFO | lyricsgenius.genius | Searching for "Programs Mac Miller"...
23:04:37 | INFO | lyricsgenius.genius | Done.
23:04:37 | INFO | scrape_lyrics |     ✓ Saved (556 words)
23:04:37 | INFO | scrape_lyrics |   [MM_08] Fetching: Dunno
23:04:37 | INFO | lyricsgenius.genius | Searching for "Dunno Mac Miller"...
23:04:39 | INFO | lyricsgenius.genius | Done.
23:04:39 | INFO | scrape_lyrics |     ✓ Saved (277 words)
23:04:39 | INFO | scrape_lyrics |   [MM_09] Fetching: Come Back to Earth
23:04:39 | INFO | lyricsgenius.genius | Searching for "Come Back to Earth Mac Miller"...
23:04:41 | INFO | lyricsgenius.genius | Done.
23:04:41 | INFO | scrape_lyrics |     ✓ Saved (167 words)
23:04:42 | INFO | scrape_lyrics |   [MM_10] Fetching: Good News
23:04:42 | INFO | lyricsgenius.genius | Searching for "Good News Mac Miller"...
23:04:44 | INFO | lyricsgenius.genius | Done.
23:04:44 | INFO | scrape_lyrics |     ✓ Saved (459 words)
23:04:44 | INFO | scrape_lyrics |   [MM_11] Fetching: What's the Use?
23:04:44 | INFO | lyricsgenius.genius | Searching for "Whats the Use Mac Miller"...
23:04:46 | INFO | lyricsgenius.genius | Done.
23:04:46 | INFO | scrape_lyrics |     ✓ Saved (608 words)
23:04:46 | INFO | scrape_lyrics |   [MM_12] Fetching: Grand Finale
23:04:46 | INFO | lyricsgenius.genius | Searching for "Grand Finale Mac Miller"...
23:04:48 | INFO | lyricsgenius.genius | Done.
23:04:48 | INFO | scrape_lyrics |     ✓ Saved (396 words)
23:04:49 | INFO | scrape_lyrics |
────────────────────────────────────────────────────────────
23:04:49 | INFO | scrape_lyrics | Artist: Chance the Rapper  (CH)
23:04:49 | INFO | scrape_lyrics |   [CH_01] Fetching: Blessings
23:04:49 | INFO | lyricsgenius.genius | Searching for "Blessings Chance the Rapper"...
23:04:51 | INFO | lyricsgenius.genius | Done.
23:04:51 | INFO | scrape_lyrics |     ✓ Saved (461 words)
23:04:51 | INFO | scrape_lyrics |   [CH_02] Fetching: No Problem
23:04:51 | INFO | lyricsgenius.genius | Searching for "No Problem Chance the Rapper"...
23:04:53 | INFO | lyricsgenius.genius | Done.
23:04:53 | INFO | scrape_lyrics |     ✓ Saved (877 words)
23:04:54 | INFO | scrape_lyrics |   [CH_03] Fetching: Same Drugs
23:04:54 | INFO | lyricsgenius.genius | Searching for "Same Drugs Chance the Rapper"...
23:04:55 | INFO | lyricsgenius.genius | Done.
23:04:55 | INFO | scrape_lyrics |     ✓ Saved (461 words)
23:04:56 | INFO | scrape_lyrics |   [CH_04] Fetching: Angels
23:04:56 | INFO | lyricsgenius.genius | Searching for "Angels Chance the Rapper"...
23:05:00 | INFO | lyricsgenius.genius | Done.
23:05:00 | INFO | scrape_lyrics |     ✓ Saved (544 words)
23:05:00 | INFO | scrape_lyrics |   [CH_05] Fetching: Paranoia
23:05:00 | INFO | lyricsgenius.genius | Searching for "Paranoia Chance the Rapper"...
23:05:02 | INFO | lyricsgenius.genius | Done.
23:05:02 | INFO | scrape_lyrics |     ✓ Saved (1003 words)
23:05:03 | INFO | scrape_lyrics |   [CH_06] Fetching: Sunday Candy
23:05:03 | INFO | lyricsgenius.genius | Searching for "Sunday Candy Chance the Rapper"...
23:05:05 | INFO | lyricsgenius.genius | Done.
23:05:05 | INFO | scrape_lyrics |     ✓ Saved (548 words)
23:05:06 | INFO | scrape_lyrics |   [CH_07] Fetching: Favorite Song
23:05:06 | INFO | lyricsgenius.genius | Searching for "Favorite Song Chance the Rapper"...
23:05:08 | INFO | lyricsgenius.genius | Done.
23:05:08 | INFO | scrape_lyrics |     ✓ Saved (657 words)
23:05:08 | INFO | scrape_lyrics |   [CH_08] Fetching: All We Got
23:05:08 | INFO | lyricsgenius.genius | Searching for "All We Got Chance the Rapper"...
23:05:10 | INFO | lyricsgenius.genius | Done.
23:05:10 | INFO | scrape_lyrics |     ✓ Saved (411 words)
23:05:11 | INFO | scrape_lyrics |   [CH_09] Fetching: Cocoa Butter Kisses
23:05:11 | INFO | lyricsgenius.genius | Searching for "Cocoa Butter Kisses Chance the Rapper"...
23:05:13 | INFO | lyricsgenius.genius | Done.
23:05:13 | INFO | scrape_lyrics |     ✓ Saved (869 words)
23:05:13 | INFO | scrape_lyrics |   [CH_10] Fetching: Smoke Again
23:05:13 | INFO | lyricsgenius.genius | Searching for "Smoke Again Chance the Rapper"...
23:05:15 | INFO | lyricsgenius.genius | Done.
23:05:15 | INFO | scrape_lyrics |     ✓ Saved (925 words)
23:05:16 | INFO | scrape_lyrics |   [CH_11] Fetching: Hot Shower
23:05:16 | INFO | lyricsgenius.genius | Searching for "Hot Shower Chance the Rapper"...
23:05:18 | INFO | lyricsgenius.genius | Done.
23:05:18 | INFO | scrape_lyrics |     ✓ Saved (758 words)
23:05:18 | INFO | scrape_lyrics |   [CH_12] Fetching: I Might Need Security
23:05:18 | INFO | lyricsgenius.genius | Searching for "I Might Need Security Chance the Rapper"...
23:05:22 | INFO | lyricsgenius.genius | Done.
23:05:22 | INFO | scrape_lyrics |     ✓ Saved (571 words)
23:05:22 | INFO | scrape_lyrics |
────────────────────────────────────────────────────────────
23:05:22 | INFO | scrape_lyrics | Artist: Nas  (NS)
23:05:22 | INFO | scrape_lyrics |   [NS_01] Fetching: N.Y. State of Mind
23:05:22 | INFO | lyricsgenius.genius | Searching for "NY State of Mind Nas"...
23:05:24 | INFO | lyricsgenius.genius | Done.
23:05:24 | INFO | scrape_lyrics |     ✓ Saved (821 words)

Fetched : 263
Skipped : 174
Failed  : 4
Failed IDs: ['TW_13', 'DP_04', 'CB_06', 'BN_12']

---
## Step 2 — Scrape Audio
Downloads each song as a 192 kbps MP3 from YouTube via yt-dlp.  
**Outputs:** `audio/{ARTIST_FOLDER}/{SONG_ID}.mp3`  
**Resume-safe:** existing files are skipped. Failures create a `.FAILED` stub.  

> **Time estimate:** ~90–120 seconds per artist (10–15 songs × ~8s per download + rate-limit delay).  
> For a quick test, set `artist_filter=["KL", "GD", "TS"]` (~3 artists, ~45 songs).

In [4]:
scrape_audio = load_script("scrape_audio", "02_scrape_audio.py")

manifest_audio = scrape_audio.download_all(
    dry_run       = False,
    artist_filter = None,    # e.g. ["KL", "GD", "TS"]
    max_retries   = 2,
)

print(f"\nDownloaded : {manifest_audio['n_downloaded']}")
print(f"Skipped    : {manifest_audio['n_skipped']}")
print(f"Failed     : {manifest_audio['n_failed']}")

# Coverage report
report = scrape_audio.get_coverage_report()
print(f"\nCoverage   : {len(report['have_audio'])} / {total_songs()} songs have audio")

23:15:20 | INFO | scrape_audio |
────────────────────────────────────────────────────────────
23:15:20 | INFO | scrape_audio | Artist: Run the Jewels  (RTJ)
23:15:20 | INFO | scrape_audio |   [RTJ_01] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/RTJ/RTJ_01.mp3
23:15:20 | INFO | scrape_audio |   [RTJ_02] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/RTJ/RTJ_02.mp3
23:15:20 | INFO | scrape_audio |   [RTJ_03] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/RTJ/RTJ_03.mp3
23:15:20 | INFO | scrape_audio |   [RTJ_04] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/RTJ/RTJ_04.mp3
23:15:20 | INFO | scrape_audio |   [RTJ_05] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/RTJ/RTJ_05.mp3
23:15:20 | INFO | scrape_audio |   [RTJ_06] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/RTJ/RTJ_06.mp3
23:15:20 | INFO | scrape_audio |   [RTJ_07] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/RTJ/RTJ_07.mp3
23:15:20 | INFO | scrape_audio |   [RTJ_08] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/RTJ/RTJ_08.mp3
23:15:20 | INFO | scrape_audio |   [RTJ_09] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/RTJ/RTJ_09.mp3
23:15:20 | INFO | scrape_audio |   [RTJ_10] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/RTJ/RTJ_10.mp3
23:15:20 | INFO | scrape_audio |   [RTJ_11] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/RTJ/RTJ_11.mp3
23:15:20 | INFO | scrape_audio |   [RTJ_12] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/RTJ/RTJ_12.mp3
23:15:20 | INFO | scrape_audio |   [RTJ_13] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/RTJ/RTJ_13.mp3
23:15:20 | INFO | scrape_audio |   [RTJ_14] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/RTJ/RTJ_14.mp3
23:15:20 | INFO | scrape_audio |   [RTJ_15] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/RTJ/RTJ_15.mp3
23:15:20 | INFO | scrape_audio |
────────────────────────────────────────────────────────────
23:15:20 | INFO | scrape_audio | Artist: Kendrick Lamar  (KL)
23:15:20 | INFO | scrape_audio |   [KL_01] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/KL/KL_01.mp3
23:15:20 | INFO | scrape_audio |   [KL_02] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/KL/KL_02.mp3
23:15:20 | INFO | scrape_audio |   [KL_03] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/KL/KL_03.mp3
23:15:20 | INFO | scrape_audio |   [KL_04] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/KL/KL_04.mp3
23:15:20 | INFO | scrape_audio |   [KL_05] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/KL/KL_05.mp3
23:15:20 | INFO | scrape_audio |   [KL_06] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/KL/KL_06.mp3
23:15:20 | INFO | scrape_audio |   [KL_07] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/KL/KL_07.mp3
23:15:20 | INFO | scrape_audio |   [KL_08] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/KL/KL_08.mp3
23:15:20 | INFO | scrape_audio |   [KL_09] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/KL/KL_09.mp3
23:15:20 | INFO | scrape_audio |   [KL_10] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/KL/KL_10.mp3
23:15:20 | INFO | scrape_audio |   [KL_11] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/KL/KL_11.mp3
23:15:20 | INFO | scrape_audio |   [KL_12] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/KL/KL_12.mp3
23:15:20 | INFO | scrape_audio |   [KL_13] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/KL/KL_13.mp3
23:15:20 | INFO | scrape_audio |   [KL_14] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/KL/KL_14.mp3
23:15:20 | INFO | scrape_audio |   [KL_15] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/KL/KL_15.mp3
23:15:20 | INFO | scrape_audio |
────────────────────────────────────────────────────────────
23:15:20 | INFO | scrape_audio | Artist: J. Cole  (JC)
23:15:20 | INFO | scrape_audio |   [JC_01] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/JC/JC_01.mp3
23:15:20 | INFO | scrape_audio |   [JC_02] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/JC/JC_02.mp3
23:15:20 | INFO | scrape_audio |   [JC_03] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/JC/JC_03.mp3
23:15:20 | INFO | scrape_audio |   [JC_04] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/JC/JC_04.mp3
23:15:20 | INFO | scrape_audio |   [JC_05] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/JC/JC_05.mp3
23:15:20 | INFO | scrape_audio |   [JC_06] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/JC/JC_06.mp3
23:15:20 | INFO | scrape_audio |   [JC_07] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/JC/JC_07.mp3
23:15:20 | INFO | scrape_audio |   [JC_08] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/JC/JC_08.mp3
23:15:20 | INFO | scrape_audio |   [JC_09] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/JC/JC_09.mp3
23:15:20 | INFO | scrape_audio |   [JC_10] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/JC/JC_10.mp3
23:15:20 | INFO | scrape_audio |   [JC_11] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/JC/JC_11.mp3
23:15:20 | INFO | scrape_audio |   [JC_12] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/JC/JC_12.mp3
23:15:20 | INFO | scrape_audio |   [JC_13] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/JC/JC_13.mp3
23:15:20 | INFO | scrape_audio |   [JC_14] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/JC/JC_14.mp3
23:15:20 | INFO | scrape_audio |   [JC_15] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/JC/JC_15.mp3
23:15:20 | INFO | scrape_audio |
────────────────────────────────────────────────────────────
23:15:20 | INFO | scrape_audio | Artist: Drake  (DR)
23:15:20 | INFO | scrape_audio |   [DR_01] Searching: Drake Gods Plan official audio

23:15:28 | INFO | scrape_audio |     ✓ Downloaded: 'God's Plan' (199s)
23:15:32 | INFO | scrape_audio |   [DR_02] Searching: Drake Hotline Bling official audio

23:15:37 | INFO | scrape_audio |     ✓ Downloaded: 'Drake - Hotline Bling (Official Audio)' (267s)
23:15:39 | INFO | scrape_audio |   [DR_03] Searching: Drake One Dance official audio

23:15:48 | INFO | scrape_audio |     ✓ Downloaded: 'One Dance (feat. WizKid & Kyla) - Drake (Official Audio)' (174s)
23:15:51 | INFO | scrape_audio |   [DR_04] Searching: Drake Passionfruit official audio

23:15:58 | INFO | scrape_audio |     ✓ Downloaded: 'Passionfruit' (299s)
23:16:00 | INFO | scrape_audio |   [DR_05] Searching: Drake Started From the Bottom audio

23:16:05 | INFO | scrape_audio |     ✓ Downloaded: 'Started From the Bottom - Drake' (174s)
23:16:09 | INFO | scrape_audio |   [DR_06] Searching: Drake Take Care Rihanna audio

23:16:14 | INFO | scrape_audio |     ✓ Downloaded: 'Take Care' (277s)
23:16:17 | INFO | scrape_audio |   [DR_07] Searching: Drake Marvins Room audio

23:16:24 | INFO | scrape_audio |     ✓ Downloaded: 'Marvins Room' (347s)
23:16:28 | INFO | scrape_audio |   [DR_08] Searching: Drake Hold On Were Going Home audio

23:16:32 | INFO | scrape_audio |     ✓ Downloaded: 'Hold On, We're Going Home (feat. Majid Jordan)' (231s)
23:16:37 | INFO | scrape_audio |   [DR_09] Searching: Drake Forever Kanye Lil Wayne Eminem audio

23:16:43 | INFO | scrape_audio |     ✓ Downloaded: 'Drake, Kanye West, Lil Wayne, Eminem - Forever (Explicit Version) (Official Music Video)' (373s)
23:16:47 | INFO | scrape_audio |   [DR_10] Searching: Drake Best I Ever Had audio

23:16:53 | INFO | scrape_audio |     ✓ Downloaded: 'Best I Ever Had' (258s)
23:16:55 | INFO | scrape_audio |   [DR_11] Searching: Drake Fancy audio

23:17:01 | INFO | scrape_audio |     ✓ Downloaded: 'Fancy' (319s)
23:17:05 | INFO | scrape_audio |   [DR_12] Searching: Drake From Time Jhene Aiko audio

23:17:10 | INFO | scrape_audio |     ✓ Downloaded: 'From Time' (322s)
23:17:15 | INFO | scrape_audio |
────────────────────────────────────────────────────────────
23:17:15 | INFO | scrape_audio | Artist: Eminem  (EM)
23:17:15 | INFO | scrape_audio |   [EM_01] Searching: Eminem Lose Yourself official audio

23:17:21 | INFO | scrape_audio |     ✓ Downloaded: 'Lose Yourself (From "8 Mile" Soundtrack)' (321s)
23:17:25 | INFO | scrape_audio |   [EM_02] Searching: Eminem Stan Dido audio

23:17:34 | INFO | scrape_audio |     ✓ Downloaded: 'Eminem Feat Dido - Stan (Audio)' (404s)
23:17:38 | INFO | scrape_audio |   [EM_03] Searching: Eminem The Real Slim Shady audio

23:17:44 | INFO | scrape_audio |     ✓ Downloaded: 'The Real Slim Shady' (284s)
23:17:47 | INFO | scrape_audio |   [EM_04] Searching: Eminem Without Me audio

23:17:55 | INFO | scrape_audio |     ✓ Downloaded: 'Eminem - Without Me (Audio)' (291s)
23:18:00 | INFO | scrape_audio |   [EM_05] Searching: Eminem Not Afraid audio

23:18:08 | INFO | scrape_audio |     ✓ Downloaded: 'Not Afraid' (248s)
23:18:11 | INFO | scrape_audio |   [EM_06] Searching: Eminem Love The Way You Lie Rihanna audio

23:18:17 | INFO | scrape_audio |     ✓ Downloaded: 'Love The Way You Lie' (263s)
23:18:20 | INFO | scrape_audio |   [EM_07] Searching: Eminem Rap God audio

23:18:27 | INFO | scrape_audio |     ✓ Downloaded: 'Eminem - Rap God (Audio)' (366s)
23:18:31 | INFO | scrape_audio |   [EM_08] Searching: Eminem River Ed Sheeran audio

23:18:37 | INFO | scrape_audio |     ✓ Downloaded: 'Eminem - River (Audio) ft. Ed Sheeran' (222s)
23:18:41 | INFO | scrape_audio |   [EM_09] Searching: Eminem Cleanin Out My Closet audio

23:18:49 | INFO | scrape_audio |     ✓ Downloaded: 'Cleanin' Out My Closet' (298s)
23:18:53 | INFO | scrape_audio |   [EM_10] Searching: Eminem When Im Gone audio

23:18:57 | INFO | scrape_audio |     ✓ Downloaded: 'When I'm Gone (Album Version (Edited))' (280s)
23:19:01 | INFO | scrape_audio |   [EM_11] Searching: Eminem Mockingbird audio

23:19:07 | INFO | scrape_audio |     ✓ Downloaded: 'Mockingbird' (251s)
23:19:09 | INFO | scrape_audio |   [EM_12] Searching: Eminem Beautiful audio

23:19:16 | INFO | scrape_audio |     ✓ Downloaded: 'Beautiful' (393s)
23:19:20 | INFO | scrape_audio |
────────────────────────────────────────────────────────────
23:19:20 | INFO | scrape_audio | Artist: Tyler, the Creator  (TC2)
23:19:20 | INFO | scrape_audio |   [TC2_01] Searching: Tyler the Creator See You Again Kali Uchis audio

23:19:25 | INFO | scrape_audio |     ✓ Downloaded: 'Tyler, The Creator - SEE YOU AGAIN (ft. Kali Uchis)' (180s)
23:19:28 | INFO | scrape_audio |   [TC2_02] Searching: Tyler the Creator EARFQUAKE audio

23:19:33 | INFO | scrape_audio |     ✓ Downloaded: 'Tyler, The Creator - Earfquake' (190s)
23:19:37 | INFO | scrape_audio |   [TC2_03] Searching: Tyler the Creator Enjoy Right Now Today audio

23:19:43 | INFO | scrape_audio |     ✓ Downloaded: 'Enjoy Right Now, Today' (235s)
23:19:46 | INFO | scrape_audio |   [TC2_04] Searching: Tyler the Creator I THINK audio

23:19:54 | INFO | scrape_audio |     ✓ Downloaded: 'Tyler, The Creator - I THINK' (212s)
23:19:56 | INFO | scrape_audio |   [TC2_05] Searching: Tyler the Creator NEW MAGIC WAND audio

23:20:02 | INFO | scrape_audio |     ✓ Downloaded: 'NEW MAGIC WAND (Official Audio) - Tyler, The Creator' (195s)
23:20:06 | INFO | scrape_audio |   [TC2_06] Searching: Tyler the Creator WUSYANAME audio

23:20:12 | INFO | scrape_audio |     ✓ Downloaded: 'WUSYANAME (Audio)' (122s)
23:20:15 | INFO | scrape_audio |   [TC2_07] Searching: Tyler the Creator Lumberjack audio

23:20:21 | INFO | scrape_audio |     ✓ Downloaded: 'LUMBERJACK (Audio)' (138s)
23:20:25 | INFO | scrape_audio |   [TC2_08] Searching: Tyler the Creator 911 Mr Lonely audio

23:20:30 | INFO | scrape_audio |     ✓ Downloaded: 'Tyler, The Creator - 911 / Mr. Lonely (Audio)' (256s)
23:20:32 | INFO | scrape_audio |   [TC2_09] Searching: Tyler the Creator Who Dat Boy audio

23:20:41 | INFO | scrape_audio |     ✓ Downloaded: 'Tyler, The Creator - Who Dat Boy' (226s)
23:20:46 | INFO | scrape_audio |   [TC2_10] Searching: Tyler the Creator Gone Gone Thank You audio

23:20:55 | INFO | scrape_audio |     ✓ Downloaded: 'Tyler, The Creator - GONE, GONE / THANK YOU' (377s)
23:20:58 | INFO | scrape_audio |   [TC2_11] Searching: Tyler the Creator Foreword Rex Orange County audio

23:21:02 | INFO | scrape_audio |     ✓ Downloaded: 'Tyler, The Creator - Foreword (Audio) ft. Rex Orange County' (194s)
23:21:05 | INFO | scrape_audio |   [TC2_12] Searching: Tyler the Creator MASSA audio

23:21:09 | INFO | scrape_audio |     ✓ Downloaded: 'MASSA (Audio)' (224s)
23:21:13 | INFO | scrape_audio |
────────────────────────────────────────────────────────────
23:21:13 | INFO | scrape_audio | Artist: Mac Miller  (MM)
23:21:13 | INFO | scrape_audio |   [MM_01] Searching: Mac Miller Self Care audio

23:21:19 | INFO | scrape_audio |     ✓ Downloaded: 'Mac Miller - Self Care' (347s)
23:21:22 | INFO | scrape_audio |   [MM_02] Searching: Mac Miller Small Worlds audio

23:21:30 | INFO | scrape_audio |     ✓ Downloaded: 'Mac Miller - Small Worlds' (272s)
23:21:34 | INFO | scrape_audio |   [MM_03] Searching: Mac Miller Circles audio

23:21:40 | INFO | scrape_audio |     ✓ Downloaded: 'Mac Miller - Circles' (170s)
23:21:43 | INFO | scrape_audio |   [MM_04] Searching: Mac Miller 2009 audio

23:21:48 | INFO | scrape_audio |     ✓ Downloaded: 'Mac Miller - 2009' (348s)
23:21:50 | INFO | scrape_audio |   [MM_05] Searching: Mac Miller Objects in the Mirror audio

23:21:57 | INFO | scrape_audio |     ✓ Downloaded: 'Objects in the Mirror' (259s)
23:22:00 | INFO | scrape_audio |   [MM_06] Searching: Mac Miller Diablo audio

23:22:08 | INFO | scrape_audio |     ✓ Downloaded: 'Diablo' (198s)
23:22:11 | INFO | scrape_audio |   [MM_07] Searching: Mac Miller Programs audio

23:22:19 | INFO | scrape_audio |     ✓ Downloaded: 'Mac Miller - Programs' (190s)
23:22:21 | INFO | scrape_audio |   [MM_08] Searching: Mac Miller Dunno audio

23:22:26 | INFO | scrape_audio |     ✓ Downloaded: 'Mac Miller - Dunno' (237s)
23:22:29 | INFO | scrape_audio |   [MM_09] Searching: Mac Miller Come Back to Earth audio

23:22:36 | INFO | scrape_audio |     ✓ Downloaded: 'Mac Miller - Come Back To Earth' (203s)
23:22:39 | INFO | scrape_audio |   [MM_10] Searching: Mac Miller Good News audio

23:22:46 | INFO | scrape_audio |     ✓ Downloaded: 'Mac Miller - Good News' (397s)
23:22:50 | INFO | scrape_audio |   [MM_11] Searching: Mac Miller Whats the Use audio

23:22:58 | INFO | scrape_audio |     ✓ Downloaded: 'Mac Miller - What's The Use?' (289s)
23:23:01 | INFO | scrape_audio |   [MM_12] Searching: Mac Miller Grand Finale audio

23:23:07 | INFO | scrape_audio |     ✓ Downloaded: 'Mac Miller - Grand Finale' (211s)
23:23:10 | INFO | scrape_audio |
────────────────────────────────────────────────────────────
23:23:10 | INFO | scrape_audio | Artist: Chance the Rapper  (CH)
23:23:10 | INFO | scrape_audio |   [CH_01] Searching: Chance the Rapper Blessings audio

23:23:15 | INFO | scrape_audio |     ✓ Downloaded: 'Blessings (feat. Jamila Woods)' (222s)
23:23:20 | INFO | scrape_audio |   [CH_02] Searching: Chance the Rapper No Problem Lil Wayne 2 Chainz audio

23:23:28 | INFO | scrape_audio |     ✓ Downloaded: 'No Problem (feat. Lil Wayne & 2 Chainz)' (305s)
23:23:32 | INFO | scrape_audio |   [CH_03] Searching: Chance the Rapper Same Drugs audio

23:23:41 | INFO | scrape_audio |     ✓ Downloaded: 'Same Drugs' (258s)
23:23:43 | INFO | scrape_audio |   [CH_04] Searching: Chance the Rapper Angels Saba audio

23:23:50 | INFO | scrape_audio |     ✓ Downloaded: 'Chance The Rapper ft. Saba - Angels' (213s)
23:23:53 | INFO | scrape_audio |   [CH_05] Searching: Chance the Rapper Paranoia audio

23:23:58 | INFO | scrape_audio |     ✓ Downloaded: 'Paranoia (feat. Nosaj Thing) [Audio]' (276s)
23:24:03 | INFO | scrape_audio |   [CH_06] Searching: Chance the Rapper Sunday Candy audio

23:24:12 | INFO | scrape_audio |     ✓ Downloaded: 'Donnie Trumpet & The Social Experiment - Sunday Candy' (227s)
23:24:17 | INFO | scrape_audio |   [CH_07] Searching: Chance the Rapper Favorite Song Childish Gambino audio

23:24:26 | INFO | scrape_audio |     ✓ Downloaded: 'Favorite Song (feat. Childish Gambino) [Audio]' (185s)
23:24:29 | INFO | scrape_audio |   [CH_08] Searching: Chance the Rapper All We Got Kanye West audio

23:24:34 | INFO | scrape_audio |     ✓ Downloaded: 'All We Got (feat. Kanye West & Chicago Children's Choir)' (204s)
23:24:38 | INFO | scrape_audio |   [CH_09] Searching: Chance the Rapper Cocoa Butter Kisses audio

23:24:44 | INFO | scrape_audio |     ✓ Downloaded: 'Cocoa Butter Kisses (feat. Vic Mensa & Twista) [Audio]' (308s)
23:24:48 | INFO | scrape_audio |   [CH_10] Searching: Chance the Rapper Smoke Again audio

23:24:52 | INFO | scrape_audio |     ✓ Downloaded: 'Chance The Rapper - Smoke Again Ft. Ab-Soul (Official Video) #ILLROOTS3' (199s)
23:24:55 | INFO | scrape_audio |   [CH_11] Searching: Chance the Rapper Hot Shower DaBaby audio

23:25:01 | INFO | scrape_audio |     ✓ Downloaded: 'Chance The Rapper - Hot Shower ( ft. DaBaby and MadeinTYO)' (226s)
23:25:05 | INFO | scrape_audio |   [CH_12] Searching: Chance the Rapper I Might Need Security audio

23:25:10 | INFO | scrape_audio |     ✓ Downloaded: 'Chance the Rapper - I Might Need Security (Audio)' (241s)
23:25:13 | INFO | scrape_audio |
────────────────────────────────────────────────────────────
23:25:13 | INFO | scrape_audio | Artist: Nas  (NS)
23:25:13 | INFO | scrape_audio |   [NS_01] Searching: Nas NY State of Mind audio

23:25:18 | INFO | scrape_audio |     ✓ Downloaded: 'Nas - N.Y. State of Mind (Official Audio)' (296s)
23:25:21 | INFO | scrape_audio |   [NS_02] Searching: Nas The World Is Yours audio

23:25:30 | INFO | scrape_audio |     ✓ Downloaded: 'The World Is Yours' (290s)
23:25:34 | INFO | scrape_audio |   [NS_03] Searching: Nas One Love audio

23:25:40 | INFO | scrape_audio |     ✓ Downloaded: 'Nas -- One Love' (330s)
23:25:45 | INFO | scrape_audio |   [NS_04] Searching: Nas If I Ruled the World Lauryn Hill audio

23:25:50 | INFO | scrape_audio |     ✓ Downloaded: 'Nas - If I Ruled the World (Imagine That) (Official Audio) ft. Lauryn Hill' (284s)
23:25:53 | INFO | scrape_audio |   [NS_05] Searching: Nas Hate Me Now audio

23:25:58 | INFO | scrape_audio |     ✓ Downloaded: 'Hate Me Now' (284s)
23:26:02 | INFO | scrape_audio |   [NS_06] Searching: Nas One Mic audio

23:26:08 | INFO | scrape_audio |     ✓ Downloaded: 'Nas - One Mic (Dirty Version)' (261s)
23:26:11 | INFO | scrape_audio |   [NS_07] Searching: Nas Made You Look audio

23:26:16 | INFO | scrape_audio |     ✓ Downloaded: 'Nas - Made You Look' (203s)
23:26:19 | INFO | scrape_audio |   [NS_08] Searching: Nas Daughters audio

23:26:27 | INFO | scrape_audio |     ✓ Downloaded: 'Nas - Daughters' (195s)
23:26:31 | INFO | scrape_audio |   [NS_09] Searching: Nas Illmatic audio

23:26:43 | INFO | scrape_audio |     ✓ Downloaded: 'Nas - Illmatic - [Full Album] - (Cassette Side B) - HQ Highest Quality' (1255s)
23:26:47 | INFO | scrape_audio |   [NS_10] Searching: Nas Represent audio

23:26:53 | INFO | scrape_audio |     ✓ Downloaded: 'Nas - Represent (Official Audio)' (254s)
23:26:57 | INFO | scrape_audio |   [NS_11] Searching: Nas Lifes a Bitch AZ audio

23:27:02 | INFO | scrape_audio |     ✓ Downloaded: 'Nas - Life's a Bitch (Official Audio) ft. AZ, Olu Dara' (212s)
23:27:06 | INFO | scrape_audio |   [NS_12] Searching: Nas Cherry Wine Amy Winehouse audio

23:27:11 | INFO | scrape_audio |     ✓ Downloaded: 'Nas ft. Amy Winehouse - Cherry Wine (CDQ HD)' (357s)
23:27:14 | INFO | scrape_audio |
────────────────────────────────────────────────────────────
23:27:14 | INFO | scrape_audio | Artist: Childish Gambino  (CG)
23:27:14 | INFO | scrape_audio |   [CG_01] Searching: Childish Gambino Redbone audio

23:27:19 | INFO | scrape_audio |     ✓ Downloaded: 'Childish Gambino|Redbone Official Audio' (327s)
23:27:22 | INFO | scrape_audio |   [CG_02] Searching: Childish Gambino This Is America audio

23:27:30 | INFO | scrape_audio |     ✓ Downloaded: 'This Is America' (226s)
23:27:32 | INFO | scrape_audio |   [CG_03] Searching: Childish Gambino 3005 audio

23:27:41 | INFO | scrape_audio |     ✓ Downloaded: 'V. 3005' (234s)
23:27:44 | INFO | scrape_audio |   [CG_04] Searching: Childish Gambino Sober audio

23:27:52 | INFO | scrape_audio |     ✓ Downloaded: 'Childish Gambino - Sober' (252s)
23:27:55 | INFO | scrape_audio |   [CG_05] Searching: Childish Gambino Sweatpants audio

23:28:03 | INFO | scrape_audio |     ✓ Downloaded: 'IV. Sweatpants' (181s)
23:28:07 | INFO | scrape_audio |   [CG_06] Searching: Childish Gambino Camp audio

23:28:11 | INFO | scrape_audio |     ✓ Downloaded: 'Bonfire' (195s)
23:28:13 | INFO | scrape_audio |   [CG_07] Searching: Childish Gambino Me and Your Mama audio

23:28:20 | INFO | scrape_audio |     ✓ Downloaded: 'Childish Gambino|Me and Your Mama Official Audio' (379s)
23:28:24 | INFO | scrape_audio |   [CG_08] Searching: Childish Gambino Terrified audio

23:28:33 | INFO | scrape_audio |     ✓ Downloaded: 'Childish Gambino - Terrified (Official Audio)' (255s)
23:28:36 | INFO | scrape_audio |   [CG_09] Searching: Childish Gambino Heartbeat audio

23:28:44 | INFO | scrape_audio |     ✓ Downloaded: 'Heartbeat' (266s)
23:28:48 | INFO | scrape_audio |   [CG_10] Searching: Childish Gambino Outside audio

23:28:57 | INFO | scrape_audio |     ✓ Downloaded: 'Outside' (270s)
23:29:01 | INFO | scrape_audio |   [CG_11] Searching: Childish Gambino telegraphs audio

23:29:09 | INFO | scrape_audio |     ✓ Downloaded: 'III. Telegraph Ave. ("Oakland" By Lloyd)' (211s)
23:29:12 | INFO | scrape_audio |   [CG_12] Searching: Childish Gambino California audio

23:29:19 | INFO | scrape_audio |     ✓ Downloaded: 'Childish Gambino - California (Official Audio)' (165s)
23:29:22 | INFO | scrape_audio |
────────────────────────────────────────────────────────────
23:29:22 | INFO | scrape_audio | Artist: Grateful Dead  (GD)
23:29:22 | INFO | scrape_audio |   [GD_01] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/GD/GD_01.mp3
23:29:22 | INFO | scrape_audio |   [GD_02] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/GD/GD_02.mp3
23:29:22 | INFO | scrape_audio |   [GD_03] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/GD/GD_03.mp3
23:29:22 | INFO | scrape_audio |   [GD_04] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/GD/GD_04.mp3
23:29:22 | INFO | scrape_audio |   [GD_05] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/GD/GD_05.mp3
23:29:22 | INFO | scrape_audio |   [GD_06] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/GD/GD_06.mp3
23:29:22 | INFO | scrape_audio |   [GD_07] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/GD/GD_07.mp3
23:29:22 | INFO | scrape_audio |   [GD_08] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/GD/GD_08.mp3
23:29:22 | INFO | scrape_audio |   [GD_09] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/GD/GD_09.mp3
23:29:22 | INFO | scrape_audio |   [GD_10] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/GD/GD_10.mp3
23:29:22 | INFO | scrape_audio |   [GD_11] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/GD/GD_11.mp3
23:29:22 | INFO | scrape_audio |   [GD_12] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/GD/GD_12.mp3
23:29:22 | INFO | scrape_audio |   [GD_13] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/GD/GD_13.mp3
23:29:22 | INFO | scrape_audio |   [GD_14] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/GD/GD_14.mp3
23:29:22 | INFO | scrape_audio |   [GD_15] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/GD/GD_15.mp3
23:29:22 | INFO | scrape_audio |
────────────────────────────────────────────────────────────
23:29:22 | INFO | scrape_audio | Artist: Bob Dylan  (BD)
23:29:22 | INFO | scrape_audio |   [BD_01] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/BD/BD_01.mp3
23:29:22 | INFO | scrape_audio |   [BD_02] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/BD/BD_02.mp3
23:29:22 | INFO | scrape_audio |   [BD_03] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/BD/BD_03.mp3
23:29:22 | INFO | scrape_audio |   [BD_04] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/BD/BD_04.mp3
23:29:22 | INFO | scrape_audio |   [BD_05] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/BD/BD_05.mp3
23:29:22 | INFO | scrape_audio |   [BD_06] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/BD/BD_06.mp3
23:29:22 | INFO | scrape_audio |   [BD_07] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/BD/BD_07.mp3
23:29:22 | INFO | scrape_audio |   [BD_08] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/BD/BD_08.mp3
23:29:22 | INFO | scrape_audio |   [BD_09] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/BD/BD_09.mp3
23:29:22 | INFO | scrape_audio |   [BD_10] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/BD/BD_10.mp3
23:29:22 | INFO | scrape_audio |   [BD_11] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/BD/BD_11.mp3
23:29:22 | INFO | scrape_audio |   [BD_12] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/BD/BD_12.mp3
23:29:22 | INFO | scrape_audio |   [BD_13] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/BD/BD_13.mp3
23:29:22 | INFO | scrape_audio |   [BD_14] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/BD/BD_14.mp3
23:29:22 | INFO | scrape_audio |   [BD_15] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/BD/BD_15.mp3
23:29:22 | INFO | scrape_audio |
────────────────────────────────────────────────────────────
23:29:22 | INFO | scrape_audio | Artist: Tyler Childers  (TC)
23:29:22 | INFO | scrape_audio |   [TC_01] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TC/TC_01.mp3
23:29:22 | INFO | scrape_audio |   [TC_02] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TC/TC_02.mp3
23:29:22 | INFO | scrape_audio |   [TC_03] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TC/TC_03.mp3
23:29:22 | INFO | scrape_audio |   [TC_04] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TC/TC_04.mp3
23:29:22 | INFO | scrape_audio |   [TC_05] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TC/TC_05.mp3
23:29:22 | INFO | scrape_audio |   [TC_06] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TC/TC_06.mp3
23:29:22 | INFO | scrape_audio |   [TC_07] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TC/TC_07.mp3
23:29:22 | INFO | scrape_audio |   [TC_08] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TC/TC_08.mp3
23:29:22 | INFO | scrape_audio |   [TC_09] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TC/TC_09.mp3
23:29:22 | INFO | scrape_audio |   [TC_10] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TC/TC_10.mp3
23:29:22 | INFO | scrape_audio |   [TC_11] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TC/TC_11.mp3
23:29:22 | INFO | scrape_audio |   [TC_12] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TC/TC_12.mp3
23:29:22 | INFO | scrape_audio |   [TC_13] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TC/TC_13.mp3
23:29:22 | INFO | scrape_audio |   [TC_14] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TC/TC_14.mp3
23:29:22 | INFO | scrape_audio |   [TC_15] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TC/TC_15.mp3
23:29:22 | INFO | scrape_audio |
────────────────────────────────────────────────────────────
23:29:22 | INFO | scrape_audio | Artist: Jason Isbell  (JI)
23:29:22 | INFO | scrape_audio |   [JI_01] Searching: Jason Isbell Cover Me Up audio

23:29:29 | INFO | scrape_audio |     ✓ Downloaded: 'Cover Me Up' (294s)
23:29:33 | INFO | scrape_audio |   [JI_02] Searching: Jason Isbell If We Were Vampires audio

23:29:40 | INFO | scrape_audio |     ✓ Downloaded: 'Jason Isbell and the 400 Unit - If We Were Vampires' (236s)
23:29:43 | INFO | scrape_audio |   [JI_03] Searching: Jason Isbell Death Wish audio

23:29:50 | INFO | scrape_audio |     ✓ Downloaded: 'Jason Isbell and the 400 Unit - Death Wish (Official Lyric Video)' (278s)
23:29:54 | INFO | scrape_audio |   [JI_04] Searching: Jason Isbell White Mans World audio

23:29:59 | INFO | scrape_audio |     ✓ Downloaded: 'Jason Isbell and the 400 Unit - White Man's World' (237s)
23:30:03 | INFO | scrape_audio |   [JI_05] Searching: Jason Isbell Last of My Kind audio

23:30:09 | INFO | scrape_audio |     ✓ Downloaded: 'Last of My Kind' (262s)
23:30:13 | INFO | scrape_audio |   [JI_06] Searching: Jason Isbell Something More Than Free audio

23:30:17 | INFO | scrape_audio |     ✓ Downloaded: 'Something More Than Free - Lyric Video' (211s)
23:30:21 | INFO | scrape_audio |   [JI_07] Searching: Jason Isbell Outfit audio

23:30:30 | INFO | scrape_audio |     ✓ Downloaded: 'Jason Isbell and the 400 Unit - Outfit (Live on KEXP)' (272s)
23:30:33 | INFO | scrape_audio |   [JI_08] Searching: Jason Isbell Elephant audio

23:30:38 | INFO | scrape_audio |     ✓ Downloaded: 'Jason Isbell and the 400 Unit - Elephant' (280s)
23:30:42 | INFO | scrape_audio |   [JI_09] Searching: Jason Isbell Speed Trap Town audio

23:30:48 | INFO | scrape_audio |     ✓ Downloaded: 'Speed Trap Town' (242s)
23:30:52 | INFO | scrape_audio |   [JI_10] Searching: Jason Isbell Relatively Easy audio

23:30:56 | INFO | scrape_audio |     ✓ Downloaded: 'Relatively Easy (Demo)' (249s)
23:30:59 | INFO | scrape_audio |   [JI_11] Searching: Jason Isbell Flying Over Water audio

23:31:05 | INFO | scrape_audio |     ✓ Downloaded: 'Jason Isbell - Flying Over Water (Live on KEXP)' (241s)
23:31:09 | INFO | scrape_audio |   [JI_12] Searching: Jason Isbell Children of Children audio

23:31:16 | INFO | scrape_audio |     ✓ Downloaded: 'Jason Isbell - Children of Children (Lyric Video)' (352s)
23:31:18 | INFO | scrape_audio |
────────────────────────────────────────────────────────────
23:31:18 | INFO | scrape_audio | Artist: Sturgill Simpson  (SS)
23:31:18 | INFO | scrape_audio |   [SS_01] Searching: Sturgill Simpson Turtles All the Way Down audio

23:31:25 | INFO | scrape_audio |     ✓ Downloaded: 'Sturgill Simpson - Turtles All The Way Down (Official 4K Video)' (183s)
23:31:29 | INFO | scrape_audio |   [SS_02] Searching: Sturgill Simpson Life of Sin audio

23:31:35 | INFO | scrape_audio |     ✓ Downloaded: 'Sturgill Simpson - Life of Sin (Live from RCA Studio A)' (166s)
23:31:37 | INFO | scrape_audio |   [SS_03] Searching: Sturgill Simpson Long White Line audio

23:31:45 | INFO | scrape_audio |     ✓ Downloaded: 'Sturgill Simpson - Long White Line' (241s)
23:31:50 | INFO | scrape_audio |   [SS_04] Searching: Sturgill Simpson Brace for Impact audio

23:31:56 | INFO | scrape_audio |     ✓ Downloaded: 'Sturgill Simpson - "Brace For Impact (Live A Little)"' (350s)
23:32:00 | INFO | scrape_audio |   [SS_05] Searching: Sturgill Simpson In Bloom audio

23:32:05 | INFO | scrape_audio |     ✓ Downloaded: 'Sturgill Simpson - "In Bloom"' (251s)
23:32:09 | INFO | scrape_audio |   [SS_06] Searching: Sturgill Simpson Welcome to Earth audio

23:32:18 | INFO | scrape_audio |     ✓ Downloaded: 'Welcome to Earth (Pollywog)' (293s)
23:32:22 | INFO | scrape_audio |   [SS_07] Searching: Sturgill Simpson Keep It Between the Lines audio

23:32:28 | INFO | scrape_audio |     ✓ Downloaded: 'Keep It Between the Lines' (241s)
23:32:32 | INFO | scrape_audio |   [SS_08] Searching: Sturgill Simpson Water in a Well audio

23:32:37 | INFO | scrape_audio |     ✓ Downloaded: 'Sturgill Simpson - "Water in a Well" (Live at Sun King Brewery)' (268s)
23:32:39 | INFO | scrape_audio |   [SS_09] Searching: Sturgill Simpson Call to Arms audio

23:32:48 | INFO | scrape_audio |     ✓ Downloaded: 'Call to Arms' (330s)
23:32:51 | INFO | scrape_audio |   [SS_10] Searching: Sturgill Simpson Oh Sarah audio

23:33:00 | INFO | scrape_audio |     ✓ Downloaded: 'Oh Sarah' (255s)
23:33:02 | INFO | scrape_audio |   [SS_11] Searching: Sturgill Simpson You Can Have the Crown audio

23:33:12 | INFO | scrape_audio |     ✓ Downloaded: 'Sturgill Simpson - "You Can Have The Crown / Some Days" (Live at Sun King Brewery)' (360s)
23:33:17 | INFO | scrape_audio |   [SS_12] Searching: Sturgill Simpson All Around You audio

23:33:25 | INFO | scrape_audio |     ✓ Downloaded: 'Sturgill Simpson - "All Around You"' (219s)
23:33:29 | INFO | scrape_audio |
────────────────────────────────────────────────────────────
23:33:29 | INFO | scrape_audio | Artist: Kacey Musgraves  (KM)
23:33:29 | INFO | scrape_audio |   [KM_01] Searching: Kacey Musgraves Golden Hour audio

23:33:35 | INFO | scrape_audio |     ✓ Downloaded: 'Kacey Musgraves - Golden Hour (Official Audio)' (201s)
23:33:39 | INFO | scrape_audio |   [KM_02] Searching: Kacey Musgraves Butterflies audio

23:33:46 | INFO | scrape_audio |     ✓ Downloaded: 'Kacey Musgraves - Butterflies (Official Audio)' (220s)
23:33:48 | INFO | scrape_audio |   [KM_03] Searching: Kacey Musgraves Happy and Sad audio

23:33:55 | INFO | scrape_audio |     ✓ Downloaded: 'Kacey Musgraves - Happy & Sad (Official Audio)' (244s)
23:33:58 | INFO | scrape_audio |   [KM_04] Searching: Kacey Musgraves Space Cowboy audio

23:34:03 | INFO | scrape_audio |     ✓ Downloaded: 'Kacey Musgraves - Space Cowboy (Official Audio)' (221s)
23:34:06 | INFO | scrape_audio |   [KM_05] Searching: Kacey Musgraves Rainbow audio

23:39:19 | INFO | scrape_audio |     ✓ Downloaded: 'Kacey Musgraves - Rainbow (Official Audio)' (215s)
23:39:21 | INFO | scrape_audio |   [KM_06] Searching: Kacey Musgraves Slow Burn audio

23:39:29 | INFO | scrape_audio |     ✓ Downloaded: 'Kacey Musgraves - Slow Burn (Official Audio)' (247s)
23:39:34 | INFO | scrape_audio |   [KM_07] Searching: Kacey Musgraves Lonely Weekend audio

23:39:39 | INFO | scrape_audio |     ✓ Downloaded: 'Kacey Musgraves - Lonely Weekend (Official Audio)' (228s)
23:43:56 | INFO | scrape_audio |   [KM_08] Searching: Kacey Musgraves Follow Your Arrow audio

23:44:00 | INFO | scrape_audio |     ✓ Downloaded: 'Kacey Musgraves - Follow Your Arrow (Audio)' (201s)
23:44:03 | INFO | scrape_audio |   [KM_09] Searching: Kacey Musgraves Merry Go Round audio

23:44:10 | INFO | scrape_audio |     ✓ Downloaded: 'Kacey Musgraves - Merry Go 'Round (Official Music Video)' (205s)
23:44:13 | INFO | scrape_audio |   [KM_10] Searching: Kacey Musgraves Velvet Elvis audio

23:44:19 | INFO | scrape_audio |     ✓ Downloaded: 'Kacey Musgraves - Velvet Elvis (Official Audio)' (155s)
23:44:24 | INFO | scrape_audio |   [KM_11] Searching: Kacey Musgraves Justified audio

23:44:30 | INFO | scrape_audio |     ✓ Downloaded: 'KACEY MUSGRAVES - justified (official lyric video)' (193s)
23:44:35 | INFO | scrape_audio |   [KM_12] Searching: Kacey Musgraves Keep Lookin Up audio

23:44:43 | INFO | scrape_audio |     ✓ Downloaded: 'KACEY MUSGRAVES - keep lookin’ up (official lyric video)' (176s)
23:44:48 | INFO | scrape_audio |
────────────────────────────────────────────────────────────
23:44:48 | INFO | scrape_audio | Artist: John Prine  (JP)
23:44:48 | INFO | scrape_audio |   [JP_01] Searching: John Prine Angel from Montgomery audio

23:44:53 | INFO | scrape_audio |     ✓ Downloaded: 'Angel from Montgomery' (222s)
23:44:55 | INFO | scrape_audio |   [JP_02] Searching: John Prine Sam Stone audio

23:44:59 | INFO | scrape_audio |     ✓ Downloaded: 'John Prine - Sam Stone' (255s)
23:45:04 | INFO | scrape_audio |   [JP_03] Searching: John Prine Hello in There audio

23:45:10 | INFO | scrape_audio |     ✓ Downloaded: 'John Prine - Hello In There (Live From Sessions at West 54th)' (359s)
23:45:13 | INFO | scrape_audio |   [JP_04] Searching: John Prine Paradise audio

23:45:20 | INFO | scrape_audio |     ✓ Downloaded: 'Paradise' (196s)
23:45:23 | INFO | scrape_audio |   [JP_05] Searching: John Prine Spanish Pipedream audio

23:45:29 | INFO | scrape_audio |     ✓ Downloaded: 'John Prine - Spanish Pipedream (Live From Sessions at West 54th)' (216s)
23:45:33 | INFO | scrape_audio |   [JP_06] Searching: John Prine Donald and Lydia audio

23:45:40 | INFO | scrape_audio |     ✓ Downloaded: 'Donald and Lydia' (271s)
23:45:42 | INFO | scrape_audio |   [JP_07] Searching: John Prine Souvenirs audio

23:45:48 | INFO | scrape_audio |     ✓ Downloaded: 'Souvenirs (2020 Remaster)' (218s)
23:45:51 | INFO | scrape_audio |   [JP_08] Searching: John Prine Lake Marie audio

23:46:02 | INFO | scrape_audio |     ✓ Downloaded: 'John Prine - Lake Marie (Live From Sessions at West 54th)' (594s)
23:46:04 | INFO | scrape_audio |   [JP_09] Searching: John Prine In Spite of Ourselves audio

23:46:12 | INFO | scrape_audio |     ✓ Downloaded: 'John Prine - In Spite of Ourselves - In Spite of Ourselves' (214s)
23:46:15 | INFO | scrape_audio |   [JP_10] Searching: John Prine Summers End audio

23:46:20 | INFO | scrape_audio |     ✓ Downloaded: 'John Prine - Summer's End Lyric Video' (221s)
23:46:23 | INFO | scrape_audio |   [JP_11] Searching: John Prine When I Get to Heaven audio

23:46:29 | INFO | scrape_audio |     ✓ Downloaded: 'John Prine "When I Get To Heaven"' (219s)
23:46:31 | INFO | scrape_audio |   [JP_12] Searching: John Prine Far From Me audio

23:46:36 | INFO | scrape_audio |     ✓ Downloaded: 'Far from Me (2020 Remaster)' (222s)
23:46:38 | INFO | scrape_audio |
────────────────────────────────────────────────────────────
23:46:38 | INFO | scrape_audio | Artist: Gillian Welch  (GW)
23:46:38 | INFO | scrape_audio |   [GW_01] Searching: Gillian Welch Everything Is Free audio

23:46:44 | INFO | scrape_audio |     ✓ Downloaded: 'Gillian Welch - Everything Is Free' (292s)
23:46:47 | INFO | scrape_audio |   [GW_02] Searching: Gillian Welch Time The Revelator audio

23:46:57 | INFO | scrape_audio |     ✓ Downloaded: 'Revelator' (381s)
23:46:59 | INFO | scrape_audio |   [GW_03] Searching: Gillian Welch Elvis Presley Blues audio

23:47:06 | INFO | scrape_audio |     ✓ Downloaded: 'Elvis Presley Blues' (296s)
23:47:09 | INFO | scrape_audio |   [GW_04] Searching: Gillian Welch Orphan Girl audio

23:47:14 | INFO | scrape_audio |     ✓ Downloaded: 'Orphan Girl (Alternate Version)' (210s)
23:47:17 | INFO | scrape_audio |   [GW_05] Searching: Gillian Welch Acony Bell audio

23:47:21 | INFO | scrape_audio |     ✓ Downloaded: 'Acony Bell - Gillian Welch with David Rawlings (lyrics)' (187s)
23:47:24 | INFO | scrape_audio |   [GW_06] Searching: Gillian Welch Look at Miss Ohio audio

23:47:31 | INFO | scrape_audio |     ✓ Downloaded: 'Gillian Welch - Look at Miss Ohio (Vinyl Video)' (256s)
23:47:35 | INFO | scrape_audio |   [GW_07] Searching: Gillian Welch One More Dollar audio

23:47:40 | INFO | scrape_audio |     ✓ Downloaded: 'One More Dollar' (275s)
23:47:43 | INFO | scrape_audio |   [GW_08] Searching: Gillian Welch By the Mark audio

23:47:48 | INFO | scrape_audio |     ✓ Downloaded: 'By The Mark - Gillian Welch.wmv' (220s)
23:47:51 | INFO | scrape_audio |   [GW_09] Searching: Gillian Welch Revelator audio

23:47:58 | INFO | scrape_audio |     ✓ Downloaded: 'Revelator' (381s)
23:48:01 | INFO | scrape_audio |   [GW_10] Searching: Gillian Welch I Dream a Highway audio

23:48:09 | INFO | scrape_audio |     ✓ Downloaded: 'Gillian Welch - I Dream A Highway' (880s)
23:48:13 | INFO | scrape_audio |   [GW_11] Searching: Gillian Welch Dear Someone audio

23:48:21 | INFO | scrape_audio |     ✓ Downloaded: 'Dear Someone' (195s)
23:48:23 | INFO | scrape_audio |   [GW_12] Searching: Gillian Welch Rock of Ages audio

23:48:31 | INFO | scrape_audio |     ✓ Downloaded: 'GILLIAN WELCH   ROCK OF AGES' (196s)
23:48:36 | INFO | scrape_audio |
────────────────────────────────────────────────────────────
23:48:36 | INFO | scrape_audio | Artist: Colter Wall  (CW)
23:48:36 | INFO | scrape_audio |   [CW_01] Searching: Colter Wall Sleeping on the Blacktop audio

23:48:44 | INFO | scrape_audio |     ✓ Downloaded: 'Colter Wall - Sleeping on the Blacktop (Audio)' (196s)
23:48:48 | INFO | scrape_audio |   [CW_02] Searching: Colter Wall Motorcycle audio

23:48:53 | INFO | scrape_audio |     ✓ Downloaded: 'Colter Wall - Motorcycle (Audio)' (139s)
23:48:55 | INFO | scrape_audio |   [CW_03] Searching: Colter Wall Imaginary Appalachia audio

23:49:11 | INFO | scrape_audio |     ✓ Downloaded: 'Colter Wall “IMAGINARY APPALACHIA”Full Album 2015' (1375s)
23:49:14 | INFO | scrape_audio |   [CW_04] Searching: Colter Wall Devil Wears a Suit and Tie audio

23:49:22 | INFO | scrape_audio |     ✓ Downloaded: 'Colter Wall - The Devil Wears a Suit and Tie (Audio)' (238s)
23:49:24 | INFO | scrape_audio |   [CW_05] Searching: Colter Wall Brands audio

23:49:32 | INFO | scrape_audio |     ✓ Downloaded: 'Colter Wall' (154s)
23:49:35 | INFO | scrape_audio |   [CW_06] Searching: Colter Wall Wild Dogs audio

23:49:41 | INFO | scrape_audio |     ✓ Downloaded: 'Colter Wall - Wild Dogs (Audio)' (294s)
23:49:44 | INFO | scrape_audio |   [CW_07] Searching: Colter Wall John Beyers audio

23:49:51 | INFO | scrape_audio |     ✓ Downloaded: 'Colter Wall - John Beyers (Camaro Song) (Audio)' (123s)
23:49:56 | INFO | scrape_audio |   [CW_08] Searching: Colter Wall Western Swing Slow Country audio

23:50:03 | INFO | scrape_audio |     ✓ Downloaded: 'Colter Wall | "Cowpoke" | Western AF' (194s)
23:50:07 | INFO | scrape_audio |   [CW_09] Searching: Colter Wall Plain to See Plainsman audio

23:50:15 | INFO | scrape_audio |     ✓ Downloaded: 'Colter Wall - Plain to See Plainsman (Audio)' (233s)
23:50:20 | INFO | scrape_audio |   [CW_10] Searching: Colter Wall Tying Knots audio

23:50:27 | INFO | scrape_audio |     ✓ Downloaded: 'Colter Wall - Tying Knots in the Devil's Tail (Audio)' (158s)
23:50:29 | INFO | scrape_audio |   [CW_11] Searching: Colter Wall Im So Lonesome I Could Cry audio

23:50:36 | INFO | scrape_audio |     ✓ Downloaded: 'Sam Williams - I’M SO LONESOME I COULD CRY (Official Audio)' (206s)
23:50:40 | INFO | scrape_audio |   [CW_12] Searching: Colter Wall Song of the Plains audio

23:50:45 | INFO | scrape_audio |     ✓ Downloaded: 'Colter Wall - Plain to See Plainsman (Audio)' (233s)
23:50:47 | INFO | scrape_audio |
────────────────────────────────────────────────────────────
23:50:47 | INFO | scrape_audio | Artist: Taylor Swift  (TS)
23:50:47 | INFO | scrape_audio |   [TS_01] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TS/TS_01.mp3
23:50:47 | INFO | scrape_audio |   [TS_02] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TS/TS_02.mp3
23:50:47 | INFO | scrape_audio |   [TS_03] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TS/TS_03.mp3
23:50:47 | INFO | scrape_audio |   [TS_04] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TS/TS_04.mp3
23:50:47 | INFO | scrape_audio |   [TS_05] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TS/TS_05.mp3
23:50:47 | INFO | scrape_audio |   [TS_06] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TS/TS_06.mp3
23:50:47 | INFO | scrape_audio |   [TS_07] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TS/TS_07.mp3
23:50:47 | INFO | scrape_audio |   [TS_08] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TS/TS_08.mp3
23:50:47 | INFO | scrape_audio |   [TS_09] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TS/TS_09.mp3
23:50:47 | INFO | scrape_audio |   [TS_10] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TS/TS_10.mp3
23:50:47 | INFO | scrape_audio |   [TS_11] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TS/TS_11.mp3
23:50:47 | INFO | scrape_audio |   [TS_12] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TS/TS_12.mp3
23:50:47 | INFO | scrape_audio |   [TS_13] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TS/TS_13.mp3
23:50:47 | INFO | scrape_audio |   [TS_14] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TS/TS_14.mp3
23:50:47 | INFO | scrape_audio |   [TS_15] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TS/TS_15.mp3
23:50:47 | INFO | scrape_audio |
────────────────────────────────────────────────────────────
23:50:47 | INFO | scrape_audio | Artist: The Weeknd  (TW)
23:50:47 | INFO | scrape_audio |   [TW_01] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TW/TW_01.mp3
23:50:47 | INFO | scrape_audio |   [TW_02] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TW/TW_02.mp3
23:50:47 | INFO | scrape_audio |   [TW_03] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TW/TW_03.mp3
23:50:47 | INFO | scrape_audio |   [TW_04] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TW/TW_04.mp3
23:50:47 | INFO | scrape_audio |   [TW_05] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TW/TW_05.mp3
23:50:47 | INFO | scrape_audio |   [TW_06] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TW/TW_06.mp3
23:50:47 | INFO | scrape_audio |   [TW_07] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TW/TW_07.mp3
23:50:47 | INFO | scrape_audio |   [TW_08] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TW/TW_08.mp3
23:50:47 | INFO | scrape_audio |   [TW_09] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TW/TW_09.mp3
23:50:47 | INFO | scrape_audio |   [TW_10] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TW/TW_10.mp3
23:50:47 | INFO | scrape_audio |   [TW_11] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TW/TW_11.mp3
23:50:47 | INFO | scrape_audio |   [TW_12] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TW/TW_12.mp3
23:50:47 | INFO | scrape_audio |   [TW_13] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TW/TW_13.mp3
23:50:47 | INFO | scrape_audio |   [TW_14] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TW/TW_14.mp3
23:50:47 | INFO | scrape_audio |   [TW_15] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/TW/TW_15.mp3
23:50:47 | INFO | scrape_audio |
────────────────────────────────────────────────────────────
23:50:47 | INFO | scrape_audio | Artist: Dua Lipa  (DL)
23:50:47 | INFO | scrape_audio |   [DL_01] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DL/DL_01.mp3
23:50:47 | INFO | scrape_audio |   [DL_02] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DL/DL_02.mp3
23:50:47 | INFO | scrape_audio |   [DL_03] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DL/DL_03.mp3
23:50:47 | INFO | scrape_audio |   [DL_04] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DL/DL_04.mp3
23:50:47 | INFO | scrape_audio |   [DL_05] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DL/DL_05.mp3
23:50:47 | INFO | scrape_audio |   [DL_06] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DL/DL_06.mp3
23:50:47 | INFO | scrape_audio |   [DL_07] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DL/DL_07.mp3
23:50:47 | INFO | scrape_audio |   [DL_08] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DL/DL_08.mp3
23:50:47 | INFO | scrape_audio |   [DL_09] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DL/DL_09.mp3
23:50:47 | INFO | scrape_audio |   [DL_10] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DL/DL_10.mp3
23:50:47 | INFO | scrape_audio |   [DL_11] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DL/DL_11.mp3
23:50:47 | INFO | scrape_audio |   [DL_12] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DL/DL_12.mp3
23:50:47 | INFO | scrape_audio |   [DL_13] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DL/DL_13.mp3
23:50:47 | INFO | scrape_audio |   [DL_14] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DL/DL_14.mp3
23:50:47 | INFO | scrape_audio |   [DL_15] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DL/DL_15.mp3
23:50:47 | INFO | scrape_audio |
────────────────────────────────────────────────────────────
23:50:47 | INFO | scrape_audio | Artist: Ariana Grande  (AG)
23:50:47 | INFO | scrape_audio |   [AG_01] Searching: Ariana Grande thank u next official audio

23:50:55 | INFO | scrape_audio |     ✓ Downloaded: 'Ariana Grande - thank u, next (audio)' (208s)
23:50:58 | INFO | scrape_audio |   [AG_02] Searching: Ariana Grande 7 rings official audio

23:51:04 | INFO | scrape_audio |     ✓ Downloaded: 'Ariana Grande - 7 rings (Official Audio)' (180s)
23:51:09 | INFO | scrape_audio |   [AG_03] Searching: Ariana Grande positions official audio

23:51:14 | INFO | scrape_audio |     ✓ Downloaded: 'positions' (172s)
23:51:17 | INFO | scrape_audio |   [AG_04] Searching: Ariana Grande God is a woman official audio

23:51:24 | INFO | scrape_audio |     ✓ Downloaded: 'Ariana Grande - God is a woman (Lyric Video)' (205s)
23:51:29 | INFO | scrape_audio |   [AG_05] Searching: Ariana Grande no tears left to cry official audio

23:51:35 | INFO | scrape_audio |     ✓ Downloaded: 'Ariana Grande - No Tears Left To Cry (Audio)' (206s)
23:51:38 | INFO | scrape_audio |   [AG_06] Searching: Ariana Grande Problem Iggy Azalea audio

23:51:46 | INFO | scrape_audio |     ✓ Downloaded: 'Ariana Grande: Problem Ft. Iggy Azalea (Audio)' (195s)
23:51:51 | INFO | scrape_audio |   [AG_07] Searching: Ariana Grande Into You official audio

23:51:58 | INFO | scrape_audio |     ✓ Downloaded: 'Ariana Grande - Into You (Official Audio)' (245s)
23:52:02 | INFO | scrape_audio |   [AG_08] Searching: Ariana Grande Side to Side Nicki Minaj audio

23:52:07 | INFO | scrape_audio |     ✓ Downloaded: 'Side To Side' (226s)
23:52:12 | INFO | scrape_audio |   [AG_09] Searching: Ariana Grande Break Free Zedd audio

23:52:16 | INFO | scrape_audio |     ✓ Downloaded: 'Ariana Grande - Break Free feat. Zedd (Audio)' (214s)
23:52:19 | INFO | scrape_audio |   [AG_10] Searching: Ariana Grande breathin official audio

23:52:27 | INFO | scrape_audio |     ✓ Downloaded: 'Ariana Grande - breathin (audio)' (197s)
23:52:29 | INFO | scrape_audio |   [AG_11] Searching: Lady Gaga Ariana Grande Rain on Me audio

23:52:37 | INFO | scrape_audio |     ✓ Downloaded: 'Lady Gaga, Ariana Grande - Rain On Me (Audio)' (183s)
23:52:39 | INFO | scrape_audio |   [AG_12] Searching: Ariana Grande Justin Bieber stuck with u audio

23:52:45 | INFO | scrape_audio |     ✓ Downloaded: 'Ariana Grande, Justin Bieber - Stuck with U (Lyric Video)' (230s)
23:52:49 | INFO | scrape_audio |
────────────────────────────────────────────────────────────
23:52:49 | INFO | scrape_audio | Artist: Ed Sheeran  (ES)
23:52:49 | INFO | scrape_audio |   [ES_01] Searching: Ed Sheeran Shape of You official audio

23:52:57 | INFO | scrape_audio |     ✓ Downloaded: 'Ed Sheeran - Shape Of You [Official Lyric Video]' (235s)
23:53:00 | INFO | scrape_audio |   [ES_02] Searching: Ed Sheeran Perfect official audio

23:53:08 | INFO | scrape_audio |     ✓ Downloaded: 'Ed Sheeran - Perfect [Official Lyric Video]' (263s)
23:53:13 | INFO | scrape_audio |   [ES_03] Searching: Ed Sheeran Thinking Out Loud official audio

23:53:22 | INFO | scrape_audio |     ✓ Downloaded: 'Ed Sheeran - Thinking Out Loud [Official Audio]' (292s)
23:53:26 | INFO | scrape_audio |   [ES_04] Searching: Ed Sheeran Photograph official audio

23:53:34 | INFO | scrape_audio |     ✓ Downloaded: 'Ed Sheeran - Photograph (Official Lyric Video)' (259s)
23:53:37 | INFO | scrape_audio |   [ES_05] Searching: Ed Sheeran Castle on the Hill official audio

23:53:43 | INFO | scrape_audio |     ✓ Downloaded: 'Ed Sheeran - Castle On The Hill [Official Lyric Video]' (260s)
23:53:48 | INFO | scrape_audio |   [ES_06] Searching: Ed Sheeran Galway Girl official audio

23:53:51 | INFO | scrape_audio |     ✓ Downloaded: 'Ed Sheeran - Galway Girl [Official Lyric Video]' (172s)
23:53:55 | INFO | scrape_audio |   [ES_07] Searching: Ed Sheeran Bad Habits official audio

23:54:00 | INFO | scrape_audio |     ✓ Downloaded: 'Ed Sheeran - Bad Habits [Official Lyric Video]' (232s)
23:54:03 | INFO | scrape_audio |   [ES_08] Searching: Ed Sheeran Shivers official audio

23:54:11 | INFO | scrape_audio |     ✓ Downloaded: 'Ed Sheeran - Shivers [Official Lyric Video]' (208s)
23:54:14 | INFO | scrape_audio |   [ES_09] Searching: Ed Sheeran Overpass Graffiti official audio

23:54:19 | INFO | scrape_audio |     ✓ Downloaded: 'Ed Sheeran - Overpass Graffiti [Official Lyric Video]' (240s)
23:54:24 | INFO | scrape_audio |   [ES_10] Searching: Ed Sheeran The A Team official audio

23:54:29 | INFO | scrape_audio |     ✓ Downloaded: 'Ed Sheeran - The A Team (Lyric Video)' (259s)
23:54:31 | INFO | scrape_audio |   [ES_11] Searching: Ed Sheeran Lego House official audio

23:54:36 | INFO | scrape_audio |     ✓ Downloaded: 'Ed Sheeran - Lego House (Lyric Video)' (191s)
23:54:39 | INFO | scrape_audio |   [ES_12] Searching: Ed Sheeran Happier official audio

23:54:43 | INFO | scrape_audio |     ✓ Downloaded: 'Ed Sheeran - Happier [Official Audio]' (207s)
23:54:46 | INFO | scrape_audio |
────────────────────────────────────────────────────────────
23:54:46 | INFO | scrape_audio | Artist: Billie Eilish  (BE)
23:54:46 | INFO | scrape_audio |   [BE_01] Searching: Billie Eilish bad guy official audio

23:54:55 | INFO | scrape_audio |     ✓ Downloaded: 'Billie Eilish - bad guy' (206s)
23:54:58 | INFO | scrape_audio |   [BE_02] Searching: Billie Eilish Happier Than Ever official audio

23:55:05 | INFO | scrape_audio |     ✓ Downloaded: 'Billie Eilish - Happier Than Ever (Official Lyric Video)' (299s)
23:55:08 | INFO | scrape_audio |   [BE_03] Searching: Billie Eilish lovely Khalid official audio

23:55:13 | INFO | scrape_audio |     ✓ Downloaded: 'Billie Eilish - lovely (with Khalid) Audio' (201s)
23:55:16 | INFO | scrape_audio |   [BE_04] Searching: Billie Eilish when the partys over official audio

23:55:23 | INFO | scrape_audio |     ✓ Downloaded: 'Billie Eilish - when the party's over (Audio)' (195s)
23:55:28 | INFO | scrape_audio |   [BE_05] Searching: Billie Eilish ocean eyes official audio

23:55:36 | INFO | scrape_audio |     ✓ Downloaded: 'Billie Eilish - Ocean Eyes (Official Audio) - Lyrics In Description' (200s)
23:55:39 | INFO | scrape_audio |   [BE_06] Searching: Billie Eilish everything i wanted official audio

23:55:46 | INFO | scrape_audio |     ✓ Downloaded: 'Billie Eilish - everything i wanted (Audio)' (246s)
23:55:51 | INFO | scrape_audio |   [BE_07] Searching: Billie Eilish Therefore I Am official audio

23:55:56 | INFO | scrape_audio |     ✓ Downloaded: 'Billie Eilish - Therefore I Am (Official Lyric Video)' (174s)
23:56:00 | INFO | scrape_audio |   [BE_08] Searching: Billie Eilish your power official audio

23:56:08 | INFO | scrape_audio |     ✓ Downloaded: 'Billie Eilish - Your Power (Official Lyric Video)' (246s)
23:56:12 | INFO | scrape_audio |   [BE_09] Searching: Billie Eilish NDA official audio

23:56:20 | INFO | scrape_audio |     ✓ Downloaded: 'NDA' (196s)
23:56:23 | INFO | scrape_audio |   [BE_10] Searching: Billie Eilish idontwannabeyouanymore audio

23:56:30 | INFO | scrape_audio |     ✓ Downloaded: 'Billie Eilish - idontwannabeyouanymore (Official Audio)' (204s)
23:56:32 | INFO | scrape_audio |   [BE_11] Searching: Billie Eilish Getting Older official audio

23:56:38 | INFO | scrape_audio |     ✓ Downloaded: 'Billie Eilish - Getting Older (Official Lyric Video)' (244s)
23:56:41 | INFO | scrape_audio |   [BE_12] Searching: Billie Eilish Male Fantasy official audio

23:56:46 | INFO | scrape_audio |     ✓ Downloaded: 'Billie Eilish - Male Fantasy (Official Lyric Video)' (195s)
23:56:49 | INFO | scrape_audio |
────────────────────────────────────────────────────────────
23:56:49 | INFO | scrape_audio | Artist: Harry Styles  (HS)
23:56:49 | INFO | scrape_audio |   [HS_01] Searching: Harry Styles As It Was official audio

23:56:53 | INFO | scrape_audio |     ✓ Downloaded: 'Harry Styles - As It Was (Audio)' (166s)
23:56:56 | INFO | scrape_audio |   [HS_02] Searching: Harry Styles Watermelon Sugar official audio

23:57:03 | INFO | scrape_audio |     ✓ Downloaded: 'Harry Styles - Watermelon Sugar (Official Audio)' (174s)
23:57:05 | INFO | scrape_audio |   [HS_03] Searching: Harry Styles Adore You official audio

23:57:10 | INFO | scrape_audio |     ✓ Downloaded: 'Harry Styles - Adore You (Official Audio)' (209s)
23:57:13 | INFO | scrape_audio |   [HS_04] Searching: Harry Styles Golden official audio

23:57:17 | INFO | scrape_audio |     ✓ Downloaded: 'Harry Styles - Golden (Official Audio)' (211s)
23:57:21 | INFO | scrape_audio |   [HS_05] Searching: Harry Styles Lights Up official audio

23:57:25 | INFO | scrape_audio |     ✓ Downloaded: 'Harry Styles - Lights Up (Official Audio)' (174s)
23:57:28 | INFO | scrape_audio |   [HS_06] Searching: Harry Styles Sign of the Times official audio

23:57:34 | INFO | scrape_audio |     ✓ Downloaded: 'Harry Styles - Sign of the Times (Audio)' (342s)
23:57:37 | INFO | scrape_audio |   [HS_07] Searching: Harry Styles Falling official audio

23:57:46 | INFO | scrape_audio |     ✓ Downloaded: 'Harry Styles - Falling (Official Audio)' (242s)
23:57:49 | INFO | scrape_audio |   [HS_08] Searching: Harry Styles Treat People With Kindness audio

23:57:56 | INFO | scrape_audio |     ✓ Downloaded: 'Harry Styles - Treat People With Kindness (Official Audio)' (199s)
23:57:59 | INFO | scrape_audio |   [HS_09] Searching: Harry Styles Late Night Talking official audio

23:58:08 | INFO | scrape_audio |     ✓ Downloaded: 'Harry Styles - Late Night Talking (Audio)' (178s)
23:58:11 | INFO | scrape_audio |   [HS_10] Searching: Harry Styles Music for a Sushi Restaurant audio

23:58:19 | INFO | scrape_audio |     ✓ Downloaded: 'Harry Styles - Music For a Sushi Restaurant (Audio)' (194s)
23:58:22 | INFO | scrape_audio |   [HS_11] Searching: Harry Styles Matilda official audio

23:58:30 | INFO | scrape_audio |     ✓ Downloaded: 'Harry Styles - Matilda (Audio)' (246s)
23:58:34 | INFO | scrape_audio |   [HS_12] Searching: Harry Styles Cinema official audio

23:58:39 | INFO | scrape_audio |     ✓ Downloaded: 'Harry Styles - Cinema (Audio)' (243s)
23:58:43 | INFO | scrape_audio |
────────────────────────────────────────────────────────────
23:58:43 | INFO | scrape_audio | Artist: Olivia Rodrigo  (OR)
23:58:43 | INFO | scrape_audio |   [OR_01] Searching: Olivia Rodrigo drivers license official audio

23:58:49 | INFO | scrape_audio |     ✓ Downloaded: 'drivers license' (242s)
23:58:53 | INFO | scrape_audio |   [OR_02] Searching: Olivia Rodrigo good 4 u official audio

23:58:58 | INFO | scrape_audio |     ✓ Downloaded: 'good 4 u' (178s)
23:59:01 | INFO | scrape_audio |   [OR_03] Searching: Olivia Rodrigo deja vu official audio

23:59:09 | INFO | scrape_audio |     ✓ Downloaded: 'deja vu' (216s)
23:59:13 | INFO | scrape_audio |   [OR_04] Searching: Olivia Rodrigo brutal official audio

23:59:18 | INFO | scrape_audio |     ✓ Downloaded: 'brutal' (144s)
23:59:23 | INFO | scrape_audio |   [OR_05] Searching: Olivia Rodrigo traitor official audio

23:59:31 | INFO | scrape_audio |     ✓ Downloaded: 'Olivia Rodrigo - traitor (Lyric Video)' (230s)
23:59:33 | INFO | scrape_audio |   [OR_06] Searching: Olivia Rodrigo happier official audio

23:59:37 | INFO | scrape_audio |     ✓ Downloaded: 'happier' (176s)
23:59:42 | INFO | scrape_audio |   [OR_07] Searching: Olivia Rodrigo vampire official audio

23:59:48 | INFO | scrape_audio |     ✓ Downloaded: 'vampire' (220s)
23:59:53 | INFO | scrape_audio |   [OR_08] Searching: Olivia Rodrigo bad idea right official audio

00:00:01 | INFO | scrape_audio |     ✓ Downloaded: 'bad idea right?' (185s)
00:00:03 | INFO | scrape_audio |   [OR_09] Searching: Olivia Rodrigo get him back official audio

00:00:07 | INFO | scrape_audio |     ✓ Downloaded: 'get him back!' (211s)
00:00:11 | INFO | scrape_audio |   [OR_10] Searching: Olivia Rodrigo lacy official audio

00:00:17 | INFO | scrape_audio |     ✓ Downloaded: 'Olivia Rodrigo - lacy (Official Lyric Video)' (177s)
00:00:20 | INFO | scrape_audio |   [OR_11] Searching: Olivia Rodrigo enough for you official audio

00:00:27 | INFO | scrape_audio |     ✓ Downloaded: 'Olivia Rodrigo - enough for you (Lyric Video)' (203s)
00:00:31 | INFO | scrape_audio |   [OR_12] Searching: Olivia Rodrigo 1 step forward 3 steps back audio

00:00:39 | INFO | scrape_audio |     ✓ Downloaded: '1 step forward, 3 steps back' (164s)
00:00:43 | INFO | scrape_audio |
────────────────────────────────────────────────────────────
00:00:43 | INFO | scrape_audio | Artist: Daft Punk  (DP)
00:00:43 | INFO | scrape_audio |   [DP_01] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DP/DP_01.mp3
00:00:43 | INFO | scrape_audio |   [DP_02] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DP/DP_02.mp3
00:00:43 | INFO | scrape_audio |   [DP_03] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DP/DP_03.mp3
00:00:43 | INFO | scrape_audio |   [DP_04] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DP/DP_04.mp3
00:00:43 | INFO | scrape_audio |   [DP_05] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DP/DP_05.mp3
00:00:43 | INFO | scrape_audio |   [DP_06] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DP/DP_06.mp3
00:00:43 | INFO | scrape_audio |   [DP_07] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DP/DP_07.mp3
00:00:43 | INFO | scrape_audio |   [DP_08] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DP/DP_08.mp3
00:00:43 | INFO | scrape_audio |   [DP_09] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DP/DP_09.mp3
00:00:43 | INFO | scrape_audio |   [DP_10] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DP/DP_10.mp3
00:00:43 | INFO | scrape_audio |   [DP_11] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DP/DP_11.mp3
00:00:43 | INFO | scrape_audio |   [DP_12] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DP/DP_12.mp3
00:00:43 | INFO | scrape_audio |   [DP_13] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DP/DP_13.mp3
00:00:43 | INFO | scrape_audio |   [DP_14] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DP/DP_14.mp3
00:00:43 | INFO | scrape_audio |   [DP_15] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DP/DP_15.mp3
00:00:43 | INFO | scrape_audio |
────────────────────────────────────────────────────────────
00:00:43 | INFO | scrape_audio | Artist: Disclosure  (DS)
00:00:43 | INFO | scrape_audio |   [DS_01] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DS/DS_01.mp3
00:00:43 | INFO | scrape_audio |   [DS_02] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DS/DS_02.mp3
00:00:43 | INFO | scrape_audio |   [DS_03] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DS/DS_03.mp3
00:00:43 | INFO | scrape_audio |   [DS_04] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DS/DS_04.mp3
00:00:43 | INFO | scrape_audio |   [DS_05] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DS/DS_05.mp3
00:00:43 | INFO | scrape_audio |   [DS_06] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DS/DS_06.mp3
00:00:43 | INFO | scrape_audio |   [DS_07] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DS/DS_07.mp3
00:00:43 | INFO | scrape_audio |   [DS_08] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DS/DS_08.mp3
00:00:43 | INFO | scrape_audio |   [DS_09] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DS/DS_09.mp3
00:00:43 | INFO | scrape_audio |   [DS_10] Searching: Disclosure Jaded official audio
ERROR: [youtube] tIS_rvlkPUM: This video is not available
00:00:45 | WARNING | scrape_audio |     ✗ FAILED: 'NoneType' object has no attribute 'get'
00:00:45 | INFO | scrape_audio |     Retry 1/2 in 9.2s…
00:00:54 | INFO | scrape_audio |   [DS_10] Searching: Disclosure Jaded official audio
ERROR: [youtube] tIS_rvlkPUM: This video is not available
00:00:56 | WARNING | scrape_audio |     ✗ FAILED: 'NoneType' object has no attribute 'get'
00:00:56 | INFO | scrape_audio |     Retry 2/2 in 8.1s…
00:01:04 | INFO | scrape_audio |   [DS_10] Searching: Disclosure Jaded official audio
ERROR: [youtube] tIS_rvlkPUM: This video is not available
00:01:06 | WARNING | scrape_audio |     ✗ FAILED: 'NoneType' object has no attribute 'get'
00:01:10 | INFO | scrape_audio |   [DS_11] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DS/DS_11.mp3
00:01:10 | INFO | scrape_audio |   [DS_12] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DS/DS_12.mp3
00:01:10 | INFO | scrape_audio |   [DS_13] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DS/DS_13.mp3
00:01:10 | INFO | scrape_audio |   [DS_14] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DS/DS_14.mp3
00:01:10 | INFO | scrape_audio |   [DS_15] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/DS/DS_15.mp3
00:01:10 | INFO | scrape_audio |
────────────────────────────────────────────────────────────
00:01:10 | INFO | scrape_audio | Artist: Caribou  (CB)
00:01:10 | INFO | scrape_audio |   [CB_01] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/CB/CB_01.mp3
00:01:10 | INFO | scrape_audio |   [CB_02] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/CB/CB_02.mp3
00:01:10 | INFO | scrape_audio |   [CB_03] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/CB/CB_03.mp3
00:01:10 | INFO | scrape_audio |   [CB_04] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/CB/CB_04.mp3
00:01:10 | INFO | scrape_audio |   [CB_05] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/CB/CB_05.mp3
00:01:10 | INFO | scrape_audio |   [CB_06] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/CB/CB_06.mp3
00:01:10 | INFO | scrape_audio |   [CB_07] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/CB/CB_07.mp3
00:01:10 | INFO | scrape_audio |   [CB_08] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/CB/CB_08.mp3
00:01:10 | INFO | scrape_audio |   [CB_09] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/CB/CB_09.mp3
00:01:10 | INFO | scrape_audio |   [CB_10] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/CB/CB_10.mp3
00:01:10 | INFO | scrape_audio |   [CB_11] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/CB/CB_11.mp3
00:01:10 | INFO | scrape_audio |   [CB_12] SKIP — /Users/budge.13/Desktop/Music Analysis/audio/CB/CB_12.mp3
00:01:10 | INFO | scrape_audio |
────────────────────────────────────────────────────────────
00:01:10 | INFO | scrape_audio | Artist: James Blake  (JB)
00:01:10 | INFO | scrape_audio |   [JB_01] Searching: James Blake Limit to Your Love audio

00:01:16 | INFO | scrape_audio |     ✓ Downloaded: 'James Blake - Limit To Your Love' (199s)
00:01:18 | INFO | scrape_audio |   [JB_02] Searching: James Blake Retrograde audio

00:01:27 | INFO | scrape_audio |     ✓ Downloaded: 'James Blake - Retrograde' (222s)
00:01:31 | INFO | scrape_audio |   [JB_03] Searching: James Blake The Wilhelm Scream audio

00:01:40 | INFO | scrape_audio |     ✓ Downloaded: 'James Blake - The Wilhelm Scream (Official Video)' (278s)
00:01:43 | INFO | scrape_audio |   [JB_04] Searching: James Blake Overgrown audio

00:01:51 | INFO | scrape_audio |     ✓ Downloaded: 'James Blake- Overgrown (Album Version)' (301s)
00:01:53 | INFO | scrape_audio |   [JB_05] Searching: James Blake Life Round Here audio

00:02:01 | INFO | scrape_audio |     ✓ Downloaded: 'Life Round Here' (217s)
00:02:03 | INFO | scrape_audio |   [JB_06] Searching: James Blake I Need a Forest Fire Bon Iver audio

00:02:07 | INFO | scrape_audio |     ✓ Downloaded: 'I Need A Forest Fire' (257s)
00:02:12 | INFO | scrape_audio |   [JB_07] Searching: James Blake Timeless audio

00:02:20 | INFO | scrape_audio |     ✓ Downloaded: 'Timeless' (262s)
00:02:22 | INFO | scrape_audio |   [JB_08] Searching: James Blake Are You Even Real audio

00:02:26 | INFO | scrape_audio |     ✓ Downloaded: 'James Blake - Are You Even Real? (Official Visualizer)' (233s)
00:02:29 | INFO | scrape_audio |   [JB_09] Searching: James Blake Famous Last Words audio

00:02:38 | INFO | scrape_audio |     ✓ Downloaded: 'James Blake - Famous Last Words (Official Audio)' (256s)
00:02:41 | INFO | scrape_audio |   [JB_10] Searching: James Blake Assume Form audio

00:02:47 | INFO | scrape_audio |     ✓ Downloaded: 'Assume Form' (290s)
00:02:49 | INFO | scrape_audio |   [JB_11] Searching: James Blake Cant Believe the Way We Flow audio

00:02:58 | INFO | scrape_audio |     ✓ Downloaded: 'James Blake - Can't Believe The Way We Flow (Official Video)' (283s)
00:03:00 | INFO | scrape_audio |   [JB_12] Searching: James Blake Mile High Travis Scott Metro Boomin audio

00:03:07 | INFO | scrape_audio |     ✓ Downloaded: 'James Blake - Mile High feat. Travis Scott and Metro Boomin  (Official Audio)' (194s)
00:03:11 | INFO | scrape_audio |
────────────────────────────────────────────────────────────
00:03:11 | INFO | scrape_audio | Artist: LCD Soundsystem  (LCD)
00:03:11 | INFO | scrape_audio |   [LCD_01] Searching: LCD Soundsystem All My Friends audio

00:03:20 | INFO | scrape_audio |     ✓ Downloaded: 'LCD Soundsystem, "All my friends"' (458s)
00:03:24 | INFO | scrape_audio |   [LCD_02] Searching: LCD Soundsystem Daft Punk Is Playing at My House audio

00:03:31 | INFO | scrape_audio |     ✓ Downloaded: 'Daft Punk Is Playing at My House' (316s)
00:03:36 | INFO | scrape_audio |   [LCD_03] Searching: LCD Soundsystem I Can Change audio

00:03:43 | INFO | scrape_audio |     ✓ Downloaded: 'I Can Change' (352s)
00:03:45 | INFO | scrape_audio |   [LCD_04] Searching: LCD Soundsystem Drunk Girls audio

00:03:50 | INFO | scrape_audio |     ✓ Downloaded: 'LCD Soundsystem - Drunk Girls' (256s)
00:03:55 | INFO | scrape_audio |   [LCD_05] Searching: LCD Soundsystem Someone Great audio

00:04:01 | INFO | scrape_audio |     ✓ Downloaded: 'LCD Soundsystem - Someone Great (Official Video)' (230s)
00:04:04 | INFO | scrape_audio |   [LCD_06] Searching: LCD Soundsystem North American Scum audio

00:04:11 | INFO | scrape_audio |     ✓ Downloaded: 'North American Scum' (329s)
00:04:13 | INFO | scrape_audio |   [LCD_07] Searching: LCD Soundsystem Call the Police audio

00:04:22 | INFO | scrape_audio |     ✓ Downloaded: 'LCD Soundsystem - call the police' (426s)
00:04:26 | INFO | scrape_audio |   [LCD_08] Searching: LCD Soundsystem American Dream audio

00:04:34 | INFO | scrape_audio |     ✓ Downloaded: 'LCD Soundsystem - american dream' (377s)
00:04:36 | INFO | scrape_audio |   [LCD_09] Searching: LCD Soundsystem Oh Baby audio

00:04:42 | INFO | scrape_audio |     ✓ Downloaded: 'LCD Soundsystem - oh baby (Official Video)' (348s)
00:04:44 | INFO | scrape_audio |   [LCD_10] Searching: LCD Soundsystem Tonite audio

00:04:49 | INFO | scrape_audio |     ✓ Downloaded: 'LCD Soundsystem - tonite (electric lady sessions - official audio)' (346s)
00:04:52 | INFO | scrape_audio |   [LCD_11] Searching: LCD Soundsystem Change Yr Mind audio

00:04:58 | INFO | scrape_audio |     ✓ Downloaded: 'change yr mind' (298s)
00:05:01 | INFO | scrape_audio |   [LCD_12] Searching: LCD Soundsystem How Do You Sleep audio

00:05:13 | INFO | scrape_audio |     ✓ Downloaded: 'how do you sleep?' (552s)
00:05:17 | INFO | scrape_audio |
────────────────────────────────────────────────────────────
00:05:17 | INFO | scrape_audio | Artist: Bonobo  (BN)
00:05:17 | INFO | scrape_audio |   [BN_01] Searching: Bonobo Kiara audio

00:05:25 | INFO | scrape_audio |     ✓ Downloaded: 'Bonobo - 'Kiara'' (231s)
00:05:29 | INFO | scrape_audio |   [BN_02] Searching: Bonobo No Reason audio

00:05:36 | INFO | scrape_audio |     ✓ Downloaded: 'Bonobo - No Reason (feat. Nick Murphy) (Official Video)' (244s)
00:05:39 | INFO | scrape_audio |   [BN_03] Searching: Bonobo Outlier audio

00:05:45 | INFO | scrape_audio |     ✓ Downloaded: 'Bonobo - Outlier (Official Audio)' (475s)
00:05:49 | INFO | scrape_audio |   [BN_04] Searching: Bonobo Break Apart Rhye audio

00:05:54 | INFO | scrape_audio |     ✓ Downloaded: 'Bonobo - Break Apart (feat. Rhye) (Official Audio)' (275s)
00:05:57 | INFO | scrape_audio |   [BN_05] Searching: Bonobo Bambro Koyo Ganda audio

00:06:05 | INFO | scrape_audio |     ✓ Downloaded: 'Bonobo - Bambro Koyo Ganda (feat. Innov Gnawa) (Official Video)' (208s)
00:06:10 | INFO | scrape_audio |   [BN_06] Searching: Bonobo Surface audio

00:06:15 | INFO | scrape_audio |     ✓ Downloaded: 'Bonobo - Surface (feat. Nicole Miglis) (Official Audio)' (251s)
00:06:18 | INFO | scrape_audio |   [BN_07] Searching: Bonobo Linked audio

00:06:28 | INFO | scrape_audio |     ✓ Downloaded: 'Bonobo - Linked (Official Audio)' (371s)
00:06:30 | INFO | scrape_audio |   [BN_08] Searching: Bonobo It Came From the Sea audio

00:07:06 | INFO | scrape_audio |     ✓ Downloaded: 'Bonobo - It Came from the Sea - Full Album' (3345s)
00:07:10 | INFO | scrape_audio |   [BN_09] Searching: Bonobo Kerala audio

00:07:17 | INFO | scrape_audio |     ✓ Downloaded: 'Bonobo - Kerala (Official Audio)' (243s)
00:07:22 | INFO | scrape_audio |   [BN_10] Searching: Bonobo Towers audio

00:07:28 | INFO | scrape_audio |     ✓ Downloaded: 'Bonobo - Towers (feat. Szjerdine) (Official Audio)' (217s)
00:07:31 | INFO | scrape_audio |   [BN_11] Searching: Bonobo Prelude audio

00:07:40 | INFO | scrape_audio |     ✓ Downloaded: 'Bonobo - Prelude + Kiara' (309s)
00:07:44 | INFO | scrape_audio |   [BN_12] Searching: Bonobo Sapphire audio

00:07:49 | INFO | scrape_audio |     ✓ Downloaded: 'Bonobo - Sapphire (Official Audio)' (288s)
00:07:52 | INFO | scrape_audio |
────────────────────────────────────────────────────────────
00:07:52 | INFO | scrape_audio | Artist: Gorillaz  (GZ)
00:07:52 | INFO | scrape_audio |   [GZ_01] Searching: Gorillaz Feel Good Inc official audio

00:08:00 | INFO | scrape_audio |     ✓ Downloaded: 'Gorillaz - Feel Good Inc.' (223s)
00:08:03 | INFO | scrape_audio |   [GZ_02] Searching: Gorillaz DARE official audio

00:08:10 | INFO | scrape_audio |     ✓ Downloaded: 'DARE' (214s)
00:08:13 | INFO | scrape_audio |   [GZ_03] Searching: Gorillaz Clint Eastwood official audio

00:08:18 | INFO | scrape_audio |     ✓ Downloaded: '[HD] Gorillaz - Clint Eastwood' (341s)
00:08:23 | INFO | scrape_audio |   [GZ_04] Searching: Gorillaz On Melancholy Hill official audio

00:08:28 | INFO | scrape_audio |     ✓ Downloaded: 'On Melancholy Hill' (209s)
00:08:30 | INFO | scrape_audio |   [GZ_05] Searching: Gorillaz Rhinestone Eyes official audio

00:08:36 | INFO | scrape_audio |     ✓ Downloaded: 'Gorillaz - Rhinestone Eyes (Official Audio)' (200s)
00:08:39 | INFO | scrape_audio |   [GZ_06] Searching: Gorillaz Stylo Bobby Womack Mos Def audio

00:08:48 | INFO | scrape_audio |     ✓ Downloaded: 'Gorillaz - Stylo (Feat. Mos Def and Bobby Womack)' (274s)
00:08:52 | INFO | scrape_audio |   [GZ_07] Searching: Gorillaz Empire Ants Little Dragon audio

00:09:02 | INFO | scrape_audio |     ✓ Downloaded: 'Gorillaz - Empire Ants - Plastic Beach' (284s)
00:09:06 | INFO | scrape_audio |   [GZ_08] Searching: Gorillaz Momentz De La Soul audio

00:09:12 | INFO | scrape_audio |     ✓ Downloaded: 'Momentz (feat. De La Soul)' (197s)
00:09:16 | INFO | scrape_audio |   [GZ_09] Searching: Gorillaz Andromeda D.R.A.M audio

00:09:23 | INFO | scrape_audio |     ✓ Downloaded: 'Gorillaz - Andromeda (DRAM Special) [Audio]' (238s)
00:09:26 | INFO | scrape_audio |   [GZ_10] Searching: Gorillaz Tranz official audio

00:09:32 | INFO | scrape_audio |     ✓ Downloaded: 'Gorillaz - Tranz (Official Visualiser)' (162s)
00:09:35 | INFO | scrape_audio |   [GZ_11] Searching: Gorillaz Hollywood Snoop Dogg Jamie Principle audio

00:09:44 | INFO | scrape_audio |     ✓ Downloaded: 'Gorillaz - Hollywood feat. Snoop Dogg & Jamie Principle (Official Visualiser)' (296s)
00:09:47 | INFO | scrape_audio |   [GZ_12] Searching: Gorillaz New Gold Tame Impala Bootie Brown audio

00:09:52 | INFO | scrape_audio |     ✓ Downloaded: 'Gorillaz - New Gold ft. Tame Impala & Bootie Brown (Official Visualiser)' (216s)
00:09:56 | INFO | scrape_audio |
════════════════════════════════════════════════════════════
00:09:56 | INFO | scrape_audio | Done. Downloaded: 264  |  Skipped: 176  |  Failed: 1
00:09:56 | WARNING | scrape_audio | Failed songs (check .FAILED stubs): ['DS_10']
00:09:56 | INFO | scrape_audio | Manifest → /Users/budge.13/Desktop/Music Analysis/audio/_manifest.json

Downloaded : 264
Skipped    : 176
Failed     : 1

Coverage   : 440 / 441 songs have audio

---
## Step 3 — Build Schemas
Reads each `lyrics/{SONG_ID}.json` and generates per-artist schema `.py` files  
(`schemas/KL_schema.py`, etc.) in the same format as the original `RTJ.py` / `GD.py`.  
Also writes `schemas/full_catalog.py` which merges all schemas.  
**Outputs:** `schemas/{ARTIST_CODE}_schema.py`, `schemas/full_catalog.py`

In [5]:
build_schema = load_script("build_schema", "03_build_schema.py")

schema_summary = build_schema.build_all_schemas(artist_filter=None)

total_included = sum(len(v["included"]) for v in schema_summary.values())
total_missing  = sum(len(v["missing"])  for v in schema_summary.values())
print(f"\nSchema build: {total_included} songs included, {total_missing} missing lyrics")

00:09:56 | INFO | build_schema | Building schema for Run the Jewels (RTJ)…
00:09:56 | INFO | build_schema |   → /Users/budge.13/Desktop/Music Analysis/schemas/RTJ_schema.py  (15 songs, 0 missing)
00:09:56 | INFO | build_schema | Building schema for Kendrick Lamar (KL)…
00:09:56 | INFO | build_schema |   → /Users/budge.13/Desktop/Music Analysis/schemas/KL_schema.py  (15 songs, 0 missing)
00:09:56 | INFO | build_schema | Building schema for J. Cole (JC)…
00:09:56 | INFO | build_schema |   → /Users/budge.13/Desktop/Music Analysis/schemas/JC_schema.py  (15 songs, 0 missing)
00:09:56 | INFO | build_schema | Building schema for Drake (DR)…
00:09:56 | INFO | build_schema |   → /Users/budge.13/Desktop/Music Analysis/schemas/DR_schema.py  (12 songs, 0 missing)
00:09:56 | INFO | build_schema | Building schema for Eminem (EM)…
00:09:56 | INFO | build_schema |   → /Users/budge.13/Desktop/Music Analysis/schemas/EM_schema.py  (12 songs, 0 missing)
00:09:56 | INFO | build_schema | Building schema for Tyler, the Creator (TC2)…
00:09:56 | INFO | build_schema |   → /Users/budge.13/Desktop/Music Analysis/schemas/TC2_schema.py  (12 songs, 0 missing)
00:09:56 | INFO | build_schema | Building schema for Mac Miller (MM)…
00:09:56 | INFO | build_schema |   → /Users/budge.13/Desktop/Music Analysis/schemas/MM_schema.py  (12 songs, 0 missing)
00:09:56 | INFO | build_schema | Building schema for Chance the Rapper (CH)…
00:09:56 | INFO | build_schema |   → /Users/budge.13/Desktop/Music Analysis/schemas/CH_schema.py  (12 songs, 0 missing)
00:09:56 | INFO | build_schema | Building schema for Nas (NS)…
00:09:56 | INFO | build_schema |   → /Users/budge.13/Desktop/Music Analysis/schemas/NS_schema.py  (12 songs, 0 missing)
00:09:56 | INFO | build_schema | Building schema for Childish Gambino (CG)…
00:09:56 | INFO | build_schema |   → /Users/budge.13/Desktop/Music Analysis/schemas/CG_schema.py  (12 songs, 0 missing)
00:09:56 | INFO | build_schema | Building schema for Grateful Dead (GD)…
00:09:56 | INFO | build_schema |   → /Users/budge.13/Desktop/Music Analysis/schemas/GD_schema.py  (15 songs, 0 missing)
00:09:56 | INFO | build_schema | Building schema for Bob Dylan (BD)…
00:09:56 | INFO | build_schema |   → /Users/budge.13/Desktop/Music Analysis/schemas/BD_schema.py  (15 songs, 0 missing)
00:09:56 | INFO | build_schema | Building schema for Tyler Childers (TC)…
00:09:56 | INFO | build_schema |   → /Users/budge.13/Desktop/Music Analysis/schemas/TC_schema.py  (15 songs, 0 missing)
00:09:56 | INFO | build_schema | Building schema for Jason Isbell (JI)…
00:09:56 | INFO | build_schema |   → /Users/budge.13/Desktop/Music Analysis/schemas/JI_schema.py  (12 songs, 0 missing)
00:09:56 | INFO | build_schema | Building schema for Sturgill Simpson (SS)…
00:09:56 | INFO | build_schema |   → /Users/budge.13/Desktop/Music Analysis/schemas/SS_schema.py  (12 songs, 0 missing)
00:09:56 | INFO | build_schema | Building schema for Kacey Musgraves (KM)…
00:09:56 | INFO | build_schema |   → /Users/budge.13/Desktop/Music Analysis/schemas/KM_schema.py  (12 songs, 0 missing)
00:09:56 | INFO | build_schema | Building schema for John Prine (JP)…
00:09:56 | INFO | build_schema |   → /Users/budge.13/Desktop/Music Analysis/schemas/JP_schema.py  (12 songs, 0 missing)
00:09:56 | INFO | build_schema | Building schema for Gillian Welch (GW)…
00:09:56 | INFO | build_schema |   → /Users/budge.13/Desktop/Music Analysis/schemas/GW_schema.py  (12 songs, 0 missing)
00:09:56 | INFO | build_schema | Building schema for Colter Wall (CW)…
00:09:56 | INFO | build_schema |   → /Users/budge.13/Desktop/Music Analysis/schemas/CW_schema.py  (12 songs, 0 missing)
00:09:56 | INFO | build_schema | Building schema for Taylor Swift (TS)…
00:09:56 | INFO | build_schema |   → /Users/budge.13/Desktop/Music Analysis/schemas/TS_schema.py  (15 songs, 0 missing)
00:09:56 | INFO | build_schema | Building schema for The Weeknd (TW)…
00:09:56 | WARNING | build_schema |   [TW_13] No lyrics file — skipping from schema
00:09:56 | INFO | build_schema |   → /Users/budge.13/Desktop/Music Analysis/schemas/TW_schema.py  (14 songs, 1 missing)
00:09:56 | INFO | build_schema | Building schema for Dua Lipa (DL)…
00:09:56 | INFO | build_schema |   → /Users/budge.13/Desktop/Music Analysis/schemas/DL_schema.py  (15 songs, 0 missing)
00:09:56 | INFO | build_schema | Building schema for Ariana Grande (AG)…
00:09:56 | INFO | build_schema |   → /Users/budge.13/Desktop/Music Analysis/schemas/AG_schema.py  (12 songs, 0 missing)
00:09:56 | INFO | build_schema | Building schema for Ed Sheeran (ES)…
00:09:56 | INFO | build_schema |   → /Users/budge.13/Desktop/Music Analysis/schemas/ES_schema.py  (12 songs, 0 missing)
00:09:56 | INFO | build_schema | Building schema for Billie Eilish (BE)…
00:09:56 | INFO | build_schema |   → /Users/budge.13/Desktop/Music Analysis/schemas/BE_schema.py  (12 songs, 0 missing)
00:09:56 | INFO | build_schema | Building schema for Harry Styles (HS)…
00:09:56 | INFO | build_schema |   → /Users/budge.13/Desktop/Music Analysis/schemas/HS_schema.py  (12 songs, 0 missing)
00:09:56 | INFO | build_schema | Building schema for Olivia Rodrigo (OR)…
00:09:56 | INFO | build_schema |   → /Users/budge.13/Desktop/Music Analysis/schemas/OR_schema.py  (12 songs, 0 missing)
00:09:56 | INFO | build_schema | Building schema for Daft Punk (DP)…
00:09:56 | WARNING | build_schema |   [DP_04] No lyrics file — skipping from schema
00:09:56 | INFO | build_schema |   → /Users/budge.13/Desktop/Music Analysis/schemas/DP_schema.py  (14 songs, 1 missing)
00:09:56 | INFO | build_schema | Building schema for Disclosure (DS)…
00:09:56 | INFO | build_schema |   → /Users/budge.13/Desktop/Music Analysis/schemas/DS_schema.py  (15 songs, 0 missing)
00:09:56 | INFO | build_schema | Building schema for Caribou (CB)…
00:09:56 | WARNING | build_schema |   [CB_06] No lyrics file — skipping from schema
00:09:56 | INFO | build_schema |   → /Users/budge.13/Desktop/Music Analysis/schemas/CB_schema.py  (11 songs, 1 missing)
00:09:56 | INFO | build_schema | Building schema for James Blake (JB)…
00:09:56 | INFO | build_schema |   → /Users/budge.13/Desktop/Music Analysis/schemas/JB_schema.py  (12 songs, 0 missing)
00:09:56 | INFO | build_schema | Building schema for LCD Soundsystem (LCD)…
00:09:56 | INFO | build_schema |   → /Users/budge.13/Desktop/Music Analysis/schemas/LCD_schema.py  (12 songs, 0 missing)
00:09:56 | INFO | build_schema | Building schema for Bonobo (BN)…
00:09:56 | WARNING | build_schema |   [BN_12] No lyrics file — skipping from schema
00:09:56 | INFO | build_schema |   → /Users/budge.13/Desktop/Music Analysis/schemas/BN_schema.py  (11 songs, 1 missing)
00:09:56 | INFO | build_schema | Building schema for Gorillaz (GZ)…
00:09:56 | INFO | build_schema |   → /Users/budge.13/Desktop/Music Analysis/schemas/GZ_schema.py  (12 songs, 0 missing)
00:09:56 | INFO | build_schema |
Full catalog → /Users/budge.13/Desktop/Music Analysis/schemas/full_catalog.py
00:09:56 | INFO | build_schema |
══════════════════════════════════════════════════
00:09:56 | INFO | build_schema | Schema build complete: 437 songs included, 4 missing

Schema build: 437 songs included, 4 missing lyrics

---
## Step 4 — MuQ-MuLan Embeddings
Computes audio and text embeddings using the jointly-trained MuQ-MuLan model.  
**Model:** `OpenMuQ/MuQ-MuLan-large` — downloads ~1.5 GB on first run.  
**Outputs:** `results/embeddings/mulan/{audio,text}_embeddings.npz`, `similarities.json`  
**Resume-safe:** `checkpoint.json` tracks completed songs.

In [6]:
embed_mulan = load_script("embed_mulan", "04_embed_mulan.py")

mulan_results = embed_mulan.embed_all(
    device = device,
    force  = False,   # set True to recompute everything from scratch
)

if mulan_results:
    sims = mulan_results["sims"]
    vals = list(sims.values())
    import numpy as np
    print(f"\nMuLan LMC  — n={len(vals)}  mean={np.mean(vals):.4f}  "
          f"sd={np.std(vals):.4f}  min={np.min(vals):.4f}  max={np.max(vals):.4f}")

00:09:56 | INFO | embed_mulan | Loading model for 263 songs…
00:10:00 | INFO | numexpr.utils | NumExpr defaulting to 10 threads.
00:10:01 | INFO | embed_mulan | Loading MuQ-MuLan on mps…
00:10:01 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/OpenMuQ/MuQ-MuLan-large/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
00:10:01 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/OpenMuQ/MuQ-MuLan-large/2e01c796b71dca71b45251384c04cd7b237c9020/config.json "HTTP/1.1 200 OK"
00:10:01 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/OpenMuQ/MuQ-large-msd-iter/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
00:10:01 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/OpenMuQ/MuQ-large-msd-iter/0562a57814f6f8bbd9fdea0a25921a2fce1a841a/config.json "HTTP/1.1 200 OK"
/opt/anaconda3/lib/python3.13/site-packages/torch/nn/utils/weight_norm.py:144: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)
00:10:02 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/OpenMuQ/MuQ-large-msd-iter/resolve/main/model.safetensors "HTTP/1.1 302 Found"
00:10:04 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/xlm-roberta-base/resolve/main/config.json "HTTP/1.1 200 OK"
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
00:10:04 | WARNING | huggingface_hub.utils._http | Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
00:10:04 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/xlm-roberta-base/resolve/main/model.safetensors "HTTP/1.1 302 Found"

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

XLMRobertaModel LOAD REPORT from: xlm-roberta-base
Key                       | Status     |  |
--------------------------+------------+--+-
lm_head.layer_norm.weight | UNEXPECTED |  |
lm_head.dense.weight      | UNEXPECTED |  |
lm_head.bias              | UNEXPECTED |  |
lm_head.dense.bias        | UNEXPECTED |  |
lm_head.layer_norm.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
00:10:04 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/OpenMuQ/MuQ-MuLan-large/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"
00:10:04 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/OpenMuQ/MuQ-MuLan-large/resolve/main/pytorch_model.bin "HTTP/1.1 302 Found"
00:10:08 | INFO | embed_mulan | [1/263] DR_01
00:10:13 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/xlm-roberta-base/resolve/main/config.json "HTTP/1.1 200 OK"
00:10:13 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/xlm-roberta-base/resolve/main/tokenizer_config.json "HTTP/1.1 200 OK"
00:10:13 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/xlm-roberta-base/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 307 Temporary Redirect"
00:10:13 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/FacebookAI/xlm-roberta-base/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
00:10:13 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/xlm-roberta-base/tree/main?recursive=true&expand=false "HTTP/1.1 307 Temporary Redirect"
00:10:13 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/FacebookAI/xlm-roberta-base/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
00:10:14 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/xlm-roberta-base "HTTP/1.1 307 Temporary Redirect"
00:10:14 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/FacebookAI/xlm-roberta-base "HTTP/1.1 200 OK"
00:10:14 | INFO | embed_mulan | [2/263] DR_02
00:10:20 | INFO | embed_mulan | [3/263] DR_03
00:10:24 | INFO | embed_mulan | [4/263] DR_04
00:10:31 | INFO | embed_mulan | [5/263] DR_05
00:10:35 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/audio_embeddings.npz
00:10:35 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/text_embeddings.npz
00:10:35 | INFO | embed_mulan |   Checkpoint saved (5 songs processed)
00:10:35 | INFO | embed_mulan | [6/263] DR_06
00:10:41 | INFO | embed_mulan | [7/263] DR_07
00:10:49 | INFO | embed_mulan | [8/263] DR_08
00:10:54 | INFO | embed_mulan | [9/263] DR_09
00:11:03 | INFO | embed_mulan | [10/263] DR_10
00:11:09 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/audio_embeddings.npz
00:11:09 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/text_embeddings.npz
00:11:09 | INFO | embed_mulan |   Checkpoint saved (10 songs processed)
00:11:09 | INFO | embed_mulan | [11/263] DR_11
00:11:16 | INFO | embed_mulan | [12/263] DR_12
00:11:23 | INFO | embed_mulan | [13/263] EM_01
00:11:31 | INFO | embed_mulan | [14/263] EM_02
00:11:40 | INFO | embed_mulan | [15/263] EM_03
00:11:46 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/audio_embeddings.npz
00:11:46 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/text_embeddings.npz
00:11:46 | INFO | embed_mulan |   Checkpoint saved (15 songs processed)
00:11:46 | INFO | embed_mulan | [16/263] EM_04
00:11:53 | INFO | embed_mulan | [17/263] EM_05
00:11:59 | INFO | embed_mulan | [18/263] EM_06
00:12:05 | INFO | embed_mulan | [19/263] EM_07
00:12:14 | INFO | embed_mulan | [20/263] EM_08
00:12:19 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/audio_embeddings.npz
00:12:19 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/text_embeddings.npz
00:12:19 | INFO | embed_mulan |   Checkpoint saved (20 songs processed)
00:12:19 | INFO | embed_mulan | [21/263] EM_09
00:12:26 | INFO | embed_mulan | [22/263] EM_10
00:12:33 | INFO | embed_mulan | [23/263] EM_11
00:12:39 | INFO | embed_mulan | [24/263] EM_12
00:12:48 | INFO | embed_mulan | [25/263] TC2_01
00:12:52 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/audio_embeddings.npz
00:12:52 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/text_embeddings.npz
00:12:52 | INFO | embed_mulan |   Checkpoint saved (25 songs processed)
00:12:52 | INFO | embed_mulan | [26/263] TC2_02
00:12:57 | INFO | embed_mulan | [27/263] TC2_03
00:13:03 | INFO | embed_mulan | [28/263] TC2_04
00:13:08 | INFO | embed_mulan | [29/263] TC2_05
00:13:12 | INFO | embed_mulan | [30/263] TC2_06
00:13:15 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/audio_embeddings.npz
00:13:15 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/text_embeddings.npz
00:13:15 | INFO | embed_mulan |   Checkpoint saved (30 songs processed)
00:13:15 | INFO | embed_mulan | [31/263] TC2_07
00:13:19 | INFO | embed_mulan | [32/263] TC2_08
00:13:25 | INFO | embed_mulan | [33/263] TC2_09
00:13:30 | INFO | embed_mulan | [34/263] TC2_10
00:13:39 | INFO | embed_mulan | [35/263] TC2_11
00:13:44 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/audio_embeddings.npz
00:13:44 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/text_embeddings.npz
00:13:44 | INFO | embed_mulan |   Checkpoint saved (35 songs processed)
00:13:44 | INFO | embed_mulan | [36/263] TC2_12
00:13:49 | INFO | embed_mulan | [37/263] MM_01
00:13:57 | INFO | embed_mulan | [38/263] MM_02
00:14:04 | INFO | embed_mulan | [39/263] MM_03
00:14:08 | INFO | embed_mulan | [40/263] MM_04
00:14:16 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/audio_embeddings.npz
00:14:16 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/text_embeddings.npz
00:14:16 | INFO | embed_mulan |   Checkpoint saved (40 songs processed)
00:14:16 | INFO | embed_mulan | [41/263] MM_05
00:14:22 | INFO | embed_mulan | [42/263] MM_06
00:14:27 | INFO | embed_mulan | [43/263] MM_07
00:14:31 | INFO | embed_mulan | [44/263] MM_08
00:14:37 | INFO | embed_mulan | [45/263] MM_09
00:14:42 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/audio_embeddings.npz
00:14:42 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/text_embeddings.npz
00:14:42 | INFO | embed_mulan |   Checkpoint saved (45 songs processed)
00:14:42 | INFO | embed_mulan | [46/263] MM_10
00:30:26 | INFO | embed_mulan | [47/263] MM_11
00:30:40 | INFO | embed_mulan | [48/263] MM_12
00:30:51 | INFO | embed_mulan | [49/263] CH_01
00:31:02 | INFO | embed_mulan | [50/263] CH_02
00:48:26 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/audio_embeddings.npz
00:48:26 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/text_embeddings.npz
00:48:26 | INFO | embed_mulan |   Checkpoint saved (50 songs processed)
00:48:26 | INFO | embed_mulan | [51/263] CH_03
00:48:37 | INFO | embed_mulan | [52/263] CH_04
00:48:47 | INFO | embed_mulan | [53/263] CH_05
00:48:59 | INFO | embed_mulan | [54/263] CH_06
00:49:09 | INFO | embed_mulan | [55/263] CH_07
00:49:17 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/audio_embeddings.npz
00:49:17 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/text_embeddings.npz
00:49:17 | INFO | embed_mulan |   Checkpoint saved (55 songs processed)
00:49:17 | INFO | embed_mulan | [56/263] CH_08
00:49:26 | INFO | embed_mulan | [57/263] CH_09
00:49:40 | INFO | embed_mulan | [58/263] CH_10
00:49:49 | INFO | embed_mulan | [59/263] CH_11
00:49:59 | INFO | embed_mulan | [60/263] CH_12
00:50:09 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/audio_embeddings.npz
00:50:09 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/text_embeddings.npz
00:50:09 | INFO | embed_mulan |   Checkpoint saved (60 songs processed)
00:50:09 | INFO | embed_mulan | [61/263] NS_01
00:50:23 | INFO | embed_mulan | [62/263] NS_02
00:50:36 | INFO | embed_mulan | [63/263] NS_03
00:50:50 | INFO | embed_mulan | [64/263] NS_04
00:51:02 | INFO | embed_mulan | [65/263] NS_05
00:51:15 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/audio_embeddings.npz
00:51:15 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/text_embeddings.npz
00:51:15 | INFO | embed_mulan |   Checkpoint saved (65 songs processed)
00:51:15 | INFO | embed_mulan | [66/263] NS_06
00:51:27 | INFO | embed_mulan | [67/263] NS_07
00:51:36 | INFO | embed_mulan | [68/263] NS_08
00:51:44 | INFO | embed_mulan | [69/263] NS_09
00:52:38 | INFO | embed_mulan | [70/263] NS_10
00:52:49 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/audio_embeddings.npz
00:52:49 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/text_embeddings.npz
00:52:49 | INFO | embed_mulan |   Checkpoint saved (70 songs processed)
00:52:49 | INFO | embed_mulan | [71/263] NS_11
00:52:58 | INFO | embed_mulan | [72/263] NS_12
00:53:14 | INFO | embed_mulan | [73/263] CG_01
00:53:28 | INFO | embed_mulan | [74/263] CG_02
00:53:38 | INFO | embed_mulan | [75/263] CG_03
00:53:49 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/audio_embeddings.npz
00:53:49 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/text_embeddings.npz
00:53:49 | INFO | embed_mulan |   Checkpoint saved (75 songs processed)
00:53:49 | INFO | embed_mulan | [76/263] CG_04
00:53:59 | INFO | embed_mulan | [77/263] CG_05
00:54:08 | INFO | embed_mulan | [78/263] CG_06
00:54:16 | INFO | embed_mulan | [79/263] CG_07
00:54:32 | INFO | embed_mulan | [80/263] CG_08
00:54:43 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/audio_embeddings.npz
00:54:43 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/text_embeddings.npz
00:54:43 | INFO | embed_mulan |   Checkpoint saved (80 songs processed)
00:54:43 | INFO | embed_mulan | [81/263] CG_09
00:54:55 | INFO | embed_mulan | [82/263] CG_10
00:55:07 | INFO | embed_mulan | [83/263] CG_11
00:55:16 | INFO | embed_mulan | [84/263] CG_12
00:55:24 | INFO | embed_mulan | [85/263] JI_01
00:55:37 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/audio_embeddings.npz
00:55:37 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/text_embeddings.npz
00:55:37 | INFO | embed_mulan |   Checkpoint saved (85 songs processed)
00:55:37 | INFO | embed_mulan | [86/263] JI_02
00:55:47 | INFO | embed_mulan | [87/263] JI_03
00:55:58 | INFO | embed_mulan | [88/263] JI_04
00:56:08 | INFO | embed_mulan | [89/263] JI_05
00:56:20 | INFO | embed_mulan | [90/263] JI_06
00:56:29 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/audio_embeddings.npz
00:56:29 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/text_embeddings.npz
00:56:29 | INFO | embed_mulan |   Checkpoint saved (90 songs processed)
00:56:29 | INFO | embed_mulan | [91/263] JI_07
00:56:40 | INFO | embed_mulan | [92/263] JI_08
00:56:52 | INFO | embed_mulan | [93/263] JI_09
00:57:02 | INFO | embed_mulan | [94/263] JI_10
00:57:13 | INFO | embed_mulan | [95/263] JI_11
00:57:23 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/audio_embeddings.npz
00:57:23 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/text_embeddings.npz
00:57:23 | INFO | embed_mulan |   Checkpoint saved (95 songs processed)
00:57:23 | INFO | embed_mulan | [96/263] JI_12
00:57:39 | INFO | embed_mulan | [97/263] SS_01
00:57:47 | INFO | embed_mulan | [98/263] SS_02
00:57:54 | INFO | embed_mulan | [99/263] SS_03
00:58:04 | INFO | embed_mulan | [100/263] SS_04
00:58:19 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/audio_embeddings.npz
00:58:19 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/text_embeddings.npz
00:58:19 | INFO | embed_mulan |   Checkpoint saved (100 songs processed)
00:58:19 | INFO | embed_mulan | [101/263] SS_05
00:58:29 | INFO | embed_mulan | [102/263] SS_06
00:58:42 | INFO | embed_mulan | [103/263] SS_07
00:58:52 | INFO | embed_mulan | [104/263] SS_08
00:59:04 | INFO | embed_mulan | [105/263] SS_09
00:59:17 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/audio_embeddings.npz
00:59:17 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/text_embeddings.npz
00:59:17 | INFO | embed_mulan |   Checkpoint saved (105 songs processed)
00:59:17 | INFO | embed_mulan | [106/263] SS_10
00:59:29 | INFO | embed_mulan | [107/263] SS_11
00:59:45 | INFO | embed_mulan | [108/263] SS_12
00:59:54 | INFO | embed_mulan | [109/263] KM_01
01:00:03 | INFO | embed_mulan | [110/263] KM_02
01:00:12 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/audio_embeddings.npz
01:00:13 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/text_embeddings.npz
01:00:13 | INFO | embed_mulan |   Checkpoint saved (110 songs processed)
01:00:13 | INFO | embed_mulan | [111/263] KM_03
01:00:23 | INFO | embed_mulan | [112/263] KM_04
01:00:32 | INFO | embed_mulan | [113/263] KM_05
01:00:42 | INFO | embed_mulan | [114/263] KM_06
01:00:52 | INFO | embed_mulan | [115/263] KM_07
01:01:02 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/audio_embeddings.npz
01:01:02 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/text_embeddings.npz
01:01:02 | INFO | embed_mulan |   Checkpoint saved (115 songs processed)
01:01:02 | INFO | embed_mulan | [116/263] KM_08
01:01:10 | INFO | embed_mulan | [117/263] KM_09
01:01:19 | INFO | embed_mulan | [118/263] KM_10
01:01:26 | INFO | embed_mulan | [119/263] KM_11
01:01:35 | INFO | embed_mulan | [120/263] KM_12
01:01:42 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/audio_embeddings.npz
01:01:43 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/text_embeddings.npz
01:01:43 | INFO | embed_mulan |   Checkpoint saved (120 songs processed)
01:01:43 | INFO | embed_mulan | [121/263] JP_01
01:01:52 | INFO | embed_mulan | [122/263] JP_02
01:02:03 | INFO | embed_mulan | [123/263] JP_03
01:02:18 | INFO | embed_mulan | [124/263] JP_04
01:02:26 | INFO | embed_mulan | [125/263] JP_05
01:02:36 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/audio_embeddings.npz
01:02:36 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/text_embeddings.npz
01:02:36 | INFO | embed_mulan |   Checkpoint saved (125 songs processed)
01:02:36 | INFO | embed_mulan | [126/263] JP_06
01:02:48 | INFO | embed_mulan | [127/263] JP_07
01:02:57 | INFO | embed_mulan | [128/263] JP_08
01:03:22 | INFO | embed_mulan | [129/263] JP_09
01:03:32 | INFO | embed_mulan | [130/263] JP_10
01:03:41 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/audio_embeddings.npz
01:03:41 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/text_embeddings.npz
01:03:41 | INFO | embed_mulan |   Checkpoint saved (130 songs processed)
01:03:41 | INFO | embed_mulan | [131/263] JP_11
01:03:51 | INFO | embed_mulan | [132/263] JP_12
01:04:00 | INFO | embed_mulan | [133/263] GW_01
01:04:13 | INFO | embed_mulan | [134/263] GW_02
01:04:28 | INFO | embed_mulan | [135/263] GW_03
01:04:41 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/audio_embeddings.npz
01:04:41 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/text_embeddings.npz
01:04:41 | INFO | embed_mulan |   Checkpoint saved (135 songs processed)
01:04:41 | INFO | embed_mulan | [136/263] GW_04
01:04:50 | INFO | embed_mulan | [137/263] GW_05
01:04:58 | INFO | embed_mulan | [138/263] GW_06
01:05:09 | INFO | embed_mulan | [139/263] GW_07
01:05:21 | INFO | embed_mulan | [140/263] GW_08
01:05:30 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/audio_embeddings.npz
01:05:30 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/text_embeddings.npz
01:05:30 | INFO | embed_mulan |   Checkpoint saved (140 songs processed)
01:05:30 | INFO | embed_mulan | [141/263] GW_09
01:05:47 | INFO | embed_mulan | [142/263] GW_10
01:06:24 | INFO | embed_mulan | [143/263] GW_11
01:06:32 | INFO | embed_mulan | [144/263] GW_12
01:06:41 | INFO | embed_mulan | [145/263] CW_01
01:06:49 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/audio_embeddings.npz
01:06:49 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/text_embeddings.npz
01:06:49 | INFO | embed_mulan |   Checkpoint saved (145 songs processed)
01:06:49 | INFO | embed_mulan | [146/263] CW_02
01:06:55 | INFO | embed_mulan | [147/263] CW_03
01:07:53 | INFO | embed_mulan | [148/263] CW_04
01:08:03 | INFO | embed_mulan | [149/263] CW_05
01:08:10 | INFO | embed_mulan | [150/263] CW_06
01:08:23 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/audio_embeddings.npz
01:08:23 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/text_embeddings.npz
01:08:23 | INFO | embed_mulan |   Checkpoint saved (150 songs processed)
01:08:23 | INFO | embed_mulan | [151/263] CW_07
01:08:28 | INFO | embed_mulan | [152/263] CW_08
01:08:49 | INFO | embed_mulan | [153/263] CW_09
01:09:00 | INFO | embed_mulan | [154/263] CW_10
01:09:07 | INFO | embed_mulan | [155/263] CW_11
01:09:16 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/audio_embeddings.npz
01:09:16 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/text_embeddings.npz
01:09:16 | INFO | embed_mulan |   Checkpoint saved (155 songs processed)
01:09:16 | INFO | embed_mulan | [156/263] CW_12
01:09:28 | INFO | embed_mulan | [157/263] AG_01
01:09:37 | INFO | embed_mulan | [158/263] AG_02
01:09:45 | INFO | embed_mulan | [159/263] AG_03
01:09:52 | INFO | embed_mulan | [160/263] AG_04
01:10:02 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mulan/audio_embeddings.npz

MuLan LMC  — n=436  mean=0.3318  sd=0.0930  min=0.0114  max=0.6435

---
## Step 5 — LAION-CLAP-Music Embeddings
Computes embeddings using the contrastive audio-language model trained specifically on music.  
**Model:** `laion/larger_clap_music` — downloads ~600 MB on first run.  
Audio is processed in 10-second overlapping chunks and averaged.  
**Outputs:** `results/embeddings/clap/{audio,text}_embeddings.npz`, `similarities.json`  

> If this step is very slow on MPS, change `device` to `"cpu"` in the cell below.

In [7]:
embed_clap = load_script("embed_clap", "05_embed_clap.py")

clap_results = embed_clap.embed_all(
    device = device,   # swap to "cpu" if MPS is slow for this model
    force  = False,
)

if clap_results:
    sims = clap_results["sims"]
    vals = list(sims.values())
    print(f"\nCLAP LMC   — n={len(vals)}  mean={np.mean(vals):.4f}  "
          f"sd={np.std(vals):.4f}  min={np.min(vals):.4f}  max={np.max(vals):.4f}")

01:30:56 | INFO | embed_clap | Loading CLAP model for 263 songs…
01:30:57 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/bert-base-uncased/resolve/main/tokenizer_config.json "HTTP/1.1 200 OK"
01:30:57 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/bert-base-uncased/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 307 Temporary Redirect"
01:30:57 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/google-bert/bert-base-uncased/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
01:30:57 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/bert-base-uncased/tree/main?recursive=true&expand=false "HTTP/1.1 307 Temporary Redirect"
01:30:57 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/google-bert/bert-base-uncased/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
01:30:57 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/roberta-base/resolve/main/tokenizer_config.json "HTTP/1.1 200 OK"
01:30:57 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/roberta-base/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 307 Temporary Redirect"
01:30:57 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/FacebookAI/roberta-base/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
01:30:57 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/roberta-base/tree/main?recursive=true&expand=false "HTTP/1.1 307 Temporary Redirect"
01:30:58 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/FacebookAI/roberta-base/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
01:30:58 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/facebook/bart-base/resolve/main/tokenizer_config.json "HTTP/1.1 404 Not Found"
01:30:58 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/facebook/bart-base/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
01:30:58 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/facebook/bart-base/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
01:30:58 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/facebook/bart-base/resolve/main/vocab.json "HTTP/1.1 307 Temporary Redirect"
01:30:58 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/facebook/bart-base/aadd2ab0ae0c8268c7c9693540e9904811f36177/vocab.json "HTTP/1.1 200 OK"
01:30:58 | INFO | embed_clap | Loading LAION-CLAP (music model) on mps...
01:30:58 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/lukewys/laion_clap/resolve/main/music_audioset_epoch_15_esc_90.14.pt "HTTP/1.1 302 Found"
01:30:58 | INFO | embed_clap | Checkpoint at: /Users/budge.13/.cache/huggingface/hub/models--lukewys--laion_clap/snapshots/b3708341862f581175dba5c356a4ebf74a9b6651/music_audioset_epoch_15_esc_90.14.pt
01:30:58 | INFO | root | Loading HTSAT-base model config.
/opt/anaconda3/lib/python3.13/site-packages/torch/functional.py:554: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/TensorShape.cpp:4324.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
01:30:59 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/roberta-base/resolve/main/config.json "HTTP/1.1 200 OK"
01:30:59 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/roberta-base/resolve/main/model.safetensors "HTTP/1.1 302 Found"

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

RobertaModel LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
pooler.dense.weight             | MISSING    |
pooler.dense.bias               | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
01:31:00 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/roberta-base/resolve/main/tokenizer_config.json "HTTP/1.1 200 OK"
01:31:00 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/roberta-base/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 307 Temporary Redirect"
01:31:00 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/FacebookAI/roberta-base/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
01:31:00 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/roberta-base/tree/main?recursive=true&expand=false "HTTP/1.1 307 Temporary Redirect"
01:31:00 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/FacebookAI/roberta-base/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"

Load the specified checkpoint /Users/budge.13/.cache/huggingface/hub/models--lukewys--laion_clap/snapshots/b3708341862f581175dba5c356a4ebf74a9b6651/music_audioset_epoch_15_esc_90.14.pt from users.
Load Checkpoint...

01:31:02 | INFO | embed_clap | [1/263] DR_01

logit_scale_a 	 Loaded
logit_scale_t 	 Loaded
audio_branch.spectrogram_extractor.stft.conv_real.weight 	 Loaded
audio_branch.spectrogram_extractor.stft.conv_imag.weight 	 Loaded
audio_branch.logmel_extractor.melW 	 Loaded
audio_branch.bn0.weight 	 Loaded
audio_branch.bn0.bias 	 Loaded
audio_branch.patch_embed.proj.weight 	 Loaded
audio_branch.patch_embed.proj.bias 	 Loaded
audio_branch.patch_embed.norm.weight 	 Loaded
audio_branch.patch_embed.norm.bias 	 Loaded
audio_branch.layers.0.blocks.0.norm1.weight 	 Loaded
audio_branch.layers.0.blocks.0.norm1.bias 	 Loaded
audio_branch.layers.0.blocks.0.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.0.blocks.0.attn.qkv.weight 	 Loaded
audio_branch.layers.0.blocks.0.attn.qkv.bias 	 Loaded
audio_branch.layers.0.blocks.0.attn.proj.weight 	 Loaded
audio_branch.layers.0.blocks.0.attn.proj.bias 	 Loaded
audio_branch.layers.0.blocks.0.norm2.weight 	 Loaded
audio_branch.layers.0.blocks.0.norm2.bias 	 Loaded
audio_branch.layers.0.blocks.0.mlp.fc1.weight 	 Loaded
audio_branch.layers.0.blocks.0.mlp.fc1.bias 	 Loaded
audio_branch.layers.0.blocks.0.mlp.fc2.weight 	 Loaded
audio_branch.layers.0.blocks.0.mlp.fc2.bias 	 Loaded
audio_branch.layers.0.blocks.1.norm1.weight 	 Loaded
audio_branch.layers.0.blocks.1.norm1.bias 	 Loaded
audio_branch.layers.0.blocks.1.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.0.blocks.1.attn.qkv.weight 	 Loaded
audio_branch.layers.0.blocks.1.attn.qkv.bias 	 Loaded
audio_branch.layers.0.blocks.1.attn.proj.weight 	 Loaded
audio_branch.layers.0.blocks.1.attn.proj.bias 	 Loaded
audio_branch.layers.0.blocks.1.norm2.weight 	 Loaded
audio_branch.layers.0.blocks.1.norm2.bias 	 Loaded
audio_branch.layers.0.blocks.1.mlp.fc1.weight 	 Loaded
audio_branch.layers.0.blocks.1.mlp.fc1.bias 	 Loaded
audio_branch.layers.0.blocks.1.mlp.fc2.weight 	 Loaded
audio_branch.layers.0.blocks.1.mlp.fc2.bias 	 Loaded
audio_branch.layers.0.downsample.reduction.weight 	 Loaded
audio_branch.layers.0.downsample.norm.weight 	 Loaded
audio_branch.layers.0.downsample.norm.bias 	 Loaded
audio_branch.layers.1.blocks.0.norm1.weight 	 Loaded
audio_branch.layers.1.blocks.0.norm1.bias 	 Loaded
audio_branch.layers.1.blocks.0.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.1.blocks.0.attn.qkv.weight 	 Loaded
audio_branch.layers.1.blocks.0.attn.qkv.bias 	 Loaded
audio_branch.layers.1.blocks.0.attn.proj.weight 	 Loaded
audio_branch.layers.1.blocks.0.attn.proj.bias 	 Loaded
audio_branch.layers.1.blocks.0.norm2.weight 	 Loaded
audio_branch.layers.1.blocks.0.norm2.bias 	 Loaded
audio_branch.layers.1.blocks.0.mlp.fc1.weight 	 Loaded
audio_branch.layers.1.blocks.0.mlp.fc1.bias 	 Loaded
audio_branch.layers.1.blocks.0.mlp.fc2.weight 	 Loaded
audio_branch.layers.1.blocks.0.mlp.fc2.bias 	 Loaded
audio_branch.layers.1.blocks.1.norm1.weight 	 Loaded
audio_branch.layers.1.blocks.1.norm1.bias 	 Loaded
audio_branch.layers.1.blocks.1.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.1.blocks.1.attn.qkv.weight 	 Loaded
audio_branch.layers.1.blocks.1.attn.qkv.bias 	 Loaded
audio_branch.layers.1.blocks.1.attn.proj.weight 	 Loaded
audio_branch.layers.1.blocks.1.attn.proj.bias 	 Loaded
audio_branch.layers.1.blocks.1.norm2.weight 	 Loaded
audio_branch.layers.1.blocks.1.norm2.bias 	 Loaded
audio_branch.layers.1.blocks.1.mlp.fc1.weight 	 Loaded
audio_branch.layers.1.blocks.1.mlp.fc1.bias 	 Loaded
audio_branch.layers.1.blocks.1.mlp.fc2.weight 	 Loaded
audio_branch.layers.1.blocks.1.mlp.fc2.bias 	 Loaded
audio_branch.layers.1.downsample.reduction.weight 	 Loaded
audio_branch.layers.1.downsample.norm.weight 	 Loaded
audio_branch.layers.1.downsample.norm.bias 	 Loaded
audio_branch.layers.2.blocks.0.norm1.weight 	 Loaded
audio_branch.layers.2.blocks.0.norm1.bias 	 Loaded
audio_branch.layers.2.blocks.0.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.2.blocks.0.attn.qkv.weight 	 Loaded
audio_branch.layers.2.blocks.0.attn.qkv.bias 	 Loaded
audio_branch.layers.2.blocks.0.attn.proj.weight 	 Loaded
audio_branch.layers.2.blocks.0.attn.proj.bias 	 Loaded
audio_branch.layers.2.blocks.0.norm2.weight 	 Loaded
audio_branch.layers.2.blocks.0.norm2.bias 	 Loaded
audio_branch.layers.2.blocks.0.mlp.fc1.weight 	 Loaded
audio_branch.layers.2.blocks.0.mlp.fc1.bias 	 Loaded
audio_branch.layers.2.blocks.0.mlp.fc2.weight 	 Loaded
audio_branch.layers.2.blocks.0.mlp.fc2.bias 	 Loaded
audio_branch.layers.2.blocks.1.norm1.weight 	 Loaded
audio_branch.layers.2.blocks.1.norm1.bias 	 Loaded
audio_branch.layers.2.blocks.1.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.2.blocks.1.attn.qkv.weight 	 Loaded
audio_branch.layers.2.blocks.1.attn.qkv.bias 	 Loaded
audio_branch.layers.2.blocks.1.attn.proj.weight 	 Loaded
audio_branch.layers.2.blocks.1.attn.proj.bias 	 Loaded
audio_branch.layers.2.blocks.1.norm2.weight 	 Loaded
audio_branch.layers.2.blocks.1.norm2.bias 	 Loaded
audio_branch.layers.2.blocks.1.mlp.fc1.weight 	 Loaded
audio_branch.layers.2.blocks.1.mlp.fc1.bias 	 Loaded
audio_branch.layers.2.blocks.1.mlp.fc2.weight 	 Loaded
audio_branch.layers.2.blocks.1.mlp.fc2.bias 	 Loaded
audio_branch.layers.2.blocks.2.norm1.weight 	 Loaded
audio_branch.layers.2.blocks.2.norm1.bias 	 Loaded
audio_branch.layers.2.blocks.2.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.2.blocks.2.attn.qkv.weight 	 Loaded
audio_branch.layers.2.blocks.2.attn.qkv.bias 	 Loaded
audio_branch.layers.2.blocks.2.attn.proj.weight 	 Loaded
audio_branch.layers.2.blocks.2.attn.proj.bias 	 Loaded
audio_branch.layers.2.blocks.2.norm2.weight 	 Loaded
audio_branch.layers.2.blocks.2.norm2.bias 	 Loaded
audio_branch.layers.2.blocks.2.mlp.fc1.weight 	 Loaded
audio_branch.layers.2.blocks.2.mlp.fc1.bias 	 Loaded
audio_branch.layers.2.blocks.2.mlp.fc2.weight 	 Loaded
audio_branch.layers.2.blocks.2.mlp.fc2.bias 	 Loaded
audio_branch.layers.2.blocks.3.norm1.weight 	 Loaded
audio_branch.layers.2.blocks.3.norm1.bias 	 Loaded
audio_branch.layers.2.blocks.3.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.2.blocks.3.attn.qkv.weight 	 Loaded
audio_branch.layers.2.blocks.3.attn.qkv.bias 	 Loaded
audio_branch.layers.2.blocks.3.attn.proj.weight 	 Loaded
audio_branch.layers.2.blocks.3.attn.proj.bias 	 Loaded
audio_branch.layers.2.blocks.3.norm2.weight 	 Loaded
audio_branch.layers.2.blocks.3.norm2.bias 	 Loaded
audio_branch.layers.2.blocks.3.mlp.fc1.weight 	 Loaded
audio_branch.layers.2.blocks.3.mlp.fc1.bias 	 Loaded
audio_branch.layers.2.blocks.3.mlp.fc2.weight 	 Loaded
audio_branch.layers.2.blocks.3.mlp.fc2.bias 	 Loaded
audio_branch.layers.2.blocks.4.norm1.weight 	 Loaded
audio_branch.layers.2.blocks.4.norm1.bias 	 Loaded
audio_branch.layers.2.blocks.4.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.2.blocks.4.attn.qkv.weight 	 Loaded
audio_branch.layers.2.blocks.4.attn.qkv.bias 	 Loaded
audio_branch.layers.2.blocks.4.attn.proj.weight 	 Loaded
audio_branch.layers.2.blocks.4.attn.proj.bias 	 Loaded
audio_branch.layers.2.blocks.4.norm2.weight 	 Loaded
audio_branch.layers.2.blocks.4.norm2.bias 	 Loaded
audio_branch.layers.2.blocks.4.mlp.fc1.weight 	 Loaded
audio_branch.layers.2.blocks.4.mlp.fc1.bias 	 Loaded
audio_branch.layers.2.blocks.4.mlp.fc2.weight 	 Loaded
audio_branch.layers.2.blocks.4.mlp.fc2.bias 	 Loaded
audio_branch.layers.2.blocks.5.norm1.weight 	 Loaded
audio_branch.layers.2.blocks.5.norm1.bias 	 Loaded
audio_branch.layers.2.blocks.5.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.2.blocks.5.attn.qkv.weight 	 Loaded
audio_branch.layers.2.blocks.5.attn.qkv.bias 	 Loaded
audio_branch.layers.2.blocks.5.attn.proj.weight 	 Loaded
audio_branch.layers.2.blocks.5.attn.proj.bias 	 Loaded
audio_branch.layers.2.blocks.5.norm2.weight 	 Loaded
audio_branch.layers.2.blocks.5.norm2.bias 	 Loaded
audio_branch.layers.2.blocks.5.mlp.fc1.weight 	 Loaded
audio_branch.layers.2.blocks.5.mlp.fc1.bias 	 Loaded
audio_branch.layers.2.blocks.5.mlp.fc2.weight 	 Loaded
audio_branch.layers.2.blocks.5.mlp.fc2.bias 	 Loaded
audio_branch.layers.2.blocks.6.norm1.weight 	 Loaded
audio_branch.layers.2.blocks.6.norm1.bias 	 Loaded
audio_branch.layers.2.blocks.6.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.2.blocks.6.attn.qkv.weight 	 Loaded
audio_branch.layers.2.blocks.6.attn.qkv.bias 	 Loaded
audio_branch.layers.2.blocks.6.attn.proj.weight 	 Loaded
audio_branch.layers.2.blocks.6.attn.proj.bias 	 Loaded
audio_branch.layers.2.blocks.6.norm2.weight 	 Loaded
audio_branch.layers.2.blocks.6.norm2.bias 	 Loaded
audio_branch.layers.2.blocks.6.mlp.fc1.weight 	 Loaded
audio_branch.layers.2.blocks.6.mlp.fc1.bias 	 Loaded
audio_branch.layers.2.blocks.6.mlp.fc2.weight 	 Loaded
audio_branch.layers.2.blocks.6.mlp.fc2.bias 	 Loaded
audio_branch.layers.2.blocks.7.norm1.weight 	 Loaded
audio_branch.layers.2.blocks.7.norm1.bias 	 Loaded
audio_branch.layers.2.blocks.7.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.2.blocks.7.attn.qkv.weight 	 Loaded
audio_branch.layers.2.blocks.7.attn.qkv.bias 	 Loaded
audio_branch.layers.2.blocks.7.attn.proj.weight 	 Loaded
audio_branch.layers.2.blocks.7.attn.proj.bias 	 Loaded
audio_branch.layers.2.blocks.7.norm2.weight 	 Loaded
audio_branch.layers.2.blocks.7.norm2.bias 	 Loaded
audio_branch.layers.2.blocks.7.mlp.fc1.weight 	 Loaded
audio_branch.layers.2.blocks.7.mlp.fc1.bias 	 Loaded
audio_branch.layers.2.blocks.7.mlp.fc2.weight 	 Loaded
audio_branch.layers.2.blocks.7.mlp.fc2.bias 	 Loaded
audio_branch.layers.2.blocks.8.norm1.weight 	 Loaded
audio_branch.layers.2.blocks.8.norm1.bias 	 Loaded
audio_branch.layers.2.blocks.8.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.2.blocks.8.attn.qkv.weight 	 Loaded
audio_branch.layers.2.blocks.8.attn.qkv.bias 	 Loaded
audio_branch.layers.2.blocks.8.attn.proj.weight 	 Loaded
audio_branch.layers.2.blocks.8.attn.proj.bias 	 Loaded
audio_branch.layers.2.blocks.8.norm2.weight 	 Loaded
audio_branch.layers.2.blocks.8.norm2.bias 	 Loaded
audio_branch.layers.2.blocks.8.mlp.fc1.weight 	 Loaded
audio_branch.layers.2.blocks.8.mlp.fc1.bias 	 Loaded
audio_branch.layers.2.blocks.8.mlp.fc2.weight 	 Loaded
audio_branch.layers.2.blocks.8.mlp.fc2.bias 	 Loaded
audio_branch.layers.2.blocks.9.norm1.weight 	 Loaded
audio_branch.layers.2.blocks.9.norm1.bias 	 Loaded
audio_branch.layers.2.blocks.9.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.2.blocks.9.attn.qkv.weight 	 Loaded
audio_branch.layers.2.blocks.9.attn.qkv.bias 	 Loaded
audio_branch.layers.2.blocks.9.attn.proj.weight 	 Loaded
audio_branch.layers.2.blocks.9.attn.proj.bias 	 Loaded
audio_branch.layers.2.blocks.9.norm2.weight 	 Loaded
audio_branch.layers.2.blocks.9.norm2.bias 	 Loaded
audio_branch.layers.2.blocks.9.mlp.fc1.weight 	 Loaded
audio_branch.layers.2.blocks.9.mlp.fc1.bias 	 Loaded
audio_branch.layers.2.blocks.9.mlp.fc2.weight 	 Loaded
audio_branch.layers.2.blocks.9.mlp.fc2.bias 	 Loaded
audio_branch.layers.2.blocks.10.norm1.weight 	 Loaded
audio_branch.layers.2.blocks.10.norm1.bias 	 Loaded
audio_branch.layers.2.blocks.10.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.2.blocks.10.attn.qkv.weight 	 Loaded
audio_branch.layers.2.blocks.10.attn.qkv.bias 	 Loaded
audio_branch.layers.2.blocks.10.attn.proj.weight 	 Loaded
audio_branch.layers.2.blocks.10.attn.proj.bias 	 Loaded
audio_branch.layers.2.blocks.10.norm2.weight 	 Loaded
audio_branch.layers.2.blocks.10.norm2.bias 	 Loaded
audio_branch.layers.2.blocks.10.mlp.fc1.weight 	 Loaded
audio_branch.layers.2.blocks.10.mlp.fc1.bias 	 Loaded
audio_branch.layers.2.blocks.10.mlp.fc2.weight 	 Loaded
audio_branch.layers.2.blocks.10.mlp.fc2.bias 	 Loaded
audio_branch.layers.2.blocks.11.norm1.weight 	 Loaded
audio_branch.layers.2.blocks.11.norm1.bias 	 Loaded
audio_branch.layers.2.blocks.11.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.2.blocks.11.attn.qkv.weight 	 Loaded
audio_branch.layers.2.blocks.11.attn.qkv.bias 	 Loaded
audio_branch.layers.2.blocks.11.attn.proj.weight 	 Loaded
audio_branch.layers.2.blocks.11.attn.proj.bias 	 Loaded
audio_branch.layers.2.blocks.11.norm2.weight 	 Loaded
audio_branch.layers.2.blocks.11.norm2.bias 	 Loaded
audio_branch.layers.2.blocks.11.mlp.fc1.weight 	 Loaded
audio_branch.layers.2.blocks.11.mlp.fc1.bias 	 Loaded
audio_branch.layers.2.blocks.11.mlp.fc2.weight 	 Loaded
audio_branch.layers.2.blocks.11.mlp.fc2.bias 	 Loaded
audio_branch.layers.2.downsample.reduction.weight 	 Loaded
audio_branch.layers.2.downsample.norm.weight 	 Loaded
audio_branch.layers.2.downsample.norm.bias 	 Loaded
audio_branch.layers.3.blocks.0.norm1.weight 	 Loaded
audio_branch.layers.3.blocks.0.norm1.bias 	 Loaded
audio_branch.layers.3.blocks.0.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.3.blocks.0.attn.qkv.weight 	 Loaded
audio_branch.layers.3.blocks.0.attn.qkv.bias 	 Loaded
audio_branch.layers.3.blocks.0.attn.proj.weight 	 Loaded
audio_branch.layers.3.blocks.0.attn.proj.bias 	 Loaded
audio_branch.layers.3.blocks.0.norm2.weight 	 Loaded
audio_branch.layers.3.blocks.0.norm2.bias 	 Loaded
audio_branch.layers.3.blocks.0.mlp.fc1.weight 	 Loaded
audio_branch.layers.3.blocks.0.mlp.fc1.bias 	 Loaded
audio_branch.layers.3.blocks.0.mlp.fc2.weight 	 Loaded
audio_branch.layers.3.blocks.0.mlp.fc2.bias 	 Loaded
audio_branch.layers.3.blocks.1.norm1.weight 	 Loaded
audio_branch.layers.3.blocks.1.norm1.bias 	 Loaded
audio_branch.layers.3.blocks.1.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.3.blocks.1.attn.qkv.weight 	 Loaded
audio_branch.layers.3.blocks.1.attn.qkv.bias 	 Loaded
audio_branch.layers.3.blocks.1.attn.proj.weight 	 Loaded
audio_branch.layers.3.blocks.1.attn.proj.bias 	 Loaded
audio_branch.layers.3.blocks.1.norm2.weight 	 Loaded
audio_branch.layers.3.blocks.1.norm2.bias 	 Loaded
audio_branch.layers.3.blocks.1.mlp.fc1.weight 	 Loaded
audio_branch.layers.3.blocks.1.mlp.fc1.bias 	 Loaded
audio_branch.layers.3.blocks.1.mlp.fc2.weight 	 Loaded
audio_branch.layers.3.blocks.1.mlp.fc2.bias 	 Loaded
audio_branch.norm.weight 	 Loaded
audio_branch.norm.bias 	 Loaded
audio_branch.tscam_conv.weight 	 Loaded
audio_branch.tscam_conv.bias 	 Loaded
audio_branch.head.weight 	 Loaded
audio_branch.head.bias 	 Loaded
text_branch.embeddings.word_embeddings.weight 	 Loaded
text_branch.embeddings.token_type_embeddings.weight 	 Loaded
text_branch.embeddings.LayerNorm.weight 	 Loaded
text_branch.embeddings.LayerNorm.bias 	 Loaded
text_branch.embeddings.position_embeddings.weight 	 Loaded
text_branch.encoder.layer.0.attention.self.query.weight 	 Loaded
text_branch.encoder.layer.0.attention.self.query.bias 	 Loaded
text_branch.encoder.layer.0.attention.self.key.weight 	 Loaded
text_branch.encoder.layer.0.attention.self.key.bias 	 Loaded
text_branch.encoder.layer.0.attention.self.value.weight 	 Loaded
text_branch.encoder.layer.0.attention.self.value.bias 	 Loaded
text_branch.encoder.layer.0.attention.output.dense.weight 	 Loaded
text_branch.encoder.layer.0.attention.output.dense.bias 	 Loaded
text_branch.encoder.layer.0.attention.output.LayerNorm.weight 	 Loaded
text_branch.encoder.layer.0.attention.output.LayerNorm.bias 	 Loaded
text_branch.encoder.layer.0.intermediate.dense.weight 	 Loaded
text_branch.encoder.layer.0.intermediate.dense.bias 	 Loaded
text_branch.encoder.layer.0.output.dense.weight 	 Loaded
text_branch.encoder.layer.0.output.dense.bias 	 Loaded
text_branch.encoder.layer.0.output.LayerNorm.weight 	 Loaded
text_branch.encoder.layer.0.output.LayerNorm.bias 	 Loaded
text_branch.encoder.layer.1.attention.self.query.weight 	 Loaded
text_branch.encoder.layer.1.attention.self.query.bias 	 Loaded
text_branch.encoder.layer.1.attention.self.key.weight 	 Loaded
text_branch.encoder.layer.1.attention.self.key.bias 	 Loaded
text_branch.encoder.layer.1.attention.self.value.weight 	 Loaded
text_branch.encoder.layer.1.attention.self.value.bias 	 Loaded
text_branch.encoder.layer.1.attention.output.dense.weight 	 Loaded
text_branch.encoder.layer.1.attention.output.dense.bias 	 Loaded
text_branch.encoder.layer.1.attention.output.LayerNorm.weight 	 Loaded
text_branch.encoder.layer.1.attention.output.LayerNorm.bias 	 Loaded
text_branch.encoder.layer.1.intermediate.dense.weight 	 Loaded
text_branch.encoder.layer.1.intermediate.dense.bias 	 Loaded
text_branch.encoder.layer.1.output.dense.weight 	 Loaded
text_branch.encoder.layer.1.output.dense.bias 	 Loaded
text_branch.encoder.layer.1.output.LayerNorm.weight 	 Loaded
text_branch.encoder.layer.1.output.LayerNorm.bias 	 Loaded
text_branch.encoder.layer.2.attention.self.query.weight 	 Loaded
text_branch.encoder.layer.2.attention.self.query.bias 	 Loaded
text_branch.encoder.layer.2.attention.self.key.weight 	 Loaded
text_branch.encoder.layer.2.attention.self.key.bias 	 Loaded
text_branch.encoder.layer.2.attention.self.value.weight 	 Loaded
text_branch.encoder.layer.2.attention.self.value.bias 	 Loaded
text_branch.encoder.layer.2.attention.output.dense.weight 	 Loaded
text_branch.encoder.layer.2.attention.output.dense.bias 	 Loaded
text_branch.encoder.layer.2.attention.output.LayerNorm.weight 	 Loaded
text_branch.encoder.layer.2.attention.output.LayerNorm.bias 	 Loaded
text_branch.encoder.layer.2.intermediate.dense.weight 	 Loaded
text_branch.encoder.layer.2.intermediate.dense.bias 	 Loaded
text_branch.encoder.layer.2.output.dense.weight 	 Loaded
text_branch.encoder.layer.2.output.dense.bias 	 Loaded
text_branch.encoder.layer.2.output.LayerNorm.weight 	 Loaded
text_branch.encoder.layer.2.output.LayerNorm.bias 	 Loaded
text_branch.encoder.layer.3.attention.self.query.weight 	 Loaded
text_branch.encoder.layer.3.attention.self.query.bias 	 Loaded
text_branch.encoder.layer.3.attention.self.key.weight 	 Loaded
text_branch.encoder.layer.3.attention.self.key.bias 	 Loaded
text_branch.encoder.layer.3.attention.self.value.weight 	 Loaded
text_branch.encoder.layer.3.attention.self.value.bias 	 Loaded
text_branch.encoder.layer.3.attention.output.dense.weight 	 Loaded
text_branch.encoder.layer.3.attention.output.dense.bias 	 Loaded
text_branch.encoder.layer.3.attention.output.LayerNorm.weight 	 Loaded
text_branch.encoder.layer.3.attention.output.LayerNorm.bias 	 Loaded
text_branch.encoder.layer.3.intermediate.dense.weight 	 Loaded
text_branch.encoder.layer.3.intermediate.dense.bias 	 Loaded
text_branch.encoder.layer.3.output.dense.weight 	 Loaded
text_branch.encoder.layer.3.output.dense.bias 	 Loaded
text_branch.encoder.layer.3.output.LayerNorm.weight 	 Loaded
text_branch.encoder.layer.3.output.LayerNorm.bias 	 Loaded
text_branch.encoder.layer.4.attention.self.query.weight 	 Loaded
text_branch.encoder.layer.4.attention.self.query.bias 	 Loaded
text_branch.encoder.layer.4.attention.self.key.weight 	 Loaded
text_branch.encoder.layer.4.attention.self.key.bias 	 Loaded
text_branch.encoder.layer.4.attention.self.value.weight 	 Loaded
text_branch.encoder.layer.4.attention.self.value.bias 	 Loaded
text_branch.encoder.layer.4.attention.output.dense.weight 	 Loaded
text_branch.encoder.layer.4.attention.output.dense.bias 	 Loaded
text_branch.encoder.layer.4.attention.output.LayerNorm.weight 	 Loaded
text_branch.encoder.layer.4.attention.output.LayerNorm.bias 	 Loaded
text_branch.encoder.layer.4.intermediate.dense.weight 	 Loaded
text_branch.encoder.layer.4.intermediate.dense.bias 	 Loaded
text_branch.encoder.layer.4.output.dense.weight 	 Loaded
text_branch.encoder.layer.4.output.dense.bias 	 Loaded
text_branch.encoder.layer.4.output.LayerNorm.weight 	 Loaded
text_branch.encoder.layer.4.output.LayerNorm.bias 	 Loaded
text_branch.encoder.layer.5.attention.self.query.weight 	 Loaded
text_branch.encoder.layer.5.attention.self.query.bias 	 Loaded
text_branch.encoder.layer.5.attention.self.key.weight 	 Loaded
text_branch.encoder.layer.5.attention.self.key.bias 	 Loaded
text_branch.encoder.layer.5.attention.self.value.weight 	 Loaded
text_branch.encoder.layer.5.attention.self.value.bias 	 Loaded
text_branch.encoder.layer.5.attention.output.dense.weight 	 Loaded
text_branch.encoder.layer.5.attention.output.dense.bias 	 Loaded

01:31:03 | INFO | embed_clap | [2/263] DR_02
01:31:03 | INFO | embed_clap | [3/263] DR_03
01:31:03 | INFO | embed_clap | [4/263] DR_04
01:31:04 | INFO | embed_clap | [5/263] DR_05
01:31:04 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:31:04 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:31:04 | INFO | embed_clap |   Checkpoint (5 done)
01:31:04 | INFO | embed_clap | [6/263] DR_06
01:31:04 | INFO | embed_clap | [7/263] DR_07
01:31:05 | INFO | embed_clap | [8/263] DR_08
01:31:05 | INFO | embed_clap | [9/263] DR_09
01:31:06 | INFO | embed_clap | [10/263] DR_10
01:31:07 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:31:07 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:31:07 | INFO | embed_clap |   Checkpoint (10 done)
01:31:07 | INFO | embed_clap | [11/263] DR_11
01:31:07 | INFO | embed_clap | [12/263] DR_12
01:31:08 | INFO | embed_clap | [13/263] EM_01
01:31:08 | INFO | embed_clap | [14/263] EM_02
01:31:09 | INFO | embed_clap | [15/263] EM_03
01:31:10 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:31:10 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:31:10 | INFO | embed_clap |   Checkpoint (15 done)
01:31:10 | INFO | embed_clap | [16/263] EM_04
01:31:10 | INFO | embed_clap | [17/263] EM_05
01:31:10 | INFO | embed_clap | [18/263] EM_06
01:31:11 | INFO | embed_clap | [19/263] EM_07
01:31:12 | INFO | embed_clap | [20/263] EM_08
01:31:12 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:31:12 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:31:12 | INFO | embed_clap |   Checkpoint (20 done)
01:31:12 | INFO | embed_clap | [21/263] EM_09
01:31:12 | INFO | embed_clap | [22/263] EM_10
01:31:13 | INFO | embed_clap | [23/263] EM_11
01:31:13 | INFO | embed_clap | [24/263] EM_12
01:31:14 | INFO | embed_clap | [25/263] TC2_01
01:31:15 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:31:15 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:31:15 | INFO | embed_clap |   Checkpoint (25 done)
01:31:15 | INFO | embed_clap | [26/263] TC2_02
01:31:15 | INFO | embed_clap | [27/263] TC2_03
01:31:16 | INFO | embed_clap | [28/263] TC2_04
01:31:17 | INFO | embed_clap | [29/263] TC2_05
01:31:17 | INFO | embed_clap | [30/263] TC2_06
01:31:17 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:31:17 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:31:17 | INFO | embed_clap |   Checkpoint (30 done)
01:31:17 | INFO | embed_clap | [31/263] TC2_07
01:31:18 | INFO | embed_clap | [32/263] TC2_08
01:31:18 | INFO | embed_clap | [33/263] TC2_09
01:31:18 | INFO | embed_clap | [34/263] TC2_10
01:31:19 | INFO | embed_clap | [35/263] TC2_11
01:31:19 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:31:19 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:31:19 | INFO | embed_clap |   Checkpoint (35 done)
01:31:19 | INFO | embed_clap | [36/263] TC2_12
01:31:20 | INFO | embed_clap | [37/263] MM_01
01:31:20 | INFO | embed_clap | [38/263] MM_02
01:31:21 | INFO | embed_clap | [39/263] MM_03
01:31:21 | INFO | embed_clap | [40/263] MM_04
01:31:21 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:31:21 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:31:21 | INFO | embed_clap |   Checkpoint (40 done)
01:31:21 | INFO | embed_clap | [41/263] MM_05
01:31:22 | INFO | embed_clap | [42/263] MM_06
01:31:22 | INFO | embed_clap | [43/263] MM_07
01:31:23 | INFO | embed_clap | [44/263] MM_08
01:31:23 | INFO | embed_clap | [45/263] MM_09
01:31:23 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:31:23 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:31:23 | INFO | embed_clap |   Checkpoint (45 done)
01:31:23 | INFO | embed_clap | [46/263] MM_10
01:31:24 | INFO | embed_clap | [47/263] MM_11
01:31:24 | INFO | embed_clap | [48/263] MM_12
01:31:25 | INFO | embed_clap | [49/263] CH_01
01:31:25 | INFO | embed_clap | [50/263] CH_02
01:31:26 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:31:26 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:31:26 | INFO | embed_clap |   Checkpoint (50 done)
01:31:26 | INFO | embed_clap | [51/263] CH_03
01:31:26 | INFO | embed_clap | [52/263] CH_04
01:31:26 | INFO | embed_clap | [53/263] CH_05
01:31:27 | INFO | embed_clap | [54/263] CH_06
01:31:27 | INFO | embed_clap | [55/263] CH_07
01:31:27 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:31:27 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:31:27 | INFO | embed_clap |   Checkpoint (55 done)
01:31:27 | INFO | embed_clap | [56/263] CH_08
01:31:28 | INFO | embed_clap | [57/263] CH_09
01:31:28 | INFO | embed_clap | [58/263] CH_10
01:31:29 | INFO | embed_clap | [59/263] CH_11
01:31:29 | INFO | embed_clap | [60/263] CH_12
01:31:30 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:31:30 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:31:30 | INFO | embed_clap |   Checkpoint (60 done)
01:31:30 | INFO | embed_clap | [61/263] NS_01
01:31:30 | INFO | embed_clap | [62/263] NS_02
01:31:31 | INFO | embed_clap | [63/263] NS_03
01:31:31 | INFO | embed_clap | [64/263] NS_04
01:31:32 | INFO | embed_clap | [65/263] NS_05
01:31:32 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:31:32 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:31:32 | INFO | embed_clap |   Checkpoint (65 done)
01:31:32 | INFO | embed_clap | [66/263] NS_06
01:31:33 | INFO | embed_clap | [67/263] NS_07
01:31:33 | INFO | embed_clap | [68/263] NS_08
01:31:33 | INFO | embed_clap | [69/263] NS_09
01:31:35 | INFO | embed_clap | [70/263] NS_10
01:31:36 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:31:36 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:31:36 | INFO | embed_clap |   Checkpoint (70 done)
01:31:36 | INFO | embed_clap | [71/263] NS_11
01:31:36 | INFO | embed_clap | [72/263] NS_12
01:31:36 | INFO | embed_clap | [73/263] CG_01
01:31:37 | INFO | embed_clap | [74/263] CG_02
01:31:37 | INFO | embed_clap | [75/263] CG_03
01:31:38 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:31:38 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:31:38 | INFO | embed_clap |   Checkpoint (75 done)
01:31:38 | INFO | embed_clap | [76/263] CG_04
01:31:38 | INFO | embed_clap | [77/263] CG_05
01:31:38 | INFO | embed_clap | [78/263] CG_06
01:31:39 | INFO | embed_clap | [79/263] CG_07
01:31:39 | INFO | embed_clap | [80/263] CG_08
01:31:40 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:31:40 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:31:40 | INFO | embed_clap |   Checkpoint (80 done)
01:31:40 | INFO | embed_clap | [81/263] CG_09
01:31:40 | INFO | embed_clap | [82/263] CG_10
01:31:41 | INFO | embed_clap | [83/263] CG_11
01:31:41 | INFO | embed_clap | [84/263] CG_12
01:31:41 | INFO | embed_clap | [85/263] JI_01
01:31:42 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:31:42 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:31:42 | INFO | embed_clap |   Checkpoint (85 done)
01:31:42 | INFO | embed_clap | [86/263] JI_02
01:31:42 | INFO | embed_clap | [87/263] JI_03
01:31:43 | INFO | embed_clap | [88/263] JI_04
01:31:43 | INFO | embed_clap | [89/263] JI_05
01:31:43 | INFO | embed_clap | [90/263] JI_06
01:31:44 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:31:44 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:31:44 | INFO | embed_clap |   Checkpoint (90 done)
01:31:44 | INFO | embed_clap | [91/263] JI_07
01:31:44 | INFO | embed_clap | [92/263] JI_08
01:31:44 | INFO | embed_clap | [93/263] JI_09
01:31:45 | INFO | embed_clap | [94/263] JI_10
01:31:45 | INFO | embed_clap | [95/263] JI_11
01:31:46 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:31:46 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:31:46 | INFO | embed_clap |   Checkpoint (95 done)
01:31:46 | INFO | embed_clap | [96/263] JI_12
01:31:46 | INFO | embed_clap | [97/263] SS_01
01:31:47 | INFO | embed_clap | [98/263] SS_02
01:31:47 | INFO | embed_clap | [99/263] SS_03
01:31:47 | INFO | embed_clap | [100/263] SS_04
01:31:48 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:31:48 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:31:48 | INFO | embed_clap |   Checkpoint (100 done)
01:31:48 | INFO | embed_clap | [101/263] SS_05
01:31:48 | INFO | embed_clap | [102/263] SS_06
01:31:49 | INFO | embed_clap | [103/263] SS_07
01:31:49 | INFO | embed_clap | [104/263] SS_08
01:31:49 | INFO | embed_clap | [105/263] SS_09
01:31:50 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:31:50 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:31:50 | INFO | embed_clap |   Checkpoint (105 done)
01:31:50 | INFO | embed_clap | [106/263] SS_10
01:31:50 | INFO | embed_clap | [107/263] SS_11
01:31:51 | INFO | embed_clap | [108/263] SS_12
01:31:51 | INFO | embed_clap | [109/263] KM_01
01:31:51 | INFO | embed_clap | [110/263] KM_02
01:31:52 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:31:52 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:31:52 | INFO | embed_clap |   Checkpoint (110 done)
01:31:52 | INFO | embed_clap | [111/263] KM_03
01:31:52 | INFO | embed_clap | [112/263] KM_04
01:31:52 | INFO | embed_clap | [113/263] KM_05
01:31:53 | INFO | embed_clap | [114/263] KM_06
01:31:53 | INFO | embed_clap | [115/263] KM_07
01:31:54 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:31:54 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:31:54 | INFO | embed_clap |   Checkpoint (115 done)
01:31:54 | INFO | embed_clap | [116/263] KM_08
01:31:54 | INFO | embed_clap | [117/263] KM_09
01:31:54 | INFO | embed_clap | [118/263] KM_10
01:31:55 | INFO | embed_clap | [119/263] KM_11
01:31:55 | INFO | embed_clap | [120/263] KM_12
01:31:55 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:31:55 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:31:55 | INFO | embed_clap |   Checkpoint (120 done)
01:31:55 | INFO | embed_clap | [121/263] JP_01
01:31:56 | INFO | embed_clap | [122/263] JP_02
01:31:56 | INFO | embed_clap | [123/263] JP_03
01:31:57 | INFO | embed_clap | [124/263] JP_04
01:31:57 | INFO | embed_clap | [125/263] JP_05
01:31:57 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:31:57 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:31:57 | INFO | embed_clap |   Checkpoint (125 done)
01:31:57 | INFO | embed_clap | [126/263] JP_06
01:31:58 | INFO | embed_clap | [127/263] JP_07
01:31:58 | INFO | embed_clap | [128/263] JP_08
01:31:59 | INFO | embed_clap | [129/263] JP_09
01:31:59 | INFO | embed_clap | [130/263] JP_10
01:32:00 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:32:00 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:32:00 | INFO | embed_clap |   Checkpoint (130 done)
01:32:00 | INFO | embed_clap | [131/263] JP_11
01:32:00 | INFO | embed_clap | [132/263] JP_12
01:32:01 | INFO | embed_clap | [133/263] GW_01
01:32:01 | INFO | embed_clap | [134/263] GW_02
01:32:02 | INFO | embed_clap | [135/263] GW_03
01:32:02 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:32:02 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:32:02 | INFO | embed_clap |   Checkpoint (135 done)
01:32:02 | INFO | embed_clap | [136/263] GW_04
01:32:02 | INFO | embed_clap | [137/263] GW_05
01:32:03 | INFO | embed_clap | [138/263] GW_06
01:32:03 | INFO | embed_clap | [139/263] GW_07
01:32:03 | INFO | embed_clap | [140/263] GW_08
01:32:04 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:32:04 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:32:04 | INFO | embed_clap |   Checkpoint (140 done)
01:32:04 | INFO | embed_clap | [141/263] GW_09
01:32:04 | INFO | embed_clap | [142/263] GW_10
01:32:06 | INFO | embed_clap | [143/263] GW_11
01:32:06 | INFO | embed_clap | [144/263] GW_12
01:32:06 | INFO | embed_clap | [145/263] CW_01
01:32:07 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:32:07 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:32:07 | INFO | embed_clap |   Checkpoint (145 done)
01:32:07 | INFO | embed_clap | [146/263] CW_02
01:32:07 | INFO | embed_clap | [147/263] CW_03
01:32:09 | INFO | embed_clap | [148/263] CW_04
01:32:09 | INFO | embed_clap | [149/263] CW_05
01:32:09 | INFO | embed_clap | [150/263] CW_06
01:32:10 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:32:10 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:32:10 | INFO | embed_clap |   Checkpoint (150 done)
01:32:10 | INFO | embed_clap | [151/263] CW_07
01:32:10 | INFO | embed_clap | [152/263] CW_08
01:32:12 | INFO | embed_clap | [153/263] CW_09
01:32:12 | INFO | embed_clap | [154/263] CW_10
01:32:12 | INFO | embed_clap | [155/263] CW_11
01:32:13 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:32:13 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:32:13 | INFO | embed_clap |   Checkpoint (155 done)
01:32:13 | INFO | embed_clap | [156/263] CW_12
01:32:14 | INFO | embed_clap | [157/263] AG_01
01:32:14 | INFO | embed_clap | [158/263] AG_02
01:32:14 | INFO | embed_clap | [159/263] AG_03
01:32:15 | INFO | embed_clap | [160/263] AG_04
01:32:15 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:32:15 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:32:15 | INFO | embed_clap |   Checkpoint (160 done)
01:32:15 | INFO | embed_clap | [161/263] AG_05
01:32:15 | INFO | embed_clap | [162/263] AG_06
01:32:16 | INFO | embed_clap | [163/263] AG_07
01:32:16 | INFO | embed_clap | [164/263] AG_08
01:32:16 | INFO | embed_clap | [165/263] AG_09
01:32:17 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:32:17 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:32:17 | INFO | embed_clap |   Checkpoint (165 done)
01:32:17 | INFO | embed_clap | [166/263] AG_10
01:32:17 | INFO | embed_clap | [167/263] AG_11
01:32:17 | INFO | embed_clap | [168/263] AG_12
01:32:18 | INFO | embed_clap | [169/263] ES_01
01:32:18 | INFO | embed_clap | [170/263] ES_02
01:32:18 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:32:18 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:32:18 | INFO | embed_clap |   Checkpoint (170 done)
01:32:18 | INFO | embed_clap | [171/263] ES_03
01:32:19 | INFO | embed_clap | [172/263] ES_04
01:32:19 | INFO | embed_clap | [173/263] ES_05
01:32:20 | INFO | embed_clap | [174/263] ES_06
01:32:20 | INFO | embed_clap | [175/263] ES_07
01:32:20 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:32:20 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:32:20 | INFO | embed_clap |   Checkpoint (175 done)
01:32:20 | INFO | embed_clap | [176/263] ES_08
01:32:21 | INFO | embed_clap | [177/263] ES_09
01:32:21 | INFO | embed_clap | [178/263] ES_10
01:32:21 | INFO | embed_clap | [179/263] ES_11
01:32:22 | INFO | embed_clap | [180/263] ES_12
01:32:22 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz
01:32:22 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/text_embeddings.npz
01:32:22 | INFO | embed_clap |   Checkpoint (180 done)
01:32:22 | INFO | embed_clap | [181/263] BE_01
01:32:22 | INFO | embed_clap | [182/263] BE_02
01:32:23 | INFO | embed_clap | [183/263] BE_03
01:32:23 | INFO | embed_clap | [184/263] BE_04
01:32:24 | INFO | embed_clap | [185/263] BE_05
01:32:24 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/clap/audio_embeddings.npz

CLAP LMC   — n=436  mean=0.0744  sd=0.0998  min=-0.2297  max=0.4262

---
## Step 6 — MERT + Sentence-BERT (Late-Fusion Baseline)
Computes audio embeddings (MERT) and text embeddings (Sentence-BERT) **independently**,  
then takes cosine similarity across the two separate spaces.  
This is the critical baseline: if jointly-trained models (Steps 4–5) outperform this,  
it confirms that the shared embedding space — not just acoustic or semantic content alone — drives LMC predictive validity.  
**Models:** `m-a-p/MERT-v1-95M` (~380 MB) + `all-mpnet-base-v2` (~420 MB)  
**Outputs:** `results/embeddings/mert_sbert/{audio,text}_embeddings.npz`, `similarities.json`

In [8]:
embed_mert = load_script("embed_mert_sbert", "06_embed_mert_sbert.py")

mert_results = embed_mert.embed_all(
    device = device,
    force  = False,
)

if mert_results:
    sims = mert_results["sims"]
    vals = list(sims.values())
    print(f"\nMERT+SBERT — n={len(vals)}  mean={np.mean(vals):.4f}  "
          f"sd={np.std(vals):.4f}  min={np.min(vals):.4f}  max={np.max(vals):.4f}")

01:33:01 | INFO | embed_mert_sbert | Loading models for 263 songs…
01:33:01 | INFO | embed_mert_sbert | Loading MERT (m-a-p/MERT-v1-95M) on mps…
01:33:01 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/m-a-p/MERT-v1-95M/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
01:33:01 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/m-a-p/MERT-v1-95M/resolve/main/preprocessor_config.json "HTTP/1.1 307 Temporary Redirect"
01:33:01 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/m-a-p/MERT-v1-95M/12af15fef9d0ac838c3f475bfbbf26d2060dd4f5/preprocessor_config.json "HTTP/1.1 200 OK"
01:33:01 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/m-a-p/MERT-v1-95M/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
01:33:01 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/m-a-p/MERT-v1-95M/12af15fef9d0ac838c3f475bfbbf26d2060dd4f5/config.json "HTTP/1.1 200 OK"
01:33:01 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/m-a-p/MERT-v1-95M/resolve/main/configuration_MERT.py "HTTP/1.1 307 Temporary Redirect"
01:33:01 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/m-a-p/MERT-v1-95M/12af15fef9d0ac838c3f475bfbbf26d2060dd4f5/configuration_MERT.py "HTTP/1.1 200 OK"
01:33:02 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/m-a-p/MERT-v1-95M/resolve/main/modeling_MERT.py "HTTP/1.1 307 Temporary Redirect"
01:33:02 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/m-a-p/MERT-v1-95M/12af15fef9d0ac838c3f475bfbbf26d2060dd4f5/modeling_MERT.py "HTTP/1.1 200 OK"
01:33:02 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/m-a-p/MERT-v1-95M/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"

Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]

01:33:03 | INFO | embed_mert_sbert | Loading SBERT (sentence-transformers/all-mpnet-base-v2) on mps…
01:33:03 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
01:33:03 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/modules.json "HTTP/1.1 200 OK"
01:33:03 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
01:33:03 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config_sentence_transformers.json "HTTP/1.1 200 OK"
01:33:03 | INFO | sentence_transformers.base.model | Loading SentenceTransformer model from sentence-transformers/all-mpnet-base-v2.
01:33:03 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
01:33:03 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config_sentence_transformers.json "HTTP/1.1 200 OK"
01:33:03 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
01:33:03 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/README.md "HTTP/1.1 200 OK"
01:33:03 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
01:33:03 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/modules.json "HTTP/1.1 200 OK"
01:33:03 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/sentence_bert_config.json "HTTP/1.1 307 Temporary Redirect"
01:33:03 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/sentence_bert_config.json "HTTP/1.1 200 OK"
01:33:03 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
01:33:03 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
01:33:03 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config.json "HTTP/1.1 200 OK"

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
01:33:03 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
01:33:03 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
01:33:03 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/video_preprocessor_config.json "HTTP/1.1 404 Not Found"
01:33:03 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
01:33:03 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
01:33:03 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/tokenizer_config.json "HTTP/1.1 200 OK"
01:33:04 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
01:33:04 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config.json "HTTP/1.1 200 OK"
01:33:04 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
01:33:04 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config.json "HTTP/1.1 200 OK"
01:33:04 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
01:33:04 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/tokenizer_config.json "HTTP/1.1 200 OK"
01:33:04 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-mpnet-base-v2/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
01:33:04 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-mpnet-base-v2/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
01:33:04 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"
01:33:04 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/1_Pooling%2Fconfig.json "HTTP/1.1 200 OK"
01:33:04 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-mpnet-base-v2 "HTTP/1.1 200 OK"
01:33:05 | INFO | embed_mert_sbert | [1/263] DR_01
`use_return_dict` is deprecated! Use `return_dict` instead!
01:33:36 | INFO | embed_mert_sbert | [2/263] DR_02
01:34:38 | INFO | embed_mert_sbert | [3/263] DR_03
01:36:17 | INFO | embed_mert_sbert | [4/263] DR_04
01:37:52 | INFO | embed_mert_sbert | [5/263] DR_05
01:40:02 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/audio_embeddings.npz
01:40:02 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/text_embeddings.npz
01:40:02 | INFO | embed_mert_sbert |   Checkpoint (5 done)
01:40:02 | INFO | embed_mert_sbert | [6/263] DR_06
01:41:36 | INFO | embed_mert_sbert | [7/263] DR_07
01:43:15 | INFO | embed_mert_sbert | [8/263] DR_08
01:44:55 | INFO | embed_mert_sbert | [9/263] DR_09
01:46:38 | INFO | embed_mert_sbert | [10/263] DR_10
01:48:23 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/audio_embeddings.npz
01:48:23 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/text_embeddings.npz
01:48:23 | INFO | embed_mert_sbert |   Checkpoint (10 done)
01:48:23 | INFO | embed_mert_sbert | [11/263] DR_11
01:49:50 | INFO | embed_mert_sbert | [12/263] DR_12
01:51:26 | INFO | embed_mert_sbert | [13/263] EM_01
01:52:55 | INFO | embed_mert_sbert | [14/263] EM_02
01:54:43 | INFO | embed_mert_sbert | [15/263] EM_03
01:56:14 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/audio_embeddings.npz
01:56:14 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/text_embeddings.npz
01:56:14 | INFO | embed_mert_sbert |   Checkpoint (15 done)
01:56:14 | INFO | embed_mert_sbert | [16/263] EM_04
01:57:47 | INFO | embed_mert_sbert | [17/263] EM_05
01:59:26 | INFO | embed_mert_sbert | [18/263] EM_06
02:01:14 | INFO | embed_mert_sbert | [19/263] EM_07
02:02:43 | INFO | embed_mert_sbert | [20/263] EM_08
02:05:01 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/audio_embeddings.npz
02:05:01 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/text_embeddings.npz
02:05:01 | INFO | embed_mert_sbert |   Checkpoint (20 done)
02:05:01 | INFO | embed_mert_sbert | [21/263] EM_09
02:06:39 | INFO | embed_mert_sbert | [22/263] EM_10
02:08:18 | INFO | embed_mert_sbert | [23/263] EM_11
02:10:03 | INFO | embed_mert_sbert | [24/263] EM_12
02:11:58 | INFO | embed_mert_sbert | [25/263] TC2_01
02:13:40 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/audio_embeddings.npz
02:13:40 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/text_embeddings.npz
02:13:40 | INFO | embed_mert_sbert |   Checkpoint (25 done)
02:13:40 | INFO | embed_mert_sbert | [26/263] TC2_02
02:15:59 | INFO | embed_mert_sbert | [27/263] TC2_03
02:17:43 | INFO | embed_mert_sbert | [28/263] TC2_04
02:19:17 | INFO | embed_mert_sbert | [29/263] TC2_05
02:21:18 | INFO | embed_mert_sbert | [30/263] TC2_06
02:23:10 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/audio_embeddings.npz
02:23:10 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/text_embeddings.npz
02:23:10 | INFO | embed_mert_sbert |   Checkpoint (30 done)
02:23:10 | INFO | embed_mert_sbert | [31/263] TC2_07
02:25:08 | INFO | embed_mert_sbert | [32/263] TC2_08
02:43:02 | INFO | embed_mert_sbert | [33/263] TC2_09
03:15:51 | INFO | embed_mert_sbert | [34/263] TC2_10
03:49:56 | INFO | embed_mert_sbert | [35/263] TC2_11
04:22:20 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/audio_embeddings.npz
04:22:20 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/text_embeddings.npz
04:22:20 | INFO | embed_mert_sbert |   Checkpoint (35 done)
04:22:20 | INFO | embed_mert_sbert | [36/263] TC2_12
04:55:16 | INFO | embed_mert_sbert | [37/263] MM_01
05:30:39 | INFO | embed_mert_sbert | [38/263] MM_02
06:07:08 | INFO | embed_mert_sbert | [39/263] MM_03
06:09:05 | INFO | embed_mert_sbert | [40/263] MM_04
06:11:22 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/audio_embeddings.npz
06:11:22 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/text_embeddings.npz
06:11:22 | INFO | embed_mert_sbert |   Checkpoint (40 done)
06:11:22 | INFO | embed_mert_sbert | [41/263] MM_05
06:13:16 | INFO | embed_mert_sbert | [42/263] MM_06
06:15:39 | INFO | embed_mert_sbert | [43/263] MM_07
06:17:25 | INFO | embed_mert_sbert | [44/263] MM_08
06:20:10 | INFO | embed_mert_sbert | [45/263] MM_09
06:22:35 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/audio_embeddings.npz
06:22:35 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/text_embeddings.npz
06:22:35 | INFO | embed_mert_sbert |   Checkpoint (45 done)
06:22:35 | INFO | embed_mert_sbert | [46/263] MM_10
06:24:06 | INFO | embed_mert_sbert | [47/263] MM_11
06:26:11 | INFO | embed_mert_sbert | [48/263] MM_12
06:27:49 | INFO | embed_mert_sbert | [49/263] CH_01
06:29:20 | INFO | embed_mert_sbert | [50/263] CH_02
06:31:43 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/audio_embeddings.npz
06:31:43 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/text_embeddings.npz
06:31:43 | INFO | embed_mert_sbert |   Checkpoint (50 done)
06:31:43 | INFO | embed_mert_sbert | [51/263] CH_03
06:33:29 | INFO | embed_mert_sbert | [52/263] CH_04
06:36:39 | INFO | embed_mert_sbert | [53/263] CH_05
06:38:18 | INFO | embed_mert_sbert | [54/263] CH_06
06:40:09 | INFO | embed_mert_sbert | [55/263] CH_07
06:41:54 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/audio_embeddings.npz
06:41:54 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/text_embeddings.npz
06:41:54 | INFO | embed_mert_sbert |   Checkpoint (55 done)
06:41:54 | INFO | embed_mert_sbert | [56/263] CH_08
06:43:46 | INFO | embed_mert_sbert | [57/263] CH_09
06:45:51 | INFO | embed_mert_sbert | [58/263] CH_10
06:47:28 | INFO | embed_mert_sbert | [59/263] CH_11
06:49:19 | INFO | embed_mert_sbert | [60/263] CH_12
06:52:24 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/audio_embeddings.npz
06:52:24 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/text_embeddings.npz
06:52:24 | INFO | embed_mert_sbert |   Checkpoint (60 done)
06:52:24 | INFO | embed_mert_sbert | [61/263] NS_01
06:54:19 | INFO | embed_mert_sbert | [62/263] NS_02
06:56:24 | INFO | embed_mert_sbert | [63/263] NS_03
06:57:54 | INFO | embed_mert_sbert | [64/263] NS_04
06:59:53 | INFO | embed_mert_sbert | [65/263] NS_05
07:01:42 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/audio_embeddings.npz
07:01:42 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/text_embeddings.npz
07:01:42 | INFO | embed_mert_sbert |   Checkpoint (65 done)
07:01:42 | INFO | embed_mert_sbert | [66/263] NS_06
07:03:37 | INFO | embed_mert_sbert | [67/263] NS_07
07:05:49 | INFO | embed_mert_sbert | [68/263] NS_08
07:07:58 | INFO | embed_mert_sbert | [69/263] NS_09
07:09:43 | INFO | embed_mert_sbert | [70/263] NS_10
07:12:31 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/audio_embeddings.npz
07:12:31 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/text_embeddings.npz
07:12:31 | INFO | embed_mert_sbert |   Checkpoint (70 done)
07:12:31 | INFO | embed_mert_sbert | [71/263] NS_11
07:14:16 | INFO | embed_mert_sbert | [72/263] NS_12
07:16:21 | INFO | embed_mert_sbert | [73/263] CG_01
07:18:04 | INFO | embed_mert_sbert | [74/263] CG_02
07:21:34 | INFO | embed_mert_sbert | [75/263] CG_03
07:23:23 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/audio_embeddings.npz
07:23:23 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/text_embeddings.npz
07:23:23 | INFO | embed_mert_sbert |   Checkpoint (75 done)
07:23:23 | INFO | embed_mert_sbert | [76/263] CG_04
07:25:28 | INFO | embed_mert_sbert | [77/263] CG_05
07:42:24 | INFO | embed_mert_sbert | [78/263] CG_06
08:02:01 | INFO | embed_mert_sbert | [79/263] CG_07
08:03:46 | INFO | embed_mert_sbert | [80/263] CG_08
08:05:22 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/audio_embeddings.npz
08:05:22 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/text_embeddings.npz
08:05:22 | INFO | embed_mert_sbert |   Checkpoint (80 done)
08:05:22 | INFO | embed_mert_sbert | [81/263] CG_09
08:07:05 | INFO | embed_mert_sbert | [82/263] CG_10
08:09:08 | INFO | embed_mert_sbert | [83/263] CG_11
08:11:49 | INFO | embed_mert_sbert | [84/263] CG_12
08:14:14 | INFO | embed_mert_sbert | [85/263] JI_01
08:15:55 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/audio_embeddings.npz
08:15:55 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/text_embeddings.npz
08:15:55 | INFO | embed_mert_sbert |   Checkpoint (85 done)
08:15:55 | INFO | embed_mert_sbert | [86/263] JI_02
08:17:26 | INFO | embed_mert_sbert | [87/263] JI_03
08:19:14 | INFO | embed_mert_sbert | [88/263] JI_04
08:20:53 | INFO | embed_mert_sbert | [89/263] JI_05
08:22:48 | INFO | embed_mert_sbert | [90/263] JI_06
08:24:53 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/audio_embeddings.npz
08:24:53 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/text_embeddings.npz
08:24:53 | INFO | embed_mert_sbert |   Checkpoint (90 done)
08:24:53 | INFO | embed_mert_sbert | [91/263] JI_07
08:26:43 | INFO | embed_mert_sbert | [92/263] JI_08
08:28:20 | INFO | embed_mert_sbert | [93/263] JI_09
08:30:17 | INFO | embed_mert_sbert | [94/263] JI_10
08:31:50 | INFO | embed_mert_sbert | [95/263] JI_11
08:34:37 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/audio_embeddings.npz
08:34:37 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/text_embeddings.npz
08:34:37 | INFO | embed_mert_sbert |   Checkpoint (95 done)
08:34:37 | INFO | embed_mert_sbert | [96/263] JI_12
08:36:36 | INFO | embed_mert_sbert | [97/263] SS_01
08:38:09 | INFO | embed_mert_sbert | [98/263] SS_02
08:56:47 | INFO | embed_mert_sbert | [99/263] SS_03
09:12:48 | INFO | embed_mert_sbert | [100/263] SS_04
09:14:32 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/audio_embeddings.npz
09:14:33 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/text_embeddings.npz
09:14:33 | INFO | embed_mert_sbert |   Checkpoint (100 done)
09:14:33 | INFO | embed_mert_sbert | [101/263] SS_05
09:16:22 | INFO | embed_mert_sbert | [102/263] SS_06
09:18:10 | INFO | embed_mert_sbert | [103/263] SS_07
09:19:46 | INFO | embed_mert_sbert | [104/263] SS_08
09:21:30 | INFO | embed_mert_sbert | [105/263] SS_09
09:22:53 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/audio_embeddings.npz
09:22:53 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/text_embeddings.npz
09:22:53 | INFO | embed_mert_sbert |   Checkpoint (105 done)
09:22:53 | INFO | embed_mert_sbert | [106/263] SS_10
09:24:39 | INFO | embed_mert_sbert | [107/263] SS_11
09:26:18 | INFO | embed_mert_sbert | [108/263] SS_12
09:27:41 | INFO | embed_mert_sbert | [109/263] KM_01
09:29:14 | INFO | embed_mert_sbert | [110/263] KM_02
09:31:08 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/audio_embeddings.npz
09:31:08 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/text_embeddings.npz
09:31:08 | INFO | embed_mert_sbert |   Checkpoint (110 done)
09:31:08 | INFO | embed_mert_sbert | [111/263] KM_03
09:33:07 | INFO | embed_mert_sbert | [112/263] KM_04
09:35:28 | INFO | embed_mert_sbert | [113/263] KM_05
09:37:01 | INFO | embed_mert_sbert | [114/263] KM_06
09:38:37 | INFO | embed_mert_sbert | [115/263] KM_07
09:41:02 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/audio_embeddings.npz
09:41:02 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/text_embeddings.npz
09:41:02 | INFO | embed_mert_sbert |   Checkpoint (115 done)
09:41:02 | INFO | embed_mert_sbert | [116/263] KM_08
09:42:31 | INFO | embed_mert_sbert | [117/263] KM_09
09:44:02 | INFO | embed_mert_sbert | [118/263] KM_10
09:46:11 | INFO | embed_mert_sbert | [119/263] KM_11
09:47:37 | INFO | embed_mert_sbert | [120/263] KM_12
09:49:09 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/audio_embeddings.npz
09:49:09 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/text_embeddings.npz
09:49:09 | INFO | embed_mert_sbert |   Checkpoint (120 done)
09:49:09 | INFO | embed_mert_sbert | [121/263] JP_01
09:51:08 | INFO | embed_mert_sbert | [122/263] JP_02
09:53:27 | INFO | embed_mert_sbert | [123/263] JP_03
09:55:07 | INFO | embed_mert_sbert | [124/263] JP_04
09:56:34 | INFO | embed_mert_sbert | [125/263] JP_05
09:58:28 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/audio_embeddings.npz
09:58:29 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/text_embeddings.npz
09:58:29 | INFO | embed_mert_sbert |   Checkpoint (125 done)
09:58:29 | INFO | embed_mert_sbert | [126/263] JP_06
10:00:09 | INFO | embed_mert_sbert | [127/263] JP_07
10:01:40 | INFO | embed_mert_sbert | [128/263] JP_08
10:03:15 | INFO | embed_mert_sbert | [129/263] JP_09
10:05:17 | INFO | embed_mert_sbert | [130/263] JP_10
10:07:37 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/audio_embeddings.npz
10:07:37 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/text_embeddings.npz
10:07:37 | INFO | embed_mert_sbert |   Checkpoint (130 done)
10:07:37 | INFO | embed_mert_sbert | [131/263] JP_11
10:09:08 | INFO | embed_mert_sbert | [132/263] JP_12
10:11:00 | INFO | embed_mert_sbert | [133/263] GW_01
10:12:22 | INFO | embed_mert_sbert | [134/263] GW_02
10:14:14 | INFO | embed_mert_sbert | [135/263] GW_03
10:16:09 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/audio_embeddings.npz
10:16:09 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/text_embeddings.npz
10:16:09 | INFO | embed_mert_sbert |   Checkpoint (135 done)
10:16:09 | INFO | embed_mert_sbert | [136/263] GW_04
10:17:34 | INFO | embed_mert_sbert | [137/263] GW_05
10:19:28 | INFO | embed_mert_sbert | [138/263] GW_06
10:21:24 | INFO | embed_mert_sbert | [139/263] GW_07
10:23:12 | INFO | embed_mert_sbert | [140/263] GW_08
10:25:05 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/audio_embeddings.npz
10:25:05 | INFO | utils | Saved embeddings → /Users/budge.13/Desktop/Music Analysis/results/embeddings/mert_sbert/text_embeddings.npz

MERT+SBERT — n=436  mean=-0.0274  sd=0.0302  min=-0.1190  max=0.0785

---
## Step 7 — Segment-Level Analysis *(optional)*
Parses lyrics into sections (`[Verse]`, `[Chorus]`, `[Bridge]`, etc.) using Genius section headers,  
splits the audio into chunks aligned to sections using WhisperX,  
and computes per-section MuLan LMC.  
**Outputs:** `results/segment_analysis/segment_details.json`, `segment_summary.csv`  

> This step is compute-intensive (~2–4 min per song). Set `enabled=False` in `config.py`  
> or skip this cell if you only need track-level results.

In [9]:
segment_analysis = load_script("segment_analysis", "07_segment_analysis.py")

seg_details, seg_summary = segment_analysis.run_segment_analysis(
    device        = device,
    force         = False,
    artist_filter = None,   # e.g. ["KL", "GD"] to limit scope
)

n_analysed = sum(1 for v in seg_details.values() if v)
print(f"\nSegment analysis complete: {n_analysed} songs with valid section data")
if seg_summary:
    import pandas as pd
    seg_df = pd.DataFrame(seg_summary)
    print(f"Mean sections per song : {seg_df['n_segments'].mean():.1f}")
    print(f"Mean segment LMC (all) : {seg_df['mean_lmc_all'].mean():.4f}")

13:11:34 | INFO | segment_analysis | Resuming — 173 songs already done.
13:11:34 | INFO | segment_analysis | Loading models for 263 songs...
13:11:34 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/OpenMuQ/MuQ-MuLan-large/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
13:11:34 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/OpenMuQ/MuQ-MuLan-large/2e01c796b71dca71b45251384c04cd7b237c9020/config.json "HTTP/1.1 200 OK"
13:11:34 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/OpenMuQ/MuQ-large-msd-iter/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
13:11:34 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/OpenMuQ/MuQ-large-msd-iter/0562a57814f6f8bbd9fdea0a25921a2fce1a841a/config.json "HTTP/1.1 200 OK"
/opt/anaconda3/lib/python3.13/site-packages/torch/nn/utils/weight_norm.py:144: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)
13:11:36 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/OpenMuQ/MuQ-large-msd-iter/resolve/main/model.safetensors "HTTP/1.1 302 Found"
13:11:40 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/xlm-roberta-base/resolve/main/config.json "HTTP/1.1 200 OK"
13:11:40 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/xlm-roberta-base/resolve/main/model.safetensors "HTTP/1.1 302 Found"

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

XLMRobertaModel LOAD REPORT from: xlm-roberta-base
Key                       | Status     |  |
--------------------------+------------+--+-
lm_head.layer_norm.weight | UNEXPECTED |  |
lm_head.dense.weight      | UNEXPECTED |  |
lm_head.bias              | UNEXPECTED |  |
lm_head.dense.bias        | UNEXPECTED |  |
lm_head.layer_norm.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
13:11:41 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/OpenMuQ/MuQ-MuLan-large/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"
13:11:41 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/OpenMuQ/MuQ-MuLan-large/resolve/main/pytorch_model.bin "HTTP/1.1 302 Found"
13:12:14 | INFO | segment_analysis | Loading WhisperX (whisper=base, align on cpu)...
/opt/anaconda3/lib/python3.13/site-packages/pyannote/audio/core/io.py:47: UserWarning:
torchcodec is not installed correctly so built-in audio decoding will fail. Solutions are:
* use audio preloaded in-memory as a {'waveform': (channel, time) torch.Tensor, 'sample_rate': int} dictionary;
* fix torchcodec installation. Error message was:

No module named 'torchcodec'
  warnings.warn(
13:12:18 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/Systran/faster-whisper-base/revision/main "HTTP/1.1 200 OK"

2026-04-20 13:12:18 - whisperx.asr - INFO - No language specified, language will be detected for each audio file (increases inference time)
2026-04-20 13:12:18 - whisperx.vads.pyannote - INFO - Performing voice activity detection using Pyannote...

INFO: Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.1. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../opt/anaconda3/lib/python3.13/site-packages/whisperx/assets/pytorch_model.bin`
13:12:19 | INFO | lightning.pytorch.utilities.migration.utils | Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.1. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../opt/anaconda3/lib/python3.13/site-packages/whisperx/assets/pytorch_model.bin`
13:12:19 | INFO | segment_analysis | [1/263] DR_01

2026-04-20 13:12:26 - whisperx.asr - INFO - Detected language: en (0.98) in first 30s of audio
2026-04-20 13:12:32 - whisperx.alignment - WARNING - Failed to align segment (" It was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was"): backtrack failed, resorting to original

13:12:36 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/xlm-roberta-base/resolve/main/config.json "HTTP/1.1 200 OK"
13:12:36 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/xlm-roberta-base/resolve/main/tokenizer_config.json "HTTP/1.1 200 OK"
13:12:36 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/xlm-roberta-base/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 307 Temporary Redirect"
13:12:37 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/FacebookAI/xlm-roberta-base/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
13:12:37 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/xlm-roberta-base/tree/main?recursive=true&expand=false "HTTP/1.1 307 Temporary Redirect"
13:12:37 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/FacebookAI/xlm-roberta-base/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
13:12:40 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/xlm-roberta-base "HTTP/1.1 307 Temporary Redirect"
13:12:40 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/FacebookAI/xlm-roberta-base "HTTP/1.1 200 OK"
13:12:50 | INFO | segment_analysis |   ✓ 6 sections | mean LMC=0.3553 | method={'whisperx'}
13:12:50 | INFO | segment_analysis | [2/263] DR_02

2026-04-20 13:12:59 - whisperx.asr - INFO - Detected language: en (0.82) in first 30s of audio

13:13:20 | INFO | segment_analysis |   ✓ 7 sections | mean LMC=0.2123 | method={'whisperx'}
13:13:20 | INFO | segment_analysis | [3/263] DR_03
python(40445) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:13:28 - whisperx.asr - INFO - Detected language: en (0.87) in first 30s of audio

13:13:40 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.2896 | method={'whisperx'}
13:13:40 | INFO | segment_analysis | [4/263] DR_04
python(40448) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:13:52 - whisperx.asr - INFO - Detected language: en (0.48) in first 30s of audio

13:14:05 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.1953 | method={'whisperx'}
13:14:05 | INFO | segment_analysis | [5/263] DR_05
python(40451) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:14:12 - whisperx.asr - INFO - Detected language: en (0.93) in first 30s of audio

13:14:24 | INFO | segment_analysis |   ✓ 1 sections | mean LMC=0.5128 | method={'whisperx'}
13:14:24 | INFO | segment_analysis |   Checkpoint saved.
13:14:24 | INFO | segment_analysis | [6/263] DR_06
python(40459) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:14:33 - whisperx.asr - INFO - Detected language: en (0.79) in first 30s of audio

13:14:53 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.2490 | method={'whisperx'}
13:14:53 | INFO | segment_analysis | [7/263] DR_07
python(40464) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:15:05 - whisperx.asr - INFO - Detected language: en (0.80) in first 30s of audio

13:15:26 | INFO | segment_analysis |   ✓ 8 sections | mean LMC=0.2521 | method={'whisperx'}
13:15:26 | INFO | segment_analysis | [8/263] DR_08
python(40475) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:15:34 - whisperx.asr - INFO - Detected language: en (0.87) in first 30s of audio

13:15:44 | INFO | segment_analysis |   ✓ 2 sections | mean LMC=0.4099 | method={'whisperx'}
13:15:44 | INFO | segment_analysis | [9/263] DR_09
python(40478) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:15:58 - whisperx.asr - INFO - Detected language: en (0.70) in first 30s of audio

13:16:24 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.3509 | method={'whisperx'}
13:16:24 | INFO | segment_analysis | [10/263] DR_10
python(40486) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:16:35 - whisperx.asr - INFO - Detected language: en (0.91) in first 30s of audio

13:16:58 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.4287 | method={'whisperx'}
13:16:58 | INFO | segment_analysis |   Checkpoint saved.
13:16:58 | INFO | segment_analysis | [11/263] DR_11
python(40493) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:17:10 - whisperx.asr - INFO - Detected language: en (0.59) in first 30s of audio

13:17:35 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.2566 | method={'whisperx'}
13:17:35 | INFO | segment_analysis | [12/263] DR_12
python(40517) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:17:47 - whisperx.asr - INFO - Detected language: en (0.93) in first 30s of audio

13:18:11 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.2536 | method={'whisperx'}
13:18:11 | INFO | segment_analysis | [13/263] EM_01
python(40529) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:18:23 - whisperx.asr - INFO - Detected language: en (0.42) in first 30s of audio

13:18:46 | INFO | segment_analysis |   ✓ 6 sections | mean LMC=0.1967 | method={'whisperx'}
13:18:46 | INFO | segment_analysis | [14/263] EM_02
python(40533) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:19:02 - whisperx.asr - INFO - Detected language: ko (0.35) in first 30s of audio

13:19:12 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/kresnik/wav2vec2-large-xlsr-korean/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
13:19:12 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
13:19:12 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/chat_template.json "HTTP/1.1 404 Not Found"
13:19:12 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/chat_template.jinja "HTTP/1.1 404 Not Found"
13:19:12 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/audio_tokenizer_config.json "HTTP/1.1 404 Not Found"
13:19:12 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
13:19:12 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/preprocessor_config.json "HTTP/1.1 307 Temporary Redirect"
13:19:12 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/kresnik/wav2vec2-large-xlsr-korean/629c9a3501c10ba128bf3fa1eebb12af3be03f61/preprocessor_config.json "HTTP/1.1 200 OK"
13:19:12 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/kresnik/wav2vec2-large-xlsr-korean/629c9a3501c10ba128bf3fa1eebb12af3be03f61/preprocessor_config.json "HTTP/1.1 200 OK"

preprocessor_config.json:   0%|          | 0.00/214 [00:00<?, ?B/s]

13:19:13 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
13:19:13 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/preprocessor_config.json "HTTP/1.1 307 Temporary Redirect"
13:19:13 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/kresnik/wav2vec2-large-xlsr-korean/629c9a3501c10ba128bf3fa1eebb12af3be03f61/preprocessor_config.json "HTTP/1.1 200 OK"
13:19:13 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
13:19:13 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/kresnik/wav2vec2-large-xlsr-korean/629c9a3501c10ba128bf3fa1eebb12af3be03f61/config.json "HTTP/1.1 200 OK"
13:19:13 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/kresnik/wav2vec2-large-xlsr-korean/629c9a3501c10ba128bf3fa1eebb12af3be03f61/config.json "HTTP/1.1 200 OK"

config.json: 0.00B [00:00, ?B/s]

13:19:13 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
13:19:13 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/kresnik/wav2vec2-large-xlsr-korean/629c9a3501c10ba128bf3fa1eebb12af3be03f61/tokenizer_config.json "HTTP/1.1 200 OK"
13:19:13 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/kresnik/wav2vec2-large-xlsr-korean/629c9a3501c10ba128bf3fa1eebb12af3be03f61/tokenizer_config.json "HTTP/1.1 200 OK"

tokenizer_config.json:   0%|          | 0.00/161 [00:00<?, ?B/s]

13:19:13 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/kresnik/wav2vec2-large-xlsr-korean/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
13:19:13 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/kresnik/wav2vec2-large-xlsr-korean/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
13:19:13 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/vocab.json "HTTP/1.1 307 Temporary Redirect"
13:19:13 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/kresnik/wav2vec2-large-xlsr-korean/629c9a3501c10ba128bf3fa1eebb12af3be03f61/vocab.json "HTTP/1.1 200 OK"
13:19:13 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/kresnik/wav2vec2-large-xlsr-korean/629c9a3501c10ba128bf3fa1eebb12af3be03f61/vocab.json "HTTP/1.1 200 OK"

vocab.json: 0.00B [00:00, ?B/s]

13:19:13 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/added_tokens.json "HTTP/1.1 404 Not Found"
13:19:13 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/special_tokens_map.json "HTTP/1.1 404 Not Found"
13:19:13 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/tokenizer.json "HTTP/1.1 404 Not Found"
13:19:14 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
13:19:14 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/kresnik/wav2vec2-large-xlsr-korean/629c9a3501c10ba128bf3fa1eebb12af3be03f61/config.json "HTTP/1.1 200 OK"
13:19:14 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/model.safetensors "HTTP/1.1 302 Found"
13:19:14 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/kresnik/wav2vec2-large-xlsr-korean/xet-read-token/629c9a3501c10ba128bf3fa1eebb12af3be03f61 "HTTP/1.1 200 OK"

model.safetensors:   0%|          | 0.00/1.27G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/424 [00:00<?, ?it/s]

13:20:40 | INFO | segment_analysis |   ✓ 7 sections | mean LMC=0.4174 | method={'whisperx'}
13:20:40 | INFO | segment_analysis | [15/263] EM_03
python(40579) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:20:51 - whisperx.asr - INFO - Detected language: en (0.94) in first 30s of audio

13:21:10 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.3352 | method={'whisperx'}
13:21:10 | INFO | segment_analysis |   Checkpoint saved.
13:21:10 | INFO | segment_analysis | [16/263] EM_04
python(40592) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:21:20 - whisperx.asr - INFO - Detected language: en (0.91) in first 30s of audio

13:21:45 | INFO | segment_analysis |   ✓ 6 sections | mean LMC=0.3021 | method={'whisperx'}
13:21:45 | INFO | segment_analysis | [17/263] EM_05
python(40602) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:21:55 - whisperx.asr - INFO - Detected language: en (0.94) in first 30s of audio

13:22:17 | INFO | segment_analysis |   ✓ 6 sections | mean LMC=0.3116 | method={'whisperx'}
13:22:17 | INFO | segment_analysis | [18/263] EM_06
python(40619) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:22:28 - whisperx.asr - INFO - Detected language: en (0.94) in first 30s of audio

13:22:58 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.3409 | method={'whisperx'}
13:22:58 | INFO | segment_analysis | [19/263] EM_07
python(41745) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:23:12 - whisperx.asr - INFO - Detected language: en (0.88) in first 30s of audio

13:23:52 | INFO | segment_analysis |   ✓ 7 sections | mean LMC=0.4366 | method={'whisperx'}
13:23:52 | INFO | segment_analysis | [20/263] EM_08
python(41933) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:24:01 - whisperx.asr - INFO - Detected language: en (0.91) in first 30s of audio

13:24:21 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.3550 | method={'whisperx'}
13:24:21 | INFO | segment_analysis |   Checkpoint saved.
13:24:21 | INFO | segment_analysis | [21/263] EM_09
python(41938) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:24:33 - whisperx.asr - INFO - Detected language: en (0.94) in first 30s of audio

13:25:03 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.2995 | method={'whisperx'}
13:25:03 | INFO | segment_analysis | [22/263] EM_10
python(41954) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:25:14 - whisperx.asr - INFO - Detected language: en (0.92) in first 30s of audio

13:25:38 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.3599 | method={'whisperx'}
13:25:38 | INFO | segment_analysis | [23/263] EM_11
python(41966) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:25:47 - whisperx.asr - INFO - Detected language: en (0.97) in first 30s of audio

13:26:14 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.3171 | method={'whisperx'}
13:26:14 | INFO | segment_analysis | [24/263] EM_12
python(41979) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:26:29 - whisperx.asr - INFO - Detected language: en (0.40) in first 30s of audio

13:27:04 | INFO | segment_analysis |   ✓ 8 sections | mean LMC=0.3960 | method={'whisperx'}
13:27:04 | INFO | segment_analysis | [25/263] TC2_01
python(41986) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:27:11 - whisperx.asr - INFO - Detected language: en (0.64) in first 30s of audio

13:27:28 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.3102 | method={'whisperx'}
13:27:28 | INFO | segment_analysis |   Checkpoint saved.
13:27:28 | INFO | segment_analysis | [26/263] TC2_02
python(41990) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:27:35 - whisperx.asr - INFO - Detected language: en (0.78) in first 30s of audio

13:27:51 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.2992 | method={'whisperx'}
13:27:51 | INFO | segment_analysis | [27/263] TC2_03
13:27:51 | INFO | segment_analysis |   [TC2_03] Only 1 section(s) — skipping
13:27:51 | INFO | segment_analysis | [28/263] TC2_04
python(42000) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:28:01 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

13:28:15 | INFO | segment_analysis |   ✓ 2 sections | mean LMC=0.3503 | method={'whisperx'}
13:28:15 | INFO | segment_analysis | [29/263] TC2_05
python(42007) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:28:22 - whisperx.asr - INFO - Detected language: en (0.99) in first 30s of audio

13:28:43 | INFO | segment_analysis |   ✓ 6 sections | mean LMC=0.3110 | method={'whisperx'}
13:28:43 | INFO | segment_analysis | [30/263] TC2_06
python(42012) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:28:49 - whisperx.asr - INFO - Detected language: en (0.85) in first 30s of audio

13:29:02 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.4141 | method={'whisperx'}
13:29:02 | INFO | segment_analysis |   Checkpoint saved.
13:29:02 | INFO | segment_analysis | [31/263] TC2_07
python(42013) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:29:08 - whisperx.asr - INFO - Detected language: en (0.97) in first 30s of audio

13:29:24 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.3917 | method={'whisperx'}
13:29:24 | INFO | segment_analysis | [32/263] TC2_08
python(42029) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:29:34 - whisperx.asr - INFO - Detected language: en (0.83) in first 30s of audio

13:30:00 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.1892 | method={'whisperx'}
13:30:00 | INFO | segment_analysis | [33/263] TC2_09
python(42044) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:30:08 - whisperx.asr - INFO - Detected language: en (0.48) in first 30s of audio

13:30:23 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.3127 | method={'whisperx'}
13:30:23 | INFO | segment_analysis | [34/263] TC2_10
python(42045) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:30:37 - whisperx.asr - INFO - Detected language: en (0.85) in first 30s of audio

13:31:04 | INFO | segment_analysis |   ✓ 7 sections | mean LMC=0.2827 | method={'whisperx'}
13:31:04 | INFO | segment_analysis | [35/263] TC2_11
python(42048) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:31:12 - whisperx.asr - INFO - Detected language: en (0.84) in first 30s of audio

13:31:28 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.3154 | method={'whisperx'}
13:31:28 | INFO | segment_analysis |   Checkpoint saved.
13:31:28 | INFO | segment_analysis | [36/263] TC2_12
python(42052) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:31:38 - whisperx.asr - INFO - Detected language: en (0.98) in first 30s of audio

13:32:01 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.2550 | method={'whisperx'}
13:32:01 | INFO | segment_analysis | [37/263] MM_01
python(42061) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:32:16 - whisperx.asr - INFO - Detected language: en (0.60) in first 30s of audio

13:32:37 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.2684 | method={'whisperx'}
13:32:37 | INFO | segment_analysis | [38/263] MM_02
python(42062) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:32:47 - whisperx.asr - INFO - Detected language: en (0.97) in first 30s of audio

13:33:10 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.3424 | method={'whisperx'}
13:33:10 | INFO | segment_analysis | [39/263] MM_03
python(42069) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:33:17 - whisperx.asr - INFO - Detected language: en (0.33) in first 30s of audio

13:33:28 | INFO | segment_analysis |   ✓ 2 sections | mean LMC=0.3440 | method={'whisperx'}
13:33:28 | INFO | segment_analysis | [40/263] MM_04
python(42070) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:33:42 - whisperx.asr - INFO - Detected language: en (0.60) in first 30s of audio

13:34:06 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.3548 | method={'whisperx'}
13:34:06 | INFO | segment_analysis |   Checkpoint saved.
13:34:06 | INFO | segment_analysis | [41/263] MM_05
python(42079) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:34:16 - whisperx.asr - INFO - Detected language: en (0.93) in first 30s of audio

13:34:31 | INFO | segment_analysis |   ✓ 2 sections | mean LMC=0.3742 | method={'whisperx'}
13:34:31 | INFO | segment_analysis | [42/263] MM_06
python(42115) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:34:39 - whisperx.asr - INFO - Detected language: en (0.98) in first 30s of audio

13:34:57 | INFO | segment_analysis |   ✓ 1 sections | mean LMC=0.4093 | method={'whisperx'}
13:34:57 | INFO | segment_analysis | [43/263] MM_07
python(42121) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:35:05 - whisperx.asr - INFO - Detected language: en (0.95) in first 30s of audio

13:35:17 | INFO | segment_analysis |   ✓ 1 sections | mean LMC=0.2584 | method={'whisperx'}
13:35:17 | INFO | segment_analysis | [44/263] MM_08
python(42123) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:35:27 - whisperx.asr - INFO - Detected language: en (0.80) in first 30s of audio

13:35:44 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.3234 | method={'whisperx'}
13:35:44 | INFO | segment_analysis | [45/263] MM_09
python(42132) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:35:52 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

13:36:07 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.2924 | method={'whisperx'}
13:36:07 | INFO | segment_analysis |   Checkpoint saved.
13:36:07 | INFO | segment_analysis | [46/263] MM_10
python(42133) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:36:21 - whisperx.asr - INFO - Detected language: en (0.98) in first 30s of audio

13:36:45 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.3345 | method={'whisperx'}
13:36:45 | INFO | segment_analysis | [47/263] MM_11
python(42144) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:36:57 - whisperx.asr - INFO - Detected language: en (0.67) in first 30s of audio

13:37:17 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.3402 | method={'whisperx'}
13:37:17 | INFO | segment_analysis | [48/263] MM_12
python(42148) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:37:25 - whisperx.asr - INFO - Detected language: en (0.79) in first 30s of audio

13:37:42 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.2129 | method={'whisperx'}
13:37:42 | INFO | segment_analysis | [49/263] CH_01
python(42161) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:37:51 - whisperx.asr - INFO - Detected language: en (0.93) in first 30s of audio

13:38:11 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.2527 | method={'whisperx'}
13:38:11 | INFO | segment_analysis | [50/263] CH_02
python(42166) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:38:23 - whisperx.asr - INFO - Detected language: en (0.95) in first 30s of audio

13:38:54 | INFO | segment_analysis |   ✓ 6 sections | mean LMC=0.4696 | method={'whisperx'}
13:38:54 | INFO | segment_analysis |   Checkpoint saved.
13:38:54 | INFO | segment_analysis | [51/263] CH_03
python(42171) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:39:04 - whisperx.asr - INFO - Detected language: en (0.68) in first 30s of audio

13:39:22 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.2483 | method={'whisperx'}
13:39:22 | INFO | segment_analysis | [52/263] CH_04
python(42172) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:39:30 - whisperx.asr - INFO - Detected language: en (0.80) in first 30s of audio

13:39:50 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.3137 | method={'whisperx'}
13:39:50 | INFO | segment_analysis | [53/263] CH_05
python(42194) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:40:01 - whisperx.asr - INFO - Detected language: en (0.65) in first 30s of audio

13:40:23 | INFO | segment_analysis |   ✓ 6 sections | mean LMC=0.2591 | method={'whisperx'}
13:40:23 | INFO | segment_analysis | [54/263] CH_06
python(42196) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:40:32 - whisperx.asr - INFO - Detected language: en (0.96) in first 30s of audio

13:40:49 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.3717 | method={'whisperx'}
13:40:49 | INFO | segment_analysis | [55/263] CH_07
python(42286) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:40:56 - whisperx.asr - INFO - Detected language: en (0.92) in first 30s of audio

13:41:11 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.4384 | method={'whisperx'}
13:41:11 | INFO | segment_analysis |   Checkpoint saved.
13:41:11 | INFO | segment_analysis | [56/263] CH_08
python(42288) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:41:19 - whisperx.asr - INFO - Detected language: en (0.78) in first 30s of audio

13:41:38 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.1905 | method={'whisperx'}
13:41:38 | INFO | segment_analysis | [57/263] CH_09
python(42292) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:41:50 - whisperx.asr - INFO - Detected language: en (0.74) in first 30s of audio

13:42:17 | INFO | segment_analysis |   ✓ 6 sections | mean LMC=0.3655 | method={'whisperx'}
13:42:17 | INFO | segment_analysis | [58/263] CH_10
python(42332) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:42:25 - whisperx.asr - INFO - Detected language: en (0.80) in first 30s of audio

13:42:42 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.3230 | method={'whisperx'}
13:42:42 | INFO | segment_analysis | [59/263] CH_11
python(42336) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:42:51 - whisperx.asr - INFO - Detected language: en (0.98) in first 30s of audio

13:43:11 | INFO | segment_analysis |   ✓ 2 sections | mean LMC=0.4279 | method={'whisperx'}
13:43:11 | INFO | segment_analysis | [60/263] CH_12
python(42420) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:43:20 - whisperx.asr - INFO - Detected language: en (0.84) in first 30s of audio

13:43:42 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.3759 | method={'whisperx'}
13:43:42 | INFO | segment_analysis |   Checkpoint saved.
13:43:42 | INFO | segment_analysis | [61/263] NS_01
python(42437) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:43:55 - whisperx.asr - INFO - Detected language: en (0.95) in first 30s of audio

13:44:23 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.3366 | method={'whisperx'}
13:44:23 | INFO | segment_analysis | [62/263] NS_02
python(42458) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:44:35 - whisperx.asr - INFO - Detected language: en (0.87) in first 30s of audio

13:45:03 | INFO | segment_analysis |   ✓ 6 sections | mean LMC=0.1971 | method={'whisperx'}
13:45:03 | INFO | segment_analysis | [63/263] NS_03
python(42468) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:45:17 - whisperx.asr - INFO - Detected language: en (0.92) in first 30s of audio

13:45:47 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.2617 | method={'whisperx'}
13:45:47 | INFO | segment_analysis | [64/263] NS_04
13:45:47 | INFO | segment_analysis |   [NS_04] Only 1 section(s) — skipping
13:45:47 | INFO | segment_analysis | [65/263] NS_05
python(42523) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:46:00 - whisperx.asr - INFO - Detected language: en (0.97) in first 30s of audio

13:46:29 | INFO | segment_analysis |   ✓ 6 sections | mean LMC=0.2637 | method={'whisperx'}
13:46:29 | INFO | segment_analysis |   Checkpoint saved.
13:46:29 | INFO | segment_analysis | [66/263] NS_06
python(42573) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:46:40 - whisperx.asr - INFO - Detected language: en (0.88) in first 30s of audio

13:47:08 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.2386 | method={'whisperx'}
13:47:08 | INFO | segment_analysis | [67/263] NS_07
python(42618) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:47:16 - whisperx.asr - INFO - Detected language: en (0.85) in first 30s of audio

13:47:37 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.4541 | method={'whisperx'}
13:47:37 | INFO | segment_analysis | [68/263] NS_08
python(42627) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:47:45 - whisperx.asr - INFO - Detected language: en (0.91) in first 30s of audio

13:48:07 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.3032 | method={'whisperx'}
13:48:07 | INFO | segment_analysis | [69/263] NS_09
13:48:07 | INFO | segment_analysis |   [NS_09] Only 1 section(s) — skipping
13:48:07 | INFO | segment_analysis | [70/263] NS_10
python(42639) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:48:17 - whisperx.asr - INFO - Detected language: en (0.88) in first 30s of audio

13:48:43 | INFO | segment_analysis |   ✓ 6 sections | mean LMC=0.1798 | method={'whisperx'}
13:48:43 | INFO | segment_analysis |   Checkpoint saved.
13:48:43 | INFO | segment_analysis | [71/263] NS_11
python(42654) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:48:53 - whisperx.asr - INFO - Detected language: en (0.91) in first 30s of audio

13:49:12 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.2768 | method={'whisperx'}
13:49:12 | INFO | segment_analysis | [72/263] NS_12
python(42712) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:49:26 - whisperx.asr - INFO - Detected language: en (0.86) in first 30s of audio

13:49:55 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.3558 | method={'whisperx'}
13:49:55 | INFO | segment_analysis | [73/263] CG_01
python(42737) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:50:09 - whisperx.asr - INFO - Detected language: km (0.28) in first 30s of audio
2026-04-20 13:50:10 - whisperx.alignment - ERROR - No default alignment model for language: km. Please find a wav2vec2.0 model finetuned on this language at https://huggingface.co/models, then pass the model name via --align_model [MODEL_NAME]

13:50:10 | WARNING | segment_analysis |   WhisperX alignment failed: No default align-model for language: km
13:50:10 | INFO | segment_analysis |   [CG_01] WhisperX returned no words — using equal splits
13:50:21 | INFO | segment_analysis |   ✓ 7 sections | mean LMC=0.3488 | method={'fallback_equal'}
13:50:21 | INFO | segment_analysis | [74/263] CG_02
python(42744) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:50:29 - whisperx.asr - INFO - Detected language: en (0.75) in first 30s of audio

13:50:52 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.3985 | method={'whisperx'}
13:50:52 | INFO | segment_analysis | [75/263] CG_03
python(42807) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:51:02 - whisperx.asr - INFO - Detected language: en (0.97) in first 30s of audio

13:51:26 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.3659 | method={'whisperx'}
13:51:26 | INFO | segment_analysis |   Checkpoint saved.
13:51:26 | INFO | segment_analysis | [76/263] CG_04
python(42835) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:51:36 - whisperx.asr - INFO - Detected language: en (0.71) in first 30s of audio

13:51:54 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.2999 | method={'whisperx'}
13:51:54 | INFO | segment_analysis | [77/263] CG_05
python(42870) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:52:01 - whisperx.asr - INFO - Detected language: en (0.91) in first 30s of audio

13:52:17 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.3673 | method={'whisperx'}
13:52:17 | INFO | segment_analysis | [78/263] CG_06
13:52:17 | INFO | segment_analysis |   [CG_06] Only 1 section(s) — skipping
13:52:17 | INFO | segment_analysis | [79/263] CG_07
python(42877) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:52:32 - whisperx.asr - INFO - Detected language: en (0.52) in first 30s of audio

13:52:36 | INFO | segment_analysis |   [CG_07] WhisperX returned no words — using equal splits
13:52:51 | INFO | segment_analysis |   ✓ 9 sections | mean LMC=0.3359 | method={'fallback_equal'}
13:52:51 | INFO | segment_analysis | [80/263] CG_08
python(42885) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:53:02 - whisperx.asr - INFO - Detected language: en (0.75) in first 30s of audio

13:53:20 | INFO | segment_analysis |   ✓ 2 sections | mean LMC=0.1555 | method={'whisperx'}
13:53:20 | INFO | segment_analysis |   Checkpoint saved.
13:53:20 | INFO | segment_analysis | [81/263] CG_09
python(42916) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:53:30 - whisperx.asr - INFO - Detected language: en (0.87) in first 30s of audio

13:53:49 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.2085 | method={'whisperx'}
13:53:49 | INFO | segment_analysis | [82/263] CG_10
python(42925) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:54:01 - whisperx.asr - INFO - Detected language: en (0.93) in first 30s of audio

13:54:22 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.3262 | method={'whisperx'}
13:54:22 | INFO | segment_analysis | [83/263] CG_11
python(42961) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:54:30 - whisperx.asr - INFO - Detected language: en (0.79) in first 30s of audio

13:54:48 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.2632 | method={'whisperx'}
13:54:48 | INFO | segment_analysis | [84/263] CG_12
python(42970) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:54:56 - whisperx.asr - INFO - Detected language: en (0.49) in first 30s of audio

13:55:09 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.4047 | method={'whisperx'}
13:55:09 | INFO | segment_analysis | [85/263] JI_01
python(42975) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:55:20 - whisperx.asr - INFO - Detected language: en (0.82) in first 30s of audio

13:55:41 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.3065 | method={'whisperx'}
13:55:41 | INFO | segment_analysis |   Checkpoint saved.
13:55:41 | INFO | segment_analysis | [86/263] JI_02
python(42980) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:55:50 - whisperx.asr - INFO - Detected language: en (0.92) in first 30s of audio

13:56:06 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.4145 | method={'whisperx'}
13:56:06 | INFO | segment_analysis | [87/263] JI_03
python(43015) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:56:18 - whisperx.asr - INFO - Detected language: en (0.88) in first 30s of audio

13:56:41 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.3518 | method={'whisperx'}
13:56:41 | INFO | segment_analysis | [88/263] JI_04
python(43024) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:56:50 - whisperx.asr - INFO - Detected language: en (0.93) in first 30s of audio

13:57:06 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.3911 | method={'whisperx'}
13:57:06 | INFO | segment_analysis | [89/263] JI_05
python(43035) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:57:18 - whisperx.asr - INFO - Detected language: en (0.94) in first 30s of audio

13:57:36 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.4082 | method={'whisperx'}
13:57:36 | INFO | segment_analysis | [90/263] JI_06
13:57:36 | INFO | segment_analysis |   [JI_06] Only 1 section(s) — skipping
13:57:36 | INFO | segment_analysis |   Checkpoint saved.
13:57:36 | INFO | segment_analysis | [91/263] JI_07
13:57:36 | INFO | segment_analysis |   [JI_07] Only 1 section(s) — skipping
13:57:36 | INFO | segment_analysis | [92/263] JI_08
13:57:36 | INFO | segment_analysis |   [JI_08] Only 1 section(s) — skipping
13:57:36 | INFO | segment_analysis | [93/263] JI_09
13:57:36 | INFO | segment_analysis |   [JI_09] Only 1 section(s) — skipping
13:57:36 | INFO | segment_analysis | [94/263] JI_10
13:57:36 | INFO | segment_analysis |   [JI_10] Only 1 section(s) — skipping
13:57:36 | INFO | segment_analysis | [95/263] JI_11
13:57:36 | INFO | segment_analysis |   [JI_11] Only 1 section(s) — skipping
13:57:36 | INFO | segment_analysis |   Checkpoint saved.
13:57:36 | INFO | segment_analysis | [96/263] JI_12
python(43155) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:57:51 - whisperx.asr - INFO - Detected language: en (0.91) in first 30s of audio

13:58:07 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.4436 | method={'whisperx'}
13:58:07 | INFO | segment_analysis | [97/263] SS_01
13:58:07 | INFO | segment_analysis |   [SS_01] Only 1 section(s) — skipping
13:58:07 | INFO | segment_analysis | [98/263] SS_02
python(43206) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:58:14 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

13:58:22 | INFO | segment_analysis | [99/263] SS_03
python(43219) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:58:32 - whisperx.asr - INFO - Detected language: en (0.82) in first 30s of audio
2026-04-20 13:58:43 - whisperx.alignment - WARNING - Failed to align segment (" It's a long, long, long time, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long,"): backtrack failed, resorting to original

13:58:54 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.5173 | method={'whisperx'}
13:58:54 | INFO | segment_analysis | [100/263] SS_04
python(43245) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:59:09 - whisperx.asr - INFO - Detected language: es (0.53) in first 30s of audio

13:59:23 | INFO | segment_analysis |   ✓ 2 sections | mean LMC=0.3390 | method={'whisperx'}
13:59:23 | INFO | segment_analysis |   Checkpoint saved.
13:59:23 | INFO | segment_analysis | [101/263] SS_05
python(43286) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 13:59:33 - whisperx.asr - INFO - Detected language: en (0.63) in first 30s of audio

13:59:50 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.4794 | method={'whisperx'}
13:59:50 | INFO | segment_analysis | [102/263] SS_06
python(43313) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:00:02 - whisperx.asr - INFO - Detected language: en (0.36) in first 30s of audio

14:00:11 | INFO | segment_analysis |   ✓ 1 sections | mean LMC=0.4970 | method={'whisperx'}
14:00:11 | INFO | segment_analysis | [103/263] SS_07
python(43331) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:00:21 - whisperx.asr - INFO - Detected language: en (0.78) in first 30s of audio

14:00:37 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.3013 | method={'whisperx'}
14:00:37 | INFO | segment_analysis | [104/263] SS_08
python(43341) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:00:48 - whisperx.asr - INFO - Detected language: en (0.89) in first 30s of audio

14:01:09 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.4108 | method={'whisperx'}
14:01:09 | INFO | segment_analysis | [105/263] SS_09
python(43360) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:01:23 - whisperx.asr - INFO - Detected language: en (0.77) in first 30s of audio

14:01:36 | INFO | segment_analysis |   ✓ 2 sections | mean LMC=0.2926 | method={'whisperx'}
14:01:36 | INFO | segment_analysis |   Checkpoint saved.
14:01:36 | INFO | segment_analysis | [106/263] SS_10
python(43379) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:01:46 - whisperx.asr - INFO - Detected language: en (0.35) in first 30s of audio

14:02:07 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.4104 | method={'whisperx'}
14:02:07 | INFO | segment_analysis | [107/263] SS_11
python(43390) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:02:22 - whisperx.asr - INFO - Detected language: en (0.95) in first 30s of audio

14:02:47 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.3730 | method={'whisperx'}
14:02:47 | INFO | segment_analysis | [108/263] SS_12
python(43423) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:02:55 - whisperx.asr - INFO - Detected language: en (0.83) in first 30s of audio

14:03:10 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.4192 | method={'whisperx'}
14:03:10 | INFO | segment_analysis | [109/263] KM_01
python(43431) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:03:18 - whisperx.asr - INFO - Detected language: en (0.93) in first 30s of audio

14:03:24 | INFO | segment_analysis |   ✓ 1 sections | mean LMC=0.3974 | method={'whisperx'}
14:03:24 | INFO | segment_analysis | [110/263] KM_02
python(43434) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:03:32 - whisperx.asr - INFO - Detected language: en (0.93) in first 30s of audio

14:03:46 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.2862 | method={'whisperx'}
14:03:46 | INFO | segment_analysis |   Checkpoint saved.
14:03:46 | INFO | segment_analysis | [111/263] KM_03
python(43444) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:03:56 - whisperx.asr - INFO - Detected language: en (0.91) in first 30s of audio

14:04:07 | INFO | segment_analysis |   ✓ 2 sections | mean LMC=0.3353 | method={'whisperx'}
14:04:07 | INFO | segment_analysis | [112/263] KM_04
python(43447) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:04:16 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

14:04:32 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.2036 | method={'whisperx'}
14:04:32 | INFO | segment_analysis | [113/263] KM_05
python(43463) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:04:42 - whisperx.asr - INFO - Detected language: en (0.91) in first 30s of audio

14:05:00 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.1960 | method={'whisperx'}
14:05:00 | INFO | segment_analysis | [114/263] KM_06
python(43497) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:05:09 - whisperx.asr - INFO - Detected language: en (0.94) in first 30s of audio

14:05:25 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.2295 | method={'whisperx'}
14:05:25 | INFO | segment_analysis | [115/263] KM_07
python(43510) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:05:34 - whisperx.asr - INFO - Detected language: en (0.89) in first 30s of audio

14:05:44 | INFO | segment_analysis |   ✓ 2 sections | mean LMC=0.2534 | method={'whisperx'}
14:05:44 | INFO | segment_analysis |   Checkpoint saved.
14:05:44 | INFO | segment_analysis | [116/263] KM_08
python(43514) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:05:53 - whisperx.asr - INFO - Detected language: en (0.93) in first 30s of audio

14:06:09 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.2888 | method={'whisperx'}
14:06:09 | INFO | segment_analysis | [117/263] KM_09
python(43525) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:06:18 - whisperx.asr - INFO - Detected language: en (0.92) in first 30s of audio

14:06:37 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.3407 | method={'whisperx'}
14:06:37 | INFO | segment_analysis | [118/263] KM_10
python(43536) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:06:43 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

14:06:56 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.3073 | method={'whisperx'}
14:06:56 | INFO | segment_analysis | [119/263] KM_11
python(43543) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:07:05 - whisperx.asr - INFO - Detected language: en (0.92) in first 30s of audio

14:07:15 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.2727 | method={'whisperx'}
14:07:15 | INFO | segment_analysis | [120/263] KM_12
python(43563) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:07:23 - whisperx.asr - INFO - Detected language: en (0.93) in first 30s of audio

14:07:32 | INFO | segment_analysis |   ✓ 2 sections | mean LMC=0.4016 | method={'whisperx'}
14:07:32 | INFO | segment_analysis |   Checkpoint saved.
14:07:32 | INFO | segment_analysis | [121/263] JP_01
python(43571) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:07:42 - whisperx.asr - INFO - Detected language: en (0.96) in first 30s of audio

14:08:02 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.4278 | method={'whisperx'}
14:08:02 | INFO | segment_analysis | [122/263] JP_02
python(43635) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:08:11 - whisperx.asr - INFO - Detected language: en (0.94) in first 30s of audio

14:08:29 | INFO | segment_analysis |   ✓ 2 sections | mean LMC=0.5306 | method={'whisperx'}
14:08:29 | INFO | segment_analysis | [123/263] JP_03
python(43651) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:08:42 - whisperx.asr - INFO - Detected language: en (0.63) in first 30s of audio

14:09:05 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.3545 | method={'whisperx'}
14:09:05 | INFO | segment_analysis | [124/263] JP_04
python(43694) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:09:14 - whisperx.asr - INFO - Detected language: en (0.98) in first 30s of audio

14:09:29 | INFO | segment_analysis |   ✓ 6 sections | mean LMC=0.5008 | method={'whisperx'}
14:09:29 | INFO | segment_analysis | [125/263] JP_05
python(43735) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:09:37 - whisperx.asr - INFO - Detected language: en (0.94) in first 30s of audio

14:09:55 | INFO | segment_analysis |   ✓ 6 sections | mean LMC=0.5049 | method={'whisperx'}
14:09:55 | INFO | segment_analysis |   Checkpoint saved.
14:09:55 | INFO | segment_analysis | [126/263] JP_06
python(43761) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:10:05 - whisperx.asr - INFO - Detected language: en (0.96) in first 30s of audio

14:10:26 | INFO | segment_analysis |   ✓ 6 sections | mean LMC=0.3555 | method={'whisperx'}
14:10:26 | INFO | segment_analysis | [127/263] JP_07
python(43788) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:10:34 - whisperx.asr - INFO - Detected language: en (0.94) in first 30s of audio

14:10:49 | INFO | segment_analysis |   ✓ 2 sections | mean LMC=0.3849 | method={'whisperx'}
14:10:49 | INFO | segment_analysis | [128/263] JP_08
14:10:49 | INFO | segment_analysis |   [JP_08] Only 1 section(s) — skipping
14:10:49 | INFO | segment_analysis | [129/263] JP_09
python(43794) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:10:58 - whisperx.asr - INFO - Detected language: en (0.98) in first 30s of audio

14:11:17 | INFO | segment_analysis |   ✓ 6 sections | mean LMC=0.3212 | method={'whisperx'}
14:11:17 | INFO | segment_analysis | [130/263] JP_10
python(43818) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:11:26 - whisperx.asr - INFO - Detected language: en (0.92) in first 30s of audio

14:11:41 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.3872 | method={'whisperx'}
14:11:41 | INFO | segment_analysis |   Checkpoint saved.
14:11:41 | INFO | segment_analysis | [131/263] JP_11
python(43826) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:11:50 - whisperx.asr - INFO - Detected language: en (0.97) in first 30s of audio

14:12:18 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.3051 | method={'whisperx'}
14:12:18 | INFO | segment_analysis | [132/263] JP_12
python(43906) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:12:27 - whisperx.asr - INFO - Detected language: en (0.99) in first 30s of audio

14:19:13 | INFO | segment_analysis |   ✓ 2 sections | mean LMC=0.3708 | method={'whisperx'}
14:19:13 | INFO | segment_analysis | [133/263] GW_01
python(43934) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:19:31 - whisperx.asr - INFO - Detected language: en (0.85) in first 30s of audio

14:35:07 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.2294 | method={'whisperx'}
14:35:07 | INFO | segment_analysis | [134/263] GW_02
python(44007) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:36:46 - whisperx.asr - INFO - Detected language: en (0.30) in first 30s of audio

14:37:22 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.2396 | method={'whisperx'}
14:37:22 | INFO | segment_analysis | [135/263] GW_03
python(44290) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:38:32 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

14:45:27 | INFO | segment_analysis |   ✓ 2 sections | mean LMC=0.3227 | method={'whisperx'}
14:45:27 | INFO | segment_analysis |   Checkpoint saved.
14:45:27 | INFO | segment_analysis | [136/263] GW_04
14:45:27 | INFO | segment_analysis |   [GW_04] Only 1 section(s) — skipping
14:45:27 | INFO | segment_analysis | [137/263] GW_05
python(44475) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:45:46 - whisperx.asr - INFO - Detected language: en (0.81) in first 30s of audio

14:48:58 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.3358 | method={'whisperx'}
14:48:58 | INFO | segment_analysis | [138/263] GW_06
python(44758) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:49:21 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

14:50:12 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.2704 | method={'whisperx'}
14:50:12 | INFO | segment_analysis | [139/263] GW_07
14:50:12 | INFO | segment_analysis |   [GW_07] Only 1 section(s) — skipping
14:50:12 | INFO | segment_analysis | [140/263] GW_08
14:50:12 | INFO | segment_analysis |   [GW_08] Only 1 section(s) — skipping
14:50:12 | INFO | segment_analysis |   Checkpoint saved.
14:50:12 | INFO | segment_analysis | [141/263] GW_09
python(45232) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:53:58 - whisperx.asr - INFO - Detected language: en (0.30) in first 30s of audio

14:55:06 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.2396 | method={'whisperx'}
14:55:06 | INFO | segment_analysis | [142/263] GW_10
python(45532) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:56:27 - whisperx.asr - INFO - Detected language: en (0.86) in first 30s of audio

14:57:23 | INFO | segment_analysis |   ✓ 9 sections | mean LMC=0.2640 | method={'whisperx'}
14:57:23 | INFO | segment_analysis | [143/263] GW_11
python(46045) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:57:31 - whisperx.asr - INFO - Detected language: en (0.58) in first 30s of audio

14:57:42 | INFO | segment_analysis |   ✓ 2 sections | mean LMC=0.2718 | method={'whisperx'}
14:57:42 | INFO | segment_analysis | [144/263] GW_12
python(46056) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:57:49 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

14:58:00 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.3250 | method={'whisperx'}
14:58:00 | INFO | segment_analysis | [145/263] CW_01
python(46057) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:58:07 - whisperx.asr - INFO - Detected language: en (0.42) in first 30s of audio

14:58:21 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.2656 | method={'whisperx'}
14:58:21 | INFO | segment_analysis |   Checkpoint saved.
14:58:21 | INFO | segment_analysis | [146/263] CW_02
python(46074) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:58:26 - whisperx.asr - INFO - Detected language: en (0.92) in first 30s of audio

14:58:39 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.3814 | method={'whisperx'}
14:58:39 | INFO | segment_analysis | [147/263] CW_03
14:58:39 | INFO | segment_analysis |   [CW_03] Only 1 section(s) — skipping
14:58:39 | INFO | segment_analysis | [148/263] CW_04
python(46085) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:58:47 - whisperx.asr - INFO - Detected language: en (0.37) in first 30s of audio

14:59:02 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.3298 | method={'whisperx'}
14:59:02 | INFO | segment_analysis | [149/263] CW_05
python(46092) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:59:07 - whisperx.asr - INFO - Detected language: en (0.99) in first 30s of audio

14:59:23 | INFO | segment_analysis |   ✓ 6 sections | mean LMC=0.3526 | method={'whisperx'}
14:59:23 | INFO | segment_analysis | [150/263] CW_06
python(46099) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:59:32 - whisperx.asr - INFO - Detected language: en (0.87) in first 30s of audio

14:59:51 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.3563 | method={'whisperx'}
14:59:51 | INFO | segment_analysis |   Checkpoint saved.
14:59:51 | INFO | segment_analysis | [151/263] CW_07
14:59:51 | INFO | segment_analysis |   [CW_07] Only 1 section(s) — skipping
14:59:51 | INFO | segment_analysis | [152/263] CW_08
14:59:51 | INFO | segment_analysis |   [CW_08] Only 1 section(s) — skipping
14:59:51 | INFO | segment_analysis | [153/263] CW_09
python(46106) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 14:59:59 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

15:00:15 | INFO | segment_analysis |   ✓ 2 sections | mean LMC=0.5275 | method={'whisperx'}
15:00:15 | INFO | segment_analysis | [154/263] CW_10
python(46115) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:00:20 - whisperx.asr - INFO - Detected language: en (0.95) in first 30s of audio

15:00:37 | INFO | segment_analysis |   ✓ 7 sections | mean LMC=0.3682 | method={'whisperx'}
15:00:37 | INFO | segment_analysis | [155/263] CW_11
15:00:37 | INFO | segment_analysis |   [CW_11] Only 1 section(s) — skipping
15:00:37 | INFO | segment_analysis |   Checkpoint saved.
15:00:37 | INFO | segment_analysis | [156/263] CW_12
python(46132) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:00:47 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

15:01:05 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.2723 | method={'whisperx'}
15:01:05 | INFO | segment_analysis | [157/263] AG_01
python(46163) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:01:12 - whisperx.asr - INFO - Detected language: en (0.80) in first 30s of audio

15:01:26 | INFO | segment_analysis |   ✓ 2 sections | mean LMC=0.3068 | method={'whisperx'}
15:01:26 | INFO | segment_analysis | [158/263] AG_02
python(46175) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:01:32 - whisperx.asr - INFO - Detected language: en (0.79) in first 30s of audio

15:01:45 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.3143 | method={'whisperx'}
15:01:45 | INFO | segment_analysis | [159/263] AG_03
python(46177) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:01:51 - whisperx.asr - INFO - Detected language: en (0.76) in first 30s of audio

15:02:00 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.3037 | method={'whisperx'}
15:02:00 | INFO | segment_analysis | [160/263] AG_04
python(46178) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:02:07 - whisperx.asr - INFO - Detected language: en (0.76) in first 30s of audio

15:02:19 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.3635 | method={'whisperx'}
15:02:19 | INFO | segment_analysis |   Checkpoint saved.
15:02:19 | INFO | segment_analysis | [161/263] AG_05
python(46213) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:02:28 - whisperx.asr - INFO - Detected language: en (0.65) in first 30s of audio

15:02:43 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.3129 | method={'whisperx'}
15:02:43 | INFO | segment_analysis | [162/263] AG_06
python(46233) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:02:52 - whisperx.asr - INFO - Detected language: en (0.70) in first 30s of audio

15:03:10 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.2887 | method={'whisperx'}
15:03:10 | INFO | segment_analysis | [163/263] AG_07
python(46253) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:03:20 - whisperx.asr - INFO - Detected language: en (0.58) in first 30s of audio

15:03:25 | INFO | segment_analysis | [164/263] AG_08
python(46276) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:03:35 - whisperx.asr - INFO - Detected language: ko (0.50) in first 30s of audio

15:03:40 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/kresnik/wav2vec2-large-xlsr-korean/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
15:03:40 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
15:03:40 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/chat_template.json "HTTP/1.1 404 Not Found"
15:03:40 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/chat_template.jinja "HTTP/1.1 404 Not Found"
15:03:40 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/audio_tokenizer_config.json "HTTP/1.1 404 Not Found"
15:03:40 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
15:03:40 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/preprocessor_config.json "HTTP/1.1 307 Temporary Redirect"
15:03:40 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/kresnik/wav2vec2-large-xlsr-korean/629c9a3501c10ba128bf3fa1eebb12af3be03f61/preprocessor_config.json "HTTP/1.1 200 OK"
15:03:40 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
15:03:40 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/preprocessor_config.json "HTTP/1.1 307 Temporary Redirect"
15:03:40 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/kresnik/wav2vec2-large-xlsr-korean/629c9a3501c10ba128bf3fa1eebb12af3be03f61/preprocessor_config.json "HTTP/1.1 200 OK"
15:03:40 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
15:03:40 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/kresnik/wav2vec2-large-xlsr-korean/629c9a3501c10ba128bf3fa1eebb12af3be03f61/config.json "HTTP/1.1 200 OK"
15:03:40 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
15:03:40 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/kresnik/wav2vec2-large-xlsr-korean/629c9a3501c10ba128bf3fa1eebb12af3be03f61/tokenizer_config.json "HTTP/1.1 200 OK"
15:03:40 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/kresnik/wav2vec2-large-xlsr-korean/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
15:03:41 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/kresnik/wav2vec2-large-xlsr-korean/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
15:03:41 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
15:03:41 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/kresnik/wav2vec2-large-xlsr-korean/629c9a3501c10ba128bf3fa1eebb12af3be03f61/config.json "HTTP/1.1 200 OK"
15:03:41 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/model.safetensors "HTTP/1.1 302 Found"

Loading weights:   0%|          | 0/424 [00:00<?, ?it/s]

15:04:17 | INFO | segment_analysis |   ✓ 6 sections | mean LMC=0.2746 | method={'whisperx'}
15:04:17 | INFO | segment_analysis | [165/263] AG_09
python(46364) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:04:25 - whisperx.asr - INFO - Detected language: en (0.42) in first 30s of audio

15:04:36 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.2036 | method={'whisperx'}
15:04:36 | INFO | segment_analysis |   Checkpoint saved.
15:04:36 | INFO | segment_analysis | [166/263] AG_10
python(46375) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:04:45 - whisperx.asr - INFO - Detected language: en (0.50) in first 30s of audio

15:05:01 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.1438 | method={'whisperx'}
15:05:01 | INFO | segment_analysis | [167/263] AG_11
15:05:01 | INFO | segment_analysis |   [AG_11] Only 1 section(s) — skipping
15:05:01 | INFO | segment_analysis | [168/263] AG_12
python(46389) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:05:11 - whisperx.asr - INFO - Detected language: en (0.53) in first 30s of audio

15:05:31 | INFO | segment_analysis |   ✓ 6 sections | mean LMC=0.2953 | method={'whisperx'}
15:05:31 | INFO | segment_analysis | [169/263] ES_01
python(46419) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:05:41 - whisperx.asr - INFO - Detected language: en (0.93) in first 30s of audio

15:06:11 | INFO | segment_analysis |   ✓ 9 sections | mean LMC=0.3659 | method={'whisperx'}
15:06:12 | INFO | segment_analysis | [170/263] ES_02
python(46456) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:06:22 - whisperx.asr - INFO - Detected language: en (0.92) in first 30s of audio

15:06:40 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.4450 | method={'whisperx'}
15:06:40 | INFO | segment_analysis |   Checkpoint saved.
15:06:40 | INFO | segment_analysis | [171/263] ES_03
python(46473) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:06:51 - whisperx.asr - INFO - Detected language: en (0.89) in first 30s of audio

15:07:10 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.4146 | method={'whisperx'}
15:07:10 | INFO | segment_analysis | [172/263] ES_04
python(46494) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:07:20 - whisperx.asr - INFO - Detected language: en (0.76) in first 30s of audio

15:07:39 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.3014 | method={'whisperx'}
15:07:39 | INFO | segment_analysis | [173/263] ES_05
15:07:39 | INFO | segment_analysis |   [ES_05] Only 1 section(s) — skipping
15:07:39 | INFO | segment_analysis | [174/263] ES_06
python(46633) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:07:47 - whisperx.asr - INFO - Detected language: en (0.92) in first 30s of audio

15:08:01 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.1939 | method={'whisperx'}
15:08:01 | INFO | segment_analysis | [175/263] ES_07
python(46645) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:08:10 - whisperx.asr - INFO - Detected language: en (0.44) in first 30s of audio

15:08:31 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.1812 | method={'whisperx'}
15:08:31 | INFO | segment_analysis |   Checkpoint saved.
15:08:31 | INFO | segment_analysis | [176/263] ES_08
python(46685) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:08:40 - whisperx.asr - INFO - Detected language: en (0.70) in first 30s of audio

15:08:59 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.2987 | method={'whisperx'}
15:08:59 | INFO | segment_analysis | [177/263] ES_09
python(46710) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:09:09 - whisperx.asr - INFO - Detected language: en (0.83) in first 30s of audio

15:09:24 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.1522 | method={'whisperx'}
15:09:24 | INFO | segment_analysis | [178/263] ES_10
python(46729) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:09:35 - whisperx.asr - INFO - Detected language: en (0.82) in first 30s of audio

15:09:57 | INFO | segment_analysis |   ✓ 6 sections | mean LMC=0.2411 | method={'whisperx'}
15:09:57 | INFO | segment_analysis | [179/263] ES_11
python(46746) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:10:05 - whisperx.asr - INFO - Detected language: en (0.83) in first 30s of audio

15:10:21 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.2316 | method={'whisperx'}
15:10:21 | INFO | segment_analysis | [180/263] ES_12
python(46769) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:10:29 - whisperx.asr - INFO - Detected language: en (0.86) in first 30s of audio

15:10:44 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.3489 | method={'whisperx'}
15:10:44 | INFO | segment_analysis |   Checkpoint saved.
15:10:44 | INFO | segment_analysis | [181/263] BE_01
python(46773) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:10:52 - whisperx.asr - INFO - Detected language: en (0.95) in first 30s of audio

15:11:02 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.2783 | method={'whisperx'}
15:11:02 | INFO | segment_analysis | [182/263] BE_02
python(46776) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:11:13 - whisperx.asr - INFO - Detected language: en (0.84) in first 30s of audio

15:11:33 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.2785 | method={'whisperx'}
15:11:33 | INFO | segment_analysis | [183/263] BE_03
python(46843) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:11:41 - whisperx.asr - INFO - Detected language: pt (0.55) in first 30s of audio

15:11:46 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
15:11:46 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
15:11:46 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/chat_template.json "HTTP/1.1 404 Not Found"
15:11:46 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/chat_template.jinja "HTTP/1.1 404 Not Found"
15:11:46 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/audio_tokenizer_config.json "HTTP/1.1 404 Not Found"
15:11:46 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
15:11:46 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/preprocessor_config.json "HTTP/1.1 307 Temporary Redirect"
15:11:46 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/634ac655299bcdc46c83bc01da9bab52d2987e4f/preprocessor_config.json "HTTP/1.1 200 OK"
15:11:46 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/634ac655299bcdc46c83bc01da9bab52d2987e4f/preprocessor_config.json "HTTP/1.1 200 OK"

preprocessor_config.json:   0%|          | 0.00/262 [00:00<?, ?B/s]

15:11:46 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
15:11:46 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/preprocessor_config.json "HTTP/1.1 307 Temporary Redirect"
15:11:47 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/634ac655299bcdc46c83bc01da9bab52d2987e4f/preprocessor_config.json "HTTP/1.1 200 OK"
15:11:47 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
15:11:47 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/634ac655299bcdc46c83bc01da9bab52d2987e4f/config.json "HTTP/1.1 200 OK"
15:11:47 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/634ac655299bcdc46c83bc01da9bab52d2987e4f/config.json "HTTP/1.1 200 OK"

config.json: 0.00B [00:00, ?B/s]

15:11:47 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/tokenizer_config.json "HTTP/1.1 404 Not Found"
15:11:47 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/tokenizer_config.json "HTTP/1.1 404 Not Found"
15:11:47 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
15:11:47 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
15:11:47 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/vocab.json "HTTP/1.1 307 Temporary Redirect"
15:11:47 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/634ac655299bcdc46c83bc01da9bab52d2987e4f/vocab.json "HTTP/1.1 200 OK"
15:11:47 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/634ac655299bcdc46c83bc01da9bab52d2987e4f/vocab.json "HTTP/1.1 200 OK"

vocab.json:   0%|          | 0.00/430 [00:00<?, ?B/s]

15:11:47 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/added_tokens.json "HTTP/1.1 404 Not Found"
15:11:47 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/special_tokens_map.json "HTTP/1.1 307 Temporary Redirect"
15:11:47 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/634ac655299bcdc46c83bc01da9bab52d2987e4f/special_tokens_map.json "HTTP/1.1 200 OK"
15:11:47 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/634ac655299bcdc46c83bc01da9bab52d2987e4f/special_tokens_map.json "HTTP/1.1 200 OK"

special_tokens_map.json:   0%|          | 0.00/85.0 [00:00<?, ?B/s]

15:11:47 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/tokenizer.json "HTTP/1.1 404 Not Found"
15:11:47 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
15:11:47 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/634ac655299bcdc46c83bc01da9bab52d2987e4f/config.json "HTTP/1.1 200 OK"
15:11:47 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"
15:11:47 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/model.safetensors.index.json "HTTP/1.1 404 Not Found"
15:11:47 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/pytorch_model.bin "HTTP/1.1 302 Found"
15:11:47 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/xet-read-token/634ac655299bcdc46c83bc01da9bab52d2987e4f "HTTP/1.1 200 OK"

pytorch_model.bin:   0%|          | 0.00/1.26G [00:00<?, ?B/s]

15:12:16 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"
15:12:16 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese "HTTP/1.1 200 OK"
15:12:16 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/commits/main "HTTP/1.1 200 OK"
15:12:16 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/discussions?p=0 "HTTP/1.1 200 OK"
15:12:16 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/commits/refs%2Fpr%2F4 "HTTP/1.1 200 OK"
15:12:16 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/refs%2Fpr%2F4/model.safetensors.index.json "HTTP/1.1 404 Not Found"
15:12:16 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/refs%2Fpr%2F4/model.safetensors "HTTP/1.1 302 Found"
15:12:16 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/xet-read-token/66153c537449086b14c100226b65a7cfa32b9bd0 "HTTP/1.1 200 OK"

model.safetensors:   0%|          | 0.00/1.26G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/424 [00:00<?, ?it/s]

15:13:05 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.3609 | method={'whisperx'}
15:13:05 | INFO | segment_analysis | [184/263] BE_04
python(46931) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:13:14 - whisperx.asr - INFO - Detected language: en (0.70) in first 30s of audio

15:13:31 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.3156 | method={'whisperx'}
15:13:31 | INFO | segment_analysis | [185/263] BE_05
python(46951) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:13:42 - whisperx.asr - INFO - Detected language: en (0.88) in first 30s of audio

15:14:00 | INFO | segment_analysis |   ✓ 2 sections | mean LMC=0.1938 | method={'whisperx'}
15:14:00 | INFO | segment_analysis |   Checkpoint saved.
15:14:00 | INFO | segment_analysis | [186/263] BE_06
python(46963) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:14:13 - whisperx.asr - INFO - Detected language: en (0.79) in first 30s of audio

15:14:38 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.2231 | method={'whisperx'}
15:14:38 | INFO | segment_analysis | [187/263] BE_07
python(47040) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:14:48 - whisperx.asr - INFO - Detected language: en (0.95) in first 30s of audio

15:15:06 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.4080 | method={'whisperx'}
15:15:06 | INFO | segment_analysis | [188/263] BE_08
python(47071) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:15:18 - whisperx.asr - INFO - Detected language: en (0.42) in first 30s of audio

15:15:37 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.2048 | method={'whisperx'}
15:15:37 | INFO | segment_analysis | [189/263] BE_09
python(47085) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:15:46 - whisperx.asr - INFO - Detected language: en (0.82) in first 30s of audio

15:16:02 | INFO | segment_analysis |   ✓ 2 sections | mean LMC=0.3601 | method={'whisperx'}
15:16:02 | INFO | segment_analysis | [190/263] BE_10
python(47088) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:16:12 - whisperx.asr - INFO - Detected language: en (0.72) in first 30s of audio

15:16:31 | INFO | segment_analysis |   ✓ 2 sections | mean LMC=0.3718 | method={'whisperx'}
15:16:31 | INFO | segment_analysis |   Checkpoint saved.
15:16:31 | INFO | segment_analysis | [191/263] BE_11
python(47117) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:16:42 - whisperx.asr - INFO - Detected language: en (0.86) in first 30s of audio

15:17:05 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.3622 | method={'whisperx'}
15:17:05 | INFO | segment_analysis | [192/263] BE_12
python(47144) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:17:13 - whisperx.asr - INFO - Detected language: en (0.69) in first 30s of audio

15:17:26 | INFO | segment_analysis |   ✓ 2 sections | mean LMC=0.3028 | method={'whisperx'}
15:17:26 | INFO | segment_analysis | [193/263] HS_01
python(47156) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:17:35 - whisperx.asr - INFO - Detected language: en (0.83) in first 30s of audio

15:17:45 | INFO | segment_analysis |   ✓ 2 sections | mean LMC=0.2250 | method={'whisperx'}
15:17:45 | INFO | segment_analysis | [194/263] HS_02
python(47194) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:17:53 - whisperx.asr - INFO - Detected language: en (0.83) in first 30s of audio

15:18:07 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.2925 | method={'whisperx'}
15:18:07 | INFO | segment_analysis | [195/263] HS_03
python(47207) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:18:17 - whisperx.asr - INFO - Detected language: en (0.85) in first 30s of audio

15:18:30 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.3045 | method={'whisperx'}
15:18:30 | INFO | segment_analysis |   Checkpoint saved.
15:18:30 | INFO | segment_analysis | [196/263] HS_04
python(47223) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:18:39 - whisperx.asr - INFO - Detected language: en (0.62) in first 30s of audio

15:18:55 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.2381 | method={'whisperx'}
15:18:55 | INFO | segment_analysis | [197/263] HS_05
python(47225) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:19:02 - whisperx.asr - INFO - Detected language: en (0.85) in first 30s of audio

15:19:12 | INFO | segment_analysis |   ✓ 1 sections | mean LMC=0.3582 | method={'whisperx'}
15:19:12 | INFO | segment_analysis | [198/263] HS_06
python(47247) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:19:27 - whisperx.asr - INFO - Detected language: en (0.76) in first 30s of audio

15:19:42 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.2281 | method={'whisperx'}
15:19:42 | INFO | segment_analysis | [199/263] HS_07
python(47261) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:19:54 - whisperx.asr - INFO - Detected language: en (0.80) in first 30s of audio

15:20:13 | INFO | segment_analysis |   ✓ 2 sections | mean LMC=0.2500 | method={'whisperx'}
15:20:13 | INFO | segment_analysis | [200/263] HS_08
python(47296) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:20:23 - whisperx.asr - INFO - Detected language: en (0.87) in first 30s of audio

15:20:36 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.3203 | method={'whisperx'}
15:20:36 | INFO | segment_analysis |   Checkpoint saved.
15:20:36 | INFO | segment_analysis | [201/263] HS_09
python(47328) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:20:46 - whisperx.asr - INFO - Detected language: en (0.94) in first 30s of audio

15:21:11 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.2450 | method={'whisperx'}
15:21:11 | INFO | segment_analysis | [202/263] HS_10
python(47349) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:21:24 - whisperx.asr - INFO - Detected language: en (0.49) in first 30s of audio

15:21:41 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.2282 | method={'whisperx'}
15:21:41 | INFO | segment_analysis | [203/263] HS_11
python(47364) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:21:56 - whisperx.asr - INFO - Detected language: en (0.89) in first 30s of audio

15:22:27 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.2168 | method={'whisperx'}
15:22:27 | INFO | segment_analysis | [204/263] HS_12
python(47448) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:22:40 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

15:23:02 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.2634 | method={'whisperx'}
15:23:02 | INFO | segment_analysis | [205/263] OR_01
python(47466) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:23:18 - whisperx.asr - INFO - Detected language: en (0.66) in first 30s of audio

15:23:44 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.2753 | method={'whisperx'}
15:23:44 | INFO | segment_analysis |   Checkpoint saved.
15:23:44 | INFO | segment_analysis | [206/263] OR_02
python(47496) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:23:57 - whisperx.asr - INFO - Detected language: en (0.82) in first 30s of audio

15:24:19 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.2792 | method={'whisperx'}
15:24:19 | INFO | segment_analysis | [207/263] OR_03
python(47615) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:24:33 - whisperx.asr - INFO - Detected language: en (0.88) in first 30s of audio

15:25:01 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.2582 | method={'whisperx'}
15:25:01 | INFO | segment_analysis | [208/263] OR_04
python(47639) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:25:10 - whisperx.asr - INFO - Detected language: en (0.89) in first 30s of audio

15:25:27 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.3122 | method={'whisperx'}
15:25:27 | INFO | segment_analysis | [209/263] OR_05
python(47683) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:25:39 - whisperx.asr - INFO - Detected language: en (0.88) in first 30s of audio

15:26:03 | INFO | segment_analysis |   ✓ 6 sections | mean LMC=0.1977 | method={'whisperx'}
15:26:03 | INFO | segment_analysis | [210/263] OR_06
python(47722) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:26:13 - whisperx.asr - INFO - Detected language: en (0.83) in first 30s of audio

15:26:33 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.4266 | method={'whisperx'}
15:26:34 | INFO | segment_analysis |   Checkpoint saved.
15:26:34 | INFO | segment_analysis | [211/263] OR_07
python(47765) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:26:46 - whisperx.asr - INFO - Detected language: en (0.88) in first 30s of audio

15:27:06 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.2212 | method={'whisperx'}
15:27:06 | INFO | segment_analysis | [212/263] OR_08
python(47787) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:27:16 - whisperx.asr - INFO - Detected language: en (0.92) in first 30s of audio

15:27:26 | INFO | segment_analysis |   ✓ 1 sections | mean LMC=0.3093 | method={'whisperx'}
15:27:26 | INFO | segment_analysis | [213/263] OR_09
python(47794) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:27:36 - whisperx.asr - INFO - Detected language: en (0.86) in first 30s of audio

15:27:55 | INFO | segment_analysis |   ✓ 1 sections | mean LMC=0.4154 | method={'whisperx'}
15:27:55 | INFO | segment_analysis | [214/263] OR_10
python(47808) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:28:04 - whisperx.asr - INFO - Detected language: en (0.83) in first 30s of audio

15:28:22 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.2073 | method={'whisperx'}
15:28:22 | INFO | segment_analysis | [215/263] OR_11
python(47816) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:28:31 - whisperx.asr - INFO - Detected language: en (0.67) in first 30s of audio

15:28:54 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.3477 | method={'whisperx'}
15:28:54 | INFO | segment_analysis |   Checkpoint saved.
15:28:54 | INFO | segment_analysis | [216/263] OR_12
python(47820) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:29:02 - whisperx.asr - INFO - Detected language: en (0.81) in first 30s of audio

15:29:18 | INFO | segment_analysis |   ✓ 2 sections | mean LMC=0.3423 | method={'whisperx'}
15:29:18 | INFO | segment_analysis | [217/263] JB_01
15:29:18 | INFO | segment_analysis |   [JB_01] Only 1 section(s) — skipping
15:29:18 | INFO | segment_analysis | [218/263] JB_02
python(47828) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:29:28 - whisperx.asr - INFO - Detected language: en (0.64) in first 30s of audio

15:29:44 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.3789 | method={'whisperx'}
15:29:44 | INFO | segment_analysis | [219/263] JB_03
python(47840) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:29:57 - whisperx.asr - INFO - Detected language: en (0.54) in first 30s of audio

15:30:05 | INFO | segment_analysis |   ✓ 1 sections | mean LMC=0.2513 | method={'whisperx'}
15:30:05 | INFO | segment_analysis | [220/263] JB_04
python(47849) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:30:21 - whisperx.asr - INFO - Detected language: en (0.76) in first 30s of audio

15:30:43 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.3128 | method={'whisperx'}
15:30:43 | INFO | segment_analysis |   Checkpoint saved.
15:30:43 | INFO | segment_analysis | [221/263] JB_05
python(47889) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:30:53 - whisperx.asr - INFO - Detected language: en (0.81) in first 30s of audio

15:31:03 | INFO | segment_analysis |   ✓ 1 sections | mean LMC=0.2998 | method={'whisperx'}
15:31:03 | INFO | segment_analysis | [222/263] JB_06
python(47893) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:31:18 - whisperx.asr - INFO - Detected language: en (0.68) in first 30s of audio

15:31:47 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.2267 | method={'whisperx'}
15:31:47 | INFO | segment_analysis | [223/263] JB_07
15:31:47 | INFO | segment_analysis |   [JB_07] Only 1 section(s) — skipping
15:31:47 | INFO | segment_analysis | [224/263] JB_08
python(47965) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:32:03 - whisperx.asr - INFO - Detected language: en (0.53) in first 30s of audio

15:32:40 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.2312 | method={'whisperx'}
15:32:40 | INFO | segment_analysis | [225/263] JB_09
python(48042) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:33:00 - whisperx.asr - INFO - Detected language: en (0.82) in first 30s of audio

15:33:35 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.2792 | method={'whisperx'}
15:33:35 | INFO | segment_analysis |   Checkpoint saved.
15:33:35 | INFO | segment_analysis | [226/263] JB_10
python(48084) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:33:57 - whisperx.asr - INFO - Detected language: en (0.87) in first 30s of audio

15:34:47 | INFO | segment_analysis |   ✓ 7 sections | mean LMC=0.2799 | method={'whisperx'}
15:34:47 | INFO | segment_analysis | [227/263] JB_11
python(48144) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:35:09 - whisperx.asr - INFO - Detected language: en (0.63) in first 30s of audio

15:35:47 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.3165 | method={'whisperx'}
15:35:47 | INFO | segment_analysis | [228/263] JB_12
python(48194) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:35:59 - whisperx.asr - INFO - Detected language: en (0.91) in first 30s of audio

15:36:33 | INFO | segment_analysis |   ✓ 8 sections | mean LMC=0.2501 | method={'whisperx'}
15:36:33 | INFO | segment_analysis | [229/263] LCD_01
python(48276) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:37:00 - whisperx.asr - INFO - Detected language: en (0.37) in first 30s of audio

15:37:45 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.3276 | method={'whisperx'}
15:37:45 | INFO | segment_analysis | [230/263] LCD_02
python(48341) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:38:04 - whisperx.asr - INFO - Detected language: en (0.91) in first 30s of audio

15:38:17 | INFO | segment_analysis |   ✓ 1 sections | mean LMC=0.2460 | method={'whisperx'}
15:38:17 | INFO | segment_analysis |   Checkpoint saved.
15:38:17 | INFO | segment_analysis | [231/263] LCD_03
python(48362) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:38:38 - whisperx.asr - INFO - Detected language: en (0.63) in first 30s of audio

15:39:06 | INFO | segment_analysis |   ✓ 1 sections | mean LMC=0.2139 | method={'whisperx'}
15:39:06 | INFO | segment_analysis | [232/263] LCD_04
python(48452) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:39:26 - whisperx.asr - INFO - Detected language: zh (0.60) in first 30s of audio

15:39:37 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
15:39:37 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
15:39:37 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/chat_template.json "HTTP/1.1 404 Not Found"
15:39:37 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/chat_template.jinja "HTTP/1.1 404 Not Found"
15:39:37 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/audio_tokenizer_config.json "HTTP/1.1 404 Not Found"
15:39:37 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
15:39:37 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/preprocessor_config.json "HTTP/1.1 307 Temporary Redirect"
15:39:37 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/99ccb2737be22b8bb50dcfcc39ad4d567fb90cfd/preprocessor_config.json "HTTP/1.1 200 OK"
15:39:37 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/99ccb2737be22b8bb50dcfcc39ad4d567fb90cfd/preprocessor_config.json "HTTP/1.1 200 OK"

preprocessor_config.json:   0%|          | 0.00/158 [00:00<?, ?B/s]

15:39:37 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
15:39:37 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/99ccb2737be22b8bb50dcfcc39ad4d567fb90cfd/config.json "HTTP/1.1 200 OK"
15:39:37 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/99ccb2737be22b8bb50dcfcc39ad4d567fb90cfd/config.json "HTTP/1.1 200 OK"

config.json: 0.00B [00:00, ?B/s]

15:39:37 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
15:39:37 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/preprocessor_config.json "HTTP/1.1 307 Temporary Redirect"
15:39:37 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/99ccb2737be22b8bb50dcfcc39ad4d567fb90cfd/preprocessor_config.json "HTTP/1.1 200 OK"
15:39:37 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
15:39:37 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/99ccb2737be22b8bb50dcfcc39ad4d567fb90cfd/config.json "HTTP/1.1 200 OK"
15:39:37 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/tokenizer_config.json "HTTP/1.1 404 Not Found"
15:39:37 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/tokenizer_config.json "HTTP/1.1 404 Not Found"
15:39:37 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
15:39:37 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
15:39:37 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/vocab.json "HTTP/1.1 307 Temporary Redirect"
15:39:37 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/99ccb2737be22b8bb50dcfcc39ad4d567fb90cfd/vocab.json "HTTP/1.1 200 OK"
15:39:37 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/99ccb2737be22b8bb50dcfcc39ad4d567fb90cfd/vocab.json "HTTP/1.1 200 OK"

vocab.json: 0.00B [00:00, ?B/s]

15:39:38 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/added_tokens.json "HTTP/1.1 404 Not Found"
15:39:38 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/special_tokens_map.json "HTTP/1.1 307 Temporary Redirect"
15:39:38 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/99ccb2737be22b8bb50dcfcc39ad4d567fb90cfd/special_tokens_map.json "HTTP/1.1 200 OK"
15:39:38 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/99ccb2737be22b8bb50dcfcc39ad4d567fb90cfd/special_tokens_map.json "HTTP/1.1 200 OK"

special_tokens_map.json:   0%|          | 0.00/85.0 [00:00<?, ?B/s]

15:39:38 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/tokenizer.json "HTTP/1.1 404 Not Found"
15:39:38 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
15:39:38 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/99ccb2737be22b8bb50dcfcc39ad4d567fb90cfd/config.json "HTTP/1.1 200 OK"
15:39:38 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"
15:39:38 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/model.safetensors.index.json "HTTP/1.1 404 Not Found"
15:39:38 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/pytorch_model.bin "HTTP/1.1 302 Found"
15:39:38 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/xet-read-token/99ccb2737be22b8bb50dcfcc39ad4d567fb90cfd "HTTP/1.1 200 OK"

pytorch_model.bin:   0%|          | 0.00/1.28G [00:00<?, ?B/s]

15:40:08 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"
15:40:08 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn "HTTP/1.1 200 OK"
15:40:08 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/commits/main "HTTP/1.1 200 OK"
15:40:08 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/discussions?p=0 "HTTP/1.1 200 OK"
15:40:08 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/commits/refs%2Fpr%2F5 "HTTP/1.1 200 OK"
15:40:08 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/refs%2Fpr%2F5/model.safetensors.index.json "HTTP/1.1 404 Not Found"
15:40:08 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/refs%2Fpr%2F5/model.safetensors "HTTP/1.1 302 Found"
15:40:08 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/xet-read-token/d9cb786880643b6161bf740f49c4a42b9ecb7d0f "HTTP/1.1 200 OK"

model.safetensors:   0%|          | 0.00/1.28G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/424 [00:00<?, ?it/s]

15:40:48 | INFO | segment_analysis |   ✓ 2 sections | mean LMC=0.3662 | method={'whisperx'}
15:40:48 | INFO | segment_analysis | [233/263] LCD_05
python(48659) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:41:03 - whisperx.asr - INFO - Detected language: en (0.57) in first 30s of audio

15:41:06 | INFO | segment_analysis |   [LCD_05] WhisperX returned no words — using equal splits
15:41:27 | INFO | segment_analysis |   ✓ 7 sections | mean LMC=0.1933 | method={'fallback_equal'}
15:41:27 | INFO | segment_analysis | [234/263] LCD_06
python(48683) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:41:50 - whisperx.asr - INFO - Detected language: en (0.58) in first 30s of audio

15:42:27 | INFO | segment_analysis |   ✓ 1 sections | mean LMC=0.2542 | method={'whisperx'}
15:42:27 | INFO | segment_analysis | [235/263] LCD_07
15:42:27 | INFO | segment_analysis |   [LCD_07] Only 1 section(s) — skipping
15:42:27 | INFO | segment_analysis |   Checkpoint saved.
15:42:27 | INFO | segment_analysis | [236/263] LCD_08
python(48720) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:42:52 - whisperx.asr - INFO - Detected language: en (0.18) in first 30s of audio

15:43:21 | INFO | segment_analysis |   ✓ 1 sections | mean LMC=0.2737 | method={'whisperx'}
15:43:21 | INFO | segment_analysis | [237/263] LCD_09
python(48826) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:43:41 - whisperx.asr - INFO - Detected language: en (0.52) in first 30s of audio

15:43:47 | INFO | segment_analysis | [238/263] LCD_10
15:43:47 | INFO | segment_analysis |   [LCD_10] Only 1 section(s) — skipping
15:43:47 | INFO | segment_analysis | [239/263] LCD_11
15:43:47 | INFO | segment_analysis |   [LCD_11] Only 1 section(s) — skipping
15:43:47 | INFO | segment_analysis | [240/263] LCD_12
15:43:47 | INFO | segment_analysis |   [LCD_12] Only 1 section(s) — skipping
15:43:47 | INFO | segment_analysis |   Checkpoint saved.
15:43:47 | INFO | segment_analysis | [241/263] BN_01
python(48847) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:44:00 - whisperx.asr - INFO - Detected language: en (0.56) in first 30s of audio

15:44:02 | INFO | segment_analysis |   [BN_01] WhisperX returned no words — using equal splits
15:44:19 | INFO | segment_analysis |   ✓ 7 sections | mean LMC=0.1402 | method={'fallback_equal'}
15:44:19 | INFO | segment_analysis | [242/263] BN_02
python(48861) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:44:31 - whisperx.asr - INFO - Detected language: en (0.72) in first 30s of audio

15:44:44 | INFO | segment_analysis |   ✓ 1 sections | mean LMC=0.2223 | method={'whisperx'}
15:44:44 | INFO | segment_analysis | [243/263] BN_03
python(48872) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:45:06 - whisperx.asr - INFO - Detected language: en (0.36) in first 30s of audio

15:45:57 | INFO | segment_analysis |   ✓ 1 sections | mean LMC=0.1436 | method={'whisperx'}
15:45:57 | INFO | segment_analysis | [244/263] BN_04
python(49026) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:46:16 - whisperx.asr - INFO - Detected language: en (0.59) in first 30s of audio

15:46:42 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.2931 | method={'whisperx'}
15:46:42 | INFO | segment_analysis | [245/263] BN_05
15:46:42 | INFO | segment_analysis |   [BN_05] Only 1 section(s) — skipping
15:46:42 | INFO | segment_analysis |   Checkpoint saved.
15:46:42 | INFO | segment_analysis | [246/263] BN_06
python(49092) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:46:57 - whisperx.asr - INFO - Detected language: en (0.65) in first 30s of audio

15:47:18 | INFO | segment_analysis |   ✓ 4 sections | mean LMC=0.1890 | method={'whisperx'}
15:47:18 | INFO | segment_analysis | [247/263] BN_07
15:47:18 | INFO | segment_analysis |   [BN_07] Only 0 section(s) — skipping
15:47:18 | INFO | segment_analysis | [248/263] BN_08
python(49108) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:49:54 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

15:52:30 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.2123 | method={'whisperx'}
15:52:30 | INFO | segment_analysis | [249/263] BN_09
15:52:30 | INFO | segment_analysis |   [BN_09] Only 1 section(s) — skipping
15:52:30 | INFO | segment_analysis | [250/263] BN_10
python(49330) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:52:41 - whisperx.asr - INFO - Detected language: en (0.51) in first 30s of audio

15:52:43 | INFO | segment_analysis |   [BN_10] WhisperX returned no words — using equal splits
15:52:56 | INFO | segment_analysis |   ✓ 10 sections | mean LMC=0.2274 | method={'fallback_equal'}
15:52:56 | INFO | segment_analysis |   Checkpoint saved.
15:52:56 | INFO | segment_analysis | [251/263] BN_11
15:52:56 | INFO | segment_analysis |   [BN_11] Only 1 section(s) — skipping
15:52:56 | INFO | segment_analysis | [252/263] GZ_01
python(49333) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:53:07 - whisperx.asr - INFO - Detected language: en (0.34) in first 30s of audio

15:53:27 | INFO | segment_analysis |   ✓ 1 sections | mean LMC=0.2781 | method={'whisperx'}
15:53:27 | INFO | segment_analysis | [253/263] GZ_02
python(49358) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:53:39 - whisperx.asr - INFO - Detected language: en (0.47) in first 30s of audio

15:53:42 | INFO | segment_analysis | [254/263] GZ_03
python(49365) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:53:58 - whisperx.asr - INFO - Detected language: en (0.78) in first 30s of audio

15:54:24 | INFO | segment_analysis |   ✓ 5 sections | mean LMC=0.3319 | method={'whisperx'}
15:54:24 | INFO | segment_analysis | [255/263] GZ_04
python(49366) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:54:36 - whisperx.asr - INFO - Detected language: en (0.42) in first 30s of audio

15:54:55 | INFO | segment_analysis |   ✓ 2 sections | mean LMC=0.2978 | method={'whisperx'}
15:54:55 | INFO | segment_analysis |   Checkpoint saved.
15:54:55 | INFO | segment_analysis | [256/263] GZ_05
python(49371) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:55:08 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

15:55:27 | INFO | segment_analysis |   ✓ 2 sections | mean LMC=0.1992 | method={'whisperx'}
15:55:27 | INFO | segment_analysis | [257/263] GZ_06
python(49400) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:55:41 - whisperx.asr - INFO - Detected language: en (0.58) in first 30s of audio

15:56:03 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.1204 | method={'whisperx'}
15:56:03 | INFO | segment_analysis | [258/263] GZ_07
python(49409) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:56:18 - whisperx.asr - INFO - Detected language: en (0.46) in first 30s of audio

15:56:31 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.1779 | method={'whisperx'}
15:56:31 | INFO | segment_analysis | [259/263] GZ_08
python(49415) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:56:45 - whisperx.asr - INFO - Detected language: en (0.96) in first 30s of audio

15:57:08 | INFO | segment_analysis |   ✓ 2 sections | mean LMC=0.3698 | method={'whisperx'}
15:57:08 | INFO | segment_analysis | [260/263] GZ_09
python(49427) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:57:22 - whisperx.asr - INFO - Detected language: en (0.92) in first 30s of audio

15:57:38 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.1707 | method={'whisperx'}
15:57:38 | INFO | segment_analysis |   Checkpoint saved.
15:57:38 | INFO | segment_analysis | [261/263] GZ_10
python(49439) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:57:49 - whisperx.asr - INFO - Detected language: en (0.63) in first 30s of audio

15:57:55 | INFO | segment_analysis | [262/263] GZ_11
python(49444) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:58:12 - whisperx.asr - INFO - Detected language: en (0.79) in first 30s of audio

15:58:30 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.3028 | method={'whisperx'}
15:58:30 | INFO | segment_analysis | [263/263] GZ_12
python(49533) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-20 15:58:45 - whisperx.asr - INFO - Detected language: en (0.33) in first 30s of audio

15:59:18 | INFO | segment_analysis |   ✓ 3 sections | mean LMC=0.1945 | method={'whisperx'}
15:59:18 | INFO | segment_analysis |   Checkpoint saved.
15:59:18 | INFO | segment_analysis |
Segment summary: 383 songs (372 WhisperX-aligned, 11 equal-split fallback)
15:59:18 | INFO | segment_analysis | → /Users/budge.13/Desktop/Music Analysis/results/segment_analysis/segment_summary.csv

Segment analysis complete: 383 songs with valid section data
Mean sections per song : 4.0
Mean segment LMC (all) : 0.3004

---
## Step 8 — Spotify Popularity
Searches the Spotify API for each song and fetches the popularity score (0–100)  
plus Echo Nest audio features (energy, danceability, valence, etc.) that serve as controls.  
**Outputs:** `results/spotify_data.json`, `results/spotify_summary.csv`  
**Resume-safe:** already-fetched songs are skipped.

In [10]:
get_popularity = load_script("get_popularity", "08_get_popularity.py")

spotify_data = get_popularity.fetch_all_popularity(force=False)

n_found   = sum(1 for v in spotify_data.values() if v.get("found"))
n_missing = len(spotify_data) - n_found
print(f"\nSpotify match rate: {n_found}/{len(spotify_data)} songs found")
if n_missing:
    missing_ids = [k for k, v in spotify_data.items() if not v.get("found")]
    print(f"Not found: {missing_ids}")

import pandas as pd
pop_vals = [v["popularity"] for v in spotify_data.values() if v.get("found")]
if pop_vals:
    import numpy as np
    print(f"Popularity — mean={np.mean(pop_vals):.1f}  "
          f"sd={np.std(pop_vals):.1f}  "
          f"min={np.min(pop_vals)}  max={np.max(pop_vals)}")

15:59:19 | INFO | get_popularity | Loaded existing Spotify data for 177 songs.
15:59:19 | INFO | get_popularity |
───────────────────────────────────────────────────────  Run the Jewels
15:59:19 | INFO | get_popularity |
───────────────────────────────────────────────────────  Kendrick Lamar
15:59:19 | INFO | get_popularity |
───────────────────────────────────────────────────────  J. Cole
15:59:19 | INFO | get_popularity |
───────────────────────────────────────────────────────  Drake
15:59:19 | INFO | get_popularity |   [DR_01] Searching: God's Plan
15:59:19 | INFO | get_popularity |     ✓ Found: 'God's Plan' | popularity=86
15:59:20 | INFO | get_popularity |   [DR_02] Searching: Hotline Bling
15:59:20 | INFO | get_popularity |     ✓ Found: 'Hotline Bling' | popularity=85
15:59:20 | INFO | get_popularity |   [DR_03] Searching: One Dance
15:59:21 | INFO | get_popularity |     ✓ Found: 'One Dance' | popularity=92
15:59:21 | INFO | get_popularity |   [DR_04] Searching: Passionfruit
15:59:22 | INFO | get_popularity |     ✓ Found: 'Passionfruit' | popularity=89
15:59:22 | INFO | get_popularity |   [DR_05] Searching: Started From the Bottom
15:59:22 | INFO | get_popularity |     ✓ Found: 'Started From the Bottom' | popularity=70
15:59:23 | INFO | get_popularity |   [DR_06] Searching: Take Care
15:59:23 | INFO | get_popularity |     ✓ Found: 'Take Care' | popularity=80
15:59:23 | INFO | get_popularity |   [DR_07] Searching: Marvins Room
15:59:23 | INFO | get_popularity |     ✓ Found: 'Marvins Room' | popularity=80
15:59:24 | INFO | get_popularity |   [DR_08] Searching: Hold On We're Going Home
15:59:24 | INFO | get_popularity |     ✓ Found: 'Hold On, We're Going Home' | popularity=82
15:59:24 | INFO | get_popularity |   [DR_09] Searching: Forever
15:59:25 | INFO | get_popularity |     ✓ Found: 'Forever' | popularity=72
15:59:25 | INFO | get_popularity |   [DR_10] Searching: Best I Ever Had
15:59:25 | INFO | get_popularity |     ✓ Found: 'Best I Ever Had' | popularity=80
15:59:26 | INFO | get_popularity |   [DR_11] Searching: Fancy
15:59:26 | INFO | get_popularity |     ✓ Found: 'Fancy' | popularity=76
15:59:26 | INFO | get_popularity |   [DR_12] Searching: From Time
15:59:27 | INFO | get_popularity |     ✓ Found: 'From Time' | popularity=73
15:59:27 | INFO | get_popularity |
───────────────────────────────────────────────────────  Eminem
15:59:27 | INFO | get_popularity |   [EM_01] Searching: Lose Yourself
15:59:27 | INFO | get_popularity |     ✓ Found: 'Lose Yourself' | popularity=81
15:59:28 | INFO | get_popularity |   [EM_02] Searching: Stan
15:59:28 | INFO | get_popularity |     ✓ Found: 'Stan' | popularity=83
15:59:28 | INFO | get_popularity |   [EM_03] Searching: The Real Slim Shady
15:59:29 | INFO | get_popularity |     ✓ Found: 'The Real Slim Shady' | popularity=87
15:59:29 | INFO | get_popularity |   [EM_04] Searching: Without Me
15:59:29 | INFO | get_popularity |     ✓ Found: 'Without Me' | popularity=90
15:59:30 | INFO | get_popularity |   [EM_05] Searching: Not Afraid
15:59:30 | INFO | get_popularity |     ✓ Found: 'Not Afraid' | popularity=81
15:59:30 | INFO | get_popularity |   [EM_06] Searching: Love The Way You Lie
15:59:31 | INFO | get_popularity |     ✓ Found: 'Love The Way You Lie' | popularity=89
15:59:31 | INFO | get_popularity |   [EM_07] Searching: Rap God
15:59:32 | INFO | get_popularity |     ✓ Found: 'Rap God' | popularity=76
15:59:32 | INFO | get_popularity |   [EM_08] Searching: River
15:59:32 | INFO | get_popularity |     ✓ Found: 'River (feat. Ed Sheeran)' | popularity=74
15:59:32 | INFO | get_popularity |   [EM_09] Searching: Cleanin Out My Closet
15:59:33 | INFO | get_popularity |     ✓ Found: 'Cleanin' Out My Closet' | popularity=75
15:59:33 | INFO | get_popularity |   [EM_10] Searching: When I'm Gone
15:59:33 | INFO | get_popularity |     ✓ Found: 'When I'm Gone' | popularity=65
15:59:34 | INFO | get_popularity |   [EM_11] Searching: Mockingbird
15:59:34 | INFO | get_popularity |     ✓ Found: 'Mockingbird' | popularity=88
15:59:34 | INFO | get_popularity |   [EM_12] Searching: Beautiful
15:59:35 | INFO | get_popularity |     ✓ Found: 'Beautiful' | popularity=72
15:59:35 | INFO | get_popularity |
───────────────────────────────────────────────────────  Tyler, the Creator
15:59:35 | INFO | get_popularity |   [TC2_01] Searching: See You Again
15:59:35 | INFO | get_popularity |     ✓ Found: 'See You Again (feat. Kali Uchis)' | popularity=91
15:59:36 | INFO | get_popularity |   [TC2_02] Searching: EARFQUAKE
15:59:36 | INFO | get_popularity |     ✓ Found: 'EARFQUAKE' | popularity=80
15:59:37 | INFO | get_popularity |   [TC2_03] Searching: Enjoy Right Now Today
15:59:37 | INFO | get_popularity |     ✓ Found: 'Enjoy Right Now, Today' | popularity=56
15:59:37 | INFO | get_popularity |   [TC2_04] Searching: I THINK
15:59:37 | INFO | get_popularity |     ✓ Found: 'I THINK' | popularity=73
15:59:38 | INFO | get_popularity |   [TC2_05] Searching: NEW MAGIC WAND
15:59:38 | INFO | get_popularity |     ✓ Found: 'NEW MAGIC WAND' | popularity=79
15:59:38 | INFO | get_popularity |   [TC2_06] Searching: WUSYANAME
15:59:39 | INFO | get_popularity |     ✓ Found: 'WUSYANAME (feat. Youngboy Never Broke Again & Ty Dolla $ign)' | popularity=71
15:59:39 | INFO | get_popularity |   [TC2_07] Searching: Lumberjack
15:59:39 | INFO | get_popularity |     ✓ Found: 'LUMBERJACK' | popularity=59
15:59:40 | INFO | get_popularity |   [TC2_08] Searching: 911 / Mr. Lonely
16:01:29 | WARNING | get_popularity |   Spotify search error: HTTPSConnectionPool(host='api.spotify.com', port=443): Read timed out. (read timeout=5)
16:01:29 | WARNING | get_popularity |     ✗ Not found on Spotify
16:01:29 | INFO | get_popularity |   [TC2_09] Searching: Who Dat Boy
16:01:31 | WARNING | get_popularity |   Spotify search error: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/search?q=track%3AWho+Dat+Boy+artist%3ATyler%2C+the+Creator&limit=10&offset=0&type=track (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x11ca9d450>: Failed to resolve 'api.spotify.com' ([Errno 8] nodename nor servname provided, or not known)"))
16:01:31 | WARNING | get_popularity |     ✗ Not found on Spotify
16:01:31 | INFO | get_popularity |   [TC2_10] Searching: Gone Gone / Thank You
16:01:33 | WARNING | get_popularity |   Spotify search error: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/search?q=track%3AGone+Gone+%2F+Thank+You+artist%3ATyler%2C+the+Creator&limit=10&offset=0&type=track (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x11ca9f890>: Failed to resolve 'api.spotify.com' ([Errno 8] nodename nor servname provided, or not known)"))
16:01:33 | WARNING | get_popularity |     ✗ Not found on Spotify
16:01:33 | INFO | get_popularity |   [TC2_11] Searching: Foreword
16:01:35 | WARNING | get_popularity |   Spotify search error: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/search?q=track%3AForeword+artist%3ATyler%2C+the+Creator&limit=10&offset=0&type=track (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x11ca9d6d0>: Failed to resolve 'api.spotify.com' ([Errno 8] nodename nor servname provided, or not known)"))
16:01:35 | WARNING | get_popularity |     ✗ Not found on Spotify
16:01:35 | INFO | get_popularity |   [TC2_12] Searching: MASSA
16:01:37 | WARNING | get_popularity |   Spotify search error: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/search?q=track%3AMASSA+artist%3ATyler%2C+the+Creator&limit=10&offset=0&type=track (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x11cc50190>: Failed to resolve 'api.spotify.com' ([Errno 8] nodename nor servname provided, or not known)"))
16:01:37 | WARNING | get_popularity |     ✗ Not found on Spotify
16:01:37 | INFO | get_popularity |
───────────────────────────────────────────────────────  Mac Miller
16:01:37 | INFO | get_popularity |   [MM_01] Searching: Self Care
16:01:39 | WARNING | get_popularity |   Spotify search error: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/search?q=track%3ASelf+Care+artist%3AMac+Miller&limit=10&offset=0&type=track (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x11cc50cd0>: Failed to resolve 'api.spotify.com' ([Errno 8] nodename nor servname provided, or not known)"))
16:01:39 | WARNING | get_popularity |     ✗ Not found on Spotify
16:01:39 | INFO | get_popularity |   [MM_02] Searching: Small Worlds
16:01:40 | WARNING | get_popularity |   Spotify search error: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/search?q=track%3ASmall+Worlds+artist%3AMac+Miller&limit=10&offset=0&type=track (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x11cc51810>: Failed to resolve 'api.spotify.com' ([Errno 8] nodename nor servname provided, or not known)"))
16:01:40 | WARNING | get_popularity |     ✗ Not found on Spotify
16:01:40 | INFO | get_popularity |   [MM_03] Searching: Circles
16:01:42 | WARNING | get_popularity |   Spotify search error: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/search?q=track%3ACircles+artist%3AMac+Miller&limit=10&offset=0&type=track (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x11cc53250>: Failed to resolve 'api.spotify.com' ([Errno 8] nodename nor servname provided, or not known)"))
16:01:42 | WARNING | get_popularity |     ✗ Not found on Spotify
16:01:42 | INFO | get_popularity |   [MM_04] Searching: 2009
16:01:44 | WARNING | get_popularity |   Spotify search error: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/search?q=track%3A2009+artist%3AMac+Miller&limit=10&offset=0&type=track (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x11ca9cf50>: Failed to resolve 'api.spotify.com' ([Errno 8] nodename nor servname provided, or not known)"))
16:01:44 | WARNING | get_popularity |     ✗ Not found on Spotify
16:01:44 | INFO | get_popularity |   [MM_05] Searching: Objects in the Mirror
16:01:46 | WARNING | get_popularity |   Spotify search error: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/search?q=track%3AObjects+in+the+Mirror+artist%3AMac+Miller&limit=10&offset=0&type=track (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x11ca9d310>: Failed to resolve 'api.spotify.com' ([Errno 8] nodename nor servname provided, or not known)"))
16:01:46 | WARNING | get_popularity |     ✗ Not found on Spotify
16:01:46 | INFO | get_popularity |   [MM_06] Searching: Diablo
16:01:49 | INFO | get_popularity |     ✓ Found: 'Diablo' | popularity=65
16:01:50 | INFO | get_popularity |   [MM_07] Searching: Programs
16:01:50 | INFO | get_popularity |     ✓ Found: 'Programs' | popularity=66
16:01:50 | INFO | get_popularity |   [MM_08] Searching: Dunno
16:01:51 | INFO | get_popularity |     ✓ Found: 'Dunno' | popularity=68
16:01:51 | INFO | get_popularity |   [MM_09] Searching: Come Back to Earth
16:01:52 | INFO | get_popularity |     ✓ Found: 'Come Back to Earth' | popularity=81
16:01:52 | INFO | get_popularity |   [MM_10] Searching: Good News
16:01:52 | INFO | get_popularity |     ✓ Found: 'Good News' | popularity=71
16:01:53 | INFO | get_popularity |   [MM_11] Searching: What's the Use?
16:01:53 | INFO | get_popularity |     ✓ Found: 'What's the Use?' | popularity=72
16:01:53 | INFO | get_popularity |   [MM_12] Searching: Grand Finale
16:01:54 | INFO | get_popularity |     ✓ Found: 'Grand Finale' | popularity=53
16:01:54 | INFO | get_popularity |
───────────────────────────────────────────────────────  Chance the Rapper
16:01:54 | INFO | get_popularity |   [CH_01] Searching: Blessings
16:01:54 | INFO | get_popularity |     ✓ Found: 'Blessings (feat. Jamila Woods)' | popularity=53
16:01:54 | INFO | get_popularity |   [CH_02] Searching: No Problem
16:01:55 | INFO | get_popularity |     ✓ Found: 'No Problem (feat. Lil Wayne & 2 Chainz)' | popularity=66
16:01:55 | INFO | get_popularity |   [CH_03] Searching: Same Drugs
16:01:55 | INFO | get_popularity |     ✓ Found: 'Same Drugs' | popularity=58
16:01:56 | INFO | get_popularity |   [CH_04] Searching: Angels
16:01:56 | INFO | get_popularity |     ✓ Found: 'Angels (feat. Saba)' | popularity=54
16:01:56 | INFO | get_popularity |   [CH_05] Searching: Paranoia
16:01:56 | INFO | get_popularity |     ✓ Found: 'Paranoia' | popularity=50
16:01:57 | INFO | get_popularity |   [CH_06] Searching: Sunday Candy
16:01:57 | INFO | get_popularity |     ✓ Found: 'Cocoa Butter Kisses' | popularity=58
16:01:58 | INFO | get_popularity |   [CH_07] Searching: Favorite Song
16:01:58 | INFO | get_popularity |     ✓ Found: 'Favorite Song' | popularity=60
16:01:58 | INFO | get_popularity |   [CH_08] Searching: All We Got
16:01:59 | INFO | get_popularity |     ✓ Found: 'All We Got (feat. Kanye West & Chicago Children's Choir)' | popularity=58
16:01:59 | INFO | get_popularity |   [CH_09] Searching: Cocoa Butter Kisses
16:01:59 | INFO | get_popularity |     ✓ Found: 'Cocoa Butter Kisses' | popularity=58
16:02:00 | INFO | get_popularity |   [CH_10] Searching: Smoke Again
16:02:00 | INFO | get_popularity |     ✓ Found: 'Smoke Again' | popularity=50
16:02:00 | INFO | get_popularity |   [CH_11] Searching: Hot Shower
16:02:01 | INFO | get_popularity |     ✓ Found: 'Hot Shower' | popularity=56
16:02:01 | INFO | get_popularity |   [CH_12] Searching: I Might Need Security
16:02:01 | INFO | get_popularity |     ✓ Found: 'I Might Need Security' | popularity=48
16:02:02 | INFO | get_popularity |
───────────────────────────────────────────────────────  Nas
16:02:02 | INFO | get_popularity |   [NS_01] Searching: N.Y. State of Mind
16:02:02 | INFO | get_popularity |     ✓ Found: 'N.Y. State of Mind' | popularity=73
16:02:02 | INFO | get_popularity |   [NS_02] Searching: The World Is Yours
16:02:03 | INFO | get_popularity |     ✓ Found: 'The World Is Yours' | popularity=70
16:02:03 | INFO | get_popularity |   [NS_03] Searching: One Love
16:02:03 | INFO | get_popularity |     ✓ Found: 'One Love (feat. Q-Tip)' | popularity=57
16:02:04 | INFO | get_popularity |   [NS_04] Searching: If I Ruled the World
16:02:04 | INFO | get_popularity |     ✓ Found: 'If I Ruled the World (Imagine That) (feat. Lauryn Hill)' | popularity=71
16:02:04 | INFO | get_popularity |   [NS_05] Searching: Hate Me Now
16:02:05 | INFO | get_popularity |     ✓ Found: 'Hate Me Now (feat. Diddy)' | popularity=58
16:02:05 | INFO | get_popularity |   [NS_06] Searching: One Mic
16:02:05 | INFO | get_popularity |     ✓ Found: 'One Mic' | popularity=51
16:02:06 | INFO | get_popularity |   [NS_07] Searching: Made You Look
16:02:06 | INFO | get_popularity |     ✓ Found: 'Made You Look' | popularity=58
16:02:06 | INFO | get_popularity |   [NS_08] Searching: Daughters
16:02:07 | INFO | get_popularity |     ✓ Found: 'Daughters' | popularity=31
16:02:07 | INFO | get_popularity |   [NS_09] Searching: Illmatic
16:02:08 | INFO | get_popularity |     ✓ Found: 'N.Y. State of Mind' | popularity=73
16:02:08 | INFO | get_popularity |   [NS_10] Searching: Represent
16:02:09 | INFO | get_popularity |     ✓ Found: 'Represent' | popularity=65
16:02:09 | INFO | get_popularity |   [NS_11] Searching: Life's a Bitch
16:02:09 | INFO | get_popularity |     ✓ Found: 'Life's a Bitch (feat. AZ & Olu Dara)' | popularity=64
16:02:10 | INFO | get_popularity |   [NS_12] Searching: Cherry Wine
16:02:10 | INFO | get_popularity |     ✓ Found: 'Cherry Wine' | popularity=49
16:02:10 | INFO | get_popularity |
───────────────────────────────────────────────────────  Childish Gambino
16:02:10 | INFO | get_popularity |   [CG_01] Searching: Redbone
16:02:11 | INFO | get_popularity |     ✓ Found: 'Redbone' | popularity=84
16:02:11 | INFO | get_popularity |   [CG_02] Searching: This Is America
16:06:25 | WARNING | get_popularity |   Spotify search error: HTTPSConnectionPool(host='api.spotify.com', port=443): Read timed out. (read timeout=5)
16:06:25 | WARNING | get_popularity |     ✗ Not found on Spotify
16:06:25 | INFO | get_popularity |   [CG_03] Searching: 3005
16:06:30 | WARNING | get_popularity |   Spotify search error: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/search?q=track%3A3005+artist%3AChildish+Gambino&limit=10&offset=0&type=track (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x11ca9de50>: Failed to resolve 'api.spotify.com' ([Errno 8] nodename nor servname provided, or not known)"))
16:06:30 | WARNING | get_popularity |     ✗ Not found on Spotify
16:06:30 | INFO | get_popularity |   [CG_04] Searching: Sober
16:06:32 | WARNING | get_popularity |   Spotify search error: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/search?q=track%3ASober+artist%3AChildish+Gambino&limit=10&offset=0&type=track (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x11ca9e850>: Failed to resolve 'api.spotify.com' ([Errno 8] nodename nor servname provided, or not known)"))
16:06:32 | WARNING | get_popularity |     ✗ Not found on Spotify
16:06:32 | INFO | get_popularity |   [CG_05] Searching: Sweatpants
16:06:34 | WARNING | get_popularity |   Spotify search error: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/search?q=track%3ASweatpants+artist%3AChildish+Gambino&limit=10&offset=0&type=track (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x11ca9d810>: Failed to resolve 'api.spotify.com' ([Errno 8] nodename nor servname provided, or not known)"))
16:06:34 | WARNING | get_popularity |     ✗ Not found on Spotify
16:06:34 | INFO | get_popularity |   [CG_06] Searching: V. 3005 (Beach Picnic Version)
16:06:36 | WARNING | get_popularity |   Spotify search error: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/search?q=track%3AV.+3005+%28Beach+Picnic+Version%29+artist%3AChildish+Gambino&limit=10&offset=0&type=track (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x11ca9f390>: Failed to resolve 'api.spotify.com' ([Errno 8] nodename nor servname provided, or not known)"))
16:06:36 | WARNING | get_popularity |     ✗ Not found on Spotify
16:06:36 | INFO | get_popularity |   [CG_07] Searching: Me and Your Mama
16:06:37 | WARNING | get_popularity |   Spotify search error: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/search?q=track%3AMe+and+Your+Mama+artist%3AChildish+Gambino&limit=10&offset=0&type=track (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x11ca9d1d0>: Failed to resolve 'api.spotify.com' ([Errno 8] nodename nor servname provided, or not known)"))
16:06:37 | WARNING | get_popularity |     ✗ Not found on Spotify
16:06:37 | INFO | get_popularity |   [CG_08] Searching: Terrified
16:06:39 | WARNING | get_popularity |   Spotify search error: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/search?q=track%3ATerrified+artist%3AChildish+Gambino&limit=10&offset=0&type=track (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x11ca9ead0>: Failed to resolve 'api.spotify.com' ([Errno 8] nodename nor servname provided, or not known)"))
16:06:39 | WARNING | get_popularity |     ✗ Not found on Spotify
16:06:39 | INFO | get_popularity |   [CG_09] Searching: Heartbeat

Spotify match rate: 363/441 songs found
Not found: ['TC2_08', 'TC2_09', 'TC2_10', 'TC2_11', 'TC2_12', 'MM_01', 'MM_02', 'MM_03', 'MM_04', 'MM_05', 'CG_02', 'CG_03', 'CG_04', 'CG_05', 'CG_06', 'CG_07', 'CG_08', 'CG_09', 'CG_10', 'CG_11', 'CG_12', 'JI_01', 'JI_02', 'JI_03', 'JI_04', 'JI_05', 'JI_06', 'JI_07', 'JI_08', 'JI_09', 'JI_10', 'JI_11', 'JI_12', 'SS_01', 'SS_02', 'SS_03', 'SS_04', 'SS_05', 'KM_08', 'KM_09', 'KM_10', 'KM_11', 'KM_12', 'ES_06', 'ES_07', 'ES_08', 'ES_09', 'ES_10', 'ES_11', 'ES_12', 'BE_04', 'HS_11', 'HS_12', 'OR_01', 'OR_02', 'LCD_02', 'LCD_03', 'LCD_04', 'LCD_05', 'LCD_06', 'LCD_07', 'LCD_08', 'LCD_09', 'LCD_10', 'LCD_11', 'LCD_12', 'BN_01', 'BN_02', 'BN_03', 'BN_04', 'BN_05', 'BN_06', 'BN_07', 'BN_08', 'BN_09', 'BN_10', 'BN_11', 'BN_12']
Popularity — mean=65.1  sd=17.2  min=10  max=92

---
## Step 9 — Combine Results
Merges all model similarity scores, Spotify data, and segment results  
into a single flat CSV ready for the R analysis.  
**Output:** `results/master_results.csv`

In [11]:
combine_results = load_script("combine_results", "09_combine_results.py")

master_df = combine_results.combine()

print(f"\nmaster_results.csv — {master_df.shape[0]} rows × {master_df.shape[1]} columns")
master_df.head(10)

16:21:39 | INFO | combine_results | LMC data: MuLan=436, CLAP=436, MERT+SBERT=436
16:21:39 | INFO | combine_results | Spotify: 363 found
16:21:39 | INFO | combine_results | Segment data: 383 songs
16:21:39 | INFO | combine_results |
════════════════════════════════════════════════════════════
16:21:39 | INFO | combine_results | Master dataset: 441 songs across 34 artists
16:21:39 | INFO | combine_results |   With popularity:      363/441
16:21:39 | INFO | combine_results |   With MuLan LMC:       436/441
16:21:39 | INFO | combine_results |   With CLAP LMC:        436/441
16:21:39 | INFO | combine_results |   With MERT+SBERT LMC:  436/441
16:21:39 | INFO | combine_results |   With segment LMC:     383/441
16:21:39 | INFO | combine_results |
LMC descriptives (MuLan):
16:21:39 | INFO | combine_results | count    436.000000
mean       0.331827
std        0.093126
min        0.011440
25%        0.267559
50%        0.333394
75%        0.394678
max        0.643509
16:21:39 | INFO | combine_results |
Popularity descriptives:
16:21:39 | INFO | combine_results | count    363.000000
mean      65.093664
std       17.253458
min       10.000000
25%       53.000000
50%       69.000000
75%       79.500000
max       92.000000
16:21:39 | INFO | combine_results |
Songs per genre:
16:21:39 | INFO | combine_results | genre
hip-hop                   129
pop                       105
electronic                 66
country                    63
folk                       39
psychedelic-electronic     24
folk-rock                  15
16:21:39 | INFO | combine_results |
Songs per orientation:
16:21:39 | INFO | combine_results | orientation
narrative     246
production    195
16:21:39 | INFO | combine_results |
Complete cases (popularity + MuLan LMC): 359
16:21:39 | INFO | combine_results |
Master CSV saved → /Users/budge.13/Desktop/Music Analysis/results/master_results.csv
16:21:39 | INFO | combine_results | Shape: 441 rows × 43 columns

master_results.csv — 441 rows × 43 columns

,song_id,title,artist_name,artist_code,genre,orientation,popularity,lmc_mulan,lmc_clap,lmc_mert_sbert,...,lmc_clap_z,lmc_mert_sbert_z,narrative,genre_country,genre_electronic,genre_folk,genre_folk-rock,genre_hip-hop,genre_pop,genre_psychedelic-electronic
0,RTJ_01,Run the Jewels,Run the Jewels,RTJ,hip-hop,narrative,52.0,0.347461,0.209607,-0.114023,...,1.352596,-2.867184,1,False,False,False,False,True,False,False
1,RTJ_02,Banana Clipper,Run the Jewels,RTJ,hip-hop,narrative,42.0,0.335946,0.248445,-0.046507,...,1.741231,-0.631636,1,False,False,False,False,True,False,False
2,RTJ_03,36 Inch Chain,Run the Jewels,RTJ,hip-hop,narrative,10.0,0.382107,0.426227,-0.019562,...,3.520206,0.260584,1,False,False,False,False,True,False,False
3,RTJ_04,DDHF,Run the Jewels,RTJ,hip-hop,narrative,38.0,0.337209,0.146885,-0.040884,...,0.724974,-0.445425,1,False,False,False,False,True,False,False
4,RTJ_05,Sea Legs,Run the Jewels,RTJ,hip-hop,narrative,38.0,0.377617,0.175617,-0.090214,...,1.012478,-2.078830,1,False,False,False,False,True,False,False
5,RTJ_06,Job Well Done,Run the Jewels,RTJ,hip-hop,narrative,32.0,0.338646,0.136837,-0.044451,...,0.624422,-0.563554,1,False,False,False,False,True,False,False
6,RTJ_07,No Come Down,Run the Jewels,RTJ,hip-hop,narrative,32.0,0.492247,0.235483,-0.029966,...,1.611525,-0.083923,1,False,False,False,False,True,False,False
7,RTJ_08,Get It,Run the Jewels,RTJ,hip-hop,narrative,40.0,0.416955,0.146924,-0.006813,...,0.725357,0.682715,1,False,False,False,False,True,False,False
8,RTJ_09,Twin Hype Back,Run the Jewels,RTJ,hip-hop,narrative,29.0,0.214881,0.179880,-0.052160,...,1.055137,-0.818791,1,False,False,False,False,True,False,False
9,RTJ_10,A Christmas Fucking Miracle,Run the Jewels,RTJ,hip-hop,narrative,36.0,0.394566,0.283586,-0.062443,...,2.092873,-1.159304,1,False,False,False,False,True,False,False

---
## Step 10 - Lyrics over Time

In [12]:
# ── Step 10: Lyric Timeline ───────────────────────────────────────────────────
lyric_timeline = load_script("lyric_timeline", "10_lyric_timeline.py")

timeline_csv = lyric_timeline.run_lyric_timeline(
    device        = device,
    force         = False,
    artist_filter = None,   # e.g. ["KL", "GD"] to test on a subset first
)

import pandas as pd
tl = pd.read_csv(timeline_csv)
print(f"Timeline: {len(tl):,} lines across {tl['song_id'].nunique()} songs")
print(f"Mean LMC: {tl['lmc'].mean():.4f}  |  SD: {tl['lmc'].std():.4f}")
tl.head(10)

09:44:46 | INFO | lyric_timeline | Processing 436 songs...
09:44:46 | INFO | lyric_timeline | Loading MuQ-MuLan...
09:44:46 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/OpenMuQ/MuQ-MuLan-large/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
09:44:46 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/OpenMuQ/MuQ-MuLan-large/2e01c796b71dca71b45251384c04cd7b237c9020/config.json "HTTP/1.1 200 OK"
09:44:46 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/OpenMuQ/MuQ-large-msd-iter/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
09:44:46 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/OpenMuQ/MuQ-large-msd-iter/0562a57814f6f8bbd9fdea0a25921a2fce1a841a/config.json "HTTP/1.1 200 OK"
/opt/anaconda3/lib/python3.13/site-packages/torch/nn/utils/weight_norm.py:144: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)
09:44:47 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/OpenMuQ/MuQ-large-msd-iter/resolve/main/model.safetensors "HTTP/1.1 302 Found"
09:44:49 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/xlm-roberta-base/resolve/main/config.json "HTTP/1.1 200 OK"
09:44:49 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/xlm-roberta-base/resolve/main/model.safetensors "HTTP/1.1 302 Found"

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

XLMRobertaModel LOAD REPORT from: xlm-roberta-base
Key                       | Status     |  |
--------------------------+------------+--+-
lm_head.layer_norm.weight | UNEXPECTED |  |
lm_head.dense.weight      | UNEXPECTED |  |
lm_head.bias              | UNEXPECTED |  |
lm_head.dense.bias        | UNEXPECTED |  |
lm_head.layer_norm.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
09:44:50 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/OpenMuQ/MuQ-MuLan-large/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"
09:44:50 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/OpenMuQ/MuQ-MuLan-large/resolve/main/pytorch_model.bin "HTTP/1.1 302 Found"
09:45:52 | INFO | lyric_timeline | Loading WhisperX on cpu...
09:45:52 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/Systran/faster-whisper-base/revision/main "HTTP/1.1 200 OK"

2026-04-21 09:45:53 - whisperx.asr - INFO - No language specified, language will be detected for each audio file (increases inference time)
2026-04-21 09:45:53 - whisperx.vads.pyannote - INFO - Performing voice activity detection using Pyannote...

INFO: Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.1. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../opt/anaconda3/lib/python3.13/site-packages/whisperx/assets/pytorch_model.bin`
09:45:54 | INFO | lightning.pytorch.utilities.migration.utils | Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.1. To apply the upgrade to your files permanently, run `python -m lightning.pytorch.utilities.upgrade_checkpoint ../../../../opt/anaconda3/lib/python3.13/site-packages/whisperx/assets/pytorch_model.bin`
09:45:54 | INFO | lyric_timeline |
[1/436] RTJ_01 — Run the Jewels
python(57372) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 09:46:03 - whisperx.asr - INFO - Detected language: en (0.88) in first 30s of audio

09:46:13 | INFO | lyric_timeline |   [RTJ_01] 72 lines, 321 WhisperX words
09:46:23 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/xlm-roberta-base/resolve/main/config.json "HTTP/1.1 200 OK"
09:46:23 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/xlm-roberta-base/resolve/main/tokenizer_config.json "HTTP/1.1 200 OK"
09:46:23 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/xlm-roberta-base/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 307 Temporary Redirect"
09:46:23 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/FacebookAI/xlm-roberta-base/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
09:46:23 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/xlm-roberta-base/tree/main?recursive=true&expand=false "HTTP/1.1 307 Temporary Redirect"
09:46:23 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/FacebookAI/xlm-roberta-base/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
09:46:26 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/xlm-roberta-base "HTTP/1.1 307 Temporary Redirect"
09:46:26 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/FacebookAI/xlm-roberta-base "HTTP/1.1 200 OK"
09:46:28 | INFO | lyric_timeline |   [RTJ_01] 2 lines matched and embedded
09:46:28 | INFO | lyric_timeline |
[2/436] RTJ_02 — Run the Jewels
python(57462) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 09:46:35 - whisperx.asr - INFO - Detected language: en (0.79) in first 30s of audio

09:46:43 | INFO | lyric_timeline |   [RTJ_02] 55 lines, 338 WhisperX words
09:46:45 | INFO | lyric_timeline |   [RTJ_02] 1 lines matched and embedded
09:46:45 | INFO | lyric_timeline |
[3/436] RTJ_03 — Run the Jewels
python(57475) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 09:46:50 - whisperx.asr - INFO - Detected language: en (0.94) in first 30s of audio

09:47:01 | INFO | lyric_timeline |   [RTJ_03] 64 lines, 438 WhisperX words
09:47:04 | INFO | lyric_timeline |   [RTJ_03] 2 lines matched and embedded
09:47:04 | INFO | lyric_timeline |
[4/436] RTJ_04 — Run the Jewels
python(57483) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 09:47:11 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

09:47:16 | INFO | lyric_timeline |   [RTJ_04] 44 lines, 194 WhisperX words
09:47:16 | INFO | lyric_timeline |   [RTJ_04] 0 lines matched and embedded
09:47:16 | INFO | lyric_timeline |
[5/436] RTJ_05 — Run the Jewels
python(57492) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 09:47:23 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

09:47:36 | INFO | lyric_timeline |   [RTJ_05] 69 lines, 648 WhisperX words
09:47:42 | INFO | lyric_timeline |   [RTJ_05] 4 lines matched and embedded
09:47:42 | INFO | lyric_timeline |   Checkpoint saved (5/436 songs done)
09:47:42 | INFO | lyric_timeline |
[6/436] RTJ_06 — Run the Jewels
python(57493) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 09:47:48 - whisperx.asr - INFO - Detected language: en (0.98) in first 30s of audio

09:47:55 | INFO | lyric_timeline |   [RTJ_06] 43 lines, 245 WhisperX words
09:47:59 | INFO | lyric_timeline |   [RTJ_06] 5 lines matched and embedded
09:47:59 | INFO | lyric_timeline |
[7/436] RTJ_07 — Run the Jewels
python(57503) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 09:48:07 - whisperx.asr - INFO - Detected language: en (0.96) in first 30s of audio

09:48:13 | INFO | lyric_timeline |   [RTJ_07] 62 lines, 343 WhisperX words
09:48:18 | INFO | lyric_timeline |   [RTJ_07] 7 lines matched and embedded
09:48:18 | INFO | lyric_timeline |
[8/436] RTJ_08 — Run the Jewels
python(57511) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 09:48:25 - whisperx.asr - INFO - Detected language: en (0.89) in first 30s of audio

09:48:29 | INFO | lyric_timeline |   [RTJ_08] 45 lines, 97 WhisperX words
09:48:29 | INFO | lyric_timeline |   [RTJ_08] 0 lines matched and embedded
09:48:29 | INFO | lyric_timeline |
[9/436] RTJ_09 — Run the Jewels
python(57513) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 09:48:35 - whisperx.asr - INFO - Detected language: en (0.96) in first 30s of audio

09:48:45 | INFO | lyric_timeline |   [RTJ_09] 58 lines, 455 WhisperX words
09:48:52 | INFO | lyric_timeline |   [RTJ_09] 7 lines matched and embedded
09:48:52 | INFO | lyric_timeline |
[10/436] RTJ_10 — Run the Jewels
python(57515) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 09:49:02 - whisperx.asr - INFO - Detected language: en (0.67) in first 30s of audio

09:49:14 | INFO | lyric_timeline |   [RTJ_10] 65 lines, 537 WhisperX words
09:49:24 | INFO | lyric_timeline |   [RTJ_10] 9 lines matched and embedded
09:49:24 | INFO | lyric_timeline |   Checkpoint saved (10/436 songs done)
09:49:24 | INFO | lyric_timeline |
[11/436] RTJ_11 — Run the Jewels
python(57525) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 09:49:30 - whisperx.asr - INFO - Detected language: en (0.97) in first 30s of audio

09:49:38 | INFO | lyric_timeline |   [RTJ_11] 42 lines, 223 WhisperX words
09:49:38 | INFO | lyric_timeline |   [RTJ_11] 0 lines matched and embedded
09:49:38 | INFO | lyric_timeline |
[12/436] RTJ_12 — Run the Jewels
python(57526) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 09:49:47 - whisperx.asr - INFO - Detected language: en (0.92) in first 30s of audio

09:50:02 | INFO | lyric_timeline |   [RTJ_12] 78 lines, 533 WhisperX words
09:50:07 | INFO | lyric_timeline |   [RTJ_12] 1 lines matched and embedded
09:50:07 | INFO | lyric_timeline |
[13/436] RTJ_13 — Run the Jewels
python(57532) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 09:50:16 - whisperx.asr - INFO - Detected language: en (0.87) in first 30s of audio

09:50:24 | INFO | lyric_timeline |   [RTJ_13] 84 lines, 237 WhisperX words
09:50:27 | INFO | lyric_timeline |   [RTJ_13] 2 lines matched and embedded
09:50:27 | INFO | lyric_timeline |
[14/436] RTJ_14 — Run the Jewels
python(57533) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 09:50:33 - whisperx.asr - INFO - Detected language: en (0.52) in first 30s of audio

09:50:44 | INFO | lyric_timeline |   [RTJ_14] 44 lines, 342 WhisperX words
09:50:53 | INFO | lyric_timeline |   [RTJ_14] 12 lines matched and embedded
09:50:53 | INFO | lyric_timeline |
[15/436] RTJ_15 — Run the Jewels
python(57537) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 09:51:01 - whisperx.asr - INFO - Detected language: en (0.95) in first 30s of audio

09:51:07 | INFO | lyric_timeline |   [RTJ_15] 94 lines, 95 WhisperX words
09:51:13 | INFO | lyric_timeline |   [RTJ_15] 5 lines matched and embedded
09:51:13 | INFO | lyric_timeline |   Checkpoint saved (15/436 songs done)
09:51:13 | INFO | lyric_timeline |
[16/436] KL_01 — Kendrick Lamar
python(57542) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 09:51:19 - whisperx.asr - INFO - Detected language: en (0.96) in first 30s of audio

09:51:27 | INFO | lyric_timeline |   [KL_01] 67 lines, 288 WhisperX words
09:51:29 | INFO | lyric_timeline |   [KL_01] 4 lines matched and embedded
09:51:29 | INFO | lyric_timeline |
[17/436] KL_02 — Kendrick Lamar
python(57549) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 09:51:36 - whisperx.asr - INFO - Detected language: en (0.98) in first 30s of audio

09:51:47 | INFO | lyric_timeline |   [KL_02] 81 lines, 519 WhisperX words
09:51:51 | INFO | lyric_timeline |   [KL_02] 6 lines matched and embedded
09:51:51 | INFO | lyric_timeline |
[18/436] KL_03 — Kendrick Lamar
python(57555) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 09:51:58 - whisperx.asr - INFO - Detected language: en (0.85) in first 30s of audio

09:52:10 | INFO | lyric_timeline |   [KL_03] 94 lines, 545 WhisperX words
09:52:17 | INFO | lyric_timeline |   [KL_03] 13 lines matched and embedded
09:52:17 | INFO | lyric_timeline |
[19/436] KL_04 — Kendrick Lamar
python(57564) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 09:52:25 - whisperx.asr - INFO - Detected language: en (0.92) in first 30s of audio

09:52:36 | INFO | lyric_timeline |   [KL_04] 95 lines, 412 WhisperX words
09:52:36 | INFO | lyric_timeline |   [KL_04] 0 lines matched and embedded
09:52:36 | INFO | lyric_timeline |
[20/436] KL_05 — Kendrick Lamar
python(57568) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 09:52:48 - whisperx.asr - INFO - Detected language: tr (0.25) in first 30s of audio

09:52:54 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/mpoyraz/wav2vec2-xls-r-300m-cv7-turkish/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
09:52:54 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/mpoyraz/wav2vec2-xls-r-300m-cv7-turkish/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
09:52:54 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/mpoyraz/wav2vec2-xls-r-300m-cv7-turkish/resolve/main/chat_template.json "HTTP/1.1 404 Not Found"
09:52:54 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/mpoyraz/wav2vec2-xls-r-300m-cv7-turkish/resolve/main/chat_template.jinja "HTTP/1.1 404 Not Found"
09:52:55 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/mpoyraz/wav2vec2-xls-r-300m-cv7-turkish/resolve/main/audio_tokenizer_config.json "HTTP/1.1 404 Not Found"
09:52:55 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/mpoyraz/wav2vec2-xls-r-300m-cv7-turkish/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
09:52:55 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/mpoyraz/wav2vec2-xls-r-300m-cv7-turkish/resolve/main/preprocessor_config.json "HTTP/1.1 307 Temporary Redirect"
09:52:55 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mpoyraz/wav2vec2-xls-r-300m-cv7-turkish/708639f50559d7970f462e13ec64d3f059ca89f6/preprocessor_config.json "HTTP/1.1 200 OK"
09:52:55 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/mpoyraz/wav2vec2-xls-r-300m-cv7-turkish/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
09:52:55 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/mpoyraz/wav2vec2-xls-r-300m-cv7-turkish/resolve/main/preprocessor_config.json "HTTP/1.1 307 Temporary Redirect"
09:52:55 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mpoyraz/wav2vec2-xls-r-300m-cv7-turkish/708639f50559d7970f462e13ec64d3f059ca89f6/preprocessor_config.json "HTTP/1.1 200 OK"
09:52:55 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/mpoyraz/wav2vec2-xls-r-300m-cv7-turkish/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
09:52:55 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mpoyraz/wav2vec2-xls-r-300m-cv7-turkish/708639f50559d7970f462e13ec64d3f059ca89f6/config.json "HTTP/1.1 200 OK"
09:52:55 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/mpoyraz/wav2vec2-xls-r-300m-cv7-turkish/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
09:52:55 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mpoyraz/wav2vec2-xls-r-300m-cv7-turkish/708639f50559d7970f462e13ec64d3f059ca89f6/tokenizer_config.json "HTTP/1.1 200 OK"
09:52:55 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/mpoyraz/wav2vec2-xls-r-300m-cv7-turkish/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
09:52:55 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/mpoyraz/wav2vec2-xls-r-300m-cv7-turkish/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
09:52:55 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/mpoyraz/wav2vec2-xls-r-300m-cv7-turkish/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
09:52:55 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mpoyraz/wav2vec2-xls-r-300m-cv7-turkish/708639f50559d7970f462e13ec64d3f059ca89f6/config.json "HTTP/1.1 200 OK"
09:52:55 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/mpoyraz/wav2vec2-xls-r-300m-cv7-turkish/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"
09:52:55 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/mpoyraz/wav2vec2-xls-r-300m-cv7-turkish/resolve/main/model.safetensors.index.json "HTTP/1.1 404 Not Found"
09:52:55 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/mpoyraz/wav2vec2-xls-r-300m-cv7-turkish/resolve/main/pytorch_model.bin "HTTP/1.1 302 Found"
09:52:55 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/mpoyraz/wav2vec2-xls-r-300m-cv7-turkish/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"
09:52:56 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/mpoyraz/wav2vec2-xls-r-300m-cv7-turkish "HTTP/1.1 200 OK"
09:52:56 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/mpoyraz/wav2vec2-xls-r-300m-cv7-turkish/commits/main "HTTP/1.1 200 OK"
09:52:56 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/mpoyraz/wav2vec2-xls-r-300m-cv7-turkish/discussions?p=0 "HTTP/1.1 200 OK"

Loading weights:   0%|          | 0/424 [00:00<?, ?it/s]

09:52:56 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/mpoyraz/wav2vec2-xls-r-300m-cv7-turkish/commits/refs%2Fpr%2F1 "HTTP/1.1 200 OK"
09:52:56 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/mpoyraz/wav2vec2-xls-r-300m-cv7-turkish/resolve/refs%2Fpr%2F1/model.safetensors.index.json "HTTP/1.1 404 Not Found"
09:52:56 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/mpoyraz/wav2vec2-xls-r-300m-cv7-turkish/resolve/refs%2Fpr%2F1/model.safetensors "HTTP/1.1 302 Found"
09:53:15 | INFO | lyric_timeline |   [KL_05] 115 lines, 316 WhisperX words
09:53:15 | INFO | lyric_timeline |   [KL_05] 0 lines matched and embedded
09:53:15 | INFO | lyric_timeline |   Checkpoint saved (20/436 songs done)
09:53:15 | INFO | lyric_timeline |
[21/436] KL_06 — Kendrick Lamar
python(57574) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 09:53:26 - whisperx.asr - INFO - Detected language: en (0.97) in first 30s of audio

09:53:42 | INFO | lyric_timeline |   [KL_06] 125 lines, 783 WhisperX words
09:53:51 | INFO | lyric_timeline |   [KL_06] 6 lines matched and embedded
09:53:51 | INFO | lyric_timeline |
[22/436] KL_07 — Kendrick Lamar
python(57583) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 09:53:58 - whisperx.asr - INFO - Detected language: en (0.65) in first 30s of audio

09:54:07 | INFO | lyric_timeline |   [KL_07] 67 lines, 327 WhisperX words
09:54:12 | INFO | lyric_timeline |   [KL_07] 6 lines matched and embedded
09:54:12 | INFO | lyric_timeline |
[23/436] KL_08 — Kendrick Lamar
python(57587) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 09:54:21 - whisperx.asr - INFO - Detected language: en (0.91) in first 30s of audio

09:54:31 | INFO | lyric_timeline |   [KL_08] 91 lines, 514 WhisperX words
09:54:38 | INFO | lyric_timeline |   [KL_08] 10 lines matched and embedded
09:54:38 | INFO | lyric_timeline |
[24/436] KL_09 — Kendrick Lamar
python(57588) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 09:54:50 - whisperx.asr - INFO - Detected language: en (0.75) in first 30s of audio

09:55:04 | INFO | lyric_timeline |   [KL_09] 75 lines, 718 WhisperX words
09:55:22 | INFO | lyric_timeline |   [KL_09] 27 lines matched and embedded
09:55:22 | INFO | lyric_timeline |
[25/436] KL_10 — Kendrick Lamar
python(57599) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 09:55:32 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

09:55:48 | INFO | lyric_timeline |   [KL_10] 89 lines, 745 WhisperX words
09:55:52 | INFO | lyric_timeline |   [KL_10] 5 lines matched and embedded
09:55:52 | INFO | lyric_timeline |   Checkpoint saved (25/436 songs done)
09:55:52 | INFO | lyric_timeline |
[26/436] KL_11 — Kendrick Lamar
python(57604) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 09:56:02 - whisperx.asr - INFO - Detected language: en (0.86) in first 30s of audio

09:56:14 | INFO | lyric_timeline |   [KL_11] 96 lines, 449 WhisperX words
09:56:24 | INFO | lyric_timeline |   [KL_11] 10 lines matched and embedded
09:56:24 | INFO | lyric_timeline |
[27/436] KL_12 — Kendrick Lamar
python(57694) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 09:56:32 - whisperx.asr - INFO - Detected language: en (0.85) in first 30s of audio

09:56:42 | INFO | lyric_timeline |   [KL_12] 129 lines, 454 WhisperX words
09:56:46 | INFO | lyric_timeline |   [KL_12] 2 lines matched and embedded
09:56:46 | INFO | lyric_timeline |
[28/436] KL_13 — Kendrick Lamar
python(57695) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 09:56:54 - whisperx.asr - INFO - Detected language: en (0.81) in first 30s of audio

09:57:03 | INFO | lyric_timeline |   [KL_13] 76 lines, 275 WhisperX words
09:57:05 | INFO | lyric_timeline |   [KL_13] 2 lines matched and embedded
09:57:05 | INFO | lyric_timeline |
[29/436] KL_14 — Kendrick Lamar
python(57698) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 09:57:12 - whisperx.asr - INFO - Detected language: en (0.93) in first 30s of audio

09:57:19 | INFO | lyric_timeline |   [KL_14] 71 lines, 262 WhisperX words
09:57:27 | INFO | lyric_timeline |   [KL_14] 10 lines matched and embedded
09:57:27 | INFO | lyric_timeline |
[30/436] KL_15 — Kendrick Lamar
python(57707) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 09:57:33 - whisperx.asr - INFO - Detected language: en (0.98) in first 30s of audio

09:57:46 | INFO | lyric_timeline |   [KL_15] 55 lines, 492 WhisperX words
09:57:53 | INFO | lyric_timeline |   [KL_15] 10 lines matched and embedded
09:57:53 | INFO | lyric_timeline |   Checkpoint saved (30/436 songs done)
09:57:53 | INFO | lyric_timeline |
[31/436] JC_01 — J. Cole
python(57709) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 09:58:03 - whisperx.asr - INFO - Detected language: en (0.93) in first 30s of audio

09:58:18 | INFO | lyric_timeline |   [JC_01] 87 lines, 685 WhisperX words
09:58:33 | INFO | lyric_timeline |   [JC_01] 25 lines matched and embedded
09:58:33 | INFO | lyric_timeline |
[32/436] JC_02 — J. Cole
python(57711) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 09:58:41 - whisperx.asr - INFO - Detected language: es (0.50) in first 30s of audio

09:58:54 | INFO | lyric_timeline |   [JC_02] 59 lines, 581 WhisperX words
09:58:56 | INFO | lyric_timeline |   [JC_02] 2 lines matched and embedded
09:58:56 | INFO | lyric_timeline |
[33/436] JC_03 — J. Cole
python(57715) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 09:59:04 - whisperx.asr - INFO - Detected language: en (0.81) in first 30s of audio

09:59:18 | INFO | lyric_timeline |   [JC_03] 90 lines, 551 WhisperX words
09:59:24 | INFO | lyric_timeline |   [JC_03] 9 lines matched and embedded
09:59:24 | INFO | lyric_timeline |
[34/436] JC_04 — J. Cole
python(57717) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 09:59:32 - whisperx.asr - INFO - Detected language: en (0.94) in first 30s of audio

09:59:43 | INFO | lyric_timeline |   [JC_04] 84 lines, 581 WhisperX words
09:59:45 | INFO | lyric_timeline |   [JC_04] 1 lines matched and embedded
09:59:45 | INFO | lyric_timeline |
[35/436] JC_05 — J. Cole
python(57726) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 09:59:53 - whisperx.asr - INFO - Detected language: en (0.62) in first 30s of audio

10:00:06 | INFO | lyric_timeline |   [JC_05] 81 lines, 532 WhisperX words
10:00:18 | INFO | lyric_timeline |   [JC_05] 16 lines matched and embedded
10:00:18 | INFO | lyric_timeline |   Checkpoint saved (35/436 songs done)
10:00:18 | INFO | lyric_timeline |
[36/436] JC_06 — J. Cole
python(57731) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:00:29 - whisperx.asr - INFO - Detected language: en (0.88) in first 30s of audio

10:00:44 | INFO | lyric_timeline |   [JC_06] 77 lines, 609 WhisperX words
10:00:50 | INFO | lyric_timeline |   [JC_06] 7 lines matched and embedded
10:00:50 | INFO | lyric_timeline |
[37/436] JC_07 — J. Cole
python(57734) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:00:57 - whisperx.asr - INFO - Detected language: en (0.98) in first 30s of audio

10:01:10 | INFO | lyric_timeline |   [JC_07] 73 lines, 586 WhisperX words
10:01:17 | INFO | lyric_timeline |   [JC_07] 14 lines matched and embedded
10:01:17 | INFO | lyric_timeline |
[38/436] JC_08 — J. Cole
python(57742) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:01:27 - whisperx.asr - INFO - Detected language: en (0.94) in first 30s of audio

10:01:37 | INFO | lyric_timeline |   [JC_08] 78 lines, 527 WhisperX words
10:01:40 | INFO | lyric_timeline |   [JC_08] 3 lines matched and embedded
10:01:40 | INFO | lyric_timeline |
[39/436] JC_09 — J. Cole
python(57750) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:12:17 - whisperx.asr - INFO - Detected language: en (0.96) in first 30s of audio

10:12:27 | INFO | lyric_timeline |   [JC_09] 85 lines, 537 WhisperX words
10:12:39 | INFO | lyric_timeline |   [JC_09] 2 lines matched and embedded
10:12:39 | INFO | lyric_timeline |
[40/436] JC_10 — J. Cole
python(57920) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:12:49 - whisperx.asr - INFO - Detected language: en (0.94) in first 30s of audio

10:13:02 | INFO | lyric_timeline |   [JC_10] 53 lines, 650 WhisperX words
10:13:06 | INFO | lyric_timeline |   [JC_10] 2 lines matched and embedded
10:13:06 | INFO | lyric_timeline |   Checkpoint saved (40/436 songs done)
10:13:06 | INFO | lyric_timeline |
[41/436] JC_11 — J. Cole
python(57921) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:13:14 - whisperx.asr - INFO - Detected language: en (0.85) in first 30s of audio

10:13:22 | INFO | lyric_timeline |   [JC_11] 89 lines, 350 WhisperX words
10:13:26 | INFO | lyric_timeline |   [JC_11] 3 lines matched and embedded
10:13:26 | INFO | lyric_timeline |
[42/436] JC_12 — J. Cole
python(57924) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:13:30 - whisperx.asr - INFO - Detected language: en (0.76) in first 30s of audio

10:13:36 | INFO | lyric_timeline |   [JC_12] 25 lines, 140 WhisperX words
10:13:39 | INFO | lyric_timeline |   [JC_12] 2 lines matched and embedded
10:13:39 | INFO | lyric_timeline |
[43/436] JC_13 — J. Cole
python(57926) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:13:50 - whisperx.asr - INFO - Detected language: en (0.83) in first 30s of audio

10:14:02 | INFO | lyric_timeline |   [JC_13] 111 lines, 687 WhisperX words
10:14:12 | INFO | lyric_timeline |   [JC_13] 16 lines matched and embedded
10:14:12 | INFO | lyric_timeline |
[44/436] JC_14 — J. Cole
python(57934) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:14:21 - whisperx.asr - INFO - Detected language: en (0.52) in first 30s of audio

10:14:32 | INFO | lyric_timeline |   [JC_14] 79 lines, 437 WhisperX words
10:14:37 | INFO | lyric_timeline |   [JC_14] 5 lines matched and embedded
10:14:37 | INFO | lyric_timeline |
[45/436] JC_15 — J. Cole
python(57937) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:14:45 - whisperx.asr - INFO - Detected language: en (0.77) in first 30s of audio

10:14:54 | INFO | lyric_timeline |   [JC_15] 95 lines, 428 WhisperX words
10:15:00 | INFO | lyric_timeline |   [JC_15] 4 lines matched and embedded
10:15:00 | INFO | lyric_timeline |   Checkpoint saved (45/436 songs done)
10:15:00 | INFO | lyric_timeline |
[46/436] DR_01 — Drake
python(57942) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:15:07 - whisperx.asr - INFO - Detected language: en (0.98) in first 30s of audio
2026-04-21 10:15:14 - whisperx.alignment - WARNING - Failed to align segment (" It was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was and it was"): backtrack failed, resorting to original

10:15:18 | INFO | lyric_timeline |   [DR_01] 41 lines, 384 WhisperX words
10:15:20 | INFO | lyric_timeline |   [DR_01] 1 lines matched and embedded
10:15:21 | INFO | lyric_timeline |
[47/436] DR_02 — Drake
python(57944) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:15:29 - whisperx.asr - INFO - Detected language: en (0.82) in first 30s of audio

10:15:40 | INFO | lyric_timeline |   [DR_02] 63 lines, 394 WhisperX words
10:15:46 | INFO | lyric_timeline |   [DR_02] 8 lines matched and embedded
10:15:46 | INFO | lyric_timeline |
[48/436] DR_03 — Drake
python(57946) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:15:52 - whisperx.asr - INFO - Detected language: en (0.87) in first 30s of audio

10:15:58 | INFO | lyric_timeline |   [DR_03] 72 lines, 167 WhisperX words
10:16:03 | INFO | lyric_timeline |   [DR_03] 3 lines matched and embedded
10:16:03 | INFO | lyric_timeline |
[49/436] DR_04 — Drake
python(57955) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:16:13 - whisperx.asr - INFO - Detected language: en (0.48) in first 30s of audio

10:16:20 | INFO | lyric_timeline |   [DR_04] 37 lines, 222 WhisperX words
10:16:25 | INFO | lyric_timeline |   [DR_04] 4 lines matched and embedded
10:16:25 | INFO | lyric_timeline |
[50/436] DR_05 — Drake
python(57959) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:16:31 - whisperx.asr - INFO - Detected language: en (0.93) in first 30s of audio

10:16:40 | INFO | lyric_timeline |   [DR_05] 53 lines, 369 WhisperX words
10:16:45 | INFO | lyric_timeline |   [DR_05] 8 lines matched and embedded
10:16:45 | INFO | lyric_timeline |   Checkpoint saved (50/436 songs done)
10:16:45 | INFO | lyric_timeline |
[51/436] DR_06 — Drake
python(57960) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:16:55 - whisperx.asr - INFO - Detected language: en (0.79) in first 30s of audio

10:17:04 | INFO | lyric_timeline |   [DR_06] 57 lines, 326 WhisperX words
10:17:09 | INFO | lyric_timeline |   [DR_06] 3 lines matched and embedded
10:17:09 | INFO | lyric_timeline |
[52/436] DR_07 — Drake
python(57961) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:17:20 - whisperx.asr - INFO - Detected language: en (0.80) in first 30s of audio

10:17:31 | INFO | lyric_timeline |   [DR_07] 76 lines, 334 WhisperX words
10:17:36 | INFO | lyric_timeline |   [DR_07] 3 lines matched and embedded
10:17:36 | INFO | lyric_timeline |
[53/436] DR_08 — Drake
python(57965) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:17:44 - whisperx.asr - INFO - Detected language: en (0.87) in first 30s of audio

10:17:48 | INFO | lyric_timeline |   [DR_08] 46 lines, 63 WhisperX words
10:17:51 | INFO | lyric_timeline |   [DR_08] 1 lines matched and embedded
10:17:51 | INFO | lyric_timeline |
[54/436] DR_09 — Drake
python(57966) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:18:05 - whisperx.asr - INFO - Detected language: en (0.70) in first 30s of audio

10:18:17 | INFO | lyric_timeline |   [DR_09] 114 lines, 546 WhisperX words
10:18:23 | INFO | lyric_timeline |   [DR_09] 5 lines matched and embedded
10:18:23 | INFO | lyric_timeline |
[55/436] DR_10 — Drake
python(57977) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:18:32 - whisperx.asr - INFO - Detected language: en (0.91) in first 30s of audio

10:18:49 | INFO | lyric_timeline |   [DR_10] 86 lines, 784 WhisperX words
10:18:58 | INFO | lyric_timeline |   [DR_10] 11 lines matched and embedded
10:18:58 | INFO | lyric_timeline |   Checkpoint saved (55/436 songs done)
10:18:58 | INFO | lyric_timeline |
[56/436] DR_11 — Drake
python(57982) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:19:08 - whisperx.asr - INFO - Detected language: en (0.59) in first 30s of audio

10:19:23 | INFO | lyric_timeline |   [DR_11] 111 lines, 665 WhisperX words
10:19:28 | INFO | lyric_timeline |   [DR_11] 6 lines matched and embedded
10:19:28 | INFO | lyric_timeline |
[57/436] DR_12 — Drake
python(57985) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:19:38 - whisperx.asr - INFO - Detected language: en (0.93) in first 30s of audio

10:19:53 | INFO | lyric_timeline |   [DR_12] 82 lines, 621 WhisperX words
10:19:59 | INFO | lyric_timeline |   [DR_12] 4 lines matched and embedded
10:19:59 | INFO | lyric_timeline |
[58/436] EM_01 — Eminem
python(57991) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:20:10 - whisperx.asr - INFO - Detected language: en (0.42) in first 30s of audio

10:20:22 | INFO | lyric_timeline |   [EM_01] 83 lines, 530 WhisperX words
10:20:23 | INFO | lyric_timeline |   [EM_01] 2 lines matched and embedded
10:20:23 | INFO | lyric_timeline |
[59/436] EM_02 — Eminem
python(58000) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:20:37 - whisperx.asr - INFO - Detected language: ko (0.35) in first 30s of audio

10:20:47 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/kresnik/wav2vec2-large-xlsr-korean/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
10:20:47 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
10:20:47 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/chat_template.json "HTTP/1.1 404 Not Found"
10:20:47 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/chat_template.jinja "HTTP/1.1 404 Not Found"
10:20:47 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/audio_tokenizer_config.json "HTTP/1.1 404 Not Found"
10:20:47 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
10:20:47 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/preprocessor_config.json "HTTP/1.1 307 Temporary Redirect"
10:20:47 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/kresnik/wav2vec2-large-xlsr-korean/629c9a3501c10ba128bf3fa1eebb12af3be03f61/preprocessor_config.json "HTTP/1.1 200 OK"
10:20:48 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
10:20:48 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/preprocessor_config.json "HTTP/1.1 307 Temporary Redirect"
10:20:48 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/kresnik/wav2vec2-large-xlsr-korean/629c9a3501c10ba128bf3fa1eebb12af3be03f61/preprocessor_config.json "HTTP/1.1 200 OK"
10:20:48 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
10:20:48 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/kresnik/wav2vec2-large-xlsr-korean/629c9a3501c10ba128bf3fa1eebb12af3be03f61/config.json "HTTP/1.1 200 OK"
10:20:48 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
10:20:48 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/kresnik/wav2vec2-large-xlsr-korean/629c9a3501c10ba128bf3fa1eebb12af3be03f61/tokenizer_config.json "HTTP/1.1 200 OK"
10:20:48 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/kresnik/wav2vec2-large-xlsr-korean/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
10:20:48 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/kresnik/wav2vec2-large-xlsr-korean/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
10:20:48 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
10:20:48 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/kresnik/wav2vec2-large-xlsr-korean/629c9a3501c10ba128bf3fa1eebb12af3be03f61/config.json "HTTP/1.1 200 OK"
10:20:48 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/model.safetensors "HTTP/1.1 302 Found"

Loading weights:   0%|          | 0/424 [00:00<?, ?it/s]

10:21:09 | INFO | lyric_timeline |   [EM_02] 123 lines, 761 WhisperX words
10:21:16 | INFO | lyric_timeline |   [EM_02] 1 lines matched and embedded
10:21:16 | INFO | lyric_timeline |
[60/436] EM_03 — Eminem
python(58005) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:21:27 - whisperx.asr - INFO - Detected language: en (0.94) in first 30s of audio

10:21:37 | INFO | lyric_timeline |   [EM_03] 108 lines, 539 WhisperX words
10:21:40 | INFO | lyric_timeline |   [EM_03] 2 lines matched and embedded
10:21:40 | INFO | lyric_timeline |   Checkpoint saved (60/436 songs done)
10:21:40 | INFO | lyric_timeline |
[61/436] EM_04 — Eminem
python(58011) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:21:50 - whisperx.asr - INFO - Detected language: en (0.91) in first 30s of audio

10:22:05 | INFO | lyric_timeline |   [EM_04] 104 lines, 634 WhisperX words
10:22:08 | INFO | lyric_timeline |   [EM_04] 2 lines matched and embedded
10:22:08 | INFO | lyric_timeline |
[62/436] EM_05 — Eminem
python(58021) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:22:18 - whisperx.asr - INFO - Detected language: en (0.94) in first 30s of audio

10:22:30 | INFO | lyric_timeline |   [EM_05] 88 lines, 634 WhisperX words
10:22:34 | INFO | lyric_timeline |   [EM_05] 2 lines matched and embedded
10:22:34 | INFO | lyric_timeline |
[63/436] EM_06 — Eminem
python(58024) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:22:43 - whisperx.asr - INFO - Detected language: en (0.94) in first 30s of audio

10:22:58 | INFO | lyric_timeline |   [EM_06] 73 lines, 683 WhisperX words
10:23:06 | INFO | lyric_timeline |   [EM_06] 10 lines matched and embedded
10:23:06 | INFO | lyric_timeline |
[64/436] EM_07 — Eminem
python(58025) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:23:18 - whisperx.asr - INFO - Detected language: en (0.88) in first 30s of audio

10:23:44 | INFO | lyric_timeline |   [EM_07] 168 lines, 1400 WhisperX words
10:23:50 | INFO | lyric_timeline |   [EM_07] 6 lines matched and embedded
10:23:50 | INFO | lyric_timeline |
[65/436] EM_08 — Eminem
python(58030) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:23:58 - whisperx.asr - INFO - Detected language: en (0.91) in first 30s of audio

10:24:12 | INFO | lyric_timeline |   [EM_08] 83 lines, 678 WhisperX words
10:24:16 | INFO | lyric_timeline |   [EM_08] 3 lines matched and embedded
10:24:16 | INFO | lyric_timeline |   Checkpoint saved (65/436 songs done)
10:24:16 | INFO | lyric_timeline |
[66/436] EM_09 — Eminem
python(58124) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:24:26 - whisperx.asr - INFO - Detected language: en (0.94) in first 30s of audio

10:24:41 | INFO | lyric_timeline |   [EM_09] 76 lines, 615 WhisperX words
10:24:46 | INFO | lyric_timeline |   [EM_09] 7 lines matched and embedded
10:24:46 | INFO | lyric_timeline |
[67/436] EM_10 — Eminem
python(58130) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:24:55 - whisperx.asr - INFO - Detected language: en (0.92) in first 30s of audio

10:25:11 | INFO | lyric_timeline |   [EM_10] 86 lines, 780 WhisperX words
10:25:19 | INFO | lyric_timeline |   [EM_10] 9 lines matched and embedded
10:25:19 | INFO | lyric_timeline |
[68/436] EM_11 — Eminem
python(58141) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:25:27 - whisperx.asr - INFO - Detected language: en (0.97) in first 30s of audio

10:25:43 | INFO | lyric_timeline |   [EM_11] 89 lines, 815 WhisperX words
10:25:47 | INFO | lyric_timeline |   [EM_11] 4 lines matched and embedded
10:25:47 | INFO | lyric_timeline |
[69/436] EM_12 — Eminem
python(58144) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:26:02 - whisperx.asr - INFO - Detected language: en (0.40) in first 30s of audio

10:26:23 | INFO | lyric_timeline |   [EM_12] 141 lines, 1018 WhisperX words
10:26:34 | INFO | lyric_timeline |   [EM_12] 16 lines matched and embedded
10:26:34 | INFO | lyric_timeline |
[70/436] TC2_01 — Tyler, the Creator
python(58161) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:26:42 - whisperx.asr - INFO - Detected language: en (0.64) in first 30s of audio

10:26:49 | INFO | lyric_timeline |   [TC2_01] 55 lines, 225 WhisperX words
10:26:54 | INFO | lyric_timeline |   [TC2_01] 4 lines matched and embedded
10:26:54 | INFO | lyric_timeline |   Checkpoint saved (70/436 songs done)
10:26:54 | INFO | lyric_timeline |
[71/436] TC2_02 — Tyler, the Creator
python(58162) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:27:00 - whisperx.asr - INFO - Detected language: en (0.78) in first 30s of audio

10:27:08 | INFO | lyric_timeline |   [TC2_02] 56 lines, 196 WhisperX words
10:27:10 | INFO | lyric_timeline |   [TC2_02] 2 lines matched and embedded
10:27:10 | INFO | lyric_timeline |
[72/436] TC2_03 — Tyler, the Creator
python(58164) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:27:17 - whisperx.asr - INFO - Detected language: en (0.44) in first 30s of audio

10:27:22 | INFO | lyric_timeline |   [TC2_03] 1 lines, 26 WhisperX words
10:27:22 | INFO | lyric_timeline |   [TC2_03] 0 lines matched and embedded
10:27:22 | INFO | lyric_timeline |
[73/436] TC2_04 — Tyler, the Creator
python(58172) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:27:29 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

10:27:35 | INFO | lyric_timeline |   [TC2_04] 56 lines, 144 WhisperX words
10:27:35 | INFO | lyric_timeline |   [TC2_04] 0 lines matched and embedded
10:27:35 | INFO | lyric_timeline |
[74/436] TC2_05 — Tyler, the Creator
python(58176) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:27:41 - whisperx.asr - INFO - Detected language: en (0.99) in first 30s of audio

10:27:52 | INFO | lyric_timeline |   [TC2_05] 60 lines, 561 WhisperX words
10:28:03 | INFO | lyric_timeline |   [TC2_05] 15 lines matched and embedded
10:28:03 | INFO | lyric_timeline |
[75/436] TC2_06 — Tyler, the Creator
python(58177) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:28:07 - whisperx.asr - INFO - Detected language: en (0.85) in first 30s of audio

10:28:15 | INFO | lyric_timeline |   [TC2_06] 55 lines, 328 WhisperX words
10:28:25 | INFO | lyric_timeline |   [TC2_06] 1 lines matched and embedded
10:28:25 | INFO | lyric_timeline |   Checkpoint saved (75/436 songs done)
10:28:25 | INFO | lyric_timeline |
[76/436] TC2_07 — Tyler, the Creator
python(58198) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:28:31 - whisperx.asr - INFO - Detected language: en (0.97) in first 30s of audio

10:28:39 | INFO | lyric_timeline |   [TC2_07] 56 lines, 340 WhisperX words
10:28:41 | INFO | lyric_timeline |   [TC2_07] 4 lines matched and embedded
10:28:41 | INFO | lyric_timeline |
[77/436] TC2_08 — Tyler, the Creator
python(58200) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:37:19 - whisperx.asr - INFO - Detected language: en (0.83) in first 30s of audio

10:37:30 | INFO | lyric_timeline |   [TC2_08] 103 lines, 598 WhisperX words
10:37:48 | INFO | lyric_timeline |   [TC2_08] 6 lines matched and embedded
10:37:48 | INFO | lyric_timeline |
[78/436] TC2_09 — Tyler, the Creator
python(58361) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:41:52 - whisperx.asr - INFO - Detected language: en (0.48) in first 30s of audio

10:42:05 | INFO | lyric_timeline |   [TC2_09] 65 lines, 267 WhisperX words
10:42:17 | INFO | lyric_timeline |   [TC2_09] 4 lines matched and embedded
10:42:17 | INFO | lyric_timeline |
[79/436] TC2_10 — Tyler, the Creator
python(58518) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:50:36 - whisperx.asr - INFO - Detected language: en (0.85) in first 30s of audio

10:51:02 | INFO | lyric_timeline |   [TC2_10] 81 lines, 300 WhisperX words
10:51:55 | INFO | lyric_timeline |   [TC2_10] 8 lines matched and embedded
10:51:55 | INFO | lyric_timeline |
[80/436] TC2_11 — Tyler, the Creator
python(58796) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:52:13 - whisperx.asr - INFO - Detected language: en (0.84) in first 30s of audio

10:52:47 | INFO | lyric_timeline |   [TC2_11] 53 lines, 421 WhisperX words
10:53:01 | INFO | lyric_timeline |   [TC2_11] 7 lines matched and embedded
10:53:01 | INFO | lyric_timeline |   Checkpoint saved (80/436 songs done)
10:53:01 | INFO | lyric_timeline |
[81/436] TC2_12 — Tyler, the Creator
python(59159) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 10:58:59 - whisperx.asr - INFO - Detected language: en (0.98) in first 30s of audio

10:59:27 | INFO | lyric_timeline |   [TC2_12] 68 lines, 633 WhisperX words
11:00:17 | INFO | lyric_timeline |   [TC2_12] 10 lines matched and embedded
11:00:17 | INFO | lyric_timeline |
[82/436] MM_01 — Mac Miller
python(59488) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:00:46 - whisperx.asr - INFO - Detected language: en (0.60) in first 30s of audio

11:01:02 | INFO | lyric_timeline |   [MM_01] 86 lines, 178 WhisperX words
11:01:13 | INFO | lyric_timeline |   [MM_01] 1 lines matched and embedded
11:01:13 | INFO | lyric_timeline |
[83/436] MM_02 — Mac Miller
python(59782) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:01:38 - whisperx.asr - INFO - Detected language: en (0.97) in first 30s of audio

11:02:11 | INFO | lyric_timeline |   [MM_02] 68 lines, 497 WhisperX words
11:02:27 | INFO | lyric_timeline |   [MM_02] 4 lines matched and embedded
11:02:27 | INFO | lyric_timeline |
[84/436] MM_03 — Mac Miller
python(60146) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:03:43 - whisperx.asr - INFO - Detected language: en (0.33) in first 30s of audio

11:03:54 | INFO | lyric_timeline |   [MM_03] 17 lines, 150 WhisperX words
11:04:01 | INFO | lyric_timeline |   [MM_03] 3 lines matched and embedded
11:04:01 | INFO | lyric_timeline |
[85/436] MM_04 — Mac Miller
python(60256) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:04:41 - whisperx.asr - INFO - Detected language: en (0.60) in first 30s of audio

11:04:55 | INFO | lyric_timeline |   [MM_04] 68 lines, 556 WhisperX words
11:05:08 | INFO | lyric_timeline |   [MM_04] 4 lines matched and embedded
11:05:08 | INFO | lyric_timeline |   Checkpoint saved (85/436 songs done)
11:05:08 | INFO | lyric_timeline |
[86/436] MM_05 — Mac Miller
python(60528) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:05:18 - whisperx.asr - INFO - Detected language: en (0.93) in first 30s of audio

11:05:24 | INFO | lyric_timeline |   [MM_05] 59 lines, 201 WhisperX words
11:05:29 | INFO | lyric_timeline |   [MM_05] 3 lines matched and embedded
11:05:29 | INFO | lyric_timeline |
[87/436] MM_06 — Mac Miller
python(60558) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:05:35 - whisperx.asr - INFO - Detected language: en (0.98) in first 30s of audio

11:05:42 | INFO | lyric_timeline |   [MM_06] 61 lines, 208 WhisperX words
11:05:45 | INFO | lyric_timeline |   [MM_06] 2 lines matched and embedded
11:05:45 | INFO | lyric_timeline |
[88/436] MM_07 — Mac Miller
python(60560) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:05:51 - whisperx.asr - INFO - Detected language: en (0.95) in first 30s of audio

11:05:58 | INFO | lyric_timeline |   [MM_07] 53 lines, 206 WhisperX words
11:05:58 | INFO | lyric_timeline |   [MM_07] 0 lines matched and embedded
11:05:58 | INFO | lyric_timeline |
[89/436] MM_08 — Mac Miller
python(60562) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:06:06 - whisperx.asr - INFO - Detected language: en (0.80) in first 30s of audio

11:06:14 | INFO | lyric_timeline |   [MM_08] 38 lines, 318 WhisperX words
11:06:19 | INFO | lyric_timeline |   [MM_08] 3 lines matched and embedded
11:06:19 | INFO | lyric_timeline |
[90/436] MM_09 — Mac Miller
python(60564) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:06:26 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

11:06:33 | INFO | lyric_timeline |   [MM_09] 27 lines, 173 WhisperX words
11:06:43 | INFO | lyric_timeline |   [MM_09] 8 lines matched and embedded
11:06:43 | INFO | lyric_timeline |   Checkpoint saved (90/436 songs done)
11:06:43 | INFO | lyric_timeline |
[91/436] MM_10 — Mac Miller
python(60568) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:06:57 - whisperx.asr - INFO - Detected language: en (0.98) in first 30s of audio

11:07:05 | INFO | lyric_timeline |   [MM_10] 61 lines, 227 WhisperX words
11:07:10 | INFO | lyric_timeline |   [MM_10] 6 lines matched and embedded
11:07:10 | INFO | lyric_timeline |
[92/436] MM_11 — Mac Miller
python(60571) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:07:19 - whisperx.asr - INFO - Detected language: en (0.67) in first 30s of audio

11:07:29 | INFO | lyric_timeline |   [MM_11] 76 lines, 374 WhisperX words
11:07:34 | INFO | lyric_timeline |   [MM_11] 4 lines matched and embedded
11:07:34 | INFO | lyric_timeline |
[93/436] MM_12 — Mac Miller
python(60580) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:07:42 - whisperx.asr - INFO - Detected language: en (0.79) in first 30s of audio

11:07:50 | INFO | lyric_timeline |   [MM_12] 45 lines, 305 WhisperX words
11:07:53 | INFO | lyric_timeline |   [MM_12] 2 lines matched and embedded
11:07:53 | INFO | lyric_timeline |
[94/436] CH_01 — Chance the Rapper
python(60586) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:08:00 - whisperx.asr - INFO - Detected language: en (0.93) in first 30s of audio

11:08:11 | INFO | lyric_timeline |   [CH_01] 56 lines, 414 WhisperX words
11:08:17 | INFO | lyric_timeline |   [CH_01] 8 lines matched and embedded
11:08:17 | INFO | lyric_timeline |
[95/436] CH_02 — Chance the Rapper
python(60588) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:08:27 - whisperx.asr - INFO - Detected language: en (0.95) in first 30s of audio

11:08:45 | INFO | lyric_timeline |   [CH_02] 103 lines, 711 WhisperX words
11:08:51 | INFO | lyric_timeline |   [CH_02] 8 lines matched and embedded
11:08:51 | INFO | lyric_timeline |   Checkpoint saved (95/436 songs done)
11:08:51 | INFO | lyric_timeline |
[96/436] CH_03 — Chance the Rapper
python(60592) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:09:00 - whisperx.asr - INFO - Detected language: en (0.68) in first 30s of audio

11:09:12 | INFO | lyric_timeline |   [CH_03] 63 lines, 393 WhisperX words
11:09:17 | INFO | lyric_timeline |   [CH_03] 7 lines matched and embedded
11:09:17 | INFO | lyric_timeline |
[97/436] CH_04 — Chance the Rapper
python(60687) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:09:24 - whisperx.asr - INFO - Detected language: en (0.80) in first 30s of audio

11:09:34 | INFO | lyric_timeline |   [CH_04] 64 lines, 426 WhisperX words
11:09:38 | INFO | lyric_timeline |   [CH_04] 2 lines matched and embedded
11:09:38 | INFO | lyric_timeline |
[98/436] CH_05 — Chance the Rapper
python(60689) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:09:49 - whisperx.asr - INFO - Detected language: en (0.65) in first 30s of audio

11:10:00 | INFO | lyric_timeline |   [CH_05] 115 lines, 550 WhisperX words
11:10:05 | INFO | lyric_timeline |   [CH_05] 1 lines matched and embedded
11:10:05 | INFO | lyric_timeline |
[99/436] CH_06 — Chance the Rapper
python(60711) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:10:14 - whisperx.asr - INFO - Detected language: en (0.96) in first 30s of audio

11:10:22 | INFO | lyric_timeline |   [CH_06] 75 lines, 342 WhisperX words
11:10:25 | INFO | lyric_timeline |   [CH_06] 3 lines matched and embedded
11:10:25 | INFO | lyric_timeline |
[100/436] CH_07 — Chance the Rapper
python(60738) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:10:32 - whisperx.asr - INFO - Detected language: en (0.92) in first 30s of audio

11:10:39 | INFO | lyric_timeline |   [CH_07] 67 lines, 275 WhisperX words
11:10:45 | INFO | lyric_timeline |   [CH_07] 3 lines matched and embedded
11:10:45 | INFO | lyric_timeline |   Checkpoint saved (100/436 songs done)
11:10:45 | INFO | lyric_timeline |
[101/436] CH_08 — Chance the Rapper
python(60741) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:10:52 - whisperx.asr - INFO - Detected language: en (0.78) in first 30s of audio

11:11:01 | INFO | lyric_timeline |   [CH_08] 56 lines, 333 WhisperX words
11:11:05 | INFO | lyric_timeline |   [CH_08] 3 lines matched and embedded
11:11:05 | INFO | lyric_timeline |
[102/436] CH_09 — Chance the Rapper
python(60743) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:11:15 - whisperx.asr - INFO - Detected language: en (0.74) in first 30s of audio

11:11:30 | INFO | lyric_timeline |   [CH_09] 96 lines, 622 WhisperX words
11:11:35 | INFO | lyric_timeline |   [CH_09] 4 lines matched and embedded
11:11:35 | INFO | lyric_timeline |
[103/436] CH_10 — Chance the Rapper
python(60776) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:11:43 - whisperx.asr - INFO - Detected language: en (0.80) in first 30s of audio

11:11:50 | INFO | lyric_timeline |   [CH_10] 98 lines, 264 WhisperX words
11:11:54 | INFO | lyric_timeline |   [CH_10] 1 lines matched and embedded
11:11:54 | INFO | lyric_timeline |
[104/436] CH_11 — Chance the Rapper
python(60784) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:12:01 - whisperx.asr - INFO - Detected language: en (0.98) in first 30s of audio

11:12:10 | INFO | lyric_timeline |   [CH_11] 88 lines, 325 WhisperX words
11:12:12 | INFO | lyric_timeline |   [CH_11] 3 lines matched and embedded
11:12:12 | INFO | lyric_timeline |
[105/436] CH_12 — Chance the Rapper
python(60789) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:12:20 - whisperx.asr - INFO - Detected language: en (0.84) in first 30s of audio

11:12:33 | INFO | lyric_timeline |   [CH_12] 74 lines, 537 WhisperX words
11:12:33 | INFO | lyric_timeline |   [CH_12] 0 lines matched and embedded
11:12:33 | INFO | lyric_timeline |   Checkpoint saved (105/436 songs done)
11:12:33 | INFO | lyric_timeline |
[106/436] NS_01 — Nas
python(60795) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:12:43 - whisperx.asr - INFO - Detected language: en (0.95) in first 30s of audio

11:12:59 | INFO | lyric_timeline |   [NS_01] 90 lines, 817 WhisperX words
11:13:04 | INFO | lyric_timeline |   [NS_01] 1 lines matched and embedded
11:13:04 | INFO | lyric_timeline |
[107/436] NS_02 — Nas
python(60799) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:13:14 - whisperx.asr - INFO - Detected language: en (0.87) in first 30s of audio

11:13:28 | INFO | lyric_timeline |   [NS_02] 89 lines, 637 WhisperX words
11:13:33 | INFO | lyric_timeline |   [NS_02] 4 lines matched and embedded
11:13:33 | INFO | lyric_timeline |
[108/436] NS_03 — Nas
python(60807) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:13:45 - whisperx.asr - INFO - Detected language: en (0.92) in first 30s of audio

11:13:59 | INFO | lyric_timeline |   [NS_03] 110 lines, 814 WhisperX words
11:14:02 | INFO | lyric_timeline |   [NS_03] 1 lines matched and embedded
11:14:02 | INFO | lyric_timeline |
[109/436] NS_04 — Nas
python(60818) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:14:12 - whisperx.asr - INFO - Detected language: en (0.93) in first 30s of audio

11:14:23 | INFO | lyric_timeline |   [NS_04] 8 lines, 468 WhisperX words
11:14:23 | INFO | lyric_timeline |   [NS_04] 0 lines matched and embedded
11:14:23 | INFO | lyric_timeline |
[110/436] NS_05 — Nas
python(60821) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:14:32 - whisperx.asr - INFO - Detected language: en (0.97) in first 30s of audio

11:14:48 | INFO | lyric_timeline |   [NS_05] 104 lines, 654 WhisperX words
11:15:01 | INFO | lyric_timeline |   [NS_05] 9 lines matched and embedded
11:15:01 | INFO | lyric_timeline |   Checkpoint saved (110/436 songs done)
11:15:01 | INFO | lyric_timeline |
[111/436] NS_06 — Nas
python(60835) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:15:12 - whisperx.asr - INFO - Detected language: en (0.88) in first 30s of audio

11:15:25 | INFO | lyric_timeline |   [NS_06] 81 lines, 669 WhisperX words
11:15:30 | INFO | lyric_timeline |   [NS_06] 5 lines matched and embedded
11:15:30 | INFO | lyric_timeline |
[112/436] NS_07 — Nas
python(60852) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:15:37 - whisperx.asr - INFO - Detected language: en (0.85) in first 30s of audio

11:15:49 | INFO | lyric_timeline |   [NS_07] 71 lines, 472 WhisperX words
11:15:49 | INFO | lyric_timeline |   [NS_07] 0 lines matched and embedded
11:15:49 | INFO | lyric_timeline |
[113/436] NS_08 — Nas
python(60855) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:15:56 - whisperx.asr - INFO - Detected language: en (0.91) in first 30s of audio

11:16:06 | INFO | lyric_timeline |   [NS_08] 61 lines, 568 WhisperX words
11:16:14 | INFO | lyric_timeline |   [NS_08] 10 lines matched and embedded
11:16:14 | INFO | lyric_timeline |
[114/436] NS_09 — Nas
python(60860) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:16:57 - whisperx.asr - INFO - Detected language: en (0.79) in first 30s of audio

11:17:48 | INFO | lyric_timeline |   [NS_09] 17 lines, 2627 WhisperX words
11:17:58 | INFO | lyric_timeline |   [NS_09] 4 lines matched and embedded
11:17:58 | INFO | lyric_timeline |
[115/436] NS_10 — Nas
python(60883) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:18:08 - whisperx.asr - INFO - Detected language: en (0.88) in first 30s of audio

11:18:23 | INFO | lyric_timeline |   [NS_10] 75 lines, 708 WhisperX words
11:18:30 | INFO | lyric_timeline |   [NS_10] 7 lines matched and embedded
11:18:30 | INFO | lyric_timeline |   Checkpoint saved (115/436 songs done)
11:18:30 | INFO | lyric_timeline |
[116/436] NS_11 — Nas
python(60888) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:18:37 - whisperx.asr - INFO - Detected language: en (0.91) in first 30s of audio

11:18:47 | INFO | lyric_timeline |   [NS_11] 63 lines, 440 WhisperX words
11:18:49 | INFO | lyric_timeline |   [NS_11] 1 lines matched and embedded
11:18:49 | INFO | lyric_timeline |
[117/436] NS_12 — Nas
python(60890) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:19:02 - whisperx.asr - INFO - Detected language: en (0.86) in first 30s of audio

11:19:18 | INFO | lyric_timeline |   [NS_12] 78 lines, 701 WhisperX words
11:19:23 | INFO | lyric_timeline |   [NS_12] 4 lines matched and embedded
11:19:23 | INFO | lyric_timeline |
[118/436] CG_01 — Childish Gambino
python(60894) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:19:35 - whisperx.asr - INFO - Detected language: km (0.28) in first 30s of audio
2026-04-21 11:19:36 - whisperx.alignment - ERROR - No default alignment model for language: km. Please find a wav2vec2.0 model finetuned on this language at https://huggingface.co/models, then pass the model name via --align_model [MODEL_NAME]

11:19:36 | WARNING | lyric_timeline |   WhisperX failed: No default align-model for language: km
11:19:36 | INFO | lyric_timeline |   [CG_01] WhisperX returned no words — skipping
11:19:36 | INFO | lyric_timeline |
[119/436] CG_02 — Childish Gambino
python(60901) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:19:44 - whisperx.asr - INFO - Detected language: en (0.75) in first 30s of audio

11:19:52 | INFO | lyric_timeline |   [CG_02] 112 lines, 214 WhisperX words
11:20:01 | INFO | lyric_timeline |   [CG_02] 7 lines matched and embedded
11:20:01 | INFO | lyric_timeline |
[120/436] CG_03 — Childish Gambino
python(60907) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:20:11 - whisperx.asr - INFO - Detected language: en (0.97) in first 30s of audio

11:20:23 | INFO | lyric_timeline |   [CG_03] 74 lines, 562 WhisperX words
11:20:25 | INFO | lyric_timeline |   [CG_03] 1 lines matched and embedded
11:20:25 | INFO | lyric_timeline |   Checkpoint saved (120/436 songs done)
11:20:25 | INFO | lyric_timeline |
[121/436] CG_04 — Childish Gambino
python(60912) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:20:35 - whisperx.asr - INFO - Detected language: en (0.71) in first 30s of audio

11:20:41 | INFO | lyric_timeline |   [CG_04] 46 lines, 224 WhisperX words
11:20:48 | INFO | lyric_timeline |   [CG_04] 7 lines matched and embedded
11:20:48 | INFO | lyric_timeline |
[122/436] CG_05 — Childish Gambino
python(60914) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:20:54 - whisperx.asr - INFO - Detected language: en (0.91) in first 30s of audio

11:21:04 | INFO | lyric_timeline |   [CG_05] 65 lines, 328 WhisperX words
11:21:05 | INFO | lyric_timeline |   [CG_05] 1 lines matched and embedded
11:21:05 | INFO | lyric_timeline |
[123/436] CG_06 — Childish Gambino
python(60917) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:21:12 - whisperx.asr - INFO - Detected language: en (0.95) in first 30s of audio

11:21:24 | INFO | lyric_timeline |   [CG_06] 59 lines, 570 WhisperX words
11:21:26 | INFO | lyric_timeline |   [CG_06] 2 lines matched and embedded
11:21:26 | INFO | lyric_timeline |
[124/436] CG_07 — Childish Gambino
python(60918) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:21:41 - whisperx.asr - INFO - Detected language: en (0.52) in first 30s of audio

11:21:44 | INFO | lyric_timeline |   [CG_07] WhisperX returned no words — skipping
11:21:44 | INFO | lyric_timeline |
[125/436] CG_08 — Childish Gambino
python(60927) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:21:53 - whisperx.asr - INFO - Detected language: en (0.75) in first 30s of audio

11:21:59 | INFO | lyric_timeline |   [CG_08] 32 lines, 78 WhisperX words
11:22:04 | INFO | lyric_timeline |   [CG_08] 4 lines matched and embedded
11:22:04 | INFO | lyric_timeline |   Checkpoint saved (125/436 songs done)
11:22:04 | INFO | lyric_timeline |
[126/436] CG_09 — Childish Gambino
python(60928) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:22:14 - whisperx.asr - INFO - Detected language: en (0.87) in first 30s of audio

11:22:22 | INFO | lyric_timeline |   [CG_09] 101 lines, 251 WhisperX words
11:22:28 | INFO | lyric_timeline |   [CG_09] 11 lines matched and embedded
11:22:28 | INFO | lyric_timeline |
[127/436] CG_10 — Childish Gambino
python(60930) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:22:38 - whisperx.asr - INFO - Detected language: en (0.93) in first 30s of audio

11:22:50 | INFO | lyric_timeline |   [CG_10] 71 lines, 498 WhisperX words
11:23:01 | INFO | lyric_timeline |   [CG_10] 18 lines matched and embedded
11:23:01 | INFO | lyric_timeline |
[128/436] CG_11 — Childish Gambino
python(60936) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:23:09 - whisperx.asr - INFO - Detected language: en (0.79) in first 30s of audio

11:23:19 | INFO | lyric_timeline |   [CG_11] 77 lines, 320 WhisperX words
11:23:25 | INFO | lyric_timeline |   [CG_11] 7 lines matched and embedded
11:23:25 | INFO | lyric_timeline |
[129/436] CG_12 — Childish Gambino
python(60954) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:23:33 - whisperx.asr - INFO - Detected language: en (0.49) in first 30s of audio

11:23:39 | INFO | lyric_timeline |   [CG_12] 46 lines, 159 WhisperX words
11:23:43 | INFO | lyric_timeline |   [CG_12] 3 lines matched and embedded
11:23:43 | INFO | lyric_timeline |
[130/436] GD_01 — Grateful Dead
python(60968) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:23:52 - whisperx.asr - INFO - Detected language: en (0.88) in first 30s of audio

11:23:55 | INFO | lyric_timeline |   [GD_01] 30 lines, 44 WhisperX words
11:23:55 | INFO | lyric_timeline |   [GD_01] 0 lines matched and embedded
11:23:55 | INFO | lyric_timeline |   Checkpoint saved (130/436 songs done)
11:23:55 | INFO | lyric_timeline |
[131/436] GD_02 — Grateful Dead
python(60981) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:24:12 - whisperx.asr - INFO - Detected language: en (0.23) in first 30s of audio

11:24:17 | INFO | lyric_timeline |   [GD_02] 33 lines, 70 WhisperX words
11:24:17 | INFO | lyric_timeline |   [GD_02] 0 lines matched and embedded
11:24:17 | INFO | lyric_timeline |
[132/436] GD_03 — Grateful Dead
python(60989) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:24:27 - whisperx.asr - INFO - Detected language: en (0.92) in first 30s of audio

11:24:33 | INFO | lyric_timeline |   [GD_03] 26 lines, 179 WhisperX words
11:24:40 | INFO | lyric_timeline |   [GD_03] 2 lines matched and embedded
11:24:40 | INFO | lyric_timeline |
[133/436] GD_04 — Grateful Dead
python(60992) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:24:50 - whisperx.asr - INFO - Detected language: en (0.80) in first 30s of audio

11:24:57 | INFO | lyric_timeline |   [GD_04] 28 lines, 139 WhisperX words
11:24:57 | INFO | lyric_timeline |   [GD_04] 0 lines matched and embedded
11:24:57 | INFO | lyric_timeline |
[134/436] GD_05 — Grateful Dead
python(60997) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:25:07 - whisperx.asr - INFO - Detected language: en (0.92) in first 30s of audio

11:25:15 | INFO | lyric_timeline |   [GD_05] 30 lines, 215 WhisperX words
11:25:22 | INFO | lyric_timeline |   [GD_05] 6 lines matched and embedded
11:25:22 | INFO | lyric_timeline |
[135/436] GD_06 — Grateful Dead
python(61000) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:25:39 - whisperx.asr - INFO - Detected language: en (0.88) in first 30s of audio

11:25:49 | INFO | lyric_timeline |   [GD_06] 36 lines, 201 WhisperX words
11:25:58 | INFO | lyric_timeline |   [GD_06] 7 lines matched and embedded
11:25:58 | INFO | lyric_timeline |   Checkpoint saved (135/436 songs done)
11:25:58 | INFO | lyric_timeline |
[136/436] GD_07 — Grateful Dead
python(61008) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:26:05 - whisperx.asr - INFO - Detected language: en (0.73) in first 30s of audio

11:26:07 | INFO | lyric_timeline |   [GD_07] 20 lines, 8 WhisperX words
11:26:07 | INFO | lyric_timeline |   [GD_07] 0 lines matched and embedded
11:26:07 | INFO | lyric_timeline |
[137/436] GD_08 — Grateful Dead
python(61094) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:26:24 - whisperx.asr - INFO - Detected language: en (0.40) in first 30s of audio

11:26:37 | INFO | lyric_timeline |   [GD_08] 38 lines, 173 WhisperX words
11:26:45 | INFO | lyric_timeline |   [GD_08] 1 lines matched and embedded
11:26:45 | INFO | lyric_timeline |
[138/436] GD_09 — Grateful Dead
python(61100) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:26:51 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

11:26:59 | INFO | lyric_timeline |   [GD_09] 30 lines, 240 WhisperX words
11:27:09 | INFO | lyric_timeline |   [GD_09] 15 lines matched and embedded
11:27:09 | INFO | lyric_timeline |
[139/436] GD_10 — Grateful Dead
python(61102) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:27:16 - whisperx.asr - INFO - Detected language: en (0.83) in first 30s of audio

11:27:26 | INFO | lyric_timeline |   [GD_10] 38 lines, 355 WhisperX words
11:27:30 | INFO | lyric_timeline |   [GD_10] 8 lines matched and embedded
11:27:30 | INFO | lyric_timeline |
[140/436] GD_11 — Grateful Dead
python(61104) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:27:41 - whisperx.asr - INFO - Detected language: en (0.82) in first 30s of audio

11:27:52 | INFO | lyric_timeline |   [GD_11] 53 lines, 352 WhisperX words
11:27:55 | INFO | lyric_timeline |   [GD_11] 2 lines matched and embedded
11:27:55 | INFO | lyric_timeline |   Checkpoint saved (140/436 songs done)
11:27:55 | INFO | lyric_timeline |
[141/436] GD_12 — Grateful Dead
python(61121) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:28:04 - whisperx.asr - INFO - Detected language: en (0.92) in first 30s of audio

11:28:15 | INFO | lyric_timeline |   [GD_12] 44 lines, 284 WhisperX words
11:28:22 | INFO | lyric_timeline |   [GD_12] 12 lines matched and embedded
11:28:22 | INFO | lyric_timeline |
[142/436] GD_13 — Grateful Dead
python(61123) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:28:35 - whisperx.asr - INFO - Detected language: en (0.87) in first 30s of audio

11:28:44 | INFO | lyric_timeline |   [GD_13] 54 lines, 179 WhisperX words
11:28:49 | INFO | lyric_timeline |   [GD_13] 5 lines matched and embedded
11:28:49 | INFO | lyric_timeline |
[143/436] GD_14 — Grateful Dead
python(61127) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:28:58 - whisperx.asr - INFO - Detected language: en (0.44) in first 30s of audio

11:29:08 | INFO | lyric_timeline |   [GD_14] 26 lines, 195 WhisperX words
11:29:11 | INFO | lyric_timeline |   [GD_14] 3 lines matched and embedded
11:29:11 | INFO | lyric_timeline |
[144/436] GD_15 — Grateful Dead
python(61131) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:29:20 - whisperx.asr - INFO - Detected language: en (0.93) in first 30s of audio

11:29:28 | INFO | lyric_timeline |   [GD_15] 48 lines, 190 WhisperX words
11:29:33 | INFO | lyric_timeline |   [GD_15] 3 lines matched and embedded
11:29:33 | INFO | lyric_timeline |
[145/436] BD_01 — Bob Dylan
python(61132) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:29:39 - whisperx.asr - INFO - Detected language: en (0.94) in first 30s of audio

11:29:47 | INFO | lyric_timeline |   [BD_01] 15 lines, 182 WhisperX words
11:29:54 | INFO | lyric_timeline |   [BD_01] 7 lines matched and embedded
11:29:54 | INFO | lyric_timeline |   Checkpoint saved (145/436 songs done)
11:29:54 | INFO | lyric_timeline |
[146/436] BD_02 — Bob Dylan
python(61145) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:30:01 - whisperx.asr - INFO - Detected language: en (0.92) in first 30s of audio

11:30:11 | INFO | lyric_timeline |   [BD_02] 30 lines, 248 WhisperX words
11:30:15 | INFO | lyric_timeline |   [BD_02] 3 lines matched and embedded
11:30:15 | INFO | lyric_timeline |
[147/436] BD_03 — Bob Dylan
python(61149) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:30:27 - whisperx.asr - INFO - Detected language: en (0.86) in first 30s of audio

11:30:39 | INFO | lyric_timeline |   [BD_03] 59 lines, 306 WhisperX words
11:30:43 | INFO | lyric_timeline |   [BD_03] 2 lines matched and embedded
11:30:43 | INFO | lyric_timeline |
[148/436] BD_04 — Bob Dylan
python(61151) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:30:55 - whisperx.asr - INFO - Detected language: en (0.91) in first 30s of audio

11:31:11 | INFO | lyric_timeline |   [BD_04] 48 lines, 450 WhisperX words
11:31:18 | INFO | lyric_timeline |   [BD_04] 9 lines matched and embedded
11:31:18 | INFO | lyric_timeline |
[149/436] BD_05 — Bob Dylan
python(61159) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:31:24 - whisperx.asr - INFO - Detected language: en (0.54) in first 30s of audio

11:31:30 | INFO | lyric_timeline |   [BD_05] 16 lines, 98 WhisperX words
11:31:36 | INFO | lyric_timeline |   [BD_05] 4 lines matched and embedded
11:31:36 | INFO | lyric_timeline |
[150/436] BD_06 — Bob Dylan
python(61160) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:31:50 - whisperx.asr - INFO - Detected language: en (0.89) in first 30s of audio

11:32:04 | INFO | lyric_timeline |   [BD_06] 96 lines, 593 WhisperX words
11:32:13 | INFO | lyric_timeline |   [BD_06] 13 lines matched and embedded
11:32:13 | INFO | lyric_timeline |   Checkpoint saved (150/436 songs done)
11:32:13 | INFO | lyric_timeline |
[151/436] BD_07 — Bob Dylan
python(61173) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:32:33 - whisperx.asr - INFO - Detected language: en (0.89) in first 30s of audio

11:32:49 | INFO | lyric_timeline |   [BD_07] 100 lines, 702 WhisperX words
11:32:56 | INFO | lyric_timeline |   [BD_07] 8 lines matched and embedded
11:32:56 | INFO | lyric_timeline |
[152/436] BD_08 — Bob Dylan
python(61178) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:33:04 - whisperx.asr - INFO - Detected language: en (0.81) in first 30s of audio

11:33:15 | INFO | lyric_timeline |   [BD_08] 36 lines, 219 WhisperX words
11:33:31 | INFO | lyric_timeline |   [BD_08] 4 lines matched and embedded
11:33:31 | INFO | lyric_timeline |
[153/436] BD_09 — Bob Dylan
python(61205) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:33:43 - whisperx.asr - INFO - Detected language: en (0.94) in first 30s of audio

11:33:54 | INFO | lyric_timeline |   [BD_09] 32 lines, 249 WhisperX words
11:34:02 | INFO | lyric_timeline |   [BD_09] 2 lines matched and embedded
11:34:02 | INFO | lyric_timeline |
[154/436] BD_10 — Bob Dylan
python(61224) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:34:09 - whisperx.asr - INFO - Detected language: en (0.82) in first 30s of audio

11:34:18 | INFO | lyric_timeline |   [BD_10] 19 lines, 177 WhisperX words
11:34:24 | INFO | lyric_timeline |   [BD_10] 6 lines matched and embedded
11:34:24 | INFO | lyric_timeline |
[155/436] BD_11 — Bob Dylan
python(61227) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:34:35 - whisperx.asr - INFO - Detected language: en (0.38) in first 30s of audio

11:34:47 | INFO | lyric_timeline |   [BD_11] 42 lines, 279 WhisperX words
11:35:03 | INFO | lyric_timeline |   [BD_11] 16 lines matched and embedded
11:35:03 | INFO | lyric_timeline |   Checkpoint saved (155/436 songs done)
11:35:03 | INFO | lyric_timeline |
[156/436] BD_12 — Bob Dylan
python(61235) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:35:16 - whisperx.asr - INFO - Detected language: en (0.93) in first 30s of audio

11:35:30 | INFO | lyric_timeline |   [BD_12] 40 lines, 445 WhisperX words
11:35:35 | INFO | lyric_timeline |   [BD_12] 3 lines matched and embedded
11:35:35 | INFO | lyric_timeline |
[157/436] BD_13 — Bob Dylan
python(61241) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:35:47 - whisperx.asr - INFO - Detected language: en (0.71) in first 30s of audio

11:35:55 | INFO | lyric_timeline |   [BD_13] 24 lines, 132 WhisperX words
11:36:13 | INFO | lyric_timeline |   [BD_13] 9 lines matched and embedded
11:36:13 | INFO | lyric_timeline |
[158/436] BD_14 — Bob Dylan
python(61275) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:36:25 - whisperx.asr - INFO - Detected language: en (0.91) in first 30s of audio

11:36:35 | INFO | lyric_timeline |   [BD_14] 34 lines, 248 WhisperX words
11:36:48 | INFO | lyric_timeline |   [BD_14] 14 lines matched and embedded
11:36:48 | INFO | lyric_timeline |
[159/436] BD_15 — Bob Dylan
python(61300) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:36:57 - whisperx.asr - INFO - Detected language: en (0.94) in first 30s of audio

11:37:05 | INFO | lyric_timeline |   [BD_15] 20 lines, 142 WhisperX words
11:37:20 | INFO | lyric_timeline |   [BD_15] 3 lines matched and embedded
11:37:20 | INFO | lyric_timeline |
[160/436] TC_01 — Tyler Childers
python(61322) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:37:31 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

11:37:41 | INFO | lyric_timeline |   [TC_01] 49 lines, 328 WhisperX words
11:37:53 | INFO | lyric_timeline |   [TC_01] 15 lines matched and embedded
11:37:53 | INFO | lyric_timeline |   Checkpoint saved (160/436 songs done)
11:37:53 | INFO | lyric_timeline |
[161/436] TC_02 — Tyler Childers
python(61358) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:38:01 - whisperx.asr - INFO - Detected language: en (0.96) in first 30s of audio

11:38:08 | INFO | lyric_timeline |   [TC_02] 32 lines, 192 WhisperX words
11:38:11 | INFO | lyric_timeline |   [TC_02] 2 lines matched and embedded
11:38:11 | INFO | lyric_timeline |
[162/436] TC_03 — Tyler Childers
python(61362) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:38:19 - whisperx.asr - INFO - Detected language: en (0.98) in first 30s of audio

11:38:27 | INFO | lyric_timeline |   [TC_03] 40 lines, 221 WhisperX words
11:38:38 | INFO | lyric_timeline |   [TC_03] 8 lines matched and embedded
11:38:38 | INFO | lyric_timeline |
[163/436] TC_04 — Tyler Childers
python(61376) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:38:46 - whisperx.asr - INFO - Detected language: en (0.95) in first 30s of audio

11:38:53 | INFO | lyric_timeline |   [TC_04] 30 lines, 191 WhisperX words
11:38:53 | INFO | lyric_timeline |   [TC_04] 0 lines matched and embedded
11:38:53 | INFO | lyric_timeline |
[164/436] TC_05 — Tyler Childers
11:38:53 | INFO | lyric_timeline |   [TC_05] No usable lyric lines — skipping
11:38:53 | INFO | lyric_timeline |
[165/436] TC_06 — Tyler Childers
python(61378) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:39:01 - whisperx.asr - INFO - Detected language: en (0.98) in first 30s of audio

11:39:07 | INFO | lyric_timeline |   [TC_06] 26 lines, 182 WhisperX words
11:39:11 | INFO | lyric_timeline |   [TC_06] 3 lines matched and embedded
11:39:11 | INFO | lyric_timeline |   Checkpoint saved (165/436 songs done)
11:39:11 | INFO | lyric_timeline |
[166/436] TC_07 — Tyler Childers
python(61384) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:39:21 - whisperx.asr - INFO - Detected language: en (0.68) in first 30s of audio

11:39:25 | INFO | lyric_timeline |   [TC_07] 25 lines, 48 WhisperX words
11:39:25 | INFO | lyric_timeline |   [TC_07] 0 lines matched and embedded
11:39:25 | INFO | lyric_timeline |
[167/436] TC_08 — Tyler Childers
python(61393) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:39:38 - whisperx.asr - INFO - Detected language: en (0.93) in first 30s of audio

11:39:46 | INFO | lyric_timeline |   [TC_08] 32 lines, 217 WhisperX words
11:39:58 | INFO | lyric_timeline |   [TC_08] 1 lines matched and embedded
11:39:58 | INFO | lyric_timeline |
[168/436] TC_09 — Tyler Childers
python(61465) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:40:04 - whisperx.asr - INFO - Detected language: en (0.96) in first 30s of audio

11:40:11 | INFO | lyric_timeline |   [TC_09] 23 lines, 168 WhisperX words
11:40:15 | INFO | lyric_timeline |   [TC_09] 4 lines matched and embedded
11:40:15 | INFO | lyric_timeline |
[169/436] TC_10 — Tyler Childers
python(61479) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:40:22 - whisperx.asr - INFO - Detected language: en (0.93) in first 30s of audio

11:40:31 | INFO | lyric_timeline |   [TC_10] 31 lines, 206 WhisperX words
11:40:34 | INFO | lyric_timeline |   [TC_10] 2 lines matched and embedded
11:40:34 | INFO | lyric_timeline |
[170/436] TC_11 — Tyler Childers
python(61494) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:40:43 - whisperx.asr - INFO - Detected language: en (0.98) in first 30s of audio

11:40:52 | INFO | lyric_timeline |   [TC_11] 32 lines, 284 WhisperX words
11:40:56 | INFO | lyric_timeline |   [TC_11] 3 lines matched and embedded
11:40:56 | INFO | lyric_timeline |   Checkpoint saved (170/436 songs done)
11:40:56 | INFO | lyric_timeline |
[171/436] TC_12 — Tyler Childers
python(61499) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:41:03 - whisperx.asr - INFO - Detected language: en (0.98) in first 30s of audio

11:41:10 | INFO | lyric_timeline |   [TC_12] 21 lines, 220 WhisperX words
11:41:13 | INFO | lyric_timeline |   [TC_12] 5 lines matched and embedded
11:41:13 | INFO | lyric_timeline |
[172/436] TC_13 — Tyler Childers
python(61505) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:41:21 - whisperx.asr - INFO - Detected language: en (0.97) in first 30s of audio

11:41:30 | INFO | lyric_timeline |   [TC_13] 54 lines, 285 WhisperX words
11:41:40 | INFO | lyric_timeline |   [TC_13] 13 lines matched and embedded
11:41:40 | INFO | lyric_timeline |
[173/436] TC_14 — Tyler Childers
python(61598) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:41:50 - whisperx.asr - INFO - Detected language: en (0.95) in first 30s of audio

11:41:59 | INFO | lyric_timeline |   [TC_14] 44 lines, 170 WhisperX words
11:42:02 | INFO | lyric_timeline |   [TC_14] 3 lines matched and embedded
11:42:02 | INFO | lyric_timeline |
[174/436] TC_15 — Tyler Childers
python(61619) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:42:12 - whisperx.asr - INFO - Detected language: en (0.88) in first 30s of audio

11:42:22 | INFO | lyric_timeline |   [TC_15] 32 lines, 205 WhisperX words
11:42:25 | INFO | lyric_timeline |   [TC_15] 3 lines matched and embedded
11:42:25 | INFO | lyric_timeline |
[175/436] JI_01 — Jason Isbell
python(61653) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:42:37 - whisperx.asr - INFO - Detected language: en (0.82) in first 30s of audio

11:42:48 | INFO | lyric_timeline |   [JI_01] 29 lines, 254 WhisperX words
11:42:57 | INFO | lyric_timeline |   [JI_01] 11 lines matched and embedded
11:42:57 | INFO | lyric_timeline |   Checkpoint saved (175/436 songs done)
11:42:57 | INFO | lyric_timeline |
[176/436] JI_02 — Jason Isbell
python(61697) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:43:06 - whisperx.asr - INFO - Detected language: en (0.92) in first 30s of audio

11:43:15 | INFO | lyric_timeline |   [JI_02] 31 lines, 239 WhisperX words
11:43:22 | INFO | lyric_timeline |   [JI_02] 9 lines matched and embedded
11:43:22 | INFO | lyric_timeline |
[177/436] JI_03 — Jason Isbell
python(61709) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:43:33 - whisperx.asr - INFO - Detected language: en (0.88) in first 30s of audio

11:43:43 | INFO | lyric_timeline |   [JI_03] 49 lines, 332 WhisperX words
11:43:54 | INFO | lyric_timeline |   [JI_03] 11 lines matched and embedded
11:43:54 | INFO | lyric_timeline |
[178/436] JI_04 — Jason Isbell
python(61737) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:44:04 - whisperx.asr - INFO - Detected language: en (0.93) in first 30s of audio

11:44:11 | INFO | lyric_timeline |   [JI_04] 29 lines, 160 WhisperX words
11:44:14 | INFO | lyric_timeline |   [JI_04] 1 lines matched and embedded
11:44:14 | INFO | lyric_timeline |
[179/436] JI_05 — Jason Isbell
python(61745) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:44:23 - whisperx.asr - INFO - Detected language: en (0.94) in first 30s of audio

11:44:33 | INFO | lyric_timeline |   [JI_05] 36 lines, 284 WhisperX words
11:44:42 | INFO | lyric_timeline |   [JI_05] 8 lines matched and embedded
11:44:42 | INFO | lyric_timeline |
[180/436] JI_06 — Jason Isbell
python(61757) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:44:51 - whisperx.asr - INFO - Detected language: en (0.92) in first 30s of audio

11:45:00 | INFO | lyric_timeline |   [JI_06] 34 lines, 250 WhisperX words
11:45:02 | INFO | lyric_timeline |   [JI_06] 1 lines matched and embedded
11:45:02 | INFO | lyric_timeline |   Checkpoint saved (180/436 songs done)
11:45:02 | INFO | lyric_timeline |
[181/436] JI_07 — Jason Isbell
python(61761) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:45:12 - whisperx.asr - INFO - Detected language: en (0.95) in first 30s of audio

11:45:22 | INFO | lyric_timeline |   [JI_07] 42 lines, 282 WhisperX words
11:45:24 | INFO | lyric_timeline |   [JI_07] 2 lines matched and embedded
11:45:24 | INFO | lyric_timeline |
[182/436] JI_08 — Jason Isbell
python(61766) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:45:34 - whisperx.asr - INFO - Detected language: en (0.37) in first 30s of audio

11:45:46 | INFO | lyric_timeline |   [JI_08] 32 lines, 256 WhisperX words
11:45:52 | INFO | lyric_timeline |   [JI_08] 6 lines matched and embedded
11:45:52 | INFO | lyric_timeline |
[183/436] JI_09 — Jason Isbell
python(61783) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:46:01 - whisperx.asr - INFO - Detected language: en (0.95) in first 30s of audio

11:46:11 | INFO | lyric_timeline |   [JI_09] 29 lines, 262 WhisperX words
11:46:15 | INFO | lyric_timeline |   [JI_09] 1 lines matched and embedded
11:46:15 | INFO | lyric_timeline |
[184/436] JI_10 — Jason Isbell
python(61785) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:46:23 - whisperx.asr - INFO - Detected language: en (0.94) in first 30s of audio

11:46:34 | INFO | lyric_timeline |   [JI_10] 43 lines, 306 WhisperX words
11:46:40 | INFO | lyric_timeline |   [JI_10] 7 lines matched and embedded
11:46:40 | INFO | lyric_timeline |
[185/436] JI_11 — Jason Isbell
python(61790) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:46:50 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

11:46:58 | INFO | lyric_timeline |   [JI_11] 31 lines, 162 WhisperX words
11:47:00 | INFO | lyric_timeline |   [JI_11] 2 lines matched and embedded
11:47:00 | INFO | lyric_timeline |   Checkpoint saved (185/436 songs done)
11:47:00 | INFO | lyric_timeline |
[186/436] JI_12 — Jason Isbell
python(61794) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:47:13 - whisperx.asr - INFO - Detected language: en (0.91) in first 30s of audio

11:47:21 | INFO | lyric_timeline |   [JI_12] 26 lines, 146 WhisperX words
11:47:25 | INFO | lyric_timeline |   [JI_12] 5 lines matched and embedded
11:47:25 | INFO | lyric_timeline |
[187/436] SS_01 — Sturgill Simpson
python(61813) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:47:34 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

11:47:41 | INFO | lyric_timeline |   [SS_01] 31 lines, 226 WhisperX words
11:47:44 | INFO | lyric_timeline |   [SS_01] 1 lines matched and embedded
11:47:44 | INFO | lyric_timeline |
[188/436] SS_02 — Sturgill Simpson
python(61839) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:47:50 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

11:47:58 | INFO | lyric_timeline |   [SS_02] 22 lines, 256 WhisperX words
11:48:00 | INFO | lyric_timeline |   [SS_02] 1 lines matched and embedded
11:48:00 | INFO | lyric_timeline |
[189/436] SS_03 — Sturgill Simpson
python(61843) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:48:08 - whisperx.asr - INFO - Detected language: en (0.82) in first 30s of audio
2026-04-21 11:48:19 - whisperx.alignment - WARNING - Failed to align segment (" It's a long, long, long time, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long,"): backtrack failed, resorting to original

11:48:19 | INFO | lyric_timeline |   [SS_03] 24 lines, 271 WhisperX words
11:48:25 | INFO | lyric_timeline |   [SS_03] 3 lines matched and embedded
11:48:25 | INFO | lyric_timeline |
[190/436] SS_04 — Sturgill Simpson
python(61898) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:48:38 - whisperx.asr - INFO - Detected language: es (0.53) in first 30s of audio

11:48:43 | INFO | lyric_timeline |   [SS_04] 24 lines, 57 WhisperX words
11:48:46 | INFO | lyric_timeline |   [SS_04] 1 lines matched and embedded
11:48:46 | INFO | lyric_timeline |   Checkpoint saved (190/436 songs done)
11:48:46 | INFO | lyric_timeline |
[191/436] SS_05 — Sturgill Simpson
python(61917) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:48:55 - whisperx.asr - INFO - Detected language: en (0.63) in first 30s of audio

11:49:04 | INFO | lyric_timeline |   [SS_05] 28 lines, 161 WhisperX words
11:49:09 | INFO | lyric_timeline |   [SS_05] 6 lines matched and embedded
11:49:09 | INFO | lyric_timeline |
[192/436] SS_06 — Sturgill Simpson
python(61923) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:49:20 - whisperx.asr - INFO - Detected language: en (0.36) in first 30s of audio

11:49:26 | INFO | lyric_timeline |   [SS_06] 31 lines, 83 WhisperX words
11:49:29 | INFO | lyric_timeline |   [SS_06] 4 lines matched and embedded
11:49:29 | INFO | lyric_timeline |
[193/436] SS_07 — Sturgill Simpson
python(61927) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:49:38 - whisperx.asr - INFO - Detected language: en (0.78) in first 30s of audio

11:49:46 | INFO | lyric_timeline |   [SS_07] 33 lines, 146 WhisperX words
11:49:51 | INFO | lyric_timeline |   [SS_07] 4 lines matched and embedded
11:49:51 | INFO | lyric_timeline |
[194/436] SS_08 — Sturgill Simpson
python(61940) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:50:02 - whisperx.asr - INFO - Detected language: en (0.89) in first 30s of audio

11:50:12 | INFO | lyric_timeline |   [SS_08] 24 lines, 216 WhisperX words
11:50:15 | INFO | lyric_timeline |   [SS_08] 1 lines matched and embedded
11:50:15 | INFO | lyric_timeline |
[195/436] SS_09 — Sturgill Simpson
python(61982) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:50:26 - whisperx.asr - INFO - Detected language: en (0.77) in first 30s of audio

11:50:32 | INFO | lyric_timeline |   [SS_09] 28 lines, 105 WhisperX words
11:50:36 | INFO | lyric_timeline |   [SS_09] 2 lines matched and embedded
11:50:36 | INFO | lyric_timeline |   Checkpoint saved (195/436 songs done)
11:50:36 | INFO | lyric_timeline |
[196/436] SS_10 — Sturgill Simpson
python(62002) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:50:46 - whisperx.asr - INFO - Detected language: en (0.35) in first 30s of audio

11:50:56 | INFO | lyric_timeline |   [SS_10] 31 lines, 242 WhisperX words
11:51:00 | INFO | lyric_timeline |   [SS_10] 1 lines matched and embedded
11:51:00 | INFO | lyric_timeline |
[197/436] SS_11 — Sturgill Simpson
python(62004) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:51:13 - whisperx.asr - INFO - Detected language: en (0.95) in first 30s of audio

11:51:30 | INFO | lyric_timeline |   [SS_11] 42 lines, 667 WhisperX words
11:51:41 | INFO | lyric_timeline |   [SS_11] 8 lines matched and embedded
11:51:41 | INFO | lyric_timeline |
[198/436] SS_12 — Sturgill Simpson
python(62079) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:51:50 - whisperx.asr - INFO - Detected language: en (0.83) in first 30s of audio

11:51:57 | INFO | lyric_timeline |   [SS_12] 26 lines, 121 WhisperX words
11:52:04 | INFO | lyric_timeline |   [SS_12] 9 lines matched and embedded
11:52:04 | INFO | lyric_timeline |
[199/436] KM_01 — Kacey Musgraves
python(62091) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:52:12 - whisperx.asr - INFO - Detected language: en (0.93) in first 30s of audio

11:52:16 | INFO | lyric_timeline |   [KM_01] 28 lines, 38 WhisperX words
11:52:18 | INFO | lyric_timeline |   [KM_01] 1 lines matched and embedded
11:52:18 | INFO | lyric_timeline |
[200/436] KM_02 — Kacey Musgraves
python(62093) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:52:27 - whisperx.asr - INFO - Detected language: en (0.93) in first 30s of audio

11:52:34 | INFO | lyric_timeline |   [KM_02] 31 lines, 168 WhisperX words
11:52:39 | INFO | lyric_timeline |   [KM_02] 4 lines matched and embedded
11:52:39 | INFO | lyric_timeline |   Checkpoint saved (200/436 songs done)
11:52:39 | INFO | lyric_timeline |
[201/436] KM_03 — Kacey Musgraves
python(62111) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:52:48 - whisperx.asr - INFO - Detected language: en (0.91) in first 30s of audio

11:52:52 | INFO | lyric_timeline |   [KM_03] 37 lines, 48 WhisperX words
11:52:55 | INFO | lyric_timeline |   [KM_03] 3 lines matched and embedded
11:52:55 | INFO | lyric_timeline |
[202/436] KM_04 — Kacey Musgraves
python(62116) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:53:04 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

11:53:13 | INFO | lyric_timeline |   [KM_04] 37 lines, 236 WhisperX words
11:53:16 | INFO | lyric_timeline |   [KM_04] 4 lines matched and embedded
11:53:16 | INFO | lyric_timeline |
[203/436] KM_05 — Kacey Musgraves
python(62120) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:53:25 - whisperx.asr - INFO - Detected language: en (0.91) in first 30s of audio

11:53:33 | INFO | lyric_timeline |   [KM_05] 39 lines, 221 WhisperX words
11:53:41 | INFO | lyric_timeline |   [KM_05] 10 lines matched and embedded
11:53:41 | INFO | lyric_timeline |
[204/436] KM_06 — Kacey Musgraves
python(62154) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:53:50 - whisperx.asr - INFO - Detected language: en (0.94) in first 30s of audio

11:53:59 | INFO | lyric_timeline |   [KM_06] 25 lines, 158 WhisperX words
11:54:08 | INFO | lyric_timeline |   [KM_06] 10 lines matched and embedded
11:54:08 | INFO | lyric_timeline |
[205/436] KM_07 — Kacey Musgraves
python(62156) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:54:16 - whisperx.asr - INFO - Detected language: en (0.89) in first 30s of audio

11:54:21 | INFO | lyric_timeline |   [KM_07] 28 lines, 72 WhisperX words
11:54:23 | INFO | lyric_timeline |   [KM_07] 3 lines matched and embedded
11:54:23 | INFO | lyric_timeline |   Checkpoint saved (205/436 songs done)
11:54:23 | INFO | lyric_timeline |
[206/436] KM_08 — Kacey Musgraves
python(62158) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:54:31 - whisperx.asr - INFO - Detected language: en (0.93) in first 30s of audio

11:54:40 | INFO | lyric_timeline |   [KM_08] 37 lines, 241 WhisperX words
11:54:44 | INFO | lyric_timeline |   [KM_08] 5 lines matched and embedded
11:54:44 | INFO | lyric_timeline |
[207/436] KM_09 — Kacey Musgraves
python(62167) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:54:52 - whisperx.asr - INFO - Detected language: en (0.92) in first 30s of audio

11:55:02 | INFO | lyric_timeline |   [KM_09] 47 lines, 238 WhisperX words
11:55:10 | INFO | lyric_timeline |   [KM_09] 13 lines matched and embedded
11:55:10 | INFO | lyric_timeline |
[208/436] KM_10 — Kacey Musgraves
python(62174) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:55:16 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

11:55:22 | INFO | lyric_timeline |   [KM_10] 24 lines, 138 WhisperX words
11:55:24 | INFO | lyric_timeline |   [KM_10] 2 lines matched and embedded
11:55:24 | INFO | lyric_timeline |
[209/436] KM_11 — Kacey Musgraves
python(62176) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:55:31 - whisperx.asr - INFO - Detected language: en (0.92) in first 30s of audio

11:55:37 | INFO | lyric_timeline |   [KM_11] 35 lines, 101 WhisperX words
11:55:40 | INFO | lyric_timeline |   [KM_11] 5 lines matched and embedded
11:55:40 | INFO | lyric_timeline |
[210/436] KM_12 — Kacey Musgraves
python(62182) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:55:47 - whisperx.asr - INFO - Detected language: en (0.93) in first 30s of audio

11:55:51 | INFO | lyric_timeline |   [KM_12] 32 lines, 89 WhisperX words
11:55:55 | INFO | lyric_timeline |   [KM_12] 5 lines matched and embedded
11:55:55 | INFO | lyric_timeline |   Checkpoint saved (210/436 songs done)
11:55:55 | INFO | lyric_timeline |
[211/436] JP_01 — John Prine
python(62185) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:56:04 - whisperx.asr - INFO - Detected language: en (0.96) in first 30s of audio

11:56:13 | INFO | lyric_timeline |   [JP_01] 24 lines, 225 WhisperX words
11:56:16 | INFO | lyric_timeline |   [JP_01] 5 lines matched and embedded
11:56:16 | INFO | lyric_timeline |
[212/436] JP_02 — John Prine
python(62191) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:56:26 - whisperx.asr - INFO - Detected language: en (0.94) in first 30s of audio

11:56:39 | INFO | lyric_timeline |   [JP_02] 36 lines, 310 WhisperX words
11:56:50 | INFO | lyric_timeline |   [JP_02] 13 lines matched and embedded
11:56:50 | INFO | lyric_timeline |
[213/436] JP_03 — John Prine
python(62210) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:57:04 - whisperx.asr - INFO - Detected language: en (0.63) in first 30s of audio

11:57:17 | INFO | lyric_timeline |   [JP_03] 28 lines, 227 WhisperX words
11:57:26 | INFO | lyric_timeline |   [JP_03] 12 lines matched and embedded
11:57:26 | INFO | lyric_timeline |
[214/436] JP_04 — John Prine
python(62228) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:57:34 - whisperx.asr - INFO - Detected language: en (0.98) in first 30s of audio

11:57:44 | INFO | lyric_timeline |   [JP_04] 32 lines, 306 WhisperX words
11:57:55 | INFO | lyric_timeline |   [JP_04] 16 lines matched and embedded
11:57:55 | INFO | lyric_timeline |
[215/436] JP_05 — John Prine
python(62300) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:58:04 - whisperx.asr - INFO - Detected language: en (0.94) in first 30s of audio

11:58:13 | INFO | lyric_timeline |   [JP_05] 32 lines, 261 WhisperX words
11:58:22 | INFO | lyric_timeline |   [JP_05] 8 lines matched and embedded
11:58:22 | INFO | lyric_timeline |   Checkpoint saved (215/436 songs done)
11:58:22 | INFO | lyric_timeline |
[216/436] JP_06 — John Prine
python(62394) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:58:32 - whisperx.asr - INFO - Detected language: en (0.96) in first 30s of audio

11:58:44 | INFO | lyric_timeline |   [JP_06] 36 lines, 282 WhisperX words
11:58:52 | INFO | lyric_timeline |   [JP_06] 11 lines matched and embedded
11:58:52 | INFO | lyric_timeline |
[217/436] JP_07 — John Prine
python(62413) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:59:00 - whisperx.asr - INFO - Detected language: en (0.94) in first 30s of audio

11:59:09 | INFO | lyric_timeline |   [JP_07] 24 lines, 161 WhisperX words
11:59:13 | INFO | lyric_timeline |   [JP_07] 5 lines matched and embedded
11:59:13 | INFO | lyric_timeline |
[218/436] JP_08 — John Prine
python(62432) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 11:59:37 - whisperx.asr - INFO - Detected language: en (0.89) in first 30s of audio

11:59:55 | INFO | lyric_timeline |   [JP_08] 59 lines, 358 WhisperX words
12:00:03 | INFO | lyric_timeline |   [JP_08] 5 lines matched and embedded
12:00:03 | INFO | lyric_timeline |
[219/436] JP_09 — John Prine
python(62478) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:00:10 - whisperx.asr - INFO - Detected language: en (0.98) in first 30s of audio

12:00:21 | INFO | lyric_timeline |   [JP_09] 38 lines, 320 WhisperX words
12:00:29 | INFO | lyric_timeline |   [JP_09] 12 lines matched and embedded
12:00:29 | INFO | lyric_timeline |
[220/436] JP_10 — John Prine
python(62488) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:00:37 - whisperx.asr - INFO - Detected language: en (0.92) in first 30s of audio

12:00:47 | INFO | lyric_timeline |   [JP_10] 31 lines, 200 WhisperX words
12:00:52 | INFO | lyric_timeline |   [JP_10] 2 lines matched and embedded
12:00:52 | INFO | lyric_timeline |   Checkpoint saved (220/436 songs done)
12:00:52 | INFO | lyric_timeline |
[221/436] JP_11 — John Prine
python(62524) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:01:00 - whisperx.asr - INFO - Detected language: en (0.97) in first 30s of audio

12:01:11 | INFO | lyric_timeline |   [JP_11] 31 lines, 337 WhisperX words
12:01:19 | INFO | lyric_timeline |   [JP_11] 9 lines matched and embedded
12:01:19 | INFO | lyric_timeline |
[222/436] JP_12 — John Prine
python(62527) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:01:29 - whisperx.asr - INFO - Detected language: en (0.99) in first 30s of audio

12:01:39 | INFO | lyric_timeline |   [JP_12] 39 lines, 280 WhisperX words
12:01:49 | INFO | lyric_timeline |   [JP_12] 13 lines matched and embedded
12:01:49 | INFO | lyric_timeline |
[223/436] GW_01 — Gillian Welch
python(62540) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:02:01 - whisperx.asr - INFO - Detected language: en (0.85) in first 30s of audio

12:02:11 | INFO | lyric_timeline |   [GW_01] 40 lines, 194 WhisperX words
12:02:20 | INFO | lyric_timeline |   [GW_01] 13 lines matched and embedded
12:02:20 | INFO | lyric_timeline |
[224/436] GW_02 — Gillian Welch
python(62545) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:02:36 - whisperx.asr - INFO - Detected language: en (0.30) in first 30s of audio

12:02:43 | INFO | lyric_timeline |   [GW_02] 18 lines, 91 WhisperX words
12:02:48 | INFO | lyric_timeline |   [GW_02] 3 lines matched and embedded
12:02:48 | INFO | lyric_timeline |
[225/436] GW_03 — Gillian Welch
python(62568) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:03:00 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

12:03:13 | INFO | lyric_timeline |   [GW_03] 45 lines, 339 WhisperX words
12:03:18 | INFO | lyric_timeline |   [GW_03] 6 lines matched and embedded
12:03:18 | INFO | lyric_timeline |   Checkpoint saved (225/436 songs done)
12:03:18 | INFO | lyric_timeline |
[226/436] GW_04 — Gillian Welch
python(62580) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:03:27 - whisperx.asr - INFO - Detected language: en (0.60) in first 30s of audio

12:03:36 | INFO | lyric_timeline |   [GW_04] 20 lines, 114 WhisperX words
12:03:42 | INFO | lyric_timeline |   [GW_04] 2 lines matched and embedded
12:03:42 | INFO | lyric_timeline |
[227/436] GW_05 — Gillian Welch
python(62615) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:03:49 - whisperx.asr - INFO - Detected language: en (0.81) in first 30s of audio

12:03:55 | INFO | lyric_timeline |   [GW_05] 14 lines, 111 WhisperX words
12:03:57 | INFO | lyric_timeline |   [GW_05] 2 lines matched and embedded
12:03:57 | INFO | lyric_timeline |
[228/436] GW_06 — Gillian Welch
python(62637) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:04:07 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

12:04:14 | INFO | lyric_timeline |   [GW_06] 25 lines, 123 WhisperX words
12:04:18 | INFO | lyric_timeline |   [GW_06] 3 lines matched and embedded
12:04:18 | INFO | lyric_timeline |
[229/436] GW_07 — Gillian Welch
python(62641) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:04:29 - whisperx.asr - INFO - Detected language: en (0.72) in first 30s of audio

12:04:38 | INFO | lyric_timeline |   [GW_07] 30 lines, 140 WhisperX words
12:04:44 | INFO | lyric_timeline |   [GW_07] 1 lines matched and embedded
12:04:44 | INFO | lyric_timeline |
[230/436] GW_08 — Gillian Welch
python(62663) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:04:52 - whisperx.asr - INFO - Detected language: en (0.75) in first 30s of audio

12:05:01 | INFO | lyric_timeline |   [GW_08] 24 lines, 156 WhisperX words
12:05:07 | INFO | lyric_timeline |   [GW_08] 7 lines matched and embedded
12:05:07 | INFO | lyric_timeline |   Checkpoint saved (230/436 songs done)
12:05:07 | INFO | lyric_timeline |
[231/436] GW_09 — Gillian Welch
python(62667) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:05:22 - whisperx.asr - INFO - Detected language: en (0.30) in first 30s of audio

12:05:30 | INFO | lyric_timeline |   [GW_09] 18 lines, 91 WhisperX words
12:05:34 | INFO | lyric_timeline |   [GW_09] 3 lines matched and embedded
12:05:34 | INFO | lyric_timeline |
[232/436] GW_10 — Gillian Welch
python(62678) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:06:07 - whisperx.asr - INFO - Detected language: en (0.86) in first 30s of audio

12:06:33 | INFO | lyric_timeline |   [GW_10] 72 lines, 385 WhisperX words
12:06:47 | INFO | lyric_timeline |   [GW_10] 7 lines matched and embedded
12:06:47 | INFO | lyric_timeline |
[233/436] GW_11 — Gillian Welch
python(62754) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:06:55 - whisperx.asr - INFO - Detected language: en (0.58) in first 30s of audio

12:07:02 | INFO | lyric_timeline |   [GW_11] 12 lines, 83 WhisperX words
12:07:08 | INFO | lyric_timeline |   [GW_11] 6 lines matched and embedded
12:07:08 | INFO | lyric_timeline |
[234/436] GW_12 — Gillian Welch
python(62773) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:07:15 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

12:07:22 | INFO | lyric_timeline |   [GW_12] 32 lines, 171 WhisperX words
12:07:26 | INFO | lyric_timeline |   [GW_12] 5 lines matched and embedded
12:07:26 | INFO | lyric_timeline |
[235/436] CW_01 — Colter Wall
python(62777) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:07:34 - whisperx.asr - INFO - Detected language: en (0.42) in first 30s of audio

12:07:41 | INFO | lyric_timeline |   [CW_01] 33 lines, 257 WhisperX words
12:07:49 | INFO | lyric_timeline |   [CW_01] 9 lines matched and embedded
12:07:49 | INFO | lyric_timeline |   Checkpoint saved (235/436 songs done)
12:07:49 | INFO | lyric_timeline |
[236/436] CW_02 — Colter Wall
python(62790) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:07:54 - whisperx.asr - INFO - Detected language: en (0.92) in first 30s of audio

12:08:01 | INFO | lyric_timeline |   [CW_02] 22 lines, 157 WhisperX words
12:08:14 | INFO | lyric_timeline |   [CW_02] 18 lines matched and embedded
12:08:14 | INFO | lyric_timeline |
[237/436] CW_03 — Colter Wall
python(62830) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:09:08 - whisperx.asr - INFO - Detected language: en (0.51) in first 30s of audio

12:09:55 | INFO | lyric_timeline |   [CW_03] 91 lines, 1382 WhisperX words
12:10:13 | INFO | lyric_timeline |   [CW_03] 15 lines matched and embedded
12:10:13 | INFO | lyric_timeline |
[238/436] CW_04 — Colter Wall
python(62962) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:10:23 - whisperx.asr - INFO - Detected language: en (0.37) in first 30s of audio

12:10:32 | INFO | lyric_timeline |   [CW_04] 28 lines, 257 WhisperX words
12:10:37 | INFO | lyric_timeline |   [CW_04] 4 lines matched and embedded
12:10:37 | INFO | lyric_timeline |
[239/436] CW_05 — Colter Wall
python(62966) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:10:42 - whisperx.asr - INFO - Detected language: en (0.99) in first 30s of audio

12:10:52 | INFO | lyric_timeline |   [CW_05] 53 lines, 243 WhisperX words
12:10:54 | INFO | lyric_timeline |   [CW_05] 1 lines matched and embedded
12:10:54 | INFO | lyric_timeline |
[240/436] CW_06 — Colter Wall
python(62971) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:11:05 - whisperx.asr - INFO - Detected language: en (0.87) in first 30s of audio

12:11:14 | INFO | lyric_timeline |   [CW_06] 18 lines, 164 WhisperX words
12:11:19 | INFO | lyric_timeline |   [CW_06] 5 lines matched and embedded
12:11:19 | INFO | lyric_timeline |   Checkpoint saved (240/436 songs done)
12:11:19 | INFO | lyric_timeline |
[241/436] CW_07 — Colter Wall
python(62982) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:11:24 - whisperx.asr - INFO - Detected language: en (0.89) in first 30s of audio

12:11:30 | INFO | lyric_timeline |   [CW_07] 19 lines, 105 WhisperX words
12:11:30 | INFO | lyric_timeline |   [CW_07] 0 lines matched and embedded
12:11:30 | INFO | lyric_timeline |
[242/436] CW_08 — Colter Wall
python(63005) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:11:37 - whisperx.asr - INFO - Detected language: en (0.99) in first 30s of audio

12:11:47 | INFO | lyric_timeline |   [CW_08] 1664 lines, 252 WhisperX words
12:11:47 | INFO | lyric_timeline |   [CW_08] 0 lines matched and embedded
12:11:47 | INFO | lyric_timeline |
[243/436] CW_09 — Colter Wall
python(63042) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:11:56 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

12:12:08 | INFO | lyric_timeline |   [CW_09] 30 lines, 256 WhisperX words
12:12:22 | INFO | lyric_timeline |   [CW_09] 9 lines matched and embedded
12:12:22 | INFO | lyric_timeline |
[244/436] CW_10 — Colter Wall
python(63098) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:12:28 - whisperx.asr - INFO - Detected language: en (0.95) in first 30s of audio

12:12:38 | INFO | lyric_timeline |   [CW_10] 58 lines, 392 WhisperX words
12:12:51 | INFO | lyric_timeline |   [CW_10] 20 lines matched and embedded
12:12:51 | INFO | lyric_timeline |
[245/436] CW_11 — Colter Wall
python(63107) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:12:59 - whisperx.asr - INFO - Detected language: en (0.65) in first 30s of audio

12:13:05 | INFO | lyric_timeline |   [CW_11] 29 lines, 92 WhisperX words
12:13:05 | INFO | lyric_timeline |   [CW_11] 0 lines matched and embedded
12:13:05 | INFO | lyric_timeline |   Checkpoint saved (245/436 songs done)
12:13:05 | INFO | lyric_timeline |
[246/436] CW_12 — Colter Wall
python(63128) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:13:14 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

12:13:25 | INFO | lyric_timeline |   [CW_12] 349 lines, 256 WhisperX words
12:13:38 | INFO | lyric_timeline |   [CW_12] 1 lines matched and embedded
12:13:38 | INFO | lyric_timeline |
[247/436] TS_01 — Taylor Swift
python(63217) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:13:47 - whisperx.asr - INFO - Detected language: en (0.61) in first 30s of audio

12:13:54 | INFO | lyric_timeline |   [TS_01] 48 lines, 195 WhisperX words
12:13:57 | INFO | lyric_timeline |   [TS_01] 2 lines matched and embedded
12:13:57 | INFO | lyric_timeline |
[248/436] TS_02 — Taylor Swift
python(63235) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:14:06 - whisperx.asr - INFO - Detected language: en (0.85) in first 30s of audio

12:14:17 | INFO | lyric_timeline |   [TS_02] 70 lines, 410 WhisperX words
12:14:22 | INFO | lyric_timeline |   [TS_02] 6 lines matched and embedded
12:14:22 | INFO | lyric_timeline |
[249/436] TS_03 — Taylor Swift
python(63260) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:14:33 - whisperx.asr - INFO - Detected language: en (0.80) in first 30s of audio

12:14:36 | INFO | lyric_timeline |   [TS_03] 47 lines, 58 WhisperX words
12:14:36 | INFO | lyric_timeline |   [TS_03] 0 lines matched and embedded
12:14:36 | INFO | lyric_timeline |
[250/436] TS_04 — Taylor Swift
python(63269) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:14:46 - whisperx.asr - INFO - Detected language: en (0.91) in first 30s of audio

12:14:54 | INFO | lyric_timeline |   [TS_04] 82 lines, 265 WhisperX words
12:15:01 | INFO | lyric_timeline |   [TS_04] 2 lines matched and embedded
12:15:01 | INFO | lyric_timeline |   Checkpoint saved (250/436 songs done)
12:15:01 | INFO | lyric_timeline |
[251/436] TS_05 — Taylor Swift
python(63288) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:15:09 - whisperx.asr - INFO - Detected language: en (0.85) in first 30s of audio

12:15:13 | INFO | lyric_timeline |   [TS_05] 42 lines, 64 WhisperX words
12:15:15 | INFO | lyric_timeline |   [TS_05] 1 lines matched and embedded
12:15:15 | INFO | lyric_timeline |
[252/436] TS_06 — Taylor Swift
python(63344) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:15:24 - whisperx.asr - INFO - Detected language: en (0.70) in first 30s of audio

12:15:30 | INFO | lyric_timeline |   [TS_06] 67 lines, 141 WhisperX words
12:15:30 | INFO | lyric_timeline |   [TS_06] 0 lines matched and embedded
12:15:30 | INFO | lyric_timeline |
[253/436] TS_07 — Taylor Swift
python(63378) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:15:39 - whisperx.asr - INFO - Detected language: en (0.65) in first 30s of audio

12:15:48 | INFO | lyric_timeline |   [TS_07] 55 lines, 270 WhisperX words
12:15:56 | INFO | lyric_timeline |   [TS_07] 7 lines matched and embedded
12:15:56 | INFO | lyric_timeline |
[254/436] TS_08 — Taylor Swift
python(63405) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:16:07 - whisperx.asr - INFO - Detected language: en (0.83) in first 30s of audio

12:16:16 | INFO | lyric_timeline |   [TS_08] 50 lines, 311 WhisperX words
12:16:24 | INFO | lyric_timeline |   [TS_08] 12 lines matched and embedded
12:16:24 | INFO | lyric_timeline |
[255/436] TS_09 — Taylor Swift
python(63411) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:16:33 - whisperx.asr - INFO - Detected language: en (0.78) in first 30s of audio

12:16:41 | INFO | lyric_timeline |   [TS_09] 33 lines, 168 WhisperX words
12:16:44 | INFO | lyric_timeline |   [TS_09] 3 lines matched and embedded
12:16:44 | INFO | lyric_timeline |   Checkpoint saved (255/436 songs done)
12:16:44 | INFO | lyric_timeline |
[256/436] TS_10 — Taylor Swift
python(63415) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:17:07 - whisperx.asr - INFO - Detected language: en (0.62) in first 30s of audio

12:17:27 | INFO | lyric_timeline |   [TS_10] 57 lines, 623 WhisperX words
12:17:34 | INFO | lyric_timeline |   [TS_10] 9 lines matched and embedded
12:17:34 | INFO | lyric_timeline |
[257/436] TS_11 — Taylor Swift
python(63445) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:17:45 - whisperx.asr - INFO - Detected language: en (0.91) in first 30s of audio

12:17:46 | INFO | lyric_timeline |   [TS_11] WhisperX returned no words — skipping
12:17:46 | INFO | lyric_timeline |
[258/436] TS_12 — Taylor Swift
python(63466) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:17:54 - whisperx.asr - INFO - Detected language: en (0.83) in first 30s of audio

12:18:00 | INFO | lyric_timeline |   [TS_12] 64 lines, 209 WhisperX words
12:18:12 | INFO | lyric_timeline |   [TS_12] 14 lines matched and embedded
12:18:12 | INFO | lyric_timeline |
[259/436] TS_13 — Taylor Swift
python(63492) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:18:19 - whisperx.asr - INFO - Detected language: en (0.81) in first 30s of audio

12:18:22 | INFO | lyric_timeline |   [TS_13] 60 lines, 18 WhisperX words
12:18:22 | INFO | lyric_timeline |   [TS_13] 0 lines matched and embedded
12:18:22 | INFO | lyric_timeline |
[260/436] TS_14 — Taylor Swift
python(63493) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:18:30 - whisperx.asr - INFO - Detected language: en (0.59) in first 30s of audio

12:18:39 | INFO | lyric_timeline |   [TS_14] 45 lines, 297 WhisperX words
12:18:50 | INFO | lyric_timeline |   [TS_14] 15 lines matched and embedded
12:18:50 | INFO | lyric_timeline |   Checkpoint saved (260/436 songs done)
12:18:50 | INFO | lyric_timeline |
[261/436] TS_15 — Taylor Swift
python(63536) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:19:00 - whisperx.asr - INFO - Detected language: en (0.84) in first 30s of audio

12:19:08 | INFO | lyric_timeline |   [TS_15] 63 lines, 232 WhisperX words
12:19:11 | INFO | lyric_timeline |   [TS_15] 5 lines matched and embedded
12:19:11 | INFO | lyric_timeline |
[262/436] TW_01 — The Weeknd
python(63547) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:19:19 - whisperx.asr - INFO - Detected language: en (0.64) in first 30s of audio

12:19:26 | INFO | lyric_timeline |   [TW_01] 34 lines, 169 WhisperX words
12:19:29 | INFO | lyric_timeline |   [TW_01] 3 lines matched and embedded
12:19:29 | INFO | lyric_timeline |
[263/436] TW_02 — The Weeknd
python(63549) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:19:37 - whisperx.asr - INFO - Detected language: en (0.60) in first 30s of audio

12:19:43 | INFO | lyric_timeline |   [TW_02] 35 lines, 118 WhisperX words
12:19:46 | INFO | lyric_timeline |   [TW_02] 1 lines matched and embedded
12:19:46 | INFO | lyric_timeline |
[264/436] TW_03 — The Weeknd
python(63572) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:19:56 - whisperx.asr - INFO - Detected language: en (0.80) in first 30s of audio

12:20:00 | INFO | lyric_timeline |   [TW_03] 64 lines, 79 WhisperX words
12:20:00 | INFO | lyric_timeline |   [TW_03] 0 lines matched and embedded
12:20:00 | INFO | lyric_timeline |
[265/436] TW_04 — The Weeknd
python(63592) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:20:09 - whisperx.asr - INFO - Detected language: en (0.78) in first 30s of audio

12:20:16 | INFO | lyric_timeline |   [TW_04] 54 lines, 151 WhisperX words
12:20:16 | INFO | lyric_timeline |   [TW_04] 0 lines matched and embedded
12:20:16 | INFO | lyric_timeline |   Checkpoint saved (265/436 songs done)
12:20:16 | INFO | lyric_timeline |
[266/436] TW_05 — The Weeknd
python(63605) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:20:25 - whisperx.asr - INFO - Detected language: en (0.77) in first 30s of audio

12:20:32 | INFO | lyric_timeline |   [TW_05] 61 lines, 210 WhisperX words
12:20:42 | INFO | lyric_timeline |   [TW_05] 12 lines matched and embedded
12:20:42 | INFO | lyric_timeline |
[267/436] TW_06 — The Weeknd
python(63609) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:20:53 - whisperx.asr - INFO - Detected language: en (0.57) in first 30s of audio

12:21:03 | INFO | lyric_timeline |   [TW_06] 65 lines, 295 WhisperX words
12:21:03 | INFO | lyric_timeline |   [TW_06] 0 lines matched and embedded
12:21:03 | INFO | lyric_timeline |
[268/436] TW_07 — The Weeknd
python(63627) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:21:12 - whisperx.asr - INFO - Detected language: en (0.79) in first 30s of audio

12:21:22 | INFO | lyric_timeline |   [TW_07] 46 lines, 229 WhisperX words
12:21:28 | INFO | lyric_timeline |   [TW_07] 2 lines matched and embedded
12:21:28 | INFO | lyric_timeline |
[269/436] TW_08 — The Weeknd
python(63638) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:21:37 - whisperx.asr - INFO - Detected language: en (0.81) in first 30s of audio

12:21:45 | INFO | lyric_timeline |   [TW_08] 59 lines, 233 WhisperX words
12:21:48 | INFO | lyric_timeline |   [TW_08] 3 lines matched and embedded
12:21:48 | INFO | lyric_timeline |
[270/436] TW_09 — The Weeknd
python(63653) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:21:56 - whisperx.asr - INFO - Detected language: en (0.89) in first 30s of audio

12:22:00 | INFO | lyric_timeline |   [TW_09] 53 lines, 101 WhisperX words
12:22:00 | INFO | lyric_timeline |   [TW_09] 0 lines matched and embedded
12:22:00 | INFO | lyric_timeline |   Checkpoint saved (270/436 songs done)
12:22:00 | INFO | lyric_timeline |
[271/436] TW_10 — The Weeknd
python(63655) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:22:09 - whisperx.asr - INFO - Detected language: en (0.61) in first 30s of audio

12:22:13 | INFO | lyric_timeline |   [TW_10] 47 lines, 101 WhisperX words
12:22:15 | INFO | lyric_timeline |   [TW_10] 1 lines matched and embedded
12:22:15 | INFO | lyric_timeline |
[272/436] TW_11 — The Weeknd
python(63693) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:22:24 - whisperx.asr - INFO - Detected language: en (0.89) in first 30s of audio

12:22:28 | INFO | lyric_timeline |   [TW_11] 39 lines, 53 WhisperX words
12:22:35 | INFO | lyric_timeline |   [TW_11] 6 lines matched and embedded
12:22:35 | INFO | lyric_timeline |
[273/436] TW_12 — The Weeknd
python(63694) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:22:49 - whisperx.asr - INFO - Detected language: en (0.70) in first 30s of audio

12:23:01 | INFO | lyric_timeline |   [TW_12] 58 lines, 199 WhisperX words
12:23:16 | INFO | lyric_timeline |   [TW_12] 6 lines matched and embedded
12:23:16 | INFO | lyric_timeline |
[274/436] TW_14 — The Weeknd
python(63776) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:23:23 - whisperx.asr - INFO - Detected language: en (0.79) in first 30s of audio

12:23:26 | INFO | lyric_timeline |   [TW_14] 43 lines, 5 WhisperX words
12:23:26 | INFO | lyric_timeline |   [TW_14] 0 lines matched and embedded
12:23:26 | INFO | lyric_timeline |
[275/436] TW_15 — The Weeknd
python(63777) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:23:34 - whisperx.asr - INFO - Detected language: en (0.87) in first 30s of audio

12:23:40 | INFO | lyric_timeline |   [TW_15] 35 lines, 141 WhisperX words
12:23:49 | INFO | lyric_timeline |   [TW_15] 9 lines matched and embedded
12:23:49 | INFO | lyric_timeline |   Checkpoint saved (275/436 songs done)
12:23:49 | INFO | lyric_timeline |
[276/436] DL_01 — Dua Lipa
python(63788) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:23:58 - whisperx.asr - INFO - Detected language: en (0.87) in first 30s of audio

12:24:08 | INFO | lyric_timeline |   [DL_01] 68 lines, 333 WhisperX words
12:24:12 | INFO | lyric_timeline |   [DL_01] 2 lines matched and embedded
12:24:12 | INFO | lyric_timeline |
[277/436] DL_02 — Dua Lipa
python(63813) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:24:19 - whisperx.asr - INFO - Detected language: en (0.87) in first 30s of audio

12:24:22 | INFO | lyric_timeline |   [DL_02] 45 lines, 37 WhisperX words
12:24:23 | INFO | lyric_timeline |   [DL_02] 1 lines matched and embedded
12:24:23 | INFO | lyric_timeline |
[278/436] DL_03 — Dua Lipa
python(63814) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:24:31 - whisperx.asr - INFO - Detected language: en (0.88) in first 30s of audio

12:24:33 | INFO | lyric_timeline |   [DL_03] 55 lines, 15 WhisperX words
12:24:33 | INFO | lyric_timeline |   [DL_03] 0 lines matched and embedded
12:24:33 | INFO | lyric_timeline |
[279/436] DL_04 — Dua Lipa
python(63816) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:24:42 - whisperx.asr - INFO - Detected language: en (0.94) in first 30s of audio

12:24:47 | INFO | lyric_timeline |   [DL_04] 66 lines, 147 WhisperX words
12:24:52 | INFO | lyric_timeline |   [DL_04] 4 lines matched and embedded
12:24:52 | INFO | lyric_timeline |
[280/436] DL_05 — Dua Lipa
python(63828) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:25:00 - whisperx.asr - INFO - Detected language: en (0.79) in first 30s of audio

12:25:09 | INFO | lyric_timeline |   [DL_05] 49 lines, 195 WhisperX words
12:25:13 | INFO | lyric_timeline |   [DL_05] 3 lines matched and embedded
12:25:13 | INFO | lyric_timeline |   Checkpoint saved (280/436 songs done)
12:25:13 | INFO | lyric_timeline |
[281/436] DL_06 — Dua Lipa
python(63834) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:25:20 - whisperx.asr - INFO - Detected language: en (0.74) in first 30s of audio

12:25:25 | INFO | lyric_timeline |   [DL_06] 63 lines, 132 WhisperX words
12:25:29 | INFO | lyric_timeline |   [DL_06] 6 lines matched and embedded
12:25:29 | INFO | lyric_timeline |
[282/436] DL_07 — Dua Lipa
python(63835) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:25:39 - whisperx.asr - INFO - Detected language: en (0.94) in first 30s of audio

12:25:50 | INFO | lyric_timeline |   [DL_07] 67 lines, 410 WhisperX words
12:26:01 | INFO | lyric_timeline |   [DL_07] 16 lines matched and embedded
12:26:01 | INFO | lyric_timeline |
[283/436] DL_08 — Dua Lipa
python(63847) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:26:10 - whisperx.asr - INFO - Detected language: en (0.76) in first 30s of audio

12:26:22 | INFO | lyric_timeline |   [DL_08] 43 lines, 368 WhisperX words
12:26:26 | INFO | lyric_timeline |   [DL_08] 3 lines matched and embedded
12:26:26 | INFO | lyric_timeline |
[284/436] DL_09 — Dua Lipa
python(63868) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:26:33 - whisperx.asr - INFO - Detected language: en (0.85) in first 30s of audio

12:26:38 | INFO | lyric_timeline |   [DL_09] 38 lines, 132 WhisperX words
12:26:42 | INFO | lyric_timeline |   [DL_09] 5 lines matched and embedded
12:26:42 | INFO | lyric_timeline |
[285/436] DL_10 — Dua Lipa
python(63869) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:26:49 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

12:26:58 | INFO | lyric_timeline |   [DL_10] 60 lines, 252 WhisperX words
12:27:02 | INFO | lyric_timeline |   [DL_10] 3 lines matched and embedded
12:27:02 | INFO | lyric_timeline |   Checkpoint saved (285/436 songs done)
12:27:02 | INFO | lyric_timeline |
[286/436] DL_11 — Dua Lipa
python(63876) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:27:09 - whisperx.asr - INFO - Detected language: en (0.38) in first 30s of audio

12:27:14 | INFO | lyric_timeline |   [DL_11] 50 lines, 76 WhisperX words
12:27:16 | INFO | lyric_timeline |   [DL_11] 3 lines matched and embedded
12:27:16 | INFO | lyric_timeline |
[287/436] DL_12 — Dua Lipa
python(63878) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:27:26 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

12:27:40 | INFO | lyric_timeline |   [DL_12] 78 lines, 458 WhisperX words
12:27:53 | INFO | lyric_timeline |   [DL_12] 22 lines matched and embedded
12:27:53 | INFO | lyric_timeline |
[288/436] DL_13 — Dua Lipa
python(63888) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:28:02 - whisperx.asr - INFO - Detected language: en (0.80) in first 30s of audio

12:28:03 | INFO | lyric_timeline |   [DL_13] 39 lines, 12 WhisperX words
12:28:03 | INFO | lyric_timeline |   [DL_13] 0 lines matched and embedded
12:28:03 | INFO | lyric_timeline |
[289/436] DL_14 — Dua Lipa
python(63905) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:28:13 - whisperx.asr - INFO - Detected language: en (0.64) in first 30s of audio

12:28:21 | INFO | lyric_timeline |   [DL_14] 51 lines, 208 WhisperX words
12:28:24 | INFO | lyric_timeline |   [DL_14] 3 lines matched and embedded
12:28:24 | INFO | lyric_timeline |
[290/436] DL_15 — Dua Lipa
python(63906) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:28:32 - whisperx.asr - INFO - Detected language: en (0.82) in first 30s of audio

12:28:37 | INFO | lyric_timeline |   [DL_15] 38 lines, 77 WhisperX words
12:28:37 | INFO | lyric_timeline |   [DL_15] 0 lines matched and embedded
12:28:37 | INFO | lyric_timeline |   Checkpoint saved (290/436 songs done)
12:28:37 | INFO | lyric_timeline |
[291/436] AG_01 — Ariana Grande
python(63908) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:28:44 - whisperx.asr - INFO - Detected language: en (0.80) in first 30s of audio

12:28:49 | INFO | lyric_timeline |   [AG_01] 84 lines, 71 WhisperX words
12:29:04 | INFO | lyric_timeline |   [AG_01] 12 lines matched and embedded
12:29:04 | INFO | lyric_timeline |
[292/436] AG_02 — Ariana Grande
python(63994) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:29:11 - whisperx.asr - INFO - Detected language: en (0.79) in first 30s of audio

12:29:18 | INFO | lyric_timeline |   [AG_02] 50 lines, 210 WhisperX words
12:29:22 | INFO | lyric_timeline |   [AG_02] 5 lines matched and embedded
12:29:22 | INFO | lyric_timeline |
[293/436] AG_03 — Ariana Grande
python(64010) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:29:29 - whisperx.asr - INFO - Detected language: en (0.76) in first 30s of audio

12:29:33 | INFO | lyric_timeline |   [AG_03] 16 lines, 75 WhisperX words
12:29:36 | INFO | lyric_timeline |   [AG_03] 1 lines matched and embedded
12:29:36 | INFO | lyric_timeline |
[294/436] AG_04 — Ariana Grande
python(64013) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:29:46 - whisperx.asr - INFO - Detected language: en (0.76) in first 30s of audio

12:29:50 | INFO | lyric_timeline |   [AG_04] 57 lines, 140 WhisperX words
12:29:58 | INFO | lyric_timeline |   [AG_04] 4 lines matched and embedded
12:29:58 | INFO | lyric_timeline |
[295/436] AG_05 — Ariana Grande
python(64041) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:30:06 - whisperx.asr - INFO - Detected language: en (0.65) in first 30s of audio

12:30:11 | INFO | lyric_timeline |   [AG_05] 70 lines, 142 WhisperX words
12:30:15 | INFO | lyric_timeline |   [AG_05] 4 lines matched and embedded
12:30:15 | INFO | lyric_timeline |   Checkpoint saved (295/436 songs done)
12:30:15 | INFO | lyric_timeline |
[296/436] AG_06 — Ariana Grande
python(64066) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:30:23 - whisperx.asr - INFO - Detected language: en (0.70) in first 30s of audio

12:30:30 | INFO | lyric_timeline |   [AG_06] 72 lines, 113 WhisperX words
12:30:30 | INFO | lyric_timeline |   [AG_06] 0 lines matched and embedded
12:30:30 | INFO | lyric_timeline |
[297/436] AG_07 — Ariana Grande
python(64070) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:30:39 - whisperx.asr - INFO - Detected language: en (0.58) in first 30s of audio

12:30:41 | INFO | lyric_timeline |   [AG_07] 69 lines, 105 WhisperX words
12:30:41 | INFO | lyric_timeline |   [AG_07] 0 lines matched and embedded
12:30:41 | INFO | lyric_timeline |
[298/436] AG_08 — Ariana Grande
python(64081) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:30:50 - whisperx.asr - INFO - Detected language: ko (0.50) in first 30s of audio

12:30:56 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/kresnik/wav2vec2-large-xlsr-korean/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
12:30:56 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
12:30:56 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/chat_template.json "HTTP/1.1 404 Not Found"
12:30:56 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/chat_template.jinja "HTTP/1.1 404 Not Found"
12:30:56 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/audio_tokenizer_config.json "HTTP/1.1 404 Not Found"
12:30:56 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
12:30:56 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/preprocessor_config.json "HTTP/1.1 307 Temporary Redirect"
12:30:56 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/kresnik/wav2vec2-large-xlsr-korean/629c9a3501c10ba128bf3fa1eebb12af3be03f61/preprocessor_config.json "HTTP/1.1 200 OK"
12:30:56 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
12:30:56 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/preprocessor_config.json "HTTP/1.1 307 Temporary Redirect"
12:30:56 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/kresnik/wav2vec2-large-xlsr-korean/629c9a3501c10ba128bf3fa1eebb12af3be03f61/preprocessor_config.json "HTTP/1.1 200 OK"
12:30:56 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
12:30:56 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/kresnik/wav2vec2-large-xlsr-korean/629c9a3501c10ba128bf3fa1eebb12af3be03f61/config.json "HTTP/1.1 200 OK"
12:30:56 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
12:30:56 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/kresnik/wav2vec2-large-xlsr-korean/629c9a3501c10ba128bf3fa1eebb12af3be03f61/tokenizer_config.json "HTTP/1.1 200 OK"
12:30:56 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/kresnik/wav2vec2-large-xlsr-korean/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
12:30:56 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/kresnik/wav2vec2-large-xlsr-korean/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
12:30:56 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
12:30:56 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/kresnik/wav2vec2-large-xlsr-korean/629c9a3501c10ba128bf3fa1eebb12af3be03f61/config.json "HTTP/1.1 200 OK"
12:30:56 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/kresnik/wav2vec2-large-xlsr-korean/resolve/main/model.safetensors "HTTP/1.1 302 Found"

Loading weights:   0%|          | 0/424 [00:00<?, ?it/s]

12:31:12 | INFO | lyric_timeline |   [AG_08] 65 lines, 339 WhisperX words
12:31:30 | INFO | lyric_timeline |   [AG_08] 5 lines matched and embedded
12:31:30 | INFO | lyric_timeline |
[299/436] AG_09 — Ariana Grande
python(64156) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:31:39 - whisperx.asr - INFO - Detected language: en (0.42) in first 30s of audio

12:31:43 | INFO | lyric_timeline |   [AG_09] 45 lines, 81 WhisperX words
12:31:46 | INFO | lyric_timeline |   [AG_09] 2 lines matched and embedded
12:31:46 | INFO | lyric_timeline |
[300/436] AG_10 — Ariana Grande
python(64170) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:31:53 - whisperx.asr - INFO - Detected language: en (0.50) in first 30s of audio

12:31:59 | INFO | lyric_timeline |   [AG_10] 41 lines, 100 WhisperX words
12:31:59 | INFO | lyric_timeline |   [AG_10] 0 lines matched and embedded
12:31:59 | INFO | lyric_timeline |   Checkpoint saved (300/436 songs done)
12:31:59 | INFO | lyric_timeline |
[301/436] AG_11 — Ariana Grande
python(64176) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:32:05 - whisperx.asr - INFO - Detected language: en (0.88) in first 30s of audio

12:32:09 | INFO | lyric_timeline |   [AG_11] 45 lines, 94 WhisperX words
12:32:14 | INFO | lyric_timeline |   [AG_11] 2 lines matched and embedded
12:32:14 | INFO | lyric_timeline |
[302/436] AG_12 — Ariana Grande
python(64198) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:32:21 - whisperx.asr - INFO - Detected language: en (0.53) in first 30s of audio

12:32:30 | INFO | lyric_timeline |   [AG_12] 52 lines, 253 WhisperX words
12:32:35 | INFO | lyric_timeline |   [AG_12] 3 lines matched and embedded
12:32:35 | INFO | lyric_timeline |
[303/436] ES_01 — Ed Sheeran
python(64201) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:32:43 - whisperx.asr - INFO - Detected language: en (0.93) in first 30s of audio

12:32:59 | INFO | lyric_timeline |   [ES_01] 91 lines, 687 WhisperX words
12:33:07 | INFO | lyric_timeline |   [ES_01] 12 lines matched and embedded
12:33:07 | INFO | lyric_timeline |
[304/436] ES_02 — Ed Sheeran
python(64224) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:33:17 - whisperx.asr - INFO - Detected language: en (0.92) in first 30s of audio

12:33:26 | INFO | lyric_timeline |   [ES_02] 33 lines, 193 WhisperX words
12:33:30 | INFO | lyric_timeline |   [ES_02] 3 lines matched and embedded
12:33:30 | INFO | lyric_timeline |
[305/436] ES_03 — Ed Sheeran
python(64226) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:33:42 - whisperx.asr - INFO - Detected language: en (0.89) in first 30s of audio

12:33:54 | INFO | lyric_timeline |   [ES_03] 37 lines, 291 WhisperX words
12:34:03 | INFO | lyric_timeline |   [ES_03] 11 lines matched and embedded
12:34:03 | INFO | lyric_timeline |   Checkpoint saved (305/436 songs done)
12:34:03 | INFO | lyric_timeline |
[306/436] ES_04 — Ed Sheeran
python(64259) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:34:14 - whisperx.asr - INFO - Detected language: en (0.76) in first 30s of audio

12:34:24 | INFO | lyric_timeline |   [ES_04] 51 lines, 222 WhisperX words
12:34:33 | INFO | lyric_timeline |   [ES_04] 4 lines matched and embedded
12:34:33 | INFO | lyric_timeline |
[307/436] ES_05 — Ed Sheeran
python(64383) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:34:45 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

12:34:57 | INFO | lyric_timeline |   [ES_05] 45 lines, 321 WhisperX words
12:35:04 | INFO | lyric_timeline |   [ES_05] 7 lines matched and embedded
12:35:04 | INFO | lyric_timeline |
[308/436] ES_06 — Ed Sheeran
python(64413) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:35:12 - whisperx.asr - INFO - Detected language: en (0.92) in first 30s of audio

12:35:20 | INFO | lyric_timeline |   [ES_06] 50 lines, 390 WhisperX words
12:35:25 | INFO | lyric_timeline |   [ES_06] 4 lines matched and embedded
12:35:25 | INFO | lyric_timeline |
[309/436] ES_07 — Ed Sheeran
python(64415) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:35:35 - whisperx.asr - INFO - Detected language: en (0.44) in first 30s of audio

12:35:43 | INFO | lyric_timeline |   [ES_07] 43 lines, 241 WhisperX words
12:35:51 | INFO | lyric_timeline |   [ES_07] 5 lines matched and embedded
12:35:51 | INFO | lyric_timeline |
[310/436] ES_08 — Ed Sheeran
python(64442) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:36:04 - whisperx.asr - INFO - Detected language: en (0.70) in first 30s of audio

12:36:16 | INFO | lyric_timeline |   [ES_08] 59 lines, 299 WhisperX words
12:36:23 | INFO | lyric_timeline |   [ES_08] 2 lines matched and embedded
12:36:23 | INFO | lyric_timeline |   Checkpoint saved (310/436 songs done)
12:36:23 | INFO | lyric_timeline |
[311/436] ES_09 — Ed Sheeran
python(64576) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:36:40 - whisperx.asr - INFO - Detected language: en (0.83) in first 30s of audio

12:36:51 | INFO | lyric_timeline |   [ES_09] 47 lines, 173 WhisperX words
12:36:58 | INFO | lyric_timeline |   [ES_09] 3 lines matched and embedded
12:36:58 | INFO | lyric_timeline |
[312/436] ES_10 — Ed Sheeran
python(67989) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:37:16 - whisperx.asr - INFO - Detected language: en (0.82) in first 30s of audio

12:37:37 | INFO | lyric_timeline |   [ES_10] 69 lines, 321 WhisperX words
12:37:55 | INFO | lyric_timeline |   [ES_10] 11 lines matched and embedded
12:37:55 | INFO | lyric_timeline |
[313/436] ES_11 — Ed Sheeran
python(68686) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:38:07 - whisperx.asr - INFO - Detected language: en (0.83) in first 30s of audio

12:38:22 | INFO | lyric_timeline |   [ES_11] 47 lines, 382 WhisperX words
12:38:35 | INFO | lyric_timeline |   [ES_11] 11 lines matched and embedded
12:38:35 | INFO | lyric_timeline |
[314/436] ES_12 — Ed Sheeran
python(70655) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:38:45 - whisperx.asr - INFO - Detected language: en (0.86) in first 30s of audio

12:38:57 | INFO | lyric_timeline |   [ES_12] 33 lines, 224 WhisperX words
12:39:04 | INFO | lyric_timeline |   [ES_12] 6 lines matched and embedded
12:39:04 | INFO | lyric_timeline |
[315/436] BE_01 — Billie Eilish
python(72454) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:39:22 - whisperx.asr - INFO - Detected language: en (0.95) in first 30s of audio

12:39:29 | INFO | lyric_timeline |   [BE_01] 46 lines, 177 WhisperX words
12:39:46 | INFO | lyric_timeline |   [BE_01] 15 lines matched and embedded
12:39:46 | INFO | lyric_timeline |   Checkpoint saved (315/436 songs done)
12:39:46 | INFO | lyric_timeline |
[316/436] BE_02 — Billie Eilish
python(74370) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:40:02 - whisperx.asr - INFO - Detected language: en (0.84) in first 30s of audio

12:40:23 | INFO | lyric_timeline |   [BE_02] 44 lines, 278 WhisperX words
12:40:35 | INFO | lyric_timeline |   [BE_02] 8 lines matched and embedded
12:40:35 | INFO | lyric_timeline |
[317/436] BE_03 — Billie Eilish
python(74927) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:40:43 - whisperx.asr - INFO - Detected language: pt (0.55) in first 30s of audio

12:40:49 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
12:40:49 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
12:40:49 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/chat_template.json "HTTP/1.1 404 Not Found"
12:40:49 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/chat_template.jinja "HTTP/1.1 404 Not Found"
12:40:49 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/audio_tokenizer_config.json "HTTP/1.1 404 Not Found"
12:40:49 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
12:40:49 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/preprocessor_config.json "HTTP/1.1 307 Temporary Redirect"
12:40:49 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/634ac655299bcdc46c83bc01da9bab52d2987e4f/preprocessor_config.json "HTTP/1.1 200 OK"
12:40:49 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
12:40:49 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/preprocessor_config.json "HTTP/1.1 307 Temporary Redirect"
12:40:49 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/634ac655299bcdc46c83bc01da9bab52d2987e4f/preprocessor_config.json "HTTP/1.1 200 OK"
12:40:49 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
12:40:49 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/634ac655299bcdc46c83bc01da9bab52d2987e4f/config.json "HTTP/1.1 200 OK"
12:40:49 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/tokenizer_config.json "HTTP/1.1 404 Not Found"
12:40:49 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/tokenizer_config.json "HTTP/1.1 404 Not Found"
12:40:49 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
12:40:49 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
12:40:49 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/vocab.json "HTTP/1.1 307 Temporary Redirect"
12:40:49 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/634ac655299bcdc46c83bc01da9bab52d2987e4f/vocab.json "HTTP/1.1 200 OK"
12:40:49 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
12:40:49 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/634ac655299bcdc46c83bc01da9bab52d2987e4f/config.json "HTTP/1.1 200 OK"
12:40:49 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"
12:40:49 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/model.safetensors.index.json "HTTP/1.1 404 Not Found"
12:40:49 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/pytorch_model.bin "HTTP/1.1 302 Found"
12:40:49 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"
12:40:50 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese "HTTP/1.1 200 OK"
12:40:50 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/commits/main "HTTP/1.1 200 OK"
12:40:50 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/discussions?p=0 "HTTP/1.1 200 OK"
12:40:50 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/commits/refs%2Fpr%2F4 "HTTP/1.1 200 OK"
12:40:50 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/refs%2Fpr%2F4/model.safetensors.index.json "HTTP/1.1 404 Not Found"
12:40:50 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-portuguese/resolve/refs%2Fpr%2F4/model.safetensors "HTTP/1.1 302 Found"

Loading weights:   0%|          | 0/424 [00:00<?, ?it/s]

12:41:02 | INFO | lyric_timeline |   [BE_03] 42 lines, 197 WhisperX words
12:41:08 | INFO | lyric_timeline |   [BE_03] 1 lines matched and embedded
12:41:08 | INFO | lyric_timeline |
[318/436] BE_04 — Billie Eilish
python(74956) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:41:17 - whisperx.asr - INFO - Detected language: en (0.70) in first 30s of audio

12:41:25 | INFO | lyric_timeline |   [BE_04] 21 lines, 163 WhisperX words
12:41:31 | INFO | lyric_timeline |   [BE_04] 7 lines matched and embedded
12:41:31 | INFO | lyric_timeline |
[319/436] BE_05 — Billie Eilish
python(74957) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:41:39 - whisperx.asr - INFO - Detected language: en (0.88) in first 30s of audio

12:41:46 | INFO | lyric_timeline |   [BE_05] 34 lines, 116 WhisperX words
12:41:52 | INFO | lyric_timeline |   [BE_05] 6 lines matched and embedded
12:41:52 | INFO | lyric_timeline |
[320/436] BE_06 — Billie Eilish
python(74969) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:42:02 - whisperx.asr - INFO - Detected language: en (0.79) in first 30s of audio

12:42:13 | INFO | lyric_timeline |   [BE_06] 48 lines, 244 WhisperX words
12:42:23 | INFO | lyric_timeline |   [BE_06] 14 lines matched and embedded
12:42:23 | INFO | lyric_timeline |   Checkpoint saved (320/436 songs done)
12:42:23 | INFO | lyric_timeline |
[321/436] BE_07 — Billie Eilish
python(74984) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:42:31 - whisperx.asr - INFO - Detected language: en (0.95) in first 30s of audio

12:42:37 | INFO | lyric_timeline |   [BE_07] 54 lines, 167 WhisperX words
12:42:42 | INFO | lyric_timeline |   [BE_07] 3 lines matched and embedded
12:42:42 | INFO | lyric_timeline |
[322/436] BE_08 — Billie Eilish
python(74988) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:42:53 - whisperx.asr - INFO - Detected language: en (0.42) in first 30s of audio

12:43:03 | INFO | lyric_timeline |   [BE_08] 36 lines, 223 WhisperX words
12:43:11 | INFO | lyric_timeline |   [BE_08] 8 lines matched and embedded
12:43:11 | INFO | lyric_timeline |
[323/436] BE_09 — Billie Eilish
python(75015) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:43:19 - whisperx.asr - INFO - Detected language: en (0.82) in first 30s of audio

12:43:25 | INFO | lyric_timeline |   [BE_09] 34 lines, 164 WhisperX words
12:43:29 | INFO | lyric_timeline |   [BE_09] 5 lines matched and embedded
12:43:29 | INFO | lyric_timeline |
[324/436] BE_10 — Billie Eilish
python(75017) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:43:37 - whisperx.asr - INFO - Detected language: en (0.72) in first 30s of audio

12:43:44 | INFO | lyric_timeline |   [BE_10] 28 lines, 99 WhisperX words
12:43:47 | INFO | lyric_timeline |   [BE_10] 5 lines matched and embedded
12:43:47 | INFO | lyric_timeline |
[325/436] BE_11 — Billie Eilish
python(75026) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:43:58 - whisperx.asr - INFO - Detected language: en (0.86) in first 30s of audio

12:44:08 | INFO | lyric_timeline |   [BE_11] 37 lines, 237 WhisperX words
12:44:14 | INFO | lyric_timeline |   [BE_11] 6 lines matched and embedded
12:44:14 | INFO | lyric_timeline |   Checkpoint saved (325/436 songs done)
12:44:14 | INFO | lyric_timeline |
[326/436] BE_12 — Billie Eilish
python(75090) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:44:22 - whisperx.asr - INFO - Detected language: en (0.69) in first 30s of audio

12:44:30 | INFO | lyric_timeline |   [BE_12] 28 lines, 156 WhisperX words
12:44:36 | INFO | lyric_timeline |   [BE_12] 1 lines matched and embedded
12:44:36 | INFO | lyric_timeline |
[327/436] HS_01 — Harry Styles
python(75101) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:44:43 - whisperx.asr - INFO - Detected language: en (0.83) in first 30s of audio

12:44:48 | INFO | lyric_timeline |   [HS_01] 36 lines, 101 WhisperX words
12:44:52 | INFO | lyric_timeline |   [HS_01] 2 lines matched and embedded
12:44:52 | INFO | lyric_timeline |
[328/436] HS_02 — Harry Styles
python(75111) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:44:58 - whisperx.asr - INFO - Detected language: en (0.83) in first 30s of audio

12:45:05 | INFO | lyric_timeline |   [HS_02] 44 lines, 176 WhisperX words
12:45:14 | INFO | lyric_timeline |   [HS_02] 14 lines matched and embedded
12:45:15 | INFO | lyric_timeline |
[329/436] HS_03 — Harry Styles
python(75125) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:45:23 - whisperx.asr - INFO - Detected language: en (0.85) in first 30s of audio

12:45:28 | INFO | lyric_timeline |   [HS_03] 50 lines, 61 WhisperX words
12:45:29 | INFO | lyric_timeline |   [HS_03] 1 lines matched and embedded
12:45:29 | INFO | lyric_timeline |
[330/436] HS_04 — Harry Styles
python(75128) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:45:37 - whisperx.asr - INFO - Detected language: en (0.62) in first 30s of audio

12:45:42 | INFO | lyric_timeline |   [HS_04] 64 lines, 80 WhisperX words
12:45:44 | INFO | lyric_timeline |   [HS_04] 1 lines matched and embedded
12:45:44 | INFO | lyric_timeline |   Checkpoint saved (330/436 songs done)
12:45:44 | INFO | lyric_timeline |
[331/436] HS_05 — Harry Styles
python(75135) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:45:50 - whisperx.asr - INFO - Detected language: en (0.85) in first 30s of audio

12:45:54 | INFO | lyric_timeline |   [HS_05] 33 lines, 40 WhisperX words
12:45:55 | INFO | lyric_timeline |   [HS_05] 2 lines matched and embedded
12:45:55 | INFO | lyric_timeline |
[332/436] HS_06 — Harry Styles
python(75137) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:46:09 - whisperx.asr - INFO - Detected language: en (0.76) in first 30s of audio

12:46:17 | INFO | lyric_timeline |   [HS_06] 55 lines, 185 WhisperX words
12:46:29 | INFO | lyric_timeline |   [HS_06] 13 lines matched and embedded
12:46:29 | INFO | lyric_timeline |
[333/436] HS_07 — Harry Styles
python(75148) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:46:38 - whisperx.asr - INFO - Detected language: en (0.80) in first 30s of audio

12:46:51 | INFO | lyric_timeline |   [HS_07] 29 lines, 238 WhisperX words
12:46:57 | INFO | lyric_timeline |   [HS_07] 9 lines matched and embedded
12:46:57 | INFO | lyric_timeline |
[334/436] HS_08 — Harry Styles
python(75178) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:47:06 - whisperx.asr - INFO - Detected language: en (0.87) in first 30s of audio

12:47:10 | INFO | lyric_timeline |   [HS_08] 43 lines, 68 WhisperX words
12:47:18 | INFO | lyric_timeline |   [HS_08] 7 lines matched and embedded
12:47:18 | INFO | lyric_timeline |
[335/436] HS_09 — Harry Styles
python(75185) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:47:25 - whisperx.asr - INFO - Detected language: en (0.94) in first 30s of audio

12:47:33 | INFO | lyric_timeline |   [HS_09] 33 lines, 192 WhisperX words
12:47:38 | INFO | lyric_timeline |   [HS_09] 4 lines matched and embedded
12:47:38 | INFO | lyric_timeline |   Checkpoint saved (335/436 songs done)
12:47:38 | INFO | lyric_timeline |
[336/436] HS_10 — Harry Styles
python(75189) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:47:45 - whisperx.asr - INFO - Detected language: en (0.49) in first 30s of audio

12:47:50 | INFO | lyric_timeline |   [HS_10] 33 lines, 97 WhisperX words
12:47:52 | INFO | lyric_timeline |   [HS_10] 3 lines matched and embedded
12:47:52 | INFO | lyric_timeline |
[337/436] HS_11 — Harry Styles
python(75192) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:48:03 - whisperx.asr - INFO - Detected language: en (0.89) in first 30s of audio

12:48:12 | INFO | lyric_timeline |   [HS_11] 36 lines, 319 WhisperX words
12:48:21 | INFO | lyric_timeline |   [HS_11] 11 lines matched and embedded
12:48:21 | INFO | lyric_timeline |
[338/436] HS_12 — Harry Styles
python(75237) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:48:31 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

12:48:40 | INFO | lyric_timeline |   [HS_12] 57 lines, 156 WhisperX words
12:48:47 | INFO | lyric_timeline |   [HS_12] 3 lines matched and embedded
12:48:47 | INFO | lyric_timeline |
[339/436] OR_01 — Olivia Rodrigo
python(75241) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:48:55 - whisperx.asr - INFO - Detected language: en (0.66) in first 30s of audio

12:49:05 | INFO | lyric_timeline |   [OR_01] 40 lines, 224 WhisperX words
12:49:08 | INFO | lyric_timeline |   [OR_01] 1 lines matched and embedded
12:49:08 | INFO | lyric_timeline |
[340/436] OR_02 — Olivia Rodrigo
python(75256) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:49:14 - whisperx.asr - INFO - Detected language: en (0.82) in first 30s of audio

12:49:21 | INFO | lyric_timeline |   [OR_02] 53 lines, 172 WhisperX words
12:49:23 | INFO | lyric_timeline |   [OR_02] 3 lines matched and embedded
12:49:23 | INFO | lyric_timeline |   Checkpoint saved (340/436 songs done)
12:49:23 | INFO | lyric_timeline |
[341/436] OR_03 — Olivia Rodrigo
python(75257) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:49:32 - whisperx.asr - INFO - Detected language: en (0.88) in first 30s of audio

12:49:41 | INFO | lyric_timeline |   [OR_03] 40 lines, 234 WhisperX words
12:49:44 | INFO | lyric_timeline |   [OR_03] 3 lines matched and embedded
12:49:44 | INFO | lyric_timeline |
[342/436] OR_04 — Olivia Rodrigo
python(75269) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:49:50 - whisperx.asr - INFO - Detected language: en (0.89) in first 30s of audio

12:49:59 | INFO | lyric_timeline |   [OR_04] 43 lines, 219 WhisperX words
12:50:01 | INFO | lyric_timeline |   [OR_04] 4 lines matched and embedded
12:50:01 | INFO | lyric_timeline |
[343/436] OR_05 — Olivia Rodrigo
python(75276) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:50:11 - whisperx.asr - INFO - Detected language: en (0.88) in first 30s of audio

12:50:23 | INFO | lyric_timeline |   [OR_05] 44 lines, 340 WhisperX words
12:50:31 | INFO | lyric_timeline |   [OR_05] 9 lines matched and embedded
12:50:31 | INFO | lyric_timeline |
[344/436] OR_06 — Olivia Rodrigo
python(75315) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:50:38 - whisperx.asr - INFO - Detected language: en (0.83) in first 30s of audio

12:50:46 | INFO | lyric_timeline |   [OR_06] 35 lines, 188 WhisperX words
12:50:49 | INFO | lyric_timeline |   [OR_06] 2 lines matched and embedded
12:50:49 | INFO | lyric_timeline |
[345/436] OR_07 — Olivia Rodrigo
python(75320) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:50:57 - whisperx.asr - INFO - Detected language: en (0.88) in first 30s of audio

12:51:06 | INFO | lyric_timeline |   [OR_07] 50 lines, 198 WhisperX words
12:51:13 | INFO | lyric_timeline |   [OR_07] 8 lines matched and embedded
12:51:13 | INFO | lyric_timeline |   Checkpoint saved (345/436 songs done)
12:51:13 | INFO | lyric_timeline |
[346/436] OR_08 — Olivia Rodrigo
python(75415) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:51:21 - whisperx.asr - INFO - Detected language: en (0.92) in first 30s of audio

12:51:25 | INFO | lyric_timeline |   [OR_08] 70 lines, 51 WhisperX words
12:51:25 | INFO | lyric_timeline |   [OR_08] 0 lines matched and embedded
12:51:25 | INFO | lyric_timeline |
[347/436] OR_09 — Olivia Rodrigo
python(75419) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:51:34 - whisperx.asr - INFO - Detected language: en (0.86) in first 30s of audio

12:51:40 | INFO | lyric_timeline |   [OR_09] 61 lines, 124 WhisperX words
12:51:48 | INFO | lyric_timeline |   [OR_09] 2 lines matched and embedded
12:51:48 | INFO | lyric_timeline |
[348/436] OR_10 — Olivia Rodrigo
python(75470) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:51:54 - whisperx.asr - INFO - Detected language: en (0.83) in first 30s of audio

12:52:02 | INFO | lyric_timeline |   [OR_10] 29 lines, 206 WhisperX words
12:52:07 | INFO | lyric_timeline |   [OR_10] 6 lines matched and embedded
12:52:07 | INFO | lyric_timeline |
[349/436] OR_11 — Olivia Rodrigo
python(75486) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:52:15 - whisperx.asr - INFO - Detected language: en (0.67) in first 30s of audio

12:52:27 | INFO | lyric_timeline |   [OR_11] 44 lines, 351 WhisperX words
12:52:35 | INFO | lyric_timeline |   [OR_11] 8 lines matched and embedded
12:52:35 | INFO | lyric_timeline |
[350/436] OR_12 — Olivia Rodrigo
python(75518) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:52:42 - whisperx.asr - INFO - Detected language: en (0.81) in first 30s of audio

12:52:51 | INFO | lyric_timeline |   [OR_12] 33 lines, 249 WhisperX words
12:52:55 | INFO | lyric_timeline |   [OR_12] 3 lines matched and embedded
12:52:55 | INFO | lyric_timeline |   Checkpoint saved (350/436 songs done)
12:52:55 | INFO | lyric_timeline |
[351/436] DP_01 — Daft Punk
python(75522) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:53:04 - whisperx.asr - INFO - Detected language: en (0.84) in first 30s of audio

12:53:18 | INFO | lyric_timeline |   [DP_01] 112 lines, 362 WhisperX words
12:53:33 | INFO | lyric_timeline |   [DP_01] 17 lines matched and embedded
12:53:33 | INFO | lyric_timeline |
[352/436] DP_02 — Daft Punk
python(75531) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:53:42 - whisperx.asr - INFO - Detected language: en (0.40) in first 30s of audio

12:53:52 | INFO | lyric_timeline |   [DP_02] 62 lines, 339 WhisperX words
12:54:00 | INFO | lyric_timeline |   [DP_02] 10 lines matched and embedded
12:54:00 | INFO | lyric_timeline |
[353/436] DP_03 — Daft Punk
python(75534) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:54:16 - whisperx.asr - INFO - Detected language: en (0.61) in first 30s of audio

12:54:21 | INFO | lyric_timeline |   [DP_03] 40 lines, 105 WhisperX words
12:54:31 | INFO | lyric_timeline |   [DP_03] 17 lines matched and embedded
12:54:31 | INFO | lyric_timeline |
[354/436] DP_05 — Daft Punk
python(75546) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:54:45 - whisperx.asr - INFO - Detected language: en (0.39) in first 30s of audio

12:54:48 | INFO | lyric_timeline |   [DP_05] 78 lines, 47 WhisperX words
12:54:48 | INFO | lyric_timeline |   [DP_05] 0 lines matched and embedded
12:54:48 | INFO | lyric_timeline |
[355/436] DP_06 — Daft Punk
python(75555) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:54:57 - whisperx.asr - INFO - Detected language: en (0.73) in first 30s of audio

12:55:01 | INFO | lyric_timeline |   [DP_06] 116 lines, 99 WhisperX words
12:55:06 | INFO | lyric_timeline |   [DP_06] 4 lines matched and embedded
12:55:06 | INFO | lyric_timeline |   Checkpoint saved (355/436 songs done)
12:55:06 | INFO | lyric_timeline |
[356/436] DP_07 — Daft Punk
python(75586) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:55:15 - whisperx.asr - INFO - Detected language: en (0.66) in first 30s of audio

12:55:21 | INFO | lyric_timeline |   [DP_07] 12 lines, 61 WhisperX words
12:55:25 | INFO | lyric_timeline |   [DP_07] 7 lines matched and embedded
12:55:25 | INFO | lyric_timeline |
[357/436] DP_08 — Daft Punk
python(75588) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:55:38 - whisperx.asr - INFO - Detected language: en (0.67) in first 30s of audio

12:55:42 | INFO | lyric_timeline |   [DP_08] 20 lines, 92 WhisperX words
12:55:46 | INFO | lyric_timeline |   [DP_08] 2 lines matched and embedded
12:55:46 | INFO | lyric_timeline |
[358/436] DP_09 — Daft Punk
python(75620) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:55:54 - whisperx.asr - INFO - Detected language: nn (0.35) in first 30s of audio

12:55:59 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/NbAiLab/nb-wav2vec2-1b-nynorsk/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
12:55:59 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/NbAiLab/nb-wav2vec2-1b-nynorsk/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
12:55:59 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/NbAiLab/nb-wav2vec2-1b-nynorsk/resolve/main/chat_template.json "HTTP/1.1 404 Not Found"
12:55:59 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/NbAiLab/nb-wav2vec2-1b-nynorsk/resolve/main/chat_template.jinja "HTTP/1.1 404 Not Found"
12:55:59 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/NbAiLab/nb-wav2vec2-1b-nynorsk/resolve/main/audio_tokenizer_config.json "HTTP/1.1 404 Not Found"
12:55:59 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/NbAiLab/nb-wav2vec2-1b-nynorsk/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
12:55:59 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/NbAiLab/nb-wav2vec2-1b-nynorsk/resolve/main/preprocessor_config.json "HTTP/1.1 307 Temporary Redirect"
12:55:59 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/NbAiLab/nb-wav2vec2-1b-nynorsk/37107327f6af742c008042d8cfdba4276de18f82/preprocessor_config.json "HTTP/1.1 200 OK"
12:55:59 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/NbAiLab/nb-wav2vec2-1b-nynorsk/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
12:55:59 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/NbAiLab/nb-wav2vec2-1b-nynorsk/resolve/main/preprocessor_config.json "HTTP/1.1 307 Temporary Redirect"
12:55:59 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/NbAiLab/nb-wav2vec2-1b-nynorsk/37107327f6af742c008042d8cfdba4276de18f82/preprocessor_config.json "HTTP/1.1 200 OK"
12:55:59 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/NbAiLab/nb-wav2vec2-1b-nynorsk/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
12:55:59 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/NbAiLab/nb-wav2vec2-1b-nynorsk/37107327f6af742c008042d8cfdba4276de18f82/config.json "HTTP/1.1 200 OK"
12:55:59 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/NbAiLab/nb-wav2vec2-1b-nynorsk/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
12:55:59 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/NbAiLab/nb-wav2vec2-1b-nynorsk/37107327f6af742c008042d8cfdba4276de18f82/tokenizer_config.json "HTTP/1.1 200 OK"
12:55:59 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/NbAiLab/nb-wav2vec2-1b-nynorsk/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
12:55:59 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/NbAiLab/nb-wav2vec2-1b-nynorsk/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
12:55:59 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/NbAiLab/nb-wav2vec2-1b-nynorsk/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
12:55:59 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/NbAiLab/nb-wav2vec2-1b-nynorsk/37107327f6af742c008042d8cfdba4276de18f82/config.json "HTTP/1.1 200 OK"
12:55:59 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/NbAiLab/nb-wav2vec2-1b-nynorsk/resolve/main/model.safetensors "HTTP/1.1 302 Found"

Loading weights:   0%|          | 0/808 [00:00<?, ?it/s]

12:56:23 | INFO | lyric_timeline |   [DP_09] 34 lines, 113 WhisperX words
12:56:37 | INFO | lyric_timeline |   [DP_09] 10 lines matched and embedded
12:56:37 | INFO | lyric_timeline |
[359/436] DP_10 — Daft Punk
python(75686) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:56:49 - whisperx.asr - INFO - Detected language: en (0.34) in first 30s of audio

12:56:51 | INFO | lyric_timeline |   [DP_10] 34 lines, 43 WhisperX words
12:56:52 | INFO | lyric_timeline |   [DP_10] 1 lines matched and embedded
12:56:52 | INFO | lyric_timeline |
[360/436] DP_11 — Daft Punk
python(75709) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:57:03 - whisperx.asr - INFO - Detected language: en (0.27) in first 30s of audio

12:57:08 | INFO | lyric_timeline |   [DP_11] 28 lines, 116 WhisperX words
12:57:14 | INFO | lyric_timeline |   [DP_11] 8 lines matched and embedded
12:57:14 | INFO | lyric_timeline |   Checkpoint saved (360/436 songs done)
12:57:14 | INFO | lyric_timeline |
[361/436] DP_12 — Daft Punk
python(75726) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:57:26 - whisperx.asr - INFO - Detected language: en (0.67) in first 30s of audio

12:57:30 | INFO | lyric_timeline |   [DP_12] 56 lines, 39 WhisperX words
12:57:30 | INFO | lyric_timeline |   [DP_12] 0 lines matched and embedded
12:57:30 | INFO | lyric_timeline |
[362/436] DP_13 — Daft Punk
python(75729) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:57:40 - whisperx.asr - INFO - Detected language: en (0.97) in first 30s of audio

12:57:49 | INFO | lyric_timeline |   [DP_13] 116 lines, 454 WhisperX words
12:58:03 | INFO | lyric_timeline |   [DP_13] 22 lines matched and embedded
12:58:03 | INFO | lyric_timeline |
[363/436] DP_14 — Daft Punk
python(75737) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:58:24 - whisperx.asr - INFO - Detected language: en (0.30) in first 30s of audio

12:58:34 | INFO | lyric_timeline |   [DP_14] 47 lines, 129 WhisperX words
12:58:47 | INFO | lyric_timeline |   [DP_14] 8 lines matched and embedded
12:58:47 | INFO | lyric_timeline |
[364/436] DP_15 — Daft Punk
12:58:47 | INFO | lyric_timeline |   [DP_15] No usable lyric lines — skipping
12:58:47 | INFO | lyric_timeline |
[365/436] DS_01 — Disclosure
python(75776) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:58:57 - whisperx.asr - INFO - Detected language: en (0.72) in first 30s of audio

12:58:59 | INFO | lyric_timeline |   [DS_01] WhisperX returned no words — skipping
12:58:59 | INFO | lyric_timeline |   Checkpoint saved (365/436 songs done)
12:58:59 | INFO | lyric_timeline |
[366/436] DS_02 — Disclosure
python(75778) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:59:08 - whisperx.asr - INFO - Detected language: en (0.69) in first 30s of audio

12:59:11 | INFO | lyric_timeline |   [DS_02] 38 lines, 24 WhisperX words
12:59:16 | INFO | lyric_timeline |   [DS_02] 1 lines matched and embedded
12:59:16 | INFO | lyric_timeline |
[367/436] DS_03 — Disclosure
python(75784) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:59:27 - whisperx.asr - INFO - Detected language: en (0.73) in first 30s of audio

12:59:34 | INFO | lyric_timeline |   [DS_03] 44 lines, 58 WhisperX words
12:59:38 | INFO | lyric_timeline |   [DS_03] 1 lines matched and embedded
12:59:38 | INFO | lyric_timeline |
[368/436] DS_04 — Disclosure
python(75787) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 12:59:49 - whisperx.asr - INFO - Detected language: en (0.64) in first 30s of audio

12:59:55 | INFO | lyric_timeline |   [DS_04] 53 lines, 129 WhisperX words
12:59:59 | INFO | lyric_timeline |   [DS_04] 3 lines matched and embedded
12:59:59 | INFO | lyric_timeline |
[369/436] DS_05 — Disclosure
python(75798) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:00:08 - whisperx.asr - INFO - Detected language: en (0.64) in first 30s of audio

13:00:18 | INFO | lyric_timeline |   [DS_05] 42 lines, 275 WhisperX words
13:00:26 | INFO | lyric_timeline |   [DS_05] 10 lines matched and embedded
13:00:26 | INFO | lyric_timeline |
[370/436] DS_06 — Disclosure
python(75828) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:00:40 - whisperx.asr - INFO - Detected language: en (0.46) in first 30s of audio

13:00:48 | INFO | lyric_timeline |   [DS_06] 71 lines, 237 WhisperX words
13:00:58 | INFO | lyric_timeline |   [DS_06] 1 lines matched and embedded
13:00:58 | INFO | lyric_timeline |   Checkpoint saved (370/436 songs done)
13:00:58 | INFO | lyric_timeline |
[371/436] DS_07 — Disclosure
python(75925) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:01:07 - whisperx.asr - INFO - Detected language: en (0.94) in first 30s of audio

13:01:10 | INFO | lyric_timeline |   [DS_07] 26 lines, 26 WhisperX words
13:01:10 | INFO | lyric_timeline |   [DS_07] 0 lines matched and embedded
13:01:10 | INFO | lyric_timeline |
[372/436] DS_08 — Disclosure
python(75950) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:01:19 - whisperx.asr - INFO - Detected language: en (0.83) in first 30s of audio

13:01:25 | INFO | lyric_timeline |   [DS_08] 41 lines, 61 WhisperX words
13:01:28 | INFO | lyric_timeline |   [DS_08] 1 lines matched and embedded
13:01:28 | INFO | lyric_timeline |
[373/436] DS_09 — Disclosure
python(75978) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:01:38 - whisperx.asr - INFO - Detected language: en (0.66) in first 30s of audio

13:01:45 | INFO | lyric_timeline |   [DS_09] 45 lines, 192 WhisperX words
13:01:52 | INFO | lyric_timeline |   [DS_09] 9 lines matched and embedded
13:01:52 | INFO | lyric_timeline |
[374/436] DS_11 — Disclosure
python(75982) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:02:02 - whisperx.asr - INFO - Detected language: en (0.32) in first 30s of audio

13:02:11 | INFO | lyric_timeline |   [DS_11] 29 lines, 163 WhisperX words
13:02:16 | INFO | lyric_timeline |   [DS_11] 5 lines matched and embedded
13:02:16 | INFO | lyric_timeline |
[375/436] DS_12 — Disclosure
python(75987) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:02:29 - whisperx.asr - INFO - Detected language: en (0.25) in first 30s of audio

13:02:34 | INFO | lyric_timeline |   [DS_12] 2 lines, 44 WhisperX words
13:02:34 | INFO | lyric_timeline |   [DS_12] 0 lines matched and embedded
13:02:34 | INFO | lyric_timeline |   Checkpoint saved (375/436 songs done)
13:02:34 | INFO | lyric_timeline |
[376/436] DS_13 — Disclosure
python(76003) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:02:43 - whisperx.vads.pyannote - WARNING - No active speech found in audio
2026-04-21 13:02:43 - whisperx.asr - INFO - Detected language: en (0.59) in first 30s of audio

13:02:43 | WARNING | lyric_timeline |   WhisperX failed: list index out of range
13:02:43 | INFO | lyric_timeline |   [DS_13] WhisperX returned no words — skipping
13:02:43 | INFO | lyric_timeline |
[377/436] DS_14 — Disclosure
python(76010) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
13:03:08 | INFO | lyric_timeline |   [DS_14] 86 lines, 434 WhisperX words
13:03:24 | INFO | lyric_timeline |   [DS_14] 12 lines matched and embedded
13:03:24 | INFO | lyric_timeline |
[378/436] DS_15 — Disclosure
python(76051) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:03:32 - whisperx.vads.pyannote - WARNING - No active speech found in audio
2026-04-21 13:03:32 - whisperx.asr - INFO - Detected language: en (0.70) in first 30s of audio

13:03:32 | WARNING | lyric_timeline |   WhisperX failed: list index out of range
13:03:32 | INFO | lyric_timeline |   [DS_15] WhisperX returned no words — skipping
13:03:32 | INFO | lyric_timeline |
[379/436] CB_01 — Caribou
python(76052) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
13:03:48 | INFO | lyric_timeline |   [CB_01] 102 lines, 159 WhisperX words
13:03:59 | INFO | lyric_timeline |   [CB_01] 15 lines matched and embedded
13:03:59 | INFO | lyric_timeline |
[380/436] CB_02 — Caribou
13:03:59 | INFO | lyric_timeline |   [CB_02] No usable lyric lines — skipping
13:03:59 | INFO | lyric_timeline |   Checkpoint saved (380/436 songs done)
13:03:59 | INFO | lyric_timeline |
[381/436] CB_03 — Caribou
python(76062) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:04:11 - whisperx.asr - INFO - Detected language: ru (0.32) in first 30s of audio

13:04:12 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-russian/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
13:04:12 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-russian/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
13:04:12 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-russian/resolve/main/chat_template.json "HTTP/1.1 404 Not Found"
13:04:12 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-russian/resolve/main/chat_template.jinja "HTTP/1.1 404 Not Found"
13:04:12 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-russian/resolve/main/audio_tokenizer_config.json "HTTP/1.1 404 Not Found"
13:04:12 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-russian/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
13:04:12 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-russian/resolve/main/preprocessor_config.json "HTTP/1.1 307 Temporary Redirect"
13:04:12 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-russian/2329100508896c6d9b157019803ab5601e6f3406/preprocessor_config.json "HTTP/1.1 200 OK"
13:04:12 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-russian/2329100508896c6d9b157019803ab5601e6f3406/preprocessor_config.json "HTTP/1.1 200 OK"

preprocessor_config.json:   0%|          | 0.00/262 [00:00<?, ?B/s]

13:04:12 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-russian/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
13:04:12 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-russian/resolve/main/preprocessor_config.json "HTTP/1.1 307 Temporary Redirect"
13:04:12 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-russian/2329100508896c6d9b157019803ab5601e6f3406/preprocessor_config.json "HTTP/1.1 200 OK"
13:04:12 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-russian/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
13:04:12 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-russian/2329100508896c6d9b157019803ab5601e6f3406/config.json "HTTP/1.1 200 OK"
13:04:12 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-russian/2329100508896c6d9b157019803ab5601e6f3406/config.json "HTTP/1.1 200 OK"

config.json: 0.00B [00:00, ?B/s]

13:04:13 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-russian/resolve/main/tokenizer_config.json "HTTP/1.1 404 Not Found"
13:04:13 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-russian/resolve/main/tokenizer_config.json "HTTP/1.1 404 Not Found"
13:04:13 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-russian/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
13:04:13 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-russian/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
13:04:13 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-russian/resolve/main/vocab.json "HTTP/1.1 307 Temporary Redirect"
13:04:13 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-russian/2329100508896c6d9b157019803ab5601e6f3406/vocab.json "HTTP/1.1 200 OK"
13:04:13 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-russian/2329100508896c6d9b157019803ab5601e6f3406/vocab.json "HTTP/1.1 200 OK"

vocab.json:   0%|          | 0.00/387 [00:00<?, ?B/s]

13:04:13 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-russian/resolve/main/added_tokens.json "HTTP/1.1 404 Not Found"
13:04:13 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-russian/resolve/main/special_tokens_map.json "HTTP/1.1 307 Temporary Redirect"
13:04:13 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-russian/2329100508896c6d9b157019803ab5601e6f3406/special_tokens_map.json "HTTP/1.1 200 OK"
13:04:13 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-russian/2329100508896c6d9b157019803ab5601e6f3406/special_tokens_map.json "HTTP/1.1 200 OK"

special_tokens_map.json:   0%|          | 0.00/85.0 [00:00<?, ?B/s]

13:04:13 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-russian/resolve/main/tokenizer.json "HTTP/1.1 404 Not Found"
13:04:13 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-russian/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
13:04:13 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-russian/2329100508896c6d9b157019803ab5601e6f3406/config.json "HTTP/1.1 200 OK"
13:04:13 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-russian/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"
13:04:13 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-russian/resolve/main/model.safetensors.index.json "HTTP/1.1 404 Not Found"
13:04:13 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-russian/resolve/main/pytorch_model.bin "HTTP/1.1 302 Found"
13:04:13 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-russian/xet-read-token/2329100508896c6d9b157019803ab5601e6f3406 "HTTP/1.1 200 OK"

pytorch_model.bin:   0%|          | 0.00/1.26G [00:00<?, ?B/s]

13:05:50 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-russian/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"
13:05:50 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-russian "HTTP/1.1 200 OK"
13:05:50 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-russian/commits/main "HTTP/1.1 200 OK"
13:05:50 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-russian/discussions?p=0 "HTTP/1.1 200 OK"
13:05:50 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-russian/commits/refs%2Fpr%2F4 "HTTP/1.1 200 OK"
13:05:50 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-russian/resolve/refs%2Fpr%2F4/model.safetensors.index.json "HTTP/1.1 404 Not Found"
13:05:50 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-russian/resolve/refs%2Fpr%2F4/model.safetensors "HTTP/1.1 302 Found"
13:05:50 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-russian/xet-read-token/ab9492f472b7de03e79117b4187ed7bf385af3e1 "HTTP/1.1 200 OK"

model.safetensors:   0%|          | 0.00/1.26G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/424 [00:00<?, ?it/s]

13:05:51 | INFO | lyric_timeline |   [CB_03] 63 lines, 5 WhisperX words
13:05:51 | INFO | lyric_timeline |   [CB_03] 0 lines matched and embedded
13:05:51 | INFO | lyric_timeline |
[382/436] CB_04 — Caribou
python(76219) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:06:02 - whisperx.asr - INFO - Detected language: en (0.54) in first 30s of audio

13:06:05 | INFO | lyric_timeline |   [CB_04] 30 lines, 49 WhisperX words
13:06:14 | INFO | lyric_timeline |   [CB_04] 1 lines matched and embedded
13:06:14 | INFO | lyric_timeline |
[383/436] CB_05 — Caribou
python(76232) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:06:22 - whisperx.asr - INFO - Detected language: en (0.81) in first 30s of audio

13:06:25 | INFO | lyric_timeline |   [CB_05] 15 lines, 50 WhisperX words
13:06:25 | INFO | lyric_timeline |   [CB_05] 0 lines matched and embedded
13:06:25 | INFO | lyric_timeline |
[384/436] CB_07 — Caribou
python(76234) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:06:36 - whisperx.asr - INFO - Detected language: en (0.55) in first 30s of audio

13:06:37 | INFO | lyric_timeline |   [CB_07] WhisperX returned no words — skipping
13:06:37 | INFO | lyric_timeline |
[385/436] CB_08 — Caribou
python(76242) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:06:49 - whisperx.asr - INFO - Detected language: en (0.51) in first 30s of audio

13:06:50 | INFO | lyric_timeline |   [CB_08] WhisperX returned no words — skipping
13:06:50 | INFO | lyric_timeline |   Checkpoint saved (385/436 songs done)
13:06:50 | INFO | lyric_timeline |
[386/436] CB_09 — Caribou
python(76243) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:06:57 - whisperx.asr - INFO - Detected language: en (0.74) in first 30s of audio

13:07:03 | INFO | lyric_timeline |   [CB_09] 24 lines, 117 WhisperX words
13:07:12 | INFO | lyric_timeline |   [CB_09] 4 lines matched and embedded
13:07:12 | INFO | lyric_timeline |
[387/436] CB_10 — Caribou
python(76264) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:07:23 - whisperx.asr - INFO - Detected language: en (0.38) in first 30s of audio

13:07:26 | INFO | lyric_timeline |   [CB_10] 70 lines, 53 WhisperX words
13:07:31 | INFO | lyric_timeline |   [CB_10] 6 lines matched and embedded
13:07:31 | INFO | lyric_timeline |
[388/436] CB_11 — Caribou
python(76266) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:07:39 - whisperx.asr - INFO - Detected language: en (0.77) in first 30s of audio

13:07:40 | INFO | lyric_timeline |   [CB_11] 37 lines, 6 WhisperX words
13:07:40 | INFO | lyric_timeline |   [CB_11] 0 lines matched and embedded
13:07:40 | INFO | lyric_timeline |
[389/436] CB_12 — Caribou
python(76267) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:07:51 - whisperx.asr - INFO - Detected language: en (0.44) in first 30s of audio

13:08:00 | INFO | lyric_timeline |   [CB_12] 21 lines, 75 WhisperX words
13:08:00 | INFO | lyric_timeline |   [CB_12] 0 lines matched and embedded
13:08:00 | INFO | lyric_timeline |
[390/436] JB_01 — James Blake
python(76342) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:08:06 - whisperx.asr - INFO - Detected language: en (0.76) in first 30s of audio

13:08:13 | INFO | lyric_timeline |   [JB_01] 31 lines, 109 WhisperX words
13:08:20 | INFO | lyric_timeline |   [JB_01] 6 lines matched and embedded
13:08:20 | INFO | lyric_timeline |   Checkpoint saved (390/436 songs done)
13:08:20 | INFO | lyric_timeline |
[391/436] JB_02 — James Blake
python(76361) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:08:28 - whisperx.asr - INFO - Detected language: en (0.64) in first 30s of audio

13:08:34 | INFO | lyric_timeline |   [JB_02] 35 lines, 106 WhisperX words
13:08:39 | INFO | lyric_timeline |   [JB_02] 3 lines matched and embedded
13:08:39 | INFO | lyric_timeline |
[392/436] JB_03 — James Blake
python(76368) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:08:50 - whisperx.asr - INFO - Detected language: en (0.54) in first 30s of audio

13:08:52 | INFO | lyric_timeline |   [JB_03] 48 lines, 9 WhisperX words
13:08:52 | INFO | lyric_timeline |   [JB_03] 0 lines matched and embedded
13:08:52 | INFO | lyric_timeline |
[393/436] JB_04 — James Blake
python(76385) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:09:04 - whisperx.asr - INFO - Detected language: en (0.76) in first 30s of audio

13:09:15 | INFO | lyric_timeline |   [JB_04] 31 lines, 241 WhisperX words
13:09:26 | INFO | lyric_timeline |   [JB_04] 7 lines matched and embedded
13:09:26 | INFO | lyric_timeline |
[394/436] JB_05 — James Blake
python(76394) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:09:35 - whisperx.asr - INFO - Detected language: en (0.81) in first 30s of audio

13:09:38 | INFO | lyric_timeline |   [JB_05] 33 lines, 35 WhisperX words
13:09:42 | INFO | lyric_timeline |   [JB_05] 1 lines matched and embedded
13:09:42 | INFO | lyric_timeline |
[395/436] JB_06 — James Blake
python(76399) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:09:54 - whisperx.asr - INFO - Detected language: en (0.68) in first 30s of audio

13:09:59 | INFO | lyric_timeline |   [JB_06] 32 lines, 52 WhisperX words
13:10:02 | INFO | lyric_timeline |   [JB_06] 2 lines matched and embedded
13:10:02 | INFO | lyric_timeline |   Checkpoint saved (395/436 songs done)
13:10:02 | INFO | lyric_timeline |
[396/436] JB_07 — James Blake
python(76405) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:10:13 - whisperx.asr - INFO - Detected language: en (0.74) in first 30s of audio

13:10:16 | INFO | lyric_timeline |   [JB_07] 8 lines, 7 WhisperX words
13:10:18 | INFO | lyric_timeline |   [JB_07] 1 lines matched and embedded
13:10:18 | INFO | lyric_timeline |
[397/436] JB_08 — James Blake
python(76407) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:10:28 - whisperx.asr - INFO - Detected language: en (0.53) in first 30s of audio

13:10:38 | INFO | lyric_timeline |   [JB_08] 50 lines, 251 WhisperX words
13:10:47 | INFO | lyric_timeline |   [JB_08] 12 lines matched and embedded
13:10:47 | INFO | lyric_timeline |
[398/436] JB_09 — James Blake
python(76408) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:10:57 - whisperx.asr - INFO - Detected language: en (0.82) in first 30s of audio

13:11:06 | INFO | lyric_timeline |   [JB_09] 24 lines, 83 WhisperX words
13:11:10 | INFO | lyric_timeline |   [JB_09] 1 lines matched and embedded
13:11:10 | INFO | lyric_timeline |
[399/436] JB_10 — James Blake
python(76411) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:11:22 - whisperx.asr - INFO - Detected language: en (0.87) in first 30s of audio

13:11:34 | INFO | lyric_timeline |   [JB_10] 41 lines, 268 WhisperX words
13:11:39 | INFO | lyric_timeline |   [JB_10] 2 lines matched and embedded
13:11:39 | INFO | lyric_timeline |
[400/436] JB_11 — James Blake
python(76445) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:11:49 - whisperx.asr - INFO - Detected language: en (0.63) in first 30s of audio

13:11:59 | INFO | lyric_timeline |   [JB_11] 55 lines, 126 WhisperX words
13:12:03 | INFO | lyric_timeline |   [JB_11] 2 lines matched and embedded
13:12:03 | INFO | lyric_timeline |   Checkpoint saved (400/436 songs done)
13:12:03 | INFO | lyric_timeline |
[401/436] JB_12 — James Blake
python(76449) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:12:13 - whisperx.asr - INFO - Detected language: en (0.91) in first 30s of audio

13:12:25 | INFO | lyric_timeline |   [JB_12] 75 lines, 332 WhisperX words
13:12:31 | INFO | lyric_timeline |   [JB_12] 2 lines matched and embedded
13:12:31 | INFO | lyric_timeline |
[402/436] LCD_01 — LCD Soundsystem
python(76457) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:12:49 - whisperx.asr - INFO - Detected language: en (0.37) in first 30s of audio

13:12:57 | INFO | lyric_timeline |   [LCD_01] 56 lines, 156 WhisperX words
13:13:00 | INFO | lyric_timeline |   [LCD_01] 2 lines matched and embedded
13:13:00 | INFO | lyric_timeline |
[403/436] LCD_02 — LCD Soundsystem
python(76459) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:13:13 - whisperx.asr - INFO - Detected language: en (0.91) in first 30s of audio

13:13:17 | INFO | lyric_timeline |   [LCD_02] 47 lines, 91 WhisperX words
13:13:23 | INFO | lyric_timeline |   [LCD_02] 3 lines matched and embedded
13:13:23 | INFO | lyric_timeline |
[404/436] LCD_03 — LCD Soundsystem
python(76473) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:13:41 - whisperx.asr - INFO - Detected language: en (0.63) in first 30s of audio

13:13:44 | INFO | lyric_timeline |   [LCD_03] 50 lines, 72 WhisperX words
13:13:44 | INFO | lyric_timeline |   [LCD_03] 0 lines matched and embedded
13:13:44 | INFO | lyric_timeline |
[405/436] LCD_04 — LCD Soundsystem
python(76482) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:13:55 - whisperx.asr - INFO - Detected language: zh (0.60) in first 30s of audio

13:14:01 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
13:14:01 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
13:14:01 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/chat_template.json "HTTP/1.1 404 Not Found"
13:14:01 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/chat_template.jinja "HTTP/1.1 404 Not Found"
13:14:01 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/audio_tokenizer_config.json "HTTP/1.1 404 Not Found"
13:14:01 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
13:14:01 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/preprocessor_config.json "HTTP/1.1 307 Temporary Redirect"
13:14:01 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/99ccb2737be22b8bb50dcfcc39ad4d567fb90cfd/preprocessor_config.json "HTTP/1.1 200 OK"
13:14:01 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
13:14:01 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/99ccb2737be22b8bb50dcfcc39ad4d567fb90cfd/config.json "HTTP/1.1 200 OK"
13:14:01 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
13:14:01 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/preprocessor_config.json "HTTP/1.1 307 Temporary Redirect"
13:14:01 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/99ccb2737be22b8bb50dcfcc39ad4d567fb90cfd/preprocessor_config.json "HTTP/1.1 200 OK"
13:14:01 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
13:14:01 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/99ccb2737be22b8bb50dcfcc39ad4d567fb90cfd/config.json "HTTP/1.1 200 OK"
13:14:01 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/tokenizer_config.json "HTTP/1.1 404 Not Found"
13:14:01 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/tokenizer_config.json "HTTP/1.1 404 Not Found"
13:14:01 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
13:14:01 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
13:14:01 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/vocab.json "HTTP/1.1 307 Temporary Redirect"
13:14:01 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/99ccb2737be22b8bb50dcfcc39ad4d567fb90cfd/vocab.json "HTTP/1.1 200 OK"
13:14:01 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
13:14:01 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/99ccb2737be22b8bb50dcfcc39ad4d567fb90cfd/config.json "HTTP/1.1 200 OK"
13:14:01 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"
13:14:02 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/model.safetensors.index.json "HTTP/1.1 404 Not Found"
13:14:02 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/pytorch_model.bin "HTTP/1.1 302 Found"
13:14:02 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"
13:14:02 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn "HTTP/1.1 200 OK"
13:14:02 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/commits/main "HTTP/1.1 200 OK"
13:14:02 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/discussions?p=0 "HTTP/1.1 200 OK"
13:14:02 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/commits/refs%2Fpr%2F5 "HTTP/1.1 200 OK"
13:14:02 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/refs%2Fpr%2F5/model.safetensors.index.json "HTTP/1.1 404 Not Found"
13:14:02 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn/resolve/refs%2Fpr%2F5/model.safetensors "HTTP/1.1 302 Found"

Loading weights:   0%|          | 0/424 [00:00<?, ?it/s]

13:14:09 | INFO | lyric_timeline |   [LCD_04] 54 lines, 860 WhisperX words
13:14:09 | INFO | lyric_timeline |   [LCD_04] 0 lines matched and embedded
13:14:09 | INFO | lyric_timeline |   Checkpoint saved (405/436 songs done)
13:14:09 | INFO | lyric_timeline |
[406/436] LCD_05 — LCD Soundsystem
python(76485) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:14:17 - whisperx.asr - INFO - Detected language: en (0.57) in first 30s of audio

13:14:19 | INFO | lyric_timeline |   [LCD_05] WhisperX returned no words — skipping
13:14:19 | INFO | lyric_timeline |
[407/436] LCD_06 — LCD Soundsystem
python(76488) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:14:32 - whisperx.asr - INFO - Detected language: en (0.58) in first 30s of audio

13:14:37 | INFO | lyric_timeline |   [LCD_06] 73 lines, 107 WhisperX words
13:14:46 | INFO | lyric_timeline |   [LCD_06] 2 lines matched and embedded
13:14:46 | INFO | lyric_timeline |
[408/436] LCD_07 — LCD Soundsystem
python(76495) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:15:03 - whisperx.asr - INFO - Detected language: en (0.55) in first 30s of audio

13:15:10 | INFO | lyric_timeline |   [LCD_07] 51 lines, 132 WhisperX words
13:15:13 | INFO | lyric_timeline |   [LCD_07] 3 lines matched and embedded
13:15:13 | INFO | lyric_timeline |
[409/436] LCD_08 — LCD Soundsystem
python(76503) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:15:27 - whisperx.asr - INFO - Detected language: en (0.18) in first 30s of audio

13:15:32 | INFO | lyric_timeline |   [LCD_08] 35 lines, 51 WhisperX words
13:15:32 | INFO | lyric_timeline |   [LCD_08] 0 lines matched and embedded
13:15:32 | INFO | lyric_timeline |
[410/436] LCD_09 — LCD Soundsystem
python(76505) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:15:44 - whisperx.asr - INFO - Detected language: en (0.52) in first 30s of audio

13:15:46 | INFO | lyric_timeline |   [LCD_09] 36 lines, 11 WhisperX words
13:15:46 | INFO | lyric_timeline |   [LCD_09] 0 lines matched and embedded
13:15:46 | INFO | lyric_timeline |   Checkpoint saved (410/436 songs done)
13:15:46 | INFO | lyric_timeline |
[411/436] LCD_10 — LCD Soundsystem
python(76507) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:15:59 - whisperx.asr - INFO - Detected language: en (0.73) in first 30s of audio

13:16:15 | INFO | lyric_timeline |   [LCD_10] 67 lines, 521 WhisperX words
13:16:24 | INFO | lyric_timeline |   [LCD_10] 8 lines matched and embedded
13:16:24 | INFO | lyric_timeline |
[412/436] LCD_11 — LCD Soundsystem
python(76512) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:16:36 - whisperx.asr - INFO - Detected language: en (0.47) in first 30s of audio

13:16:39 | INFO | lyric_timeline |   [LCD_11] 29 lines, 35 WhisperX words
13:16:39 | INFO | lyric_timeline |   [LCD_11] 0 lines matched and embedded
13:16:39 | INFO | lyric_timeline |
[413/436] LCD_12 — LCD Soundsystem
python(76513) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:17:00 - whisperx.asr - INFO - Detected language: en (0.43) in first 30s of audio

13:17:03 | INFO | lyric_timeline |   [LCD_12] 82 lines, 36 WhisperX words
13:17:09 | INFO | lyric_timeline |   [LCD_12] 1 lines matched and embedded
13:17:09 | INFO | lyric_timeline |
[414/436] BN_01 — Bonobo
python(76522) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:17:18 - whisperx.asr - INFO - Detected language: en (0.56) in first 30s of audio

13:17:21 | INFO | lyric_timeline |   [BN_01] WhisperX returned no words — skipping
13:17:21 | INFO | lyric_timeline |
[415/436] BN_02 — Bonobo
python(76524) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:17:30 - whisperx.asr - INFO - Detected language: en (0.72) in first 30s of audio

13:17:32 | INFO | lyric_timeline |   [BN_02] 29 lines, 11 WhisperX words
13:17:32 | INFO | lyric_timeline |   [BN_02] 0 lines matched and embedded
13:17:32 | INFO | lyric_timeline |   Checkpoint saved (415/436 songs done)
13:17:32 | INFO | lyric_timeline |
[416/436] BN_03 — Bonobo
python(76525) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:17:49 - whisperx.asr - INFO - Detected language: en (0.36) in first 30s of audio

13:17:53 | INFO | lyric_timeline |   [BN_03] 139 lines, 14 WhisperX words
13:17:53 | INFO | lyric_timeline |   [BN_03] 0 lines matched and embedded
13:17:53 | INFO | lyric_timeline |
[417/436] BN_04 — Bonobo
python(76526) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:18:03 - whisperx.asr - INFO - Detected language: en (0.59) in first 30s of audio

13:18:09 | INFO | lyric_timeline |   [BN_04] 32 lines, 108 WhisperX words
13:18:16 | INFO | lyric_timeline |   [BN_04] 1 lines matched and embedded
13:18:16 | INFO | lyric_timeline |
[418/436] BN_05 — Bonobo
python(76529) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:18:23 - whisperx.asr - INFO - Detected language: en (0.39) in first 30s of audio

13:18:27 | INFO | lyric_timeline |   [BN_05] 13 lines, 21 WhisperX words
13:18:27 | INFO | lyric_timeline |   [BN_05] 0 lines matched and embedded
13:18:27 | INFO | lyric_timeline |
[419/436] BN_06 — Bonobo
python(76531) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:18:36 - whisperx.asr - INFO - Detected language: en (0.65) in first 30s of audio

13:18:44 | INFO | lyric_timeline |   [BN_06] 51 lines, 170 WhisperX words
13:18:49 | INFO | lyric_timeline |   [BN_06] 4 lines matched and embedded
13:18:49 | INFO | lyric_timeline |
[420/436] BN_07 — Bonobo
13:18:49 | INFO | lyric_timeline |   [BN_07] No usable lyric lines — skipping
13:18:49 | INFO | lyric_timeline |   Checkpoint saved (420/436 songs done)
13:18:49 | INFO | lyric_timeline |
[421/436] BN_08 — Bonobo
python(76538) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:20:57 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

13:21:17 | INFO | lyric_timeline |   [BN_08] 66 lines, 470 WhisperX words
13:21:31 | INFO | lyric_timeline |   [BN_08] 1 lines matched and embedded
13:21:31 | INFO | lyric_timeline |
[422/436] BN_09 — Bonobo
python(76622) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:21:40 - whisperx.asr - INFO - Detected language: en (0.29) in first 30s of audio

13:21:42 | INFO | lyric_timeline |   [BN_09] 44 lines, 12 WhisperX words
13:21:44 | INFO | lyric_timeline |   [BN_09] 2 lines matched and embedded
13:21:44 | INFO | lyric_timeline |
[423/436] BN_10 — Bonobo
python(76624) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:21:52 - whisperx.asr - INFO - Detected language: en (0.51) in first 30s of audio

13:21:54 | INFO | lyric_timeline |   [BN_10] WhisperX returned no words — skipping
13:21:54 | INFO | lyric_timeline |
[424/436] BN_11 — Bonobo
python(76625) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:22:05 - whisperx.asr - INFO - Detected language: en (0.35) in first 30s of audio

13:22:07 | INFO | lyric_timeline |   [BN_11] 7 lines, 7 WhisperX words
13:22:07 | INFO | lyric_timeline |   [BN_11] 0 lines matched and embedded
13:22:07 | INFO | lyric_timeline |
[425/436] GZ_01 — Gorillaz
python(76627) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:22:16 - whisperx.asr - INFO - Detected language: en (0.34) in first 30s of audio

13:22:19 | INFO | lyric_timeline |   [GZ_01] 65 lines, 43 WhisperX words
13:22:19 | INFO | lyric_timeline |   [GZ_01] 0 lines matched and embedded
13:22:19 | INFO | lyric_timeline |   Checkpoint saved (425/436 songs done)
13:22:19 | INFO | lyric_timeline |
[426/436] GZ_02 — Gorillaz
python(76628) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:22:26 - whisperx.asr - INFO - Detected language: en (0.47) in first 30s of audio

13:22:28 | INFO | lyric_timeline |   [GZ_02] 52 lines, 20 WhisperX words
13:22:31 | INFO | lyric_timeline |   [GZ_02] 4 lines matched and embedded
13:22:31 | INFO | lyric_timeline |
[427/436] GZ_03 — Gorillaz
python(76629) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:22:45 - whisperx.asr - INFO - Detected language: en (0.78) in first 30s of audio

13:22:57 | INFO | lyric_timeline |   [GZ_03] 74 lines, 485 WhisperX words
13:23:03 | INFO | lyric_timeline |   [GZ_03] 6 lines matched and embedded
13:23:03 | INFO | lyric_timeline |
[428/436] GZ_04 — Gorillaz
python(76642) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:23:11 - whisperx.asr - INFO - Detected language: en (0.42) in first 30s of audio

13:23:16 | INFO | lyric_timeline |   [GZ_04] 18 lines, 72 WhisperX words
13:23:21 | INFO | lyric_timeline |   [GZ_04] 7 lines matched and embedded
13:23:21 | INFO | lyric_timeline |
[429/436] GZ_05 — Gorillaz
python(76643) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:23:29 - whisperx.asr - INFO - Detected language: en (0.90) in first 30s of audio

13:23:36 | INFO | lyric_timeline |   [GZ_05] 38 lines, 158 WhisperX words
13:23:41 | INFO | lyric_timeline |   [GZ_05] 5 lines matched and embedded
13:23:41 | INFO | lyric_timeline |
[430/436] GZ_06 — Gorillaz
python(76646) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:23:52 - whisperx.asr - INFO - Detected language: en (0.58) in first 30s of audio

13:23:58 | INFO | lyric_timeline |   [GZ_06] 66 lines, 141 WhisperX words
13:24:00 | INFO | lyric_timeline |   [GZ_06] 3 lines matched and embedded
13:24:00 | INFO | lyric_timeline |   Checkpoint saved (430/436 songs done)
13:24:00 | INFO | lyric_timeline |
[431/436] GZ_07 — Gorillaz
python(76648) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:24:12 - whisperx.asr - INFO - Detected language: en (0.46) in first 30s of audio

13:24:18 | INFO | lyric_timeline |   [GZ_07] 26 lines, 76 WhisperX words
13:24:21 | INFO | lyric_timeline |   [GZ_07] 3 lines matched and embedded
13:24:21 | INFO | lyric_timeline |
[432/436] GZ_08 — Gorillaz
python(76653) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:24:29 - whisperx.asr - INFO - Detected language: en (0.96) in first 30s of audio

13:24:36 | INFO | lyric_timeline |   [GZ_08] 63 lines, 160 WhisperX words
13:24:43 | INFO | lyric_timeline |   [GZ_08] 9 lines matched and embedded
13:24:43 | INFO | lyric_timeline |
[433/436] GZ_09 — Gorillaz
python(76665) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:24:54 - whisperx.asr - INFO - Detected language: en (0.92) in first 30s of audio

13:24:57 | INFO | lyric_timeline |   [GZ_09] 40 lines, 74 WhisperX words
13:25:01 | INFO | lyric_timeline |   [GZ_09] 1 lines matched and embedded
13:25:01 | INFO | lyric_timeline |
[434/436] GZ_10 — Gorillaz
python(76676) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:25:07 - whisperx.asr - INFO - Detected language: en (0.63) in first 30s of audio

13:25:08 | INFO | lyric_timeline |   [GZ_10] 32 lines, 11 WhisperX words
13:25:08 | INFO | lyric_timeline |   [GZ_10] 0 lines matched and embedded
13:25:08 | INFO | lyric_timeline |
[435/436] GZ_11 — Gorillaz
python(76677) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:25:20 - whisperx.asr - INFO - Detected language: en (0.79) in first 30s of audio

13:25:24 | INFO | lyric_timeline |   [GZ_11] 76 lines, 133 WhisperX words
13:25:26 | INFO | lyric_timeline |   [GZ_11] 1 lines matched and embedded
13:25:26 | INFO | lyric_timeline |   Checkpoint saved (435/436 songs done)
13:25:26 | INFO | lyric_timeline |
[436/436] GZ_12 — Gorillaz
python(76679) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

2026-04-21 13:25:35 - whisperx.asr - INFO - Detected language: en (0.33) in first 30s of audio

13:25:41 | INFO | lyric_timeline |   [GZ_12] 72 lines, 141 WhisperX words
13:25:43 | INFO | lyric_timeline |   [GZ_12] 1 lines matched and embedded
13:25:43 | INFO | lyric_timeline |   Checkpoint saved (436/436 songs done)
13:25:43 | INFO | lyric_timeline |
============================================================
13:25:43 | INFO | lyric_timeline | Timeline complete.
13:25:43 | INFO | lyric_timeline |   Rows    : 2,087
13:25:43 | INFO | lyric_timeline |   Songs   : 366
13:25:43 | INFO | lyric_timeline |   LMC mean: 0.2513
13:25:43 | INFO | lyric_timeline |   LMC sd  : 0.1095
13:25:43 | INFO | lyric_timeline |   Output  : /Users/budge.13/Desktop/Music Analysis/results/lyric_timeline/lyric_timeline.csv

Timeline: 2,087 lines across 366 songs
Mean LMC: 0.2513  |  SD: 0.1095

,song_id,artist_name,genre,orientation,line_idx,line_text,line_words,match_start_s,match_end_s,window_start_s,window_end_s,position_pct,total_duration_s,lmc,match_confidence
0,RTJ_01,Run the Jewels,hip-hop,narrative,0,"Run, run, run, run, run",5,50.413,79.041,45.413,84.041,31.101,208.120,0.233961,0.400
1,RTJ_01,Run the Jewels,hip-hop,narrative,8,Better hide all the snacks and the dough,8,147.829,149.330,142.829,154.330,71.391,208.120,0.283325,0.250
2,RTJ_02,Run the Jewels,hip-hop,narrative,1,"I presented the evidence, eloquent as the Pres...",8,57.016,58.978,52.016,63.978,33.808,171.549,0.161249,0.250
3,RTJ_03,Run the Jewels,hip-hop,narrative,4,Move like Jesus die like a martyr,7,82.183,83.404,77.183,88.404,47.880,172.919,0.160052,0.286
4,RTJ_03,Run the Jewels,hip-hop,narrative,13,"Bad hoes, we in the DR",6,145.648,146.969,140.648,151.969,84.611,172.919,0.201795,0.333
5,RTJ_05,Run the Jewels,hip-hop,narrative,0,Really fell out the lane with this shit,8,27.834,29.957,22.834,34.957,13.008,222.144,0.182380,0.375
6,RTJ_05,Run the Jewels,hip-hop,narrative,1,"Man, print this shit: I'm a misfit",7,31.198,32.659,26.198,37.659,14.373,222.144,0.131243,0.286
7,RTJ_05,Run the Jewels,hip-hop,narrative,3,Born to the next-gen system,5,36.924,37.825,31.924,42.825,16.824,222.144,0.060803,0.400
8,RTJ_05,Run the Jewels,hip-hop,narrative,21,"I don't only bite, but I'm rabid",7,156.167,157.348,151.167,162.348,70.566,222.144,0.336220,0.286
9,RTJ_06,Run the Jewels,hip-hop,narrative,0,"Killer Mike and El-P, fuck boys know the combi...",11,0.411,4.596,0.000,9.596,1.391,180.001,0.234441,0.636

---
## Step 11 - Mood

In [14]:
pip install essentia

python(82237) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Collecting essentia
  Downloading essentia-2.1b6.dev1389-cp313-cp313-macosx_15_0_arm64.whl.metadata (2.0 kB)
Requirement already satisfied: numpy>=1.25 in /opt/anaconda3/lib/python3.13/site-packages (from essentia) (1.26.4)
Requirement already satisfied: pyyaml in /opt/anaconda3/lib/python3.13/site-packages (from essentia) (6.0.2)
Requirement already satisfied: six in /opt/anaconda3/lib/python3.13/site-packages (from essentia) (1.17.0)
Downloading essentia-2.1b6.dev1389-cp313-cp313-macosx_15_0_arm64.whl (20.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.4/20.4 MB 15.8 MB/s eta 0:00:00 MB/s eta 0:00:0101
Installing collected packages: essentia
Successfully installed essentia-2.1b6.dev1389
Note: you may need to restart the kernel to use updated packages.

In [22]:
mood_extractor = load_script("extract_mood", "11_extract_mood.py")
mood_csv = mood_extractor.extract_all_mood(force=False)

16:27:04 | INFO | extract_mood | Resuming — 0 songs already extracted.
16:27:04 | INFO | extract_mood | Extracting features for 440 songs (librosa, no TF)...
16:27:04 | INFO | extract_mood | [1/440] RTJ_01
16:27:14 | INFO | extract_mood | [2/440] RTJ_02
16:27:18 | INFO | extract_mood | [3/440] RTJ_03
16:27:22 | INFO | extract_mood | [4/440] RTJ_04
16:27:26 | INFO | extract_mood | [5/440] RTJ_05
16:27:30 | INFO | extract_mood | [6/440] RTJ_06
16:27:34 | INFO | extract_mood | [7/440] RTJ_07
16:27:38 | INFO | extract_mood | [8/440] RTJ_08
16:27:42 | INFO | extract_mood | [9/440] RTJ_09
16:27:46 | INFO | extract_mood | [10/440] RTJ_10
16:27:50 | INFO | extract_mood |   Checkpoint (10/440 done)
16:27:50 | INFO | extract_mood | [11/440] RTJ_11
16:27:54 | INFO | extract_mood | [12/440] RTJ_12
16:27:58 | INFO | extract_mood | [13/440] RTJ_13
16:28:02 | INFO | extract_mood | [14/440] RTJ_14
16:28:06 | INFO | extract_mood | [15/440] RTJ_15
16:28:10 | INFO | extract_mood | [16/440] KL_01
16:28:14 | INFO | extract_mood | [17/440] KL_02
16:28:18 | INFO | extract_mood | [18/440] KL_03
16:28:22 | INFO | extract_mood | [19/440] KL_04
16:28:26 | INFO | extract_mood | [20/440] KL_05
16:28:30 | INFO | extract_mood |   Checkpoint (20/440 done)
16:28:30 | INFO | extract_mood | [21/440] KL_06
16:28:34 | INFO | extract_mood | [22/440] KL_07
16:28:38 | INFO | extract_mood | [23/440] KL_08
16:28:42 | INFO | extract_mood | [24/440] KL_09
16:28:46 | INFO | extract_mood | [25/440] KL_10
16:28:50 | INFO | extract_mood | [26/440] KL_11
16:28:54 | INFO | extract_mood | [27/440] KL_12
16:28:58 | INFO | extract_mood | [28/440] KL_13
16:29:02 | INFO | extract_mood | [29/440] KL_14
16:29:06 | INFO | extract_mood | [30/440] KL_15
16:29:10 | INFO | extract_mood |   Checkpoint (30/440 done)
16:29:10 | INFO | extract_mood | [31/440] JC_01
16:29:14 | INFO | extract_mood | [32/440] JC_02
16:29:18 | INFO | extract_mood | [33/440] JC_03
16:29:22 | INFO | extract_mood | [34/440] JC_04
16:29:26 | INFO | extract_mood | [35/440] JC_05
16:29:30 | INFO | extract_mood | [36/440] JC_06
16:29:34 | INFO | extract_mood | [37/440] JC_07
16:29:38 | INFO | extract_mood | [38/440] JC_08
16:29:42 | INFO | extract_mood | [39/440] JC_09
16:29:46 | INFO | extract_mood | [40/440] JC_10
16:29:50 | INFO | extract_mood |   Checkpoint (40/440 done)
16:29:50 | INFO | extract_mood | [41/440] JC_11
16:29:54 | INFO | extract_mood | [42/440] JC_12
16:29:58 | INFO | extract_mood | [43/440] JC_13
16:30:02 | INFO | extract_mood | [44/440] JC_14
16:30:06 | INFO | extract_mood | [45/440] JC_15
16:30:10 | INFO | extract_mood | [46/440] DR_01
16:30:14 | INFO | extract_mood | [47/440] DR_02
16:30:18 | INFO | extract_mood | [48/440] DR_03
16:30:22 | INFO | extract_mood | [49/440] DR_04
16:30:26 | INFO | extract_mood | [50/440] DR_05
16:30:30 | INFO | extract_mood |   Checkpoint (50/440 done)
16:30:30 | INFO | extract_mood | [51/440] DR_06
16:30:35 | INFO | extract_mood | [52/440] DR_07
16:30:39 | INFO | extract_mood | [53/440] DR_08
16:30:43 | INFO | extract_mood | [54/440] DR_09
16:30:47 | INFO | extract_mood | [55/440] DR_10
16:30:51 | INFO | extract_mood | [56/440] DR_11
16:30:55 | INFO | extract_mood | [57/440] DR_12
16:30:59 | INFO | extract_mood | [58/440] EM_01
16:31:03 | INFO | extract_mood | [59/440] EM_02
16:31:07 | INFO | extract_mood | [60/440] EM_03
16:31:11 | INFO | extract_mood |   Checkpoint (60/440 done)
16:31:11 | INFO | extract_mood | [61/440] EM_04
16:31:15 | INFO | extract_mood | [62/440] EM_05
16:31:19 | INFO | extract_mood | [63/440] EM_06
16:31:23 | INFO | extract_mood | [64/440] EM_07
16:31:27 | INFO | extract_mood | [65/440] EM_08
16:31:31 | INFO | extract_mood | [66/440] EM_09
16:31:35 | INFO | extract_mood | [67/440] EM_10
16:31:39 | INFO | extract_mood | [68/440] EM_11
16:31:43 | INFO | extract_mood | [69/440] EM_12
16:31:47 | INFO | extract_mood | [70/440] TC2_01
16:31:51 | INFO | extract_mood |   Checkpoint (70/440 done)
16:31:51 | INFO | extract_mood | [71/440] TC2_02
16:31:56 | INFO | extract_mood | [72/440] TC2_03
16:32:00 | INFO | extract_mood | [73/440] TC2_04
16:32:04 | INFO | extract_mood | [74/440] TC2_05
16:32:08 | INFO | extract_mood | [75/440] TC2_06
16:32:12 | INFO | extract_mood | [76/440] TC2_07
16:32:16 | INFO | extract_mood | [77/440] TC2_08
16:32:20 | INFO | extract_mood | [78/440] TC2_09
16:32:24 | INFO | extract_mood | [79/440] TC2_10
16:32:28 | INFO | extract_mood | [80/440] TC2_11
16:32:32 | INFO | extract_mood |   Checkpoint (80/440 done)
16:32:32 | INFO | extract_mood | [81/440] TC2_12
16:32:36 | INFO | extract_mood | [82/440] MM_01
16:32:40 | INFO | extract_mood | [83/440] MM_02
16:32:44 | INFO | extract_mood | [84/440] MM_03
16:32:48 | INFO | extract_mood | [85/440] MM_04
16:32:52 | INFO | extract_mood | [86/440] MM_05
16:32:56 | INFO | extract_mood | [87/440] MM_06
16:33:00 | INFO | extract_mood | [88/440] MM_07
16:33:05 | INFO | extract_mood | [89/440] MM_08
16:33:09 | INFO | extract_mood | [90/440] MM_09
16:33:13 | INFO | extract_mood |   Checkpoint (90/440 done)
16:33:13 | INFO | extract_mood | [91/440] MM_10
16:33:17 | INFO | extract_mood | [92/440] MM_11
16:33:21 | INFO | extract_mood | [93/440] MM_12
16:33:26 | INFO | extract_mood | [94/440] CH_01
16:33:30 | INFO | extract_mood | [95/440] CH_02
16:33:34 | INFO | extract_mood | [96/440] CH_03
16:33:38 | INFO | extract_mood | [97/440] CH_04
16:33:42 | INFO | extract_mood | [98/440] CH_05
16:33:46 | INFO | extract_mood | [99/440] CH_06
16:33:50 | INFO | extract_mood | [100/440] CH_07
16:33:54 | INFO | extract_mood |   Checkpoint (100/440 done)
16:33:54 | INFO | extract_mood | [101/440] CH_08
16:33:59 | INFO | extract_mood | [102/440] CH_09
16:34:03 | INFO | extract_mood | [103/440] CH_10
16:34:07 | INFO | extract_mood | [104/440] CH_11
16:34:11 | INFO | extract_mood | [105/440] CH_12
16:34:16 | INFO | extract_mood | [106/440] NS_01
16:34:20 | INFO | extract_mood | [107/440] NS_02
16:34:24 | INFO | extract_mood | [108/440] NS_03
16:34:28 | INFO | extract_mood | [109/440] NS_04
16:34:33 | INFO | extract_mood | [110/440] NS_05
16:34:37 | INFO | extract_mood |   Checkpoint (110/440 done)
16:34:37 | INFO | extract_mood | [111/440] NS_06
16:34:41 | INFO | extract_mood | [112/440] NS_07
16:34:45 | INFO | extract_mood | [113/440] NS_08
16:34:50 | INFO | extract_mood | [114/440] NS_09
16:34:54 | INFO | extract_mood | [115/440] NS_10
16:34:58 | INFO | extract_mood | [116/440] NS_11
16:35:02 | INFO | extract_mood | [117/440] NS_12
16:35:06 | INFO | extract_mood | [118/440] CG_01
16:35:10 | INFO | extract_mood | [119/440] CG_02
16:35:15 | INFO | extract_mood | [120/440] CG_03
16:35:19 | INFO | extract_mood |   Checkpoint (120/440 done)
16:35:19 | INFO | extract_mood | [121/440] CG_04
16:35:24 | INFO | extract_mood | [122/440] CG_05
16:35:28 | INFO | extract_mood | [123/440] CG_06
16:35:32 | INFO | extract_mood | [124/440] CG_07
16:35:36 | INFO | extract_mood | [125/440] CG_08
16:35:41 | INFO | extract_mood | [126/440] CG_09
16:35:45 | INFO | extract_mood | [127/440] CG_10
16:35:50 | INFO | extract_mood | [128/440] CG_11
16:35:54 | INFO | extract_mood | [129/440] CG_12
16:35:58 | INFO | extract_mood | [130/440] GD_01
16:36:02 | INFO | extract_mood |   Checkpoint (130/440 done)
16:36:02 | INFO | extract_mood | [131/440] GD_02
16:36:07 | INFO | extract_mood | [132/440] GD_03
16:36:11 | INFO | extract_mood | [133/440] GD_04
16:36:15 | INFO | extract_mood | [134/440] GD_05
16:36:19 | INFO | extract_mood | [135/440] GD_06
16:36:23 | INFO | extract_mood | [136/440] GD_07
16:36:27 | INFO | extract_mood | [137/440] GD_08
16:36:32 | INFO | extract_mood | [138/440] GD_09
16:36:36 | INFO | extract_mood | [139/440] GD_10
16:36:40 | INFO | extract_mood | [140/440] GD_11
16:36:44 | INFO | extract_mood |   Checkpoint (140/440 done)
16:36:44 | INFO | extract_mood | [141/440] GD_12
16:36:48 | INFO | extract_mood | [142/440] GD_13
16:36:53 | INFO | extract_mood | [143/440] GD_14
16:36:57 | INFO | extract_mood | [144/440] GD_15
16:37:01 | INFO | extract_mood | [145/440] BD_01
16:37:05 | INFO | extract_mood | [146/440] BD_02
16:37:09 | INFO | extract_mood | [147/440] BD_03
16:37:13 | INFO | extract_mood | [148/440] BD_04
16:37:17 | INFO | extract_mood | [149/440] BD_05
16:37:21 | INFO | extract_mood | [150/440] BD_06
16:37:26 | INFO | extract_mood |   Checkpoint (150/440 done)
16:37:26 | INFO | extract_mood | [151/440] BD_07
16:37:30 | INFO | extract_mood | [152/440] BD_08
16:37:34 | INFO | extract_mood | [153/440] BD_09
16:37:38 | INFO | extract_mood | [154/440] BD_10
16:37:42 | INFO | extract_mood | [155/440] BD_11
16:37:46 | INFO | extract_mood | [156/440] BD_12
16:37:50 | INFO | extract_mood | [157/440] BD_13
16:37:54 | INFO | extract_mood | [158/440] BD_14
16:37:58 | INFO | extract_mood | [159/440] BD_15
16:38:02 | INFO | extract_mood | [160/440] TC_01
16:38:06 | INFO | extract_mood |   Checkpoint (160/440 done)
16:38:06 | INFO | extract_mood | [161/440] TC_02
16:38:11 | INFO | extract_mood | [162/440] TC_03
16:38:15 | INFO | extract_mood | [163/440] TC_04
16:38:19 | INFO | extract_mood | [164/440] TC_05
16:38:23 | INFO | extract_mood | [165/440] TC_06
16:38:27 | INFO | extract_mood | [166/440] TC_07
16:38:31 | INFO | extract_mood | [167/440] TC_08
16:38:35 | INFO | extract_mood | [168/440] TC_09
16:38:39 | INFO | extract_mood | [169/440] TC_10
16:38:43 | INFO | extract_mood | [170/440] TC_11
16:38:47 | INFO | extract_mood |   Checkpoint (170/440 done)
16:38:47 | INFO | extract_mood | [171/440] TC_12
16:38:51 | INFO | extract_mood | [172/440] TC_13
16:38:55 | INFO | extract_mood | [173/440] TC_14
16:38:59 | INFO | extract_mood | [174/440] TC_15
16:39:03 | INFO | extract_mood | [175/440] JI_01
16:39:08 | INFO | extract_mood | [176/440] JI_02
16:39:12 | INFO | extract_mood | [177/440] JI_03
16:39:16 | INFO | extract_mood | [178/440] JI_04
16:39:20 | INFO | extract_mood | [179/440] JI_05
16:39:24 | INFO | extract_mood | [180/440] JI_06
16:39:28 | INFO | extract_mood |   Checkpoint (180/440 done)
16:39:28 | INFO | extract_mood | [181/440] JI_07
16:39:32 | INFO | extract_mood | [182/440] JI_08
16:39:36 | INFO | extract_mood | [183/440] JI_09
16:39:40 | INFO | extract_mood | [184/440] JI_10
16:39:44 | INFO | extract_mood | [185/440] JI_11
16:39:48 | INFO | extract_mood | [186/440] JI_12
16:39:52 | INFO | extract_mood | [187/440] SS_01
16:39:56 | INFO | extract_mood | [188/440] SS_02
16:40:00 | INFO | extract_mood | [189/440] SS_03
16:40:04 | INFO | extract_mood | [190/440] SS_04
16:40:09 | INFO | extract_mood |   Checkpoint (190/440 done)
16:40:09 | INFO | extract_mood | [191/440] SS_05
16:40:13 | INFO | extract_mood | [192/440] SS_06
16:40:17 | INFO | extract_mood | [193/440] SS_07
16:40:21 | INFO | extract_mood | [194/440] SS_08
16:40:25 | INFO | extract_mood | [195/440] SS_09
16:40:29 | INFO | extract_mood | [196/440] SS_10
16:40:33 | INFO | extract_mood | [197/440] SS_11
16:40:38 | INFO | extract_mood | [198/440] SS_12
16:40:42 | INFO | extract_mood | [199/440] KM_01
16:40:46 | INFO | extract_mood | [200/440] KM_02
16:40:50 | INFO | extract_mood |   Checkpoint (200/440 done)
16:40:50 | INFO | extract_mood | [201/440] KM_03
16:40:54 | INFO | extract_mood | [202/440] KM_04
16:40:58 | INFO | extract_mood | [203/440] KM_05
16:41:02 | INFO | extract_mood | [204/440] KM_06
16:41:06 | INFO | extract_mood | [205/440] KM_07
16:41:10 | INFO | extract_mood | [206/440] KM_08
16:41:14 | INFO | extract_mood | [207/440] KM_09
16:41:18 | INFO | extract_mood | [208/440] KM_10
16:41:22 | INFO | extract_mood | [209/440] KM_11
16:41:26 | INFO | extract_mood | [210/440] KM_12
16:41:31 | INFO | extract_mood |   Checkpoint (210/440 done)
16:41:31 | INFO | extract_mood | [211/440] JP_01
16:41:35 | INFO | extract_mood | [212/440] JP_02
16:41:39 | INFO | extract_mood | [213/440] JP_03
16:41:43 | INFO | extract_mood | [214/440] JP_04
16:41:47 | INFO | extract_mood | [215/440] JP_05
16:41:51 | INFO | extract_mood | [216/440] JP_06
16:41:55 | INFO | extract_mood | [217/440] JP_07
16:41:59 | INFO | extract_mood | [218/440] JP_08
16:42:03 | INFO | extract_mood | [219/440] JP_09
16:42:07 | INFO | extract_mood | [220/440] JP_10
16:42:11 | INFO | extract_mood |   Checkpoint (220/440 done)
16:42:11 | INFO | extract_mood | [221/440] JP_11
16:42:15 | INFO | extract_mood | [222/440] JP_12
16:42:19 | INFO | extract_mood | [223/440] GW_01
16:42:23 | INFO | extract_mood | [224/440] GW_02
16:42:27 | INFO | extract_mood | [225/440] GW_03
16:42:31 | INFO | extract_mood | [226/440] GW_04
16:42:35 | INFO | extract_mood | [227/440] GW_05
16:42:39 | INFO | extract_mood | [228/440] GW_06
16:42:43 | INFO | extract_mood | [229/440] GW_07
16:42:47 | INFO | extract_mood | [230/440] GW_08
16:42:51 | INFO | extract_mood |   Checkpoint (230/440 done)
16:42:51 | INFO | extract_mood | [231/440] GW_09
16:42:55 | INFO | extract_mood | [232/440] GW_10
16:43:00 | INFO | extract_mood | [233/440] GW_11
16:43:04 | INFO | extract_mood | [234/440] GW_12
16:43:08 | INFO | extract_mood | [235/440] CW_01
16:43:12 | INFO | extract_mood | [236/440] CW_02
16:43:16 | INFO | extract_mood | [237/440] CW_03
16:43:20 | INFO | extract_mood | [238/440] CW_04
16:43:24 | INFO | extract_mood | [239/440] CW_05
16:43:28 | INFO | extract_mood | [240/440] CW_06
16:43:32 | INFO | extract_mood |   Checkpoint (240/440 done)
16:43:32 | INFO | extract_mood | [241/440] CW_07
16:43:36 | INFO | extract_mood | [242/440] CW_08
16:43:40 | INFO | extract_mood | [243/440] CW_09
16:43:44 | INFO | extract_mood | [244/440] CW_10
16:43:48 | INFO | extract_mood | [245/440] CW_11
16:43:52 | INFO | extract_mood | [246/440] CW_12
16:43:57 | INFO | extract_mood | [247/440] TS_01
16:44:01 | INFO | extract_mood | [248/440] TS_02
16:44:05 | INFO | extract_mood | [249/440] TS_03
16:44:09 | INFO | extract_mood | [250/440] TS_04
16:44:13 | INFO | extract_mood |   Checkpoint (250/440 done)
16:44:13 | INFO | extract_mood | [251/440] TS_05
16:44:17 | INFO | extract_mood | [252/440] TS_06
16:44:21 | INFO | extract_mood | [253/440] TS_07
16:44:26 | INFO | extract_mood | [254/440] TS_08
16:44:30 | INFO | extract_mood | [255/440] TS_09
16:44:34 | INFO | extract_mood | [256/440] TS_10
16:44:38 | INFO | extract_mood | [257/440] TS_11
16:44:42 | INFO | extract_mood | [258/440] TS_12
16:44:46 | INFO | extract_mood | [259/440] TS_13
16:44:51 | INFO | extract_mood | [260/440] TS_14
16:44:55 | INFO | extract_mood |   Checkpoint (260/440 done)
16:44:55 | INFO | extract_mood | [261/440] TS_15
16:44:59 | INFO | extract_mood | [262/440] TW_01
16:45:03 | INFO | extract_mood | [263/440] TW_02
16:45:07 | INFO | extract_mood | [264/440] TW_03
16:45:11 | INFO | extract_mood | [265/440] TW_04
16:45:15 | INFO | extract_mood | [266/440] TW_05
16:45:19 | INFO | extract_mood | [267/440] TW_06
16:45:23 | INFO | extract_mood | [268/440] TW_07
16:45:27 | INFO | extract_mood | [269/440] TW_08
16:45:31 | INFO | extract_mood | [270/440] TW_09
16:45:36 | INFO | extract_mood |   Checkpoint (270/440 done)
16:45:36 | INFO | extract_mood | [271/440] TW_10
16:45:40 | INFO | extract_mood | [272/440] TW_11
16:45:44 | INFO | extract_mood | [273/440] TW_12
16:45:48 | INFO | extract_mood | [274/440] TW_13
16:45:52 | INFO | extract_mood | [275/440] TW_14
16:45:56 | INFO | extract_mood | [276/440] TW_15
16:46:00 | INFO | extract_mood | [277/440] DL_01
16:46:04 | INFO | extract_mood | [278/440] DL_02
16:46:08 | INFO | extract_mood | [279/440] DL_03
16:46:12 | INFO | extract_mood | [280/440] DL_04
16:46:16 | INFO | extract_mood |   Checkpoint (280/440 done)
16:46:16 | INFO | extract_mood | [281/440] DL_05
16:46:21 | INFO | extract_mood | [282/440] DL_06
16:46:25 | INFO | extract_mood | [283/440] DL_07
16:46:29 | INFO | extract_mood | [284/440] DL_08
16:46:33 | INFO | extract_mood | [285/440] DL_09
16:46:37 | INFO | extract_mood | [286/440] DL_10
16:46:41 | INFO | extract_mood | [287/440] DL_11
16:46:45 | INFO | extract_mood | [288/440] DL_12
16:46:49 | INFO | extract_mood | [289/440] DL_13
16:46:53 | INFO | extract_mood | [290/440] DL_14
16:46:57 | INFO | extract_mood |   Checkpoint (290/440 done)
16:46:57 | INFO | extract_mood | [291/440] DL_15
16:47:01 | INFO | extract_mood | [292/440] AG_01
16:47:06 | INFO | extract_mood | [293/440] AG_02
16:47:10 | INFO | extract_mood | [294/440] AG_03
16:47:14 | INFO | extract_mood | [295/440] AG_04
16:47:18 | INFO | extract_mood | [296/440] AG_05
16:47:22 | INFO | extract_mood | [297/440] AG_06
16:47:26 | INFO | extract_mood | [298/440] AG_07
16:47:30 | INFO | extract_mood | [299/440] AG_08
16:47:34 | INFO | extract_mood | [300/440] AG_09
16:47:38 | INFO | extract_mood |   Checkpoint (300/440 done)
16:47:38 | INFO | extract_mood | [301/440] AG_10
16:47:43 | INFO | extract_mood | [302/440] AG_11
16:47:47 | INFO | extract_mood | [303/440] AG_12
16:47:51 | INFO | extract_mood | [304/440] ES_01
16:47:55 | INFO | extract_mood | [305/440] ES_02
16:47:59 | INFO | extract_mood | [306/440] ES_03
16:48:03 | INFO | extract_mood | [307/440] ES_04
16:48:07 | INFO | extract_mood | [308/440] ES_05
16:48:12 | INFO | extract_mood | [309/440] ES_06
16:48:16 | INFO | extract_mood | [310/440] ES_07
16:48:20 | INFO | extract_mood |   Checkpoint (310/440 done)
16:48:20 | INFO | extract_mood | [311/440] ES_08
16:48:24 | INFO | extract_mood | [312/440] ES_09
16:48:28 | INFO | extract_mood | [313/440] ES_10
16:48:32 | INFO | extract_mood | [314/440] ES_11
16:48:36 | INFO | extract_mood | [315/440] ES_12
16:48:40 | INFO | extract_mood | [316/440] BE_01
16:48:44 | INFO | extract_mood | [317/440] BE_02
16:48:48 | INFO | extract_mood | [318/440] BE_03
16:48:52 | INFO | extract_mood | [319/440] BE_04
16:48:57 | INFO | extract_mood | [320/440] BE_05
16:49:01 | INFO | extract_mood |   Checkpoint (320/440 done)
16:49:01 | INFO | extract_mood | [321/440] BE_06
16:49:05 | INFO | extract_mood | [322/440] BE_07
16:49:09 | INFO | extract_mood | [323/440] BE_08
16:49:13 | INFO | extract_mood | [324/440] BE_09
16:49:17 | INFO | extract_mood | [325/440] BE_10
16:49:22 | INFO | extract_mood | [326/440] BE_11
16:49:26 | INFO | extract_mood | [327/440] BE_12
16:49:30 | INFO | extract_mood | [328/440] HS_01
16:49:34 | INFO | extract_mood | [329/440] HS_02
16:49:38 | INFO | extract_mood | [330/440] HS_03
16:49:42 | INFO | extract_mood |   Checkpoint (330/440 done)
16:49:42 | INFO | extract_mood | [331/440] HS_04
16:49:46 | INFO | extract_mood | [332/440] HS_05
16:49:50 | INFO | extract_mood | [333/440] HS_06
16:49:54 | INFO | extract_mood | [334/440] HS_07
16:49:59 | INFO | extract_mood | [335/440] HS_08
16:50:03 | INFO | extract_mood | [336/440] HS_09
16:50:07 | INFO | extract_mood | [337/440] HS_10
16:50:11 | INFO | extract_mood | [338/440] HS_11
16:50:15 | INFO | extract_mood | [339/440] HS_12
16:50:19 | INFO | extract_mood | [340/440] OR_01
16:50:23 | INFO | extract_mood |   Checkpoint (340/440 done)
16:50:23 | INFO | extract_mood | [341/440] OR_02
16:50:27 | INFO | extract_mood | [342/440] OR_03
16:50:31 | INFO | extract_mood | [343/440] OR_04
16:50:35 | INFO | extract_mood | [344/440] OR_05
16:50:39 | INFO | extract_mood | [345/440] OR_06
16:50:43 | INFO | extract_mood | [346/440] OR_07
16:50:48 | INFO | extract_mood | [347/440] OR_08
16:50:52 | INFO | extract_mood | [348/440] OR_09
16:50:56 | INFO | extract_mood | [349/440] OR_10
16:51:00 | INFO | extract_mood | [350/440] OR_11
16:51:04 | INFO | extract_mood |   Checkpoint (350/440 done)
16:51:04 | INFO | extract_mood | [351/440] OR_12
16:51:08 | INFO | extract_mood | [352/440] DP_01
16:51:12 | INFO | extract_mood | [353/440] DP_02
16:51:16 | INFO | extract_mood | [354/440] DP_03
16:51:20 | INFO | extract_mood | [355/440] DP_04
16:51:24 | INFO | extract_mood | [356/440] DP_05
16:51:28 | INFO | extract_mood | [357/440] DP_06
16:51:33 | INFO | extract_mood | [358/440] DP_07
16:51:37 | INFO | extract_mood | [359/440] DP_08
16:51:41 | INFO | extract_mood | [360/440] DP_09
16:51:45 | INFO | extract_mood |   Checkpoint (360/440 done)
16:51:45 | INFO | extract_mood | [361/440] DP_10

---
## Quick Sanity Check
A fast inline look at the data before handing off to R:  
LMC distributions per model, popularity by genre cluster, and a raw correlation table.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

df = master_df.copy()
lmc_cols = ["lmc_mulan", "lmc_clap", "lmc_mert_sbert"]
lmc_labels = ["MuQ-MuLan", "LAION-CLAP-Music", "MERT+SBERT"]

genre_order = ["Hip-Hop", "Folk/Country", "Pop", "Electronic"]
genre_map   = {
    "hip-hop": "Hip-Hop",
    "folk-rock": "Folk/Country", "folk": "Folk/Country", "country": "Folk/Country",
    "pop": "Pop",
    "electronic": "Electronic", "psychedelic-electronic": "Electronic",
}
df["genre_cluster"] = df["genre"].map(genre_map).fillna("Other")

COLORS = {"Hip-Hop": "#E63946", "Folk/Country": "#2A9D8F",
          "Pop": "#457B9D", "Electronic": "#9B2335"}

fig = plt.figure(figsize=(16, 11))
gs  = gridspec.GridSpec(2, 3, figure=fig, hspace=0.4, wspace=0.35)

# ── Row 1: LMC distributions by model ────────────────────────────────────────
for col_idx, (col, label) in enumerate(zip(lmc_cols, lmc_labels)):
    ax = fig.add_subplot(gs[0, col_idx])
    data = df.dropna(subset=[col])
    for gc, grp in data.groupby("genre_cluster"):
        if gc in COLORS:
            ax.hist(grp[col], bins=12, alpha=0.55, label=gc,
                    color=COLORS.get(gc), edgecolor="white")
    ax.set_title(label, fontweight="bold")
    ax.set_xlabel("LMC Score")
    ax.set_ylabel("Count" if col_idx == 0 else "")
    if col_idx == 2:
        ax.legend(fontsize=7, loc="upper left")

# ── Row 2, col 1: Popularity by genre cluster ─────────────────────────────────
ax2 = fig.add_subplot(gs[1, 0])
pop_data = df.dropna(subset=["popularity", "genre_cluster"])
genre_pops = [pop_data[pop_data["genre_cluster"]==g]["popularity"].dropna().values
              for g in genre_order]
bp = ax2.boxplot(genre_pops, labels=genre_order, patch_artist=True, notch=False)
for patch, gc in zip(bp["boxes"], genre_order):
    patch.set_facecolor(COLORS.get(gc, "grey"))
    patch.set_alpha(0.7)
ax2.set_title("Popularity by Genre Cluster", fontweight="bold")
ax2.set_ylabel("Spotify Popularity")
ax2.tick_params(axis="x", labelsize=8)

# ── Row 2, col 2: LMC (MuLan) vs. Popularity scatter ─────────────────────────
ax3 = fig.add_subplot(gs[1, 1])
scatter_df = df.dropna(subset=["lmc_mulan", "popularity"])
for gc in genre_order:
    grp = scatter_df[scatter_df["genre_cluster"] == gc]
    ax3.scatter(grp["lmc_mulan"], grp["popularity"],
                color=COLORS.get(gc), alpha=0.7, s=40, label=gc)
if len(scatter_df) >= 3:
    z = np.polyfit(scatter_df["lmc_mulan"], scatter_df["popularity"], 1)
    xr = np.linspace(scatter_df["lmc_mulan"].min(), scatter_df["lmc_mulan"].max(), 100)
    ax3.plot(xr, np.polyval(z, xr), color="black", linewidth=1.5, linestyle="--")
    r = np.corrcoef(scatter_df["lmc_mulan"], scatter_df["popularity"])[0,1]
    ax3.set_title(f"LMC (MuLan) vs. Popularity  (r = {r:.3f})", fontweight="bold")
ax3.set_xlabel("LMC Score (MuQ-MuLan)")
ax3.set_ylabel("Spotify Popularity")

# ── Row 2, col 3: Correlation table (text) ────────────────────────────────────
ax4 = fig.add_subplot(gs[1, 2])
ax4.axis("off")
corr_cols = ["popularity"] + lmc_cols
corr_df   = df[corr_cols].dropna()
if len(corr_df) >= 3:
    corr_mat = corr_df.corr().round(3)
    short_names = ["Popularity", "MuLan", "CLAP", "MERT+SBERT"]
    rows = [[short_names[i]] + [f"{corr_mat.iloc[i,j]:.3f}" for j in range(len(corr_cols))]
            for i in range(len(corr_cols))]
    tbl = ax4.table(
        cellText=rows,
        colLabels=["Variable"] + short_names,
        loc="center", cellLoc="center"
    )
    tbl.auto_set_font_size(False)
    tbl.set_fontsize(8)
    tbl.scale(1, 1.6)
    ax4.set_title("Pearson Correlations", fontweight="bold", pad=12)

fig.suptitle("Musical Congruence — Pipeline Sanity Check",
             fontsize=14, fontweight="bold", y=1.01)
plt.savefig("results/sanity_check.png", dpi=150, bbox_inches="tight")
plt.show()
print("Saved → results/sanity_check.png")

---
## Pipeline Summary

In [ ]:
import os
from pathlib import Path
from config import RESULTS_DIR, EMBEDDINGS_DIR

def file_exists(path):
    return "✓" if Path(path).exists() else "✗"

print("Pipeline output summary")
print("─" * 52)
print(f"  {file_exists('lyrics/_manifest.json')}  Lyrics manifest")
print(f"  {file_exists('results/embeddings/mulan/similarities.json')}  MuLan similarities")
print(f"  {file_exists('results/embeddings/clap/similarities.json')}  CLAP similarities")
print(f"  {file_exists('results/embeddings/mert_sbert/similarities.json')}  MERT+SBERT similarities")
print(f"  {file_exists('results/segment_analysis/segment_summary.csv')}  Segment summary")
print(f"  {file_exists('results/spotify_data.json')}  Spotify data")
print(f"  {file_exists('results/master_results.csv')}  master_results.csv  ← R input")
print()

master_path = Path("results/master_results.csv")
if master_path.exists():
    import pandas as pd
    m = pd.read_csv(master_path)
    print(f"  master_results.csv: {len(m)} songs, {m.columns.tolist().count} columns")
    print(f"  Complete (popularity + MuLan): "
          f"{m.dropna(subset=['popularity','lmc_mulan']).shape[0]} songs")
    print()
    print("Next step: open analysis/analysis.R in RStudio and run top-to-bottom.")
else:
    print("  master_results.csv not yet generated — run Steps 1–9 above.")